#message:06:(MAC_Housing_0000) {
	[Style right]
	[Wave]Hey, you![BR]
	[Pause 5]Thief!![Wait][End]
}

#message:06:(MAC_Housing_0001) {
	[Style right]
	Oh, Mario. It's you.[BR]
	[Pause 10]A Shy Guy stole my Storeroom[BR]
	Key![BR]
	[Wait][Next]
	I can't stay in business if I[BR]
	can't get into my storeroom![BR]
	[Wait][Next]
	What in the world will I do?![Wait][End]
}

#message:06:(MAC_Housing_0002) {
	[Style right]
	Why, Mario![BR]
	[Pause 10]Is... Isn't that...[BR]
	[Pause 10]my Storeroom Key?[Wait][End]
}

#message:06:(MAC_Housing_0003) {
	[Style right]
	All right, Mario![BR]
	[Pause 10]You did it! You got back my[BR]
	Storeroom Key![BR]
	[Wait][Next]
	Thank you so much![BR]
	[Pause 10]You saved my livelihood!![Wait][End]
}

#message:06:(MAC_Housing_0004) {
	[Style right]
	Ahem... Uh, Mario?[BR]
	[Pause 10]Please don't open the storeroom[BR]
	without my permission, all right?[BR]
	[Wait][Next]
	Huh?![BR]
	[Pause 10]Hey! You got back my[BR]
	Storeroom Key![BR]
	[Wait][Next]
	Oh, thank you, thank you![BR]
	[Pause 10]You saved my business!![Wait][End]
}

#message:06:(MAC_Housing_0005) {
	[Style right]
	Tell you what. Take anything you[BR]
	like from the storeroom.[BR]
	[Wait][Next]
	It's just a little thank-you for[BR]
	getting my Storeroom Key back.[Wait][End]
}

#message:06:(MAC_Housing_0006) {
	[Style right]
	Hi! I'm new to the neighborhood.[BR]
	[Pause 5]I never expected it to be so nice[BR]
	and quiet in the big city.[BR]
	[Wait][Next]
	It cost me a small fortune in[BR]
	coins to get this place, but I[BR]
	think it was worth it.[BR]
	[Wait][Next]
	It's such a lovely house, isn't it?[BR]
	[Pause 10]It sure is![Wait][End]
}

#message:06:(MAC_Housing_0007) {
	[Style right]
	Hi! I'm new to the neighborhood.[BR]
	[Pause 5]I never expected it to be so nice[BR]
	and quiet in the big city.[BR]
	[Wait][Next]
	It cost me a small fortune in[BR]
	coins to get this place, but I[BR]
	think it was worth it.[BR]
	[Wait][Next]
	It's such a lovely house, isn't it?[BR]
	[Pause 10]It sure is![Wait][End]
}

#message:06:(MAC_Housing_0008) {
	[Style right]
	Oh. Hi, Mario![BR]
	[Pause 10]Thanks for coming to visit me![BR]
	[Wait][Next]
	It's so quiet around here. I've[BR]
	been really bored...[BR]
	[Wait][Next]
	I know I just moved here, but I[BR]
	kind of wish I'd moved somewhere[BR]
	more...happening.[Wait][End]
}

#message:06:(MAC_Housing_0009) {
	[Style right]
	Hi, Mario! Hey, by the way...[BR]
	[Pause 10]Did you know the house next door[BR]
	is supposed to be vacant?[BR]
	[Wait][Next]
	...But you know what? I hear lots[BR]
	of noises coming from there. [BR]
	[Wait][Next]
	Maybe it's a thief's hideout...[BR]
	[Pause 10]Oh, how scary! Right next door![Wait][End]
}

#message:06:(MAC_Housing_000A) {
	[Style right]
	Hi, Mario! Hey, by the way...[BR]
	[Pause 10]Did you know the house next door[BR]
	is supposed to be vacant?[BR]
	[Wait][Next]
	...But you know what? I hear lots[BR]
	of noises coming from there.[BR]
	[Wait][Next]
	Maybe it's a thief's hideout...[BR]
	[Pause 10]Oh, how scary! Right next door![Wait][End]
}

#message:06:(MAC_Housing_000B) {
	[Style right]
	What!? You're kidding me![BR]
	[Pause 10]Shy Guys are living in the vacant[BR]
	house right next to us?![BR]
	[Wait][Next]
	I would never have bought this[BR]
	house if I had known...[BR]
	[Pause 10]I'm calling my realtor![Wait][End]
}

#message:06:(MAC_Housing_000C) {
	[Style right]
	Those Shy Guys really seem to[BR]
	have quieted down recently.[BR]
	[Wait][Next]
	Too quiet... I get really lonely[BR]
	when it's so dull.[BR]
	[Wait][Next]
	I wish those Shy Guys weren't so[BR]
	bad. I bet we could be really[BR]
	good friends if they shaped up.[Wait][End]
}

#message:06:(MAC_Housing_000D) {
	[Style right]
	Those Shy Guys really seem to[BR]
	have quieted down recently.[BR]
	[Wait][Next]
	Too quiet... I get really lonely[BR]
	when it's so dull.[BR]
	[Wait][Next]
	I wish those Shy Guys weren't so[BR]
	bad. I bet we could be really[BR]
	good friends if they shaped up.[Wait][End]
}

#message:06:(MAC_Housing_000E) {
	[Style right]
	My wish was to live a peaceful,[BR]
	fulfilling life in this lovely,[BR]
	quiet house.[BR]
	[Wait][Next]
	But recently, I've been feeling[BR]
	very blue inside.[BR]
	[Wait][Next]
	My wish may have come true, but[BR]
	the princess was kidnapped and[BR]
	all...[BR]
	[Wait][Next]
	It's tough to feel happy when[BR]
	everyone around you seems to be[BR]
	suffering.[Wait][End]
}

#message:06:(MAC_Housing_000F) {
	[Style right]
	My wish was to live a peaceful,[BR]
	fulfilling life in this lovely,[BR]
	quiet house.[BR]
	[Wait][Next]
	But recently, I've been feeling[BR]
	very blue inside.[BR]
	[Wait][Next]
	My wish may have come true, but[BR]
	the princess was kidnapped and[BR]
	all...[BR]
	[Wait][Next]
	It's tough to feel happy when[BR]
	everyone around you seems to be[BR]
	suffering.[Wait][End]
}

#message:06:(MAC_Housing_0010) {
	[Style right]
	Hey, Mario. Are you good at[BR]
	saving up your coins?[BR]
	[Wait][Next]
	I still have tons of coins in my[BR]
	savings. I have no idea how to[BR]
	spend them all![BR]
	[Wait][Next]
	You don't know of any smart[BR]
	investments, do you?[Wait][End]
}

#message:06:(MAC_Housing_0011) {
	[Style right]
	Hey, Mario. Are you good at[BR]
	saving up your coins?[BR]
	[Wait][Next]
	I still have tons of coins in my[BR]
	savings. I have no idea how to[BR]
	spend them all![BR]
	[Wait][Next]
	You don't know of any smart[BR]
	investments, do you?[Wait][End]
}

#message:06:(MAC_Housing_0012) {
	[Style right]
	Hi, Mario! Are you ready?[BR]
	I heard you're off to take on[BR]
	the evil Bowser![BR]
	[Wait][Next]
	If you can beat him, I'm going to[BR]
	spend all my coins on one huge[BR]
	celebration.[BR]
	[Wait][Next]
	Just to show how much you mean[BR]
	to this town, I'm going to fill the[BR]
	sky with booms and pops and[BR]
	bangs and zings! All for you![BR]
	[Wait][Next]
	I won't tell you more...[BR]
	It'll ruin the surprise![BR]
	[Pause 10]Hee hee hee hee...[Wait][End]
}

#message:06:(MAC_Housing_0013) {
	[Style right]
	Hey, you're Mario, right?[BR]
	[Pause 10]We just moved in! We've only just[BR]
	unpacked![BR]
	[Wait][Next]
	It's like a dream come true. A[BR]
	quiet and gorgeous home all to[BR]
	ourselves![HEART][BR]
	[Pause 10]Ah, I'm so happy![BR]
	[Wait][Next]
	Of course, happy as I am, I know[BR]
	these are sad times. I try not[BR]
	to act too jolly when I'm out and[BR]
	about.[Wait][End]
}

#message:06:(MAC_Housing_0014) {
	[Style right]
	Hey, you're Mario, right?[BR]
	[Pause 10]We just moved in! We've only just[BR]
	unpacked![BR]
	[Wait][Next]
	It's like a dream come true. A[BR]
	quiet and gorgeous home all to[BR]
	ourselves![HEART][BR]
	[Pause 10]Ah, I'm so happy![BR]
	[Wait][Next]
	Of course, happy as I am, I know[BR]
	these are sad times. I try not[BR]
	to act too jolly when I'm out and[BR]
	about.[Wait][End]
}

#message:06:(MAC_Housing_0015) {
	[Style right]
	It's so quiet...[BR]
	[Pause 10]It's actually kind of unsettling.[BR]
	[Wait][Next]
	I miss all the hustle and bustle[BR]
	that was here when we first[BR]
	moved in.[Wait][End]
}

#message:06:(MAC_Housing_0016) {
	[Style right]
	Somebody's really been raising a[BR]
	racket in the house next door,[BR]
	that's for sure![BR]
	[Wait][Next]
	It sounds like a bunch of kids[BR]
	bouncing off the walls.[BR]
	[Wait][Next]
	And I thought that house was[BR]
	vacant...[BR]
	[Pause 10]How creepy![Wait][End]
}

#message:06:(MAC_Housing_0017) {
	[Style right]
	Somebody's really been raising a[BR]
	racket in the house next door, [BR]
	that's for sure![BR]
	[Wait][Next]
	It sounds like a bunch of kids[BR]
	bouncing off the walls.[BR]
	[Wait][Next]
	And I thought that house was[BR]
	vacant...[BR]
	[Pause 10]How creepy![Wait][End]
}

#message:06:(MAC_Housing_0018) {
	[Style right]
	Huh?[BR]
	[Pause 10]You mean Shy Guys were staying[BR]
	in that house next door?[BR]
	[Wait][Next]
	No wonder it was so noisy...[BR]
	[Pause 10]I knew something was weird.[BR]
	Empty houses don't make noise.[Wait][End]
}

#message:06:(MAC_Housing_0019) {
	[Style right]
	Toad Town's back to being quiet[BR]
	now that the Shy Guys are gone.[BR]
	[Wait][Next]
	Yup... Reeeeal quiet. Nothing[BR]
	going on at all.[BR]
	[Pause 10]Ugh... I need some excitement.[BR]
	[Wait][Next]
	I can kinda understand why the[BR]
	Shy Guys were running wild. This[BR]
	town is sort of stifling.[Wait][End]
}

#message:06:(MAC_Housing_001A) {
	[Style right]
	Toad Town's back to being quiet[BR]
	now that the Shy Guys are gone.[BR]
	[Wait][Next]
	Yup... Reeeeal quiet. Nothing[BR]
	going on at all.[BR]
	[Pause 10]Ugh... I need some excitement.[BR]
	[Wait][Next]
	I can kinda understand why the[BR]
	Shy Guys were running wild. This[BR]
	town is sort of stifling.[Wait][End]
}

#message:06:(MAC_Housing_001B) {
	[Style right]
	When we first moved in here,[BR]
	Toad Town was hopping! Now it's[BR]
	just depressing.[BR]
	[Wait][Next]
	Even when I wish to the Stars,[BR]
	my wishes don't come true any-[BR]
	more. This place is really[BR]
	getting me down.[Wait][End]
}

#message:06:(MAC_Housing_001C) {
	[Style right]
	When we first moved in here,[BR]
	Toad Town was hopping! Now it's[BR]
	just depressing.[BR]
	[Wait][Next]
	Even when I wish to the Stars,[BR]
	my wishes don't come true any-[BR]
	more. This place is really[BR]
	getting me down.[Wait][End]
}

#message:06:(MAC_Housing_001D) {
	[Style right]
	My sister's thinking of a good[BR]
	way to spend her coins.[BR]
	[Wait][Next]
	I think she should spend it for[BR]
	the good of others...[Wait][End]
}

#message:06:(MAC_Housing_001E) {
	[Style right]
	My sister's thinking of a good[BR]
	way to spend her coins.[BR]
	[Wait][Next]
	I think she should spend it for[BR]
	the good of others...[Wait][End]
}

#message:06:(MAC_Housing_001F) {
	[Style right]
	I guess my sister decided what[BR]
	she's gonna do with her coins.[BR]
	[Wait][Next]
	She won't even tell me! Can you[BR]
	believe that? Her own sister![BR]
	[Pause 10]Aren't you just dying to know[BR]
	what she's gonna do?[Wait][End]
}

#message:06:(MAC_Housing_0020) {
	[Style right]
	By the by, Mario,[BR]
	[Pause 10]if you can't hold any more items,[BR]
	you should leave them at the[BR]
	shop.[BR]
	[Wait][Next]
	You can pick the items up again[BR]
	at any shop in the world, so it's[BR]
	a useful system.[Wait][End]
}

#message:06:(MAC_Housing_0021) {
	[Style right]
	By the by, Mario,[BR]
	[Pause 10]if you can't hold any more items,[BR]
	you should leave them at the[BR]
	shop.[BR]
	[Wait][Next]
	You can pick the items up again[BR]
	at any shop in the world, so it's[BR]
	a useful system.[Wait][End]
}

#message:06:(MAC_Housing_0022) {
	[Style right]
	By the by, Mario,[BR]
	[Pause 10]if you can't hold any more items,[BR]
	you should leave them at the[BR]
	shop.[BR]
	[Wait][Next]
	You can pick the items up again[BR]
	at any shop in the world, so it's[BR]
	a useful system.[Wait][End]
}

#message:06:(MAC_Housing_0023) {
	[Style right]
	Eek! Mario![BR]
	[Pause 10]Some Shy Guys just ran into the[BR]
	shop over there![BR]
	[Wait][Next]
	There's no way they're gonna do[BR]
	anything good in there![BR]
	[Pause 10]Get 'em! Please![Wait][End]
}

#message:06:(MAC_Housing_0024) {
	[Style right]
	I tried to chase the Shy Guys,[BR]
	but I fell and lost their trail.[BR]
	[Wait][Next]
	I was real busy holding my toe[BR]
	and shrieking, but I think maybe[BR]
	they went to the port.[Wait][End]
}

#message:06:(MAC_Housing_0025) {
	[Style right]
	If you get tired, you really[BR]
	ought to rest at a Toad House.[BR]
	[Pause 10]A good nap is the best medicine.[BR]
	[Wait][Next]
	Maybe you should hit the Save[BR]
	Block after you rest, too. Just[BR]
	to be safe.[Wait][End]
}

#message:06:(MAC_Housing_0026) {
	[Style right]
	If you're going to travel far,[BR]
	you really should get healthy at[BR]
	a Toad House first. [BR]
	[Wait][Next]
	Oh, and you should stop by a[BR]
	shop and get some items.[BR]
	[Wait][Next]
	And brush your teeth.[BR]
	Maybe comb your mustache.[BR]
	[Pause 10]Don't forget to save, too.[Wait][End]
}

#message:06:(MAC_Housing_0027) {
	[Style right]
	If you're going to travel far,[BR]
	you really should get healthy at[BR]
	a Toad House first. [BR]
	[Wait][Next]
	Oh, and you should stop by a [BR]
	shop and get some items.[BR]
	[Wait][Next]
	And brush your teeth.[BR]
	Maybe comb your mustache.[BR]
	[Pause 10]Don't forget to save, too.[Wait][End]
}

#message:06:(MAC_Housing_0028) {
	[Style right]
	Hey there, Mario![BR]
	[Pause 10]Did you recently go some place[BR]
	tropical or something?[BR]
	[Wait][Next]
	You look like you came back with[BR]
	a little tan.[BR]
	[Pause 10]I didn't think you could possibly[BR]
	look any cooler, but you do.[Wait][End]
}

#message:06:(MAC_Housing_0029) {
	[Style right]
	Mario,[BR]
	[Pause 10]aren't you tired at all?[BR]
	[Wait][Next]
	Adventuring must take its toll.[BR]
	[Wait][Next]
	Try to relax while you're here in[BR]
	Toad Town, OK?[Wait][End]
}

#message:06:(MAC_Housing_002A) {
	[Style right]
	The Stars used to make wishes[BR]
	come true for the citizens of[BR]
	Mushroom Kingdom.[BR]
	[Wait][Next]
	Supposedly, they only grant good[BR]
	wishes, but who's to say which[BR]
	wishes are good?[Wait][End]
}

#message:06:(MAC_Housing_002B) {
	[Style right]
	The Stars used to make wishes[BR]
	come true for the citizens of[BR]
	Mushroom Kingdom.[BR]
	[Wait][Next]
	Supposedly, they only grant good[BR]
	wishes, but who's to say which[BR]
	wishes are good?[Wait][End]
}

#message:06:(MAC_Housing_002C) {
	[Style right]
	I know this wish is a good one.[BR]
	I wish the princess and everyone[BR]
	else will come back safely.[BR]
	[Wait][Next]
	I wish, I wish, I wish![BR]
	[Pause 10]Good luck, Mario![Wait][End]
}

#message:06:(MAC_Housing_002D) {
	[Style right]
	I've heard a rumor about this[BR]
	great big hidden ruin somewhere[BR]
	in Dry Dry Desert, but[BR]
	[Wait][Next]
	I don't believe it.[BR]
	[Pause 10]Well, I've never seen it.[BR]
	[Pause 10]Once I see it with my own eyes,[BR]
	then I'll believe it.[Wait][End]
}

#message:06:(MAC_Housing_002E) {
	[Style right]
	I've heard a rumor about this[BR]
	great big hidden ruin somewhere[BR]
	in Dry Dry Desert, but[BR]
	[Wait][Next]
	I don't believe it.[BR]
	[Pause 10]Well, I've never seen it.[BR]
	[Pause 10]Once I see it with my own eyes,[BR]
	then I'll believe it.[Wait][End]
}

#message:06:(MAC_Housing_002F) {
	[Style right]
	I've heard a rumor about this[BR]
	dark, scary Boo Mansion deep in[BR]
	Forever Forest...[BR]
	[Wait][Next]
	I don't believe it.[BR]
	[Pause 10]Well, nobody's ever seen it.[BR]
	[Wait][Next]
	It must be a lie.[Wait][End]
}

#message:06:(MAC_Housing_0030) {
	[Style right]
	I've heard a rumor that Shy[BR]
	Guys are hiding in somebody's[BR]
	house in Toad Town. Here! Shy[BR]
	Guys in Toad Town!?[BR]
	[Wait][Next]
	What rubbish![BR]
	[Wait][Next]
	I think that people would notice[BR]
	a huge group of Shy Guys living[BR]
	in one of the houses in the[BR]
	neighborhood.[BR]
	[Wait][Next]
	There's no way that's true.[Wait][End]
}

#message:06:(MAC_Housing_0031) {
	[Style right]
	I've heard a rumor that Shy[BR]
	Guys are hiding in somebody's[BR]
	house in Toad Town. Here! Shy[BR]
	Guys in Toad Town!?[BR]
	[Wait][Next]
	What rubbish![BR]
	[Wait][Next]
	I think that people would notice[BR]
	a huge group of Shy Guys living[BR]
	in one of the houses in the[BR]
	neighborhood.[BR]
	[Wait][Next]
	There's no way that's true.[Wait][End]
}

#message:06:(MAC_Housing_0032) {
	[Style right]
	What!?[BR]
	[Pause 10]The Shy Guys were hiding in that[BR]
	house over there?![BR]
	[Wait][Next]
	Why... [Pause 10]Why didn't I notice it??? [BR]
	I'm always around here!!![BR]
	[Wait][Next]
	I... [Pause 10]I just can't...[BR]
	[Pause 5]believe such a tale! No way![Wait][End]
}

#message:06:(MAC_Housing_0033) {
	[Style right]
	Huh...?[BR]
	[Pause 10]Mario, you're trying to go to [BR]
	Lavalava Island?[BR]
	[Wait][Next]
	Good luck. You're completely[BR]
	wasting your time, though.[BR]
	[Wait][Next]
	Lavalava Island only exists in[BR]
	rumors spread by idiots.[BR]
	[Pause 10]It's a figment of imagination.[Wait][End]
}

#message:06:(MAC_Housing_0034) {
	[Style right]
	You're going to Lavalava Island[BR]
	on a whale?![BR]
	[Wait][Next]
	Mario, there's no such island![BR]
	[Pause 10]And furthermore, there's no way[BR]
	you can ride a whale.[BR]
	[Wait][Next]
	I'm shocked that you would make[BR]
	up such lies, Mario.[Wait][End]
}

#message:06:(MAC_Housing_0035) {
	[Style right]
	You went to Lavalava Island?[BR]
	[Pause 10]Yoshis? Ravens? Erupting[BR]
	volcanoes?[BR]
	[Wait][Next]
	Wow, that's amazing![BR]
	[Wait][Next]
	...You know something, Mario?[BR]
	[Pause 10]It's also a big, fat lie![BR]
	I don't believe it for a second![Wait][End]
}

#message:06:(MAC_Housing_0036) {
	[Style right]
	I've heard a rumor that the door[BR]
	in the flower garden leads to a[BR]
	region that's full of flowers.[BR]
	It's called Flower Fields.[BR]
	[Wait][Next]
	Oh, come on. No more of this.[BR]
	[Pause 10]Another world? Unbelievable. [Wait][End]
}

#message:06:(MAC_Housing_0037) {
	[Style right]
	A lot of people around here say [BR]
	that there's something inside[BR]
	that pipe in the town, but...[BR]
	[Wait][Next]
	I don't believe one word of it![BR]
	[Wait][Next]
	Well,[Pause 20] think about it...[BR]
	[Pause 20]If there really were something...[BR]
	That'd be really creepy![Wait][End]
}

#message:06:(MAC_Housing_0038) {
	[Style right]
	A lot of people around here say [BR]
	that there's something inside [BR]
	that pipe in the town, but...[BR]
	[Wait][Next]
	I don't believe one word of it![BR]
	[Wait][Next]
	Well,[Pause 20] think about it...[BR]
	[Pause 20]If there really were something...[BR]
	That'd be really creepy![Wait][End]
}

#message:06:(MAC_Housing_0039) {
	[Style right]
	Mario... I heard a rumor...[BR]
	[Pause 10]It was about you going to fight[BR]
	Bowser and save the princess.[BR]
	[Wait][Next]
	I don't believe it.[BR]
	[Pause 10]Well, for one thing, it's scary.[BR]
	[Pause 10]You could get hurt, you know.[BR]
	[Wait][Next]
	I can't believe a sane man would[BR]
	willingly do such a thing.[BR]
	[Pause 10]I won't believe it! No! I don't[BR]
	believe it![BR]
	[Wait][Next]
	I'll never believe you! Neveeeer![Wait][End]
}

#message:06:(MAC_Housing_003A) {
	[Style right]
	Here comes Red Ranger T.![BR]
	[Pause 15]Pow![Wait][End]
}

#message:06:(MAC_Housing_003B) {
	[Style right]
	Here comes Yellow Ranger T.![BR]
	[Pause 15]Boom![Wait][End]
}

#message:06:(MAC_Housing_003C) {
	[Style right]
	Here comes Green Ranger T.![BR]
	[Pause 15]Donk![BR]
	[Wait][Next]
	Look, look, Mario![BR]
	[Pause 10]We three are heroes like you![Wait][End]
}

#message:06:(MAC_Housing_003D) {
	[Style right]
	Here comes Red Ranger T.![BR]
	[Pause 15]Pow![Wait][End]
}

#message:06:(MAC_Housing_003E) {
	[Style right]
	Here comes Yellow Ranger T.![BR]
	[Pause 15]Boom![Wait][End]
}

#message:06:(MAC_Housing_003F) {
	[Style right]
	Here comes Green Ranger T.![BR]
	[Pause 15]Donk![BR]
	[Wait][Next]
	Look, look, Mario![BR]
	[Pause 10]We three are heroes like you![Wait][End]
}

#message:06:(MAC_Housing_0040) {
	[Style right]
	[PrintRising][Shake]Yaaaaaaaargh... They got me...[Wait][End]
}

#message:06:(MAC_Housing_0041) {
	[Style right]
	Come on, Red![BR]
	[Pause 10]Shake it off! Get up![Wait][End]
}

#message:06:(MAC_Housing_0042) {
	[Style right]
	[PrintRising]We must avenge Red![BR]
	[/PrintRising][Wait][Next]
	...mmm... [Pause 10]It doesn't feel the same[BR]
	without a bad guy.[BR]
	[Wait][Next]
	Mario, you aren't busy, are you?[BR]
	Why don't you be the Evil King[BR]
	Bowser?[Wait][End]
}

#message:06:(MAC_Housing_0043) {
	[Style right]
	Shy Guys! [PrintRising]After them, Rangers![Wait][End]
}

#message:06:(MAC_Housing_0044) {
	[Style right]
	No...! [PrintRising]Retreat![Wait][End]
}

#message:06:(MAC_Housing_0045) {
	[Style right]
	The Shy Guys are after us![BR]
	[PrintRising]Hide---------![BR]
	[/PrintRising][Wait][Next]
	Playing Shy Guy Battle is our [BR]
	favorite game right now. [BR]
	[Pause 10]It rules![Wait][End]
}

#message:06:(MAC_Housing_0046) {
	[Style right]
	Shy Guys! [PrintRising]After them, Rangers![Wait][End]
}

#message:06:(MAC_Housing_0047) {
	[Style right]
	No...! [PrintRising]Retreat![Wait][End]
}

#message:06:(MAC_Housing_0048) {
	[Style right]
	The Shy Guys are after us![BR]
	[PrintRising]Hide---------![BR]
	[/PrintRising][Wait][Next]
	Playing Shy Guy Battle is our [BR]
	favorite game right now. [BR]
	[Pause 10]It rules![Wait][End]
}

#message:06:(MAC_Housing_0049) {
	[Style right]
	Shy Guys! [PrintRising]After them, Rangers![Wait][End]
}

#message:06:(MAC_Housing_004A) {
	[Style right]
	No...! [PrintRising]Retreat![Wait][End]
}

#message:06:(MAC_Housing_004B) {
	[Style right]
	The Shy Guys are after us![BR]
	[PrintRising]Hide---------![BR]
	[/PrintRising][Wait][Next]
	Playing Shy Guy Battle is our [BR]
	favorite game right now. [BR]
	[Pause 10]It rules![Wait][End]
}

#message:06:(MAC_Housing_004C) {
	[Style right]
	My Grandpa said that[BR]
	[Wait][Next]
	far away in the southern sea is [BR]
	an island called Lavalava Island.[BR]
	He says Yoshis live there. He's[BR]
	really smart.[Wait][End]
}

#message:06:(MAC_Housing_004D) {
	[Style right]
	There are Yoshis?![BR]
	[Pause 10]Yiiippeeee![BR]
	[Pause 5]Real live Yoshis?[BR]
	[Wait][Next]
	I wanna go to Lavalava Island![BR]
	Right now! Right now![BR]
	[Pause 10]Maybe we can swim there from[BR]
	here. C'mon, Rangers![Wait][End]
}

#message:06:(MAC_Housing_004E) {
	[Style right]
	[Wave]No------! None of us know how[BR]
	to swim, dummy![BR]
	[/Wave][Wait][End]
}

#message:06:(MAC_Housing_004F) {
	[Style right]
	My Grandpa said that[BR]
	[Wait][Next]
	far away in the southern sea is[BR]
	an island called Lavalava Island.[BR]
	He says Yoshis live there. He's[BR]
	really smart.[Wait][End]
}

#message:06:(MAC_Housing_0050) {
	[Style right]
	There are Yoshis?![BR]
	[Pause 10]Yiiippeeee![BR]
	[Pause 5]Real live Yoshis?[BR]
	[Wait][Next]
	I wanna go to Lavalava Island![BR]
	Right now! Right now![BR]
	[Pause 10]Maybe we can swim there from[BR]
	here. C'mon, Rangers![Wait][End]
}

#message:06:(MAC_Housing_0051) {
	[Style right]
	[Wave]No------! None of us know how[BR]
	to swim, dummy![BR]
	[/Wave][Wait][End]
}

#message:06:(MAC_Housing_0052) {
	[Style right]
	Hey! Hey! Hey![BR]
	[Pause 10]Wanna play hide-and-seek in[BR]
	Forever Forest?[BR]
	[Pause 10]It'll be really scary![Wait][End]
}

#message:06:(MAC_Housing_0053) {
	[Style right]
	No, we can't.[BR]
	[Pause 10]Don't you know it's dangerous?[BR]
	There are ghosts in there![BR]
	[Wait][Next]
	Mom says I should never, ever go[BR]
	in Forever Forest.[Wait][End]
}

#message:06:(MAC_Housing_0054) {
	[Style right]
	Yeah, yeah...[BR]
	[Pause 10]You and your mom...[Wait][End]
}

#message:06:(MAC_Housing_0055) {
	[Style right]
	Hey! Hey! Hey![BR]
	[Pause 10]Wanna play hide-and-seek in[BR]
	Forever Forest?[BR]
	[Pause 10]It'll be really scary![Wait][End]
}

#message:06:(MAC_Housing_0056) {
	[Style right]
	No, we can't.[BR]
	[Pause 10]Don't you know it's dangerous?[BR]
	There are ghosts in there![BR]
	[Wait][Next]
	Mom says I should never, ever go[BR]
	in Forever Forest.[Wait][End]
}

#message:06:(MAC_Housing_0057) {
	[Style right]
	Yeah, yeah...[BR]
	[Pause 10]You and your mom...[Wait][End]
}

#message:06:(MAC_Housing_0058) {
	[Style right]
	Hey, guys. My mom's...[BR]
	[Pause 5]She's really into this book she's[BR]
	reading.[BR]
	[Wait][Next]
	I guess it's really interesting.[BR]
	She doesn't play much anymore.[Wait][End]
}

#message:06:(MAC_Housing_0059) {
	[Style right]
	My mom's reading it, too.[BR]
	[Pause 10]It was written by some guy[BR]
	named Herringway.[BR]
	[Wait][Next]
	Mom says it's a real page-[BR]
	turner but that it's not for[BR]
	children. I tried to sneak a[BR]
	peek, but she caught me.[Wait][End]
}

#message:06:(MAC_Housing_005A) {
	[Style right]
	Who'd want to read it anyway?[BR]
	Grown-up books are boring.[Wait][End]
}

#message:06:(MAC_Housing_005B) {
	[Style right]
	Hey, guys. My mom's...[BR]
	[Pause 5]She's really into this book she's[BR]
	reading.[BR]
	[Wait][Next]
	I guess it's really interesting.[BR]
	She doesn't play much anymore.[Wait][End]
}

#message:06:(MAC_Housing_005C) {
	[Style right]
	My mom's reading it, too.[BR]
	[Pause 10]It was written by some guy[BR]
	named Herringway.[BR]
	[Wait][Next]
	Mom says it's a real page-[BR]
	turner but that it's not for[BR]
	children. I tried to sneak a[BR]
	peek, but she caught me.[Wait][End]
}

#message:06:(MAC_Housing_005D) {
	[Style right]
	Who'd want to read it anyway?[BR]
	Grown-up books are boring.[Wait][End]
}

#message:06:(MAC_Housing_005E) {
	[Style right]
	Hey, guys! Mario's off to beat[BR]
	up Bowser![BR]
	[Wait][Next]
	Cool! Ker-pow![BR]
	[Pause 10]I'm gonna be just like Mario when[BR]
	I grow up.[Wait][End]
}

#message:06:(MAC_Housing_005F) {
	[Style right]
	But...[BR]
	[Pause 10]Mario... You actually have to[BR]
	fight the real Bowser. Yikes![BR]
	[Wait][Next]
	That's so scary![Wait][End]
}

#message:06:(MAC_Housing_0060) {
	[Style right]
	Mario, will you be all right?[BR]
	[Pause 10]Yeah, of course you will![BR]
	Good luck! Save the princess![Wait][End]
}

#message:06:(MAC_Housing_0061) {
	[Style right]
	This neighborhood is the[BR]
	quietest place in Toad Town.[BR]
	[Wait][Next]
	That's why I often come here to[BR]
	walk and think.[BR]
	[Wait][Next]
	Oh, I try to put on a glad face.[BR]
	The castle won't come back just[BR]
	because we stay home and mope,[BR]
	now will it?[Wait][End]
}

#message:06:(MAC_Housing_0062) {
	[Style right]
	This neighborhood is the[BR]
	quietest place in Toad Town.[BR]
	[Wait][Next]
	That's why I often come here to[BR]
	walk and think.[BR]
	[Wait][Next]
	Oh, I try to put on a glad face.[BR]
	The castle won't come back just[BR]
	because we stay home and mope,[BR]
	now will it?[Wait][End]
}

#message:06:(MAC_Housing_0063) {
	[Style right]
	I often come here to walk.[BR]
	[Pause 10]It's nice and quiet, is it not?[BR]
	[Wait][Next]
	On sunny days, I even head over[BR]
	to the port sometimes.[Wait][End]
}

#message:06:(MAC_Housing_0064) {
	[Style right]
	I saw them! The scoundrels![BR]
	[Pause 10]Shy Guys just went into that[BR]
	empty house right there.[BR]
	[Wait][Next]
	Do you suppose... Could that be[BR]
	the Shy Guy hideout?[Wait][End]
}

#message:06:(MAC_Housing_0065) {
	[Style right]
	Our pleasant local shopkeeper[BR]
	has been hit by Shy Guys! They[BR]
	stole his Storeroom Key.[BR]
	[Wait][Next]
	The dear man said that it's the[BR]
	most important key he has.[BR]
	[Pause 10]Oh, this is simply awful! How will[BR]
	he ever get it back?[Wait][End]
}

#message:06:(MAC_Housing_0066) {
	[Style right]
	Mario, that key you hold...[BR]
	[Pause 10]Isn't that the Storeroom Key?[BR]
	[Wait][Next]
	The shopkeeper is truly pulling[BR]
	his hair out over that key. You[BR]
	must take it to him![Wait][End]
}

#message:06:(MAC_Housing_0067) {
	[Style right]
	Whenever I have problems, I take[BR]
	a brief journey across town to[BR]
	where Merlon resides. He tells[BR]
	the future.[BR]
	[Wait][Next]
	He's an old wizard, you know. A[BR]
	bit unusual, perhaps, but his[BR]
	prophecies are usually right on[BR]
	the money.[Wait][End]
}

#message:06:(MAC_Housing_0068) {
	[Style right]
	My, my, that's quite a nice[BR]
	Frying Pan you're carrying.[BR]
	[Wait][Next]
	It seems like it was used quite a[BR]
	bit in its time. Its owner must[BR]
	have really loved to cook. Is it[BR]
	yours?[Wait][End]
}

#message:06:(MAC_Housing_0069) {
	[Style right]
	Our local scholar, Russ T., has[BR]
	met with an ill fate. It seems[BR]
	that Shy Guys have made off[BR]
	with his beloved dictionary.[BR]
	[Wait][Next]
	My heart aches for that poor[BR]
	man. He loved that dictionary[BR]
	like a son![BR]
	[Wait][Next]
	Dearest Mario, is there any[BR]
	chance you can retrieve it?[Wait][End]
}

#message:06:(MAC_Housing_006A) {
	[Style right]
	My dear Mario,[BR]
	[Pause 5]what an odd note you have![BR]
	[Wait][Next]
	Perhaps...[BR]
	Our scholar Russ T. might just[BR]
	be able to read it.[Wait][End]
}

#message:06:(MAC_Housing_006B) {
	[Style right]
	Whenever I have problems, I take[BR]
	a brief journey across town to[BR]
	where Merlon resides. He tells[BR]
	the future.[BR]
	[Wait][Next]
	He's an old wizard, you know. A[BR]
	bit unusual, perhaps, but his[BR]
	prophecies are usually right on[BR]
	the money.[Wait][End]
}

#message:06:(MAC_Housing_006C) {
	[Style right]
	Whenever I have problems, I take[BR]
	a brief journey across town to[BR]
	where Merlon resides. He tells[BR]
	the future.[BR]
	[Wait][Next]
	He's an old wizard, you know. A[BR]
	bit unusual, perhaps, but his[BR]
	prophecies are usually right on[BR]
	the money.[Wait][End]
}

#message:06:(MAC_Housing_006D) {
	[Style right]
	The local gossip is that there's[BR]
	something like an island afloat[BR]
	at the port.[BR]
	[Wait][Next]
	Others say it's a monster.[BR]
	[Pause 10]How frightful...[BR]
	[Wait][Next]
	It looks like I won't be walking[BR]
	there for some time.[Wait][End]
}

#message:06:(MAC_Housing_006E) {
	[Style right]
	I beg your pardon!?[BR]
	[Pause 10]The thing floating at the port[BR]
	was a whale?[BR]
	[Wait][Next]
	Oh, silly me! I shouldn't have[BR]
	been so frightened![HEART][Wait][End]
}

#message:06:(MAC_Housing_006F) {
	[Style right]
	I'd love to walk alone in a park[BR]
	full of flowers.[BR]
	[Wait][Next]
	It would be quiet and relaxing.[BR]
	[Wait][Next]
	Flowers don't chatter endlessly[BR]
	like people are prone to do.[Wait][End]
}

#message:06:(MAC_Housing_0070) {
	[Style right]
	I'd love to walk alone in a park[BR]
	full of flowers.[BR]
	[Wait][Next]
	It would be quiet and relaxing.[BR]
	[Wait][Next]
	Flowers don't chatter endlessly[BR]
	like people are prone to do.[Wait][End]
}

#message:06:(MAC_Housing_0071) {
	[Style right]
	People often ask me if I don't[BR]
	get bored going for walks in the[BR]
	same place every day.[BR]
	[Wait][Next]
	But I don't get bored at all.[BR]
	[Pause 10]It seems like something changes[BR]
	a little bit every day.[Wait][End]
}

#message:06:(MAC_Housing_0072) {
	[Style right]
	People often ask me if I don't [BR]
	get bored going for walks in the[BR]
	same place every day.[BR]
	[Wait][Next]
	But I don't get bored at all.[BR]
	[Pause 10]It seems like something changes[BR]
	a little bit every day.[Wait][End]
}

#message:06:(MAC_Housing_0073) {
	[Style right]
	People often ask me if I don't [BR]
	get bored going for walks in the[BR]
	same place every day.[BR]
	[Wait][Next]
	But I don't get bored at all.[BR]
	[Pause 10]It seems like something changes[BR]
	a little bit every day.[Wait][End]
}

#message:06:(MAC_Housing_0074) {
	[Style right]
	If you want to get to Dry Dry [BR]
	Desert, take the train from[BR]
	Toad Town Station. You dig?[Wait][End]
}

#message:06:(MAC_Housing_0075) {
	[Style right]
	If you want to get to Dry Dry [BR]
	Desert, take the train from[BR]
	Toad Town Station. You dig?[Wait][End]
}

#message:06:(MAC_Housing_0076) {
	[Style right]
	If you go to the west, you'll [BR]
	reach the port.[BR]
	[Pause 10]If you want to go to Forever [BR]
	Forest, head east. Got it?[Wait][End]
}

#message:06:(MAC_Housing_0077) {
	[Style right]
	I'm positive that the Shy Guys[BR]
	are coming from somewhere in[BR]
	Toad Town.[BR]
	[Wait][Next]
	But where... Where could they be[BR]
	hiding around here?[BR]
	[Wait][Next]
	Unless I miss my guess, they[BR]
	must be in a house. Dig me?[Wait][End]
}

#message:06:(MAC_Housing_0078) {
	[Style right]
	I'm positive that the Shy Guys[BR]
	are coming from somewhere in[BR]
	Toad Town.[BR]
	[Wait][Next]
	But where... Where could they be[BR]
	hiding around here?[BR]
	[Wait][Next]
	Unless I miss my guess, they[BR]
	must be in a house. Dig me?[Wait][End]
}

#message:06:(MAC_Housing_0079) {
	[Style right]
	I'm positive that the Shy Guys[BR]
	are coming from somewhere in[BR]
	Toad Town.[BR]
	[Wait][Next]
	But where... Where could they be[BR]
	hiding around here?[BR]
	[Wait][Next]
	Unless I miss my guess, they[BR]
	must be in a house. Dig me?[Wait][End]
}

#message:06:(MAC_Housing_007A) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_007B) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_007C) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_007D) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_007E) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_007F) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_0080) {
	[Style right]
	Hey, Mario.[BR]
	[Pause 10]About Rowf's Badge Shop...[BR]
	[Wait][Next]
	I've heard it said that there[BR]
	are lots of Badges there.[BR]
	[Pause 10]Might be a good idea to go there[BR]
	often, you dig me?[Wait][End]
}

#message:06:(MAC_Housing_0081) {
	[Style right]
	Do you know postman Parakarry?[Wait][End]
}

#message:06:(MAC_Housing_0082) {
	[Style right]
	He delivers letters to many[BR]
	towns in the Mushroom Kingdom.[Wait][End]
}

#message:06:(MAC_Housing_0083) {
	[Style right]
	But he's easily distracted, so[BR]
	more often than not, the mail[BR]
	runs a little slow.[Wait][End]
}

#message:06:(MAC_Housing_0084) {
	[Style right]
	Do you know postman Parakarry? [Wait][End]
}

#message:06:(MAC_Housing_0085) {
	[Style right]
	He delivers letters to many [BR]
	towns in Mushroom Kingdom.[Wait][End]
}

#message:06:(MAC_Housing_0086) {
	[Style right]
	But he's easily distracted, so[BR]
	more often than not, the mail[BR]
	runs a little slow.[Wait][End]
}

#message:06:(MAC_Housing_0087) {
	[Style right]
	The guard of Forever Forest is[BR]
	really chicken. He's especially[BR]
	afraid of ghosts.[Wait][End]
}

#message:06:(MAC_Housing_0088) {
	[Style right]
	I know, I know. He's a riot.[BR]
	[Pause 5]Sometimes even I scare him.[Wait][End]
}

#message:06:(MAC_Housing_0089) {
	[Style right]
	That guy will run for the hills if[BR]
	he ever sees a real ghost.[Wait][End]
}

#message:06:(MAC_Housing_008A) {
	[Style right]
	My keen intuition tells me that[BR]
	Shy Guys must be hiding in a[BR]
	house somewhere.[BR]
	[Wait][Next]
	What do you guys think about[BR]
	finding their hideout and taking[BR]
	them on ourselves?[Wait][End]
}

#message:06:(MAC_Housing_008B) {
	[Style right]
	Yeah, there's a plan! But have[BR]
	you ever seen those guys run?[BR]
	They're way too fast. If they[BR]
	see us, they'll bolt.[BR]
	[Wait][Next]
	...Wait! I know![BR]
	[Pause 10]Why don't we turn invisible?[BR]
	[Wait][Next]
	If we do, the Shy Guys will be[BR]
	off guard and reveal themselves[BR]
	to us.[Wait][End]
}

#message:06:(MAC_Housing_008C) {
	[Style right]
	Uh... One problem, guys. How do[BR]
	we become invisible?[Wait][End]
}

#message:06:(MAC_Housing_008D) {
	[Style right]
	My keen intuition tells me that[BR]
	Shy Guys must be hiding in a[BR]
	house somewhere.[BR]
	[Wait][Next]
	What do you guys think about[BR]
	finding their hideout and taking[BR]
	them on ourselves?[Wait][End]
}

#message:06:(MAC_Housing_008E) {
	[Style right]
	Yeah, there's a plan! But have[BR]
	you ever seen those guys run?[BR]
	They're way too fast. If they[BR]
	see us, they'll bolt.[BR]
	[Wait][Next]
	...Wait! I know![BR]
	[Pause 10]Why don't we turn invisible?[BR]
	[Wait][Next]
	If we do, the Shy Guys will be[BR]
	off guard and reveal themselves[BR]
	to us.[Wait][End]
}

#message:06:(MAC_Housing_008F) {
	[Style right]
	Uh... One problem, guys. How do[BR]
	we become invisible?[Wait][End]
}

#message:06:(MAC_Housing_0090) {
	[Style right]
	Y'know, it's great having pals[BR]
	like you around.[BR]
	[Wait][Next]
	When you've got friends, you've[BR]
	got people who can lend a hand[BR]
	with stuff you can't manage.[BR]
	[Wait][Next]
	There's no obstacle too great[BR]
	when you're with friends![Wait][End]
}

#message:06:(MAC_Housing_0091) {
	[Style right]
	Aw, man. You're the greatest![BR]
	[Pause 10]Stop getting all mushy on us![BR]
	You're making me bashful.[BR]
	[Wait][Next]
	And you know, it's really[BR]
	important to know what kind of[BR]
	unique abilities your friends[BR]
	have.[Wait][End]
}

#message:06:(MAC_Housing_0092) {
	[Style right]
	What in the world does that have[BR]
	to do with being bashful?[Wait][End]
}

#message:06:(MAC_Housing_0093) {
	[Style right]
	What's that, Mario? You want to[BR]
	go to Lavalava Island?[BR]
	[Wait][Next]
	Yeah, Lavalava Island...[BR]
	I'm pretty sure that's an island[BR]
	way south of here.[Wait][End]
}

#message:06:(MAC_Housing_0094) {
	[Style right]
	There aren't any ships that go [BR]
	there from Toad Town...[BR]
	[Wait][Next]
	You'd better have strong arms,[BR]
	'cause you'll have to swim there.[Wait][End]
}

#message:06:(MAC_Housing_0095) {
	[Style right]
	That's impossible.[BR]
	[Pause 10]If there's a person who can swim[BR]
	there, I'll eat a Fuzzy.[Wait][End]
}

#message:06:(MAC_Housing_0096) {
	[Style right]
	What's that, Mario? You want to[BR]
	go to Lavalava Island?[BR]
	[Wait][Next]
	Yeah, Lavalava Island...[BR]
	I'm pretty sure that's an island[BR]
	way south of here.[Wait][End]
}

#message:06:(MAC_Housing_0097) {
	[Style right]
	There aren't any ships that go [BR]
	there from Toad Town...[BR]
	[Wait][Next]
	You better have strong arms,[BR]
	'cause you'll have to swim there.[Wait][End]
}

#message:06:(MAC_Housing_0098) {
	[Style right]
	That's impossible.[BR]
	[Pause 10]If there's a person who can swim[BR]
	there, I'll eat a Fuzzy.[Wait][End]
}

#message:06:(MAC_Housing_0099) {
	[Style right]
	You know, guys. There's a girl I[BR]
	kind of have a crush on.[BR]
	[Wait][Next]
	But I'm terrible at expressing[BR]
	my feelings. Know what I mean?[Wait][End]
}

#message:06:(MAC_Housing_009A) {
	[Style right]
	Really, [Pause 10]I never knew![BR]
	[Pause 10]Way to go, man! Just lemme know[BR]
	if you need any advice. I'm the[BR]
	master![BR]
	[Wait][Next]
	To start with, you can never go[BR]
	wrong with flowers.[Wait][End]
}

#message:06:(MAC_Housing_009B) {
	[Style right]
	Yeah right, flowers! Flowers![BR]
	[Pause 10]Girls love getting flowers like[BR]
	nobody's business![Wait][End]
}

#message:06:(MAC_Housing_009C) {
	[Style right]
	You know, guys. There's a girl I[BR]
	kind of have a crush on.[BR]
	[Wait][Next]
	But I'm terrible at expressing[BR]
	my feelings. Know what I mean?[Wait][End]
}

#message:06:(MAC_Housing_009D) {
	[Style right]
	Really, [Pause 10]I never knew![BR]
	[Pause 10]Way to go, man! Just lemme know[BR]
	if you need any advice. I'm the[BR]
	master![BR]
	[Wait][Next]
	To start with, you can never go[BR]
	wrong with flowers.[Wait][End]
}

#message:06:(MAC_Housing_009E) {
	[Style right]
	Yeah right, flowers! Flowers![BR]
	[Pause 10]Girls love getting flowers like[BR]
	nobody's business![Wait][End]
}

#message:06:(MAC_Housing_009F) {
	[Style right]
	Mario, you're really rolling on[BR]
	this adventure of yours, aren't[BR]
	you? Kickin' Koopa![BR]
	[Wait][Next]
	We read all about it on the town[BR]
	bulletin board.[BR]
	You make headlines all the time![Wait][End]
}

#message:06:(MAC_Housing_00A0) {
	[Style right]
	But... Well...[BR]
	[Wait][Next]
	Are you gonna save the princess[BR]
	soon or what?[Wait][End]
}

#message:06:(MAC_Housing_00A1) {
	[Style right]
	Hey, that's not cool![BR]
	[Pause 10]Don't be rude to the man![Wait][End]
}

#message:06:(MAC_Housing_00A2) {
	[Style right]
	Even when you're out of town,[BR]
	Luigi is still around, so we feel[BR]
	safe.[BR]
	[Wait][Next]
	With two local heroes, we have[BR]
	nothing to worry about.[Wait][End]
}

#message:06:(MAC_Housing_00A3) {
	[Style right]
	I noticed that Luigi looked a[BR]
	little down in the mouth, though,[BR]
	since you've been out.[BR]
	[Wait][Next]
	You should go visit him.[Wait][End]
}

#message:06:(MAC_Housing_00A4) {
	[Style right]
	I'm sure I know what his problem[BR]
	is. He probably just wants to go[BR]
	on adventures, too.[Wait][End]
}

#message:06:(MAC_Housing_00A5) {
	[Style right]
	Mario![BR]
	[Pause 10]Good luck, big guy![BR]
	[Wait][Next]
	I know you can beat Bowser![Wait][End]
}

#message:06:(MAC_Housing_00A6) {
	[Style right]
	We're behind you 100 percent,[BR]
	Mario, old pal![BR]
	[Wait][Next]
	With you on the job, Peach is as[BR]
	good as saved![Wait][End]
}

#message:06:(MAC_Housing_00A7) {
	[Style right]
	We all believe in you, my man![BR]
	[Wait][Next]
	Good luck![BR]
	[Pause 10]Give it up for Mario![Wait][End]
}

#message:06:(MAC_Housing_00A8) {
	[Style right]
	Yo, little man.[BR]
	[Pause 5]Name's Chet Rippo.[BR]
	[Pause 10]Pleasure meeting you.[BR]
	[Wait][Next]
	Say, man, don't you want to[BR]
	change your status?[BR]
	[Pause 10]Heh heh... [Pause 10]Yeah, I know you do.[BR]
	[Wait][Next]
	It's usually 390 coins, but for[BR]
	you and only you, I'll do it for[BR]
	just 39 coins.[BR]
	[Wait][Next]
	If you gimme 39 coins, I'll[BR]
	change your HP, FP or BP.[BR]
	[Wait][Next]
	I'm not lying or cheating you.[BR]
	[Pause 10]Come on... You know you want it.[BR]
	[Yield][End]
}

#message:06:(MAC_Housing_00A9) {
	[Style right]
	Yo, little man.[BR]
	[Pause 5]It's your old friend, Chet Rippo.[BR]
	[Pause 10]Good to see you again.[BR]
	[Wait][Next]
	Usually this costs 390 coins, but[BR]
	for you and only you, I'll do it[BR]
	for just 39 coins.[BR]
	[Wait][Next]
	If you gimme 39 coins, I'll[BR]
	change your HP, FP, or BP.[BR]
	[Wait][Next]
	Trust ol' Chet Rippo... [Pause 5]Come on![BR]
	[Yield][End]
}

#message:06:(MAC_Housing_00AA) {
	[Next]
	Too bad... Your loss.[BR]
	[Pause 10]Another time, maybe.[Wait][End]
}

#message:06:(MAC_Housing_00AB) {
	[Next]
	What are you trying to pull?[BR]
	[Pause 10]You don't have 39 coins![BR]
	[Wait][Next]
	Too bad for you...[BR]
	[Pause 10]Try coming back when you have a[BR]
	few coins in your pocket.[BR]
	[Wait][End]
}

#message:06:(MAC_Housing_00AC) {
	[Next]
	There you go! Good call![BR]
	[Wait][End]
}

#message:06:(MAC_Housing_00AC_FirstTime) {
	[Next]
	There you go! Good call![BR]
	[Wait][Next][Color red][InputOff]
	Listen up[InputOn][Color 0xA], little man.[BR]
	[Wait][Next]
	I can convert your existing[BR]
	stats into [Color green]Star Tokens[Color 0xA], which you[BR]
	can then convert to any other[BR]
	stat upgrade you'd like.[BR]
	[Wait][Next]
	Feel free to completely change[BR]
	your stats, all for 39 coins.[BR]
	Incredible value, isn't it?[BR]
	[Wait][End]
}

#message:06:(MAC_Housing_00AD) {
	[Next]
	Aw, man. You're backing out...?[BR]
	[Pause 10]Oh, well. Your loss.[BR]
	[Pause 10]See ya.[Wait][End]
}

#message:06:(MAC_Housing_00AE) {
	[Next]
	All right.[BR]
	So you want [Var 0] to [BR]
	be upgraded.[BR]
	[Pause 10]Here goes![Wait][End]
}

#message:06:(MAC_Housing_00AF) {
	[Style right]
	All right, now your stats[BR]
	have been changed.[BR]
	[Wait][Next]
	Heh heh... See ya![Wait][End]
}

#message:06:(MAC_Housing_00B0) {
	[Style right]
	All right, now your stats[BR]
	have been changed.[BR]
	[Wait][Next]
	Oh, and the Badges you had on[BR]
	are now off. So don't forget to[BR]
	put them back on.[BR]
	[Wait][Next]
	See ya later.[Wait][End]
}

#message:06:(MAC_Housing_00B1) {
	[Next]
	Oh, too bad, man.[BR]
	[Pause 10]That one can't be upgraded any[BR]
	more.[BR]
	[Wait][Next]
	It's a bummer, but there's[BR]
	nothing you can do.[BR]
	[Pause 10]See ya.[Wait][End]
}

#message:06:(MAC_Housing_00B2) {
	[Style right]
	[PrintRising]Oh, no! It's Mario!![Wait][End]
}

#message:06:(MAC_Housing_00B3) {
	[Style right]
	[Wave][BR]
	[Down 6][Right 105][NOTE][Wait][End]
}

#message:06:(MAC_Housing_00B4) {
	[Style right]
	[Wave][BR]
	[Down 6][Right 90][NOTE] [NOTE] [NOTE][Wait][End]
}

#message:06:(MAC_Housing_00B5) {
	[Style right]
	Well, well. If it isn't Mario![BR]
	[Pause 10]How wonderful to see you![BR]
	[Wait][Next]
	I came to go shopping today.[BR]
	[Pause 10]It was a long walk to get here[BR]
	from Goomba Village...[BR]
	[Wait][Next]
	but it was worth it to see you![BR]
	[Pause 10]I was hoping to see Goombario.[Wait][End]
}

#message:06:(MAC_Housing_00B6) {
	[Style right]
	Goombario, you're looking just[BR]
	fine, aren't you?[BR]
	[Pause 10]You be careful not to be a[BR]
	burden on Mario's adventure.[Wait][End]
}

#message:06:(MAC_Housing_00B7) {
	[Style right]
	Hey! No way I'm a burden![BR]
	[Wait][Next]
	I help out all the time![Wait][End]
}

#message:06:(MAC_Housing_00B8) {
	[Style right]
	Well, well![BR]
	[Pause 10]Our dear little Goombario is[BR]
	helping out the great Mario![BR]
	[Wait][Next]
	I'm so proud![HEART][BR]
	[Pause 10]I'm going to tell Dad and[BR]
	Goompa![BR]
	[Wait][Next]
	Mario, you must come over to our[BR]
	house again someday![Wait][End]
}

#message:06:(MAC_Housing_00B9) {
	[Style right]
	Come on, stop it, Mom![BR]
	[Pause 5]You're embarrassing me.[BR]
	[Wait][Next]
	I'm not a kid anymore.[Wait][End]
}

#message:06:(MAC_Housing_00BA) {
	[Style right]
	Oh, don't be silly, punkin![BR]
	[Pause 10]I'm not saying anything [BR]
	embarrassing at all.[BR]
	[Wait][Next]
	I just love you, that's all.[BR]
	[Pause 10]Can't a mother be proud of her[BR]
	children?[Wait][End]
}

#message:06:(MAC_Housing_00BB) {
	[Style right]
	Aw, Mommmmm...[BR]
	[Pause 10]You always treat me like a kid.[Wait][End]
}

#message:06:(MAC_Housing_00BC) {
	[Style right]
	Nyeah, nyeah![BR]
	[Pause 5]Goombario's getting scolded![Wait][End]
}

#message:06:(MAC_Housing_00BD) {
	[Style right]
	Shut up, Goombaria![Wait][End]
}

#message:06:(MAC_Housing_00BE) {
	[Style right]
	Waaah! Mom![BR]
	[Pause 5]Goombario's being mean![Wait][End]
}

#message:06:(MAC_Housing_00BF) {
	[Style right]
	Goombario. [Pause 5]Good luck and take[BR]
	care of yourself.[BR]
	[Wait][Next]
	Don't forget to visit us.[BR]
	[Wait][Next]
	The whole family worries about[BR]
	you, so you should be sure to[BR]
	stop by our home every once in[BR]
	a while.[Wait][End]
}

#message:06:(MAC_Housing_00C0) {
	[Style right]
	Mario![HEART][BR]
	[Pause 10]Nice to see you again![BR]
	[Wait][Next]
	How's my brother doing?[BR]
	[Pause 10]I really worry about him. After[BR]
	all, I'm his sister.[Wait][End]
}

#message:06:(MAC_Housing_00C1) {
	[Style right]
	Mario...[HEART][BR]
	[Pause 10]Please take good care of my[BR]
	brother, OK?[Wait][End]
}

#message:06:(MAC_Housing_00C2) {
	[Style right]
	Come on, we're in a hurry, [BR]
	Goombaria! Seriously![BR]
	[Pause 5]You're so obnoxious sometimes.[Wait][End]
}

#message:06:(MAC_Housing_00C3) {
	[Style right]
	Be quiet![Wait][End]
}

#message:06:(MAC_Housing_00C4) {
	[Style right]
	Bye, Mario! Good luck![BR]
	Take care, Goombario![Wait][End]
}

#message:06:(MAC_Housing_00C5) {
	[Style right]
	[Voice star]
	Phew![BR]
	[Pause 10]Ahhh, fresh air![BR]
	[Wait][Next]
	After being cooped up in there[BR]
	for so long, I could really use[BR]
	some outdoor exercise.[Wait][End]
}

#message:06:(MAC_Housing_00C6) {
	[Style right]
	[Voice star]
	My name is Muskular.[BR]
	[Pause 15]Mario,[BR]
	[Pause 5]I must thank you for saving me.[BR]
	[Wait][Next]
	Now it's my turn to help you.[BR]
	[Wait][Next]
	Behold![Wait][End]
}

#message:06:(MAC_Housing_00C7) {
	[Style right]
	[Voice star]
	Call on me whenever you find[BR]
	yourself in trouble.[BR]
	[Wait][Next]
	I'll always come quickly to aid[BR]
	you in battle.[BR]
	[Wait][Next]
	Now...[BR]
	[Pause 5]I'm going back to my dear old[BR]
	Star Haven...[Wait][End]
}

#message:06:(MAC_Housing_00C8) {
	[Style right]
	[Voice star]
	[Down 6][PrintRising][Size 32,32]
	Mario![Wait][End]
}

#message:06:(MAC_Housing_00C9) {
	[Style right]
	[Voice star]
	Mario! Mario![BR]
	[Pause 10]I have news...[BR]
	News from the castle...[Wait][End]
}

#message:06:(MAC_Housing_00CA) {
	[Style right]
	[Voice star]
	[PrintRising]Gasp![BR]
	[/PrintRising]Honorable Star Spirit![Wait][End]
}

#message:06:(MAC_Housing_00CB) {
	[Style right]
	[Voice star]
	Hi![BR]
	[Wait][Next]
	Hmm[Pause 3]mmm[Pause 3]mmmmm[Pause 3].[Pause 3].[Pause 3].[BR]
	[Wait][Next]
	I believe you are...[BR]
	[Pause 5]Twink, no?[BR]
	[Wait][Next]
	You're that youngster who[BR]
	recently ascended from[BR]
	Starborn Valley up to Star[BR]
	Haven.[Wait][End]
}

#message:06:(MAC_Housing_00CC) {
	[Style right]
	[Voice star]
	What!?[BR]
	[Pause 10]You remember my name?![Wait][End]
}

#message:06:(MAC_Housing_00CD) {
	[Style right]
	[Voice star]
	Ha ha ha! [Pause 5]Why, of course![BR]
	[Pause 10]We're [Pause 5]like family![Wait][End]
}

#message:06:(MAC_Housing_00CE) {
	[Style right]
	[Voice star]
	I... [Pause 5]I...[BR]
	[Pause 5]I'm so touched!![Wait][End]
}

#message:06:(MAC_Housing_00CF) {
	[Style right]
	[Voice star]
	Ho ho ho![BR]
	[Pause 5]Don't make such a fuss, lad.[BR]
	[Pause 10]I'm sure you'll go on to do great[BR]
	things![BR]
	[Wait][Next]
	I must take my leave now.[BR]
	[Pause 10]Good-bye![BR]
	[Pause 5]Twink, Mario![Wait][End]
}

#message:06:(MAC_Housing_00D0) {
	[Style right]
	[Voice star]
	Wow![BR]
	[Pause 10]I talked with Muskular, the[BR]
	honorable Star Spirit![BR]
	[Wait][Next]
	I rarely have such a chance,[BR]
	even at Star Haven.[BR]
	[Pause 10]I'm shaking![Wait][End]
}

#message:06:(MAC_Housing_00D1) {
	[Style right]
	[Voice star]
	Oops, [Pause 5]I'm sorry![BR]
	[Pause 10]I have some important news[BR]
	from the castle.[Wait][End]
}

#message:06:(MAC_Housing_00D2) {
	[Style right]
	[Voice star]
	According to the information [BR]
	Princess Peach and I got...[BR]
	[Wait][Next]
	It seems that one of the[BR]
	honorable Star Spirits is being[BR]
	held at Mt. Lavalava on[BR]
	Lavalava Island.[BR]
	[Wait][Next]
	You wouldn't believe what the[BR]
	princess went through to get[BR]
	this information.[BR]
	[Wait][Next]
	I hope it will be of help...[Wait][End]
}

#message:06:(MAC_Housing_00D3) {
	[Style right]
	[Voice star]
	I'm going back to rejoin[BR]
	Princess Peach now.[BR]
	[Wait][Next]
	Mario, as always, good luck.[BR]
	[Wait][Next]
	The princess and I will keep[BR]
	looking for useful information.[Wait][End]
}
