#message:08:(MGM_0000) {
	[Style right]
	[Shake][Size 48,48]
	[PrintRising]BLOOPER![Wait][End]
}

#message:08:(MGM_0001) {
	[Style right]
	Well, well. Looky here.[BR]
	Hello, hello, hello![BR]
	[Pause 10]Rip Cheato at your service.[BR]
	[Wait][Next]
	You're quite an enterprising[BR]
	fellow, finding this place.[BR]
	[Wait][Next]
	What am I doing here?[BR]
	Just doing a little business...[BR]
	and minding my own.[BR]
	[Wait][Next]
	You, my friend, have just[BR]
	stumbled into great fortune,[BR]
	for I have a deal for you.[BR]
	[Wait][Next]
	I have something special, and[BR]
	it costs only 64 coins. Deal?[BR]
	[Pause 10]Trust me... It's a bargain.[BR]
	[Yield][End]
}

#message:08:(MGM_0002) {
	[Style right]
	My good sir,[BR]
	[Pause 10]you can't do without this one.[BR]
	[Wait][Next]
	It's worlds better than the[BR]
	last one, but for you, the[BR]
	price is the same: 64 coins.[BR]
	[Wait][Next]
	I, the eminent Rip Cheato,[BR]
	will sleep better knowing[BR]
	you've bought it, for you are[BR]
	a man of great taste.[BR]
	[Wait][Next]
	How about it?[BR]
	[Pause 10]Do we have a deal or not?[BR]
	[Yield][End]
}

#message:08:(MGM_0003) {
	[Style right]
	Ah ha...[BR]
	[Pause 10]So you cannot resist the[BR]
	temptation of my goods![BR]
	[Pause 10]I knew you would return![BR]
	[Wait][Next]
	If you miss this chance, you'll[BR]
	never again find this item at[BR]
	such a low, low price.[BR]
	[Wait][Next]
	Right now--just for you--I'll[BR]
	let it go for a mere 64 coins.[BR]
	[Pause 10]Do we have a deal or not?[BR]
	[Yield][End]
}

#message:08:(MGM_0004) {
	[Style right]
	Well done, my good man![BR]
	[Pause 10]I thank you deeply.[BR]
	[Wait][Next]
	Now, if you thought that item[BR]
	was good...[BR]
	[Wait][Next]
	I have something even better[BR]
	at the same price: 64 coins.[BR]
	[Wait][Next]
	But I warn you, this offer's[BR]
	only good right now.[BR]
	[Pause 10]You'll be kicking yourself if[BR]
	you miss this opportunity![BR]
	[Wait][Next]
	So how about it?[BR]
	[Pause 10]Do we have a deal or not?[BR]
	[Yield][End]
}

#message:08:(MGM_0005) {
	[Next]
	Okay...pinch your pennies.[BR]
	[Pause 10]It's a shame, really.[BR]
	This item's so amazing...[BR]
	[Wait][Next]
	And, well...it could be gone[BR]
	when you come back...[Wait][End]
}

#message:08:(MGM_0006) {
	[Next]
	Oh, this is no good...[BR]
	[Pause 10]I'm afraid I can't sell anything[BR]
	on credit.[BR]
	[Wait][Next]
	Try coming back when you have[BR]
	enough coins.[BR]
	[Wait][Next]
	You'd better hurry, though![BR]
	Items as good as this one[BR]
	don't stay around forever![Wait][End]
}

#message:08:(MGM_0007) {
	[Next]
	Oh, this is unfortunate...[BR]
	[Pause 10]You have too much stuff![BR]
	[Wait][Next]
	Try coming back after selling[BR]
	or checking some of your items[BR]
	in a shop.[Wait][End]
}

#message:08:(MGM_0008) {
	[Style right]
	[PrintRising]Kaaaa-wiiiizzz![BR]
	[/PrintRising][Pause 20][Next]
	Chuck Quizmo's the name,[BR]
	[Pause 10]and quizzes are my game![BR]
	You want quizzes, I got 'em![BR]
	[Wait][Next]
	If you can manage to answer[BR]
	my brain-busting questions[BR]
	correctly, then...[BR]
	[Wait][Next]
	Y... [Pause 3]Yaa... [Pause 5][PrintRising]Yaaaaaahooo![BR]
	[/PrintRising][Pause 15]I'll give you a Star Piece![BR]
	[Wait][Next]
	Want to try a quiz?[BR]
	[Yield][End]
}

#message:08:(MGM_0009) {
	[Style right]
	[PrintRising]Kaaaa-wiiiizzz![BR]
	[/PrintRising][Pause 5]It's everyone's favorite[BR]
	quizmaster, Chuck Quizmo![BR]
	[Wait][Next]
	Want to try the quiz?[BR]
	[Yield][End]
}

#message:08:(MGM_000A) {
	[Style right]
	[PrintRising]Kaaaa-wiiiizzz![BR]
	[/PrintRising][Pause 5]It's everyone's favorite[BR]
	quizmaster, Chuck Quizmo![BR]
	[Wait][Next]
	I know it's a pity, but this is[BR]
	our final quiz show.[BR]
	[Pause 10]Time for the grand finale![BR]
	[Wait][Next]
	I'm a man of a million[BR]
	questions, but this is the[BR]
	last one![BR]
	[Wait][Next]
	Want to try the quiz?[BR]
	[Yield][End]
}

#message:08:(MGM_000B) {
	[Next]
	Then let's go to the question![Wait][End]
}

#message:08:(MGM_000C) {
	[Next]
	Uh, oh. Not up to it, huh?[BR]
	[Pause 5]Maybe another time![BR]
	[Wait][Next]
	Well, well... [Pause 5][Wave]so [Pause 3]long, [Pause 3]fare[Pause 3]well.[BR]
	[Pause 3]'Til we meet again![Wait][End]
}

#message:08:(MGM_000D) {
	[Next]
	Oops! Tough luck, pal![BR]
	[Pause 5][Wave]Wrong answer![BR]
	[/Wave][Wait][Next]
	Better luck next time.[BR]
	[Wait][Next]
	Well, well... [Pause 5][Wave]so [Pause 3]long, [Pause 3]fare[Pause 3]well.[BR]
	[Pause 3]'Til we meet again![Wait][End]
}

#message:08:(MGM_000E) {
	[Next]
	[PrintRising][Wave]Correct![BR]
	[/Wave][/PrintRising][Wait][Next]
	Congratulations![BR]
	[Wait][Next]
	Here's your Star Piece![Wait][End]
}

#message:08:(MGM_000F) {
	[Style right]
	You've correctly answered[BR]
	[Var 0] question[Var 1] so far.[BR]
	[Wait][End]
}

#message:08:(MGM_0010) {
	[Next]
	[PrintRising][Wave]Correct!![BR]
	[/Wave][/PrintRising][Wait][Next]
	Congratulations![BR]
	[Pause 10]This is my last prize![BR]
	[Wait][Next]
	A final Star Piece for you![BR]
	Thanks for playing![Wait][End]
}

#message:08:(MGM_0011) {
	[Style right]
	You've managed to correctly[BR]
	answer all [Var 0] questions.[BR]
	[Pause 10][PrintRising]Incredible!![BR]
	[/PrintRising][Wait][Next]
	Never in all my years did[BR]
	I think I'd find someone who[BR]
	had all the answers![BR]
	[Wait][Next]
	This is truly a momentous[BR]
	and exciting day![BR]
	[Wait][Next]
	I no longer have any regrets.[BR]
	I've reached my peak.[BR]
	I can now retire as quizmaster.[BR]
	[Wait][Next]
	Hee hee![BR]
	[Pause 10]Really? You flatter me![BR]
	[Wait][Next]
	Perhaps our paths will cross[BR]
	again someday.[BR]
	[Wait][Next]
	'Til then...[BR]
	[Pause 5][Wave]so [Pause 3]long, [Pause 3]fare[Pause 3]well.[BR]
	[Pause 3]Bye![Wait][End]
}

#message:08:(MGM_0012) {
	[Style right]
	Hello there, Mario![BR]
	[Pause 5]Welcome to the Playroom![BR]
	[Wait][Next]
	To play here, you need a[BR]
	Member Credit.[BR]
	[Wait][Next]
	The kind of game you can play [BR]
	depends on the kind of [BR]
	Member Credit you have.[BR]
	[Wait][Yield][End]
}

#message:08:(MGM_0013) {
	[Style right]
	Hello there, Mario.[BR]
	[Pause 5]Welcome to the Playroom![BR]
	[Wait][Next]
	To play here, you need a[BR]
	Member Credit.[Wait][End]
}

#message:08:(MGM_0014) {
	[Style right]
	Hello there, Mario![BR]
	[Pause 5]Welcome to the Playroom![BR]
	[Wait][Yield][End]
}

#message:08:(MGM_0015) {
	[Style right]
	Hello there, Mario![BR]
	[Pause 5]Are you enjoying the game?[BR]
	[Wait][Next]
	Did you know there's another [BR]
	game in this Playroom?[BR]
	[Wait][Next]
	If you get a Gold Credit, you [BR]
	can play the other one, too.[Wait][End]
}

#message:08:(MGM_0016) {
	[Style right]
	Hello there, Mario![BR]
	[Pause 5]Welcome to the Playroom![BR]
	[Wait][Yield][End]
}

#message:08:(MGM_0017) {
	[Style right]
	Please enjoy the game.[Wait][End]
}

#message:08:(MGM_0018) {
	[Next]
	Cool! You have a Silver Credit.[BR]
	[Wait][Next]
	In that case, I'll make a pipe[BR]
	appear that will lead down to[BR]
	the Jump Attack floor.[Wait][End]
}

#message:08:(MGM_0019) {
	[Next]
	Cool! You have a Gold Credit.[BR]
	[Wait][Next]
	In that case, I'll make a pipe[BR]
	appear that will lead down to[BR]
	the Smash Attack floor.[Wait][End]
}

#message:08:(MGM_001A) {
	[Next]
	Cool! You have a Gold Credit.[BR]
	[Wait][Next]
	In that case, I'll make a pipe[BR]
	appear that will lead down to[BR]
	both the Jump Attack and Smash[BR]
	Attack floors.[Wait][End]
}

#message:08:(MGM_001B) {
	[Style right]
	Please enjoy the games.[Wait][End]
}

#message:08:(MGM_001C) {
	Results for Jump Attack[End]
}

#message:08:(MGM_001D) {
	Results for Smash Attack[End]
}

#message:08:(MGM_001E) {
	Times Played[End]
}

#message:08:(MGM_001F) {
	Coins Won[End]
}

#message:08:(MGM_0020) {
	Highest Score[End]
}

#message:08:(MGM_0021) {
	Coins[End]
}

#message:08:(MGM_0022) {
	[End]
}

#message:08:(MGM_0023) {
	Times[End]
}

#message:08:(MGM_0024) {
	.[End]
}

#message:08:(MGM_0025) {
	[Style right]
	Y'know, I haven't seen that old[BR]
	Koopa Troopa lately.[BR]
	[Wait][Next]
	He came here often, but[BR]
	[Pause 10]he always lost a bundle.[Wait][End]
}

#message:08:(MGM_0026) {
	[Style right]
	It was never fun when that old[BR]
	Koopa Troopa lost.[BR]
	[Wait][Next]
	He'd blame it on everyone but[BR]
	himself then raise a big stink.[BR]
	[Pause 10]Phew! It was a crazy scene.[Wait][End]
}

#message:08:(MGM_0027) {
	[Style right]
	Hey, are you having a good time[BR]
	here at the Playroom, Mario?[BR]
	[Wait][Next]
	I heard the 9-Blocks Option in [BR]
	Jump Attack is really hard to[BR]
	clear successfully.[BR]
	[Wait][Next]
	Maybe I'll have better odds[BR]
	playing the 5-Blocks Option.[Wait][End]
}

#message:08:(MGM_0028) {
	[Style right]
	Hey, Mario! So you come here,[BR]
	too. Having a good time?[BR]
	[Wait][Next]
	Smash Attack is pretty hard.[BR]
	[Wait][Next]
	I've never cleared it before.[BR]
	[Pause 10]Have you?[Wait][End]
}

#message:08:(MGM_0029) {
	[Style right]
	I'm winning big, baby![Wait][End]
}

#message:08:(MGM_002A) {
	[Style right]
	Grrr... I was so close today![Wait][End]
}

#message:08:(MGM_002B) {
	[Style right]
	I won a little today.[BR]
	[Pause 10]Good luck, Mario.[Wait][End]
}

#message:08:(MGM_002C) {
	[Style right]
	Ugh. Double ugh.[BR]
	[Pause 10]Talk about rotten luck...[Wait][End]
}

#message:08:(MGM_002D) {
	[Style right]
	Greetings, my good man![BR]
	[Pause 10]This is the floor for Jump[BR]
	Attack.[BR]
	[Wait][Next]
	Gimme a second, and I'll explain[BR]
	the rules for you.[BR]
	[Wait][Next]
	Eleven blocks will appear in[BR]
	the air. When you hit one, a[BR]
	panel will come out of it.[BR]
	[Wait][Next]
	There are four kinds of panels.[BR]
	The number of coins you get[BR]
	depends on the order you hit[BR]
	the panels in.[BR]
	[Wait][Next]
	[SavePos][Down 10][InlineImage index=0]
	[SetPosX 40]This is a 1-Coin Panel.[BR]
	[SetPosX 40]It will give you [Color 0x20]1 [Color 0xA]coin.[BR]
	[RestorePos][Down 48][Wait][Scroll 4][SavePos][Down 10][InlineImage index=1]
	[SetPosX 40]This is a 5-Coin Panel.[BR]
	[SetPosX 40]It will give you [Color 0x20]5 [Color 0xA]coins.[BR]
	[RestorePos][Down 48][Wait][Scroll 4][SavePos][Down 10][InlineImage index=2]
	[Up 6][SetPosX 40]This is a 5-Times Panel.[BR]
	[SetPosX 40]Your coins will be multiplied[BR]
	[Color 0x20][SetPosX 40]5 [Color 0xA]times.[BR]
	[RestorePos][Down 48][Wait][Scroll 4][SavePos][Down 10][InlineImage index=3]
	[Up 10][SetPosX 40]This is a Bowser Panel.[BR]
	[SetPosX 40]If you find this panel,[BR]
	[SetPosX 40]unfortunately, it's[BR]
	[Color 0x20][SetPosX 40]Game Over[Color 0xA].[BR]
	[RestorePos][Down 48][Wait][Scroll 4]If you clear the 9-Blocks[BR]
	Option, as a special bonus,[BR]
	your coins will be [Color 0x20]doubled[Color 0xA].[BR]
	[Wait][Scroll 3]The rules are written on that[BR]
	board over there.[BR]
	[Wait][Scroll 2]I think you'll catch on quickly[BR]
	once you start playing.[BR]
	[Pause 10]Anyway, you might as well try[BR]
	it at least once.[BR]
	[Wait][Scroll 4]You need ten coins to play.[BR]
	[Pause 10]How about it? Wanna try?[BR]
	[Yield][End]
}

#message:08:(MGM_002E) {
	[Style right]
	Welcome![BR]
	[Pause 10]You need ten coins to play.[BR]
	[Pause 10]How about it? Wanna try?[BR]
	[Yield][End]
}

#message:08:(MGM_002F) {
	[Next]
	Try to hit five blocks.[BR]
	[Wait][Yield][Next]
	Get ready to...[BR]
	[Wait][InputOff]
	[Next]
	[Down 8][Size 32,32]
	[Wave]JUMP...[BR]
	[/Wave][Down 6][Yield][Scroll 4][Down 5][Size 48,48]
	[PrintRising]ATTACK!!![BR]
	[Yield][End]
}

#message:08:(MGM_0030) {
	[Next]
	Try to hit seven blocks.[BR]
	[Wait][Yield][Next]
	Get ready to...[BR]
	[Wait][InputOff]
	[Next]
	[Down 8][Size 32,32]
	[Wave]JUMP...[BR]
	[/Wave][Down 6][Yield][Scroll 4][Down 5][Size 48,48]
	[PrintRising]ATTACK!!![BR]
	[Yield][End]
}

#message:08:(MGM_0031) {
	[Next]
	Try to hit nine blocks.[BR]
	[Wait][Yield][Next]
	Get ready to...[BR]
	[Wait][InputOff]
	[Next]
	[Down 8][Size 32,32]
	[Wave]JUMP...[BR]
	[/Wave][Down 6][Yield][Scroll 4][Down 5][Size 48,48]
	[PrintRising]ATTACK!!![BR]
	[Yield][End]
}

#message:08:(MGM_0032) {
	[Next]
	Whatever suits you.[BR]
	[Pause 10]Come again sometime![BR]
	[Wait][Next]
	See you.[Wait][End]
}

#message:08:(MGM_0033) {
	[Style right]
	Get jumping, Mario![BR]
	[Pause 10]You need to hit [Var 0] more block[Var 1].[Wait][End]
}

#message:08:(MGM_0034) {
	[Style right]
	Oops... Bummer![BR]
	[Pause 5]Game over.[BR]
	[Wait][Next]
	Too bad.[BR]
	[Pause 5]Better luck next time.[Wait][End]
}

#message:08:(MGM_0035) {
	[Style right]
	5-Blocks Option cleared![BR]
	[Pause 5]You get [Var 0] coins![Wait][End]
}

#message:08:(MGM_0036) {
	[Style right]
	7-Blocks Option cleared![BR]
	[Pause 5]You get [Var 0] coins![Wait][End]
}

#message:08:(MGM_0037) {
	[Style right]
	Wow! Yeah![BR]
	[Pause 5]9-Blocks Option cleared![BR]
	[Wait][Next]
	As a special bonus, your coins[BR]
	will be doubled![Wait][End]
}

#message:08:(MGM_0038) {
	[Style right]
	You get [Var 0] coins!![Wait][End]
}

#message:08:(MGM_0039) {
	[Wait][Next]
	...Mario,[BR]
	[Pause 5]you don't have ten coins.[BR]
	[Wait][Next]
	You can't play the game[BR]
	without enough coins.[Wait][End]
}

#message:08:(MGM_003A) {
	[Style right]
	Come again sometime![Wait][End]
}

#message:08:(MGM_003B) {
	[DelayOff]
	[Style sign]
	[BR]
	[Down 2][Right 40]Rules for Jump Attack[BR]
	[Down 6][BR]
	[Down 4]When the game starts, eleven[BR]
	blocks will appear in the air.[BR]
	When you hit a block, a panel[BR]
	will come out of it.[BR]
	There are four kinds of panels.[BR]
	Hitting blocks is the only way[BR]
	to make the panels appear.[BR]
	[BR]
	The coins you get will be[BR]
	determined by the order you[BR]
	hit the panels in.[BR]
	[BR]
	[SavePos][Down 10][InlineImage index=0]
	[SetPosX 40]This is a 1-Coin Panel.[BR]
	[SetPosX 40]It will give you [Color 0x20]1 [Color 0xA]coin.[BR]
	[RestorePos][Down 48][SavePos][Down 10][InlineImage index=1]
	[SetPosX 40]This is a 5-Coin Panel.[BR]
	[SetPosX 40]It will give you [Color 0x20]5 [Color 0xA]coins.[BR]
	[RestorePos][Down 48][SavePos][Down 10][InlineImage index=2]
	[Up 6][SetPosX 40]This is a 5-Times Panel.[BR]
	[SetPosX 40]Your coins will be multiplied [BR]
	[Color 0x20][SetPosX 40]5 [Color 0xA]times.[BR]
	[RestorePos][Down 48][SavePos][Down 10][InlineImage index=3]
	[Up 10][SetPosX 40]This is a Bowser Panel.[BR]
	[SetPosX 40]If you find this panel,[BR]
	[SetPosX 40]unfortunately, it's[BR]
	[Color 0x20][SetPosX 40]Game Over[Color 0xA].[BR]
	[RestorePos][Down 48]If you clear the 9-Blocks[BR]
	Option, your coins will be[BR]
	doubled as a special bonus![BR]
	You need ten coins to play.[BR]
	[DelayOn]
	[Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][DelayOn]
	[Wait][End]
}

#message:08:(MGM_003C) {
	[Style right]
	Hello, Mario![BR]
	[Pause 10]This is the floor for Smash[BR]
	Attack.[BR]
	[Wait][Next]
	Let me explain the rules to[BR]
	you, OK?[BR]
	[Wait][Next]
	When the game starts, blocks [BR]
	will appear along the ground.[BR]
	[Wait][Next]
	When you hit a block, something[BR]
	will come out of it.[BR]
	[Wait][Next]
	[SavePos][Down 10][InlineImage index=0]
	[Up 10][SetPosX 40]You'll clear the game[BR]
	[SetPosX 40]if you get ten of[BR]
	[SetPosX 40]these Peach Panels[BR]
	[SetPosX 40]before time runs out.[BR]
	[RestorePos][Down 48][Wait][Scroll 4]If you hit a block where a[BR]
	Fuzzy or Bob-omb is hiding, [BR]
	it'll slow you down a bit.[BR]
	[Wait][Next]
	The time limit is 30 seconds.[BR]
	[Pause 10]You need ten coins to play. [BR]
	Would you like to try?[BR]
	[Yield][End]
}

#message:08:(MGM_003D) {
	[Style right]
	Welcome to Smash Attack![BR]
	[Pause 10]You need ten coins to play. [BR]
	Like to give it a try?[BR]
	[Yield][End]
}

#message:08:(MGM_003E) {
	[Wait][Next]
	...Mario, you don't have ten[BR]
	coins.[BR]
	[Wait][Next]
	Please bring more money with[BR]
	you next time.[Wait][End]
}

#message:08:(MGM_003F) {
	[Next]
	Ready to get ten Peach Panels?[BR]
	[Wait][Yield][Next]
	Get set to...[BR]
	[Wait][InputOff]
	[Next]
	[Down 8][Size 32,32]
	[Wave]SMASH...[BR]
	[/Wave][Down 10][Yield][Scroll 4][Down 5][Size 48,48]
	[PrintRising]ATTACK!!![BR]
	[Yield][End]
}

#message:08:(MGM_0040) {
	[Next]
	Another time, perhaps.[Wait][End]
}

#message:08:(MGM_0041) {
	[Style right]
	[InputOff]
	[Down 8][Size 32,32]
	Game [Pause 15]Over[BR]
	[SizeReset]
	[Pause 15][InputOn]
	[End]
}

#message:08:(MGM_0042) {
	[Style right]
	Game cleared![BR]
	[Wait][Next]
	The remaining time is [Var 0].[Var 1]...[BR]
	So, [Pause 10]well... [Pause 15]You get [Var 2] coins![BR]
	[Yield][Wait][End]
}

#message:08:(MGM_0043) {
	[Style right]
	Game cleared![BR]
	[Wait][Next]
	The remaining time is...[BR]
	[Pause 15]Oh. [Pause 5]Too bad! Zero seconds.[BR]
	You don't get any coins.[BR]
	[Wait][Next]
	Better luck next time.[Wait][End]
}

#message:08:(MGM_0044) {
	[Style right]
	No more time![BR]
	[Pause 10]Too bad.[BR]
	[Wait][Next]
	Please come again.[Wait][End]
}

#message:08:(MGM_0045) {
	Please come again.[Wait][End]
}

#message:08:(MGM_0046) {
	[DelayOff]
	[Style sign]
	[BR]
	[Down 2][Right 35]Rules for Smash Attack[BR]
	[Down 6][BR]
	[Down 4][BR]
	When the game starts, blocks [BR]
	will appear along the ground.[BR]
	[BR]
	[BR]
	When you hit a block, something[BR]
	will pop out of it.[BR]
	[BR]
	[SavePos][Down 10][InlineImage index=0]
	[Up 10][SetPosX 40]You'll clear the game[BR]
	[SetPosX 40]if you get ten of[BR]
	[SetPosX 40]these Peach Panels[BR]
	[SetPosX 40]before time runs out.[BR]
	[RestorePos][Down 48]If you hit a block where a[BR]
	Fuzzy or Bob-omb is hiding,[BR]
	you'll be immobilized briefly.[BR]
	[BR]
	The time limit is 30 seconds.[BR]
	It costs ten coins to play.[BR]
	[BR]
	[BR]
	[DelayOn]
	[Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][DelayOn]
	[Wait][End]
}

#message:08:(MGM_0047) {
	more[End]
}

#message:08:(MGM_0048) {
	panels[End]
}

#message:08:(MGM_EndOfCurrentQuestions) {
	[Style right]
	Well, well... [Pause 5][Wave]so [Pause 3]long, [Pause 3]fare[Pause 3]well.[BR]
	[Pause 3]'Til we meet again![BR]
	[Wait][End]
}

#message:08:(MGM_AskIfNextQuestion) {
	[Style right]
	But we're not done yet![BR]
	Are you ready to answer[BR]
	another question?[BR]
	[Yield][End]
}

#message:08:(MGM_NextQuestionDeclined) {
	[Next]
	Uh, oh. Not up to it, huh?[BR]
	Maybe another time![BR]
	[Wait][Next]
	Well, well... [Pause 5][Wave]so [Pause 3]long, [Pause 3]fare[Pause 3]well.[BR]
	[Pause 3]'Til we meet again![BR]
	[Wait][End]
}

#message:08:(MGM_LetsGoToNextQuestion) {
	[Next]
	Then let's go to the question![BR]
	[Wait][End]
}


#message:08:(BooTrial_Intoduction_BeforeCh3) {
	[Style right]
	Hello, Mario![BR]
	Are you interested in testing[BR]
	your combat skills?[BR]
	[Wait][Next]
	Normally, I would be in[BR]
	Boo's Mansion, but due to[BR]
	[Wave]certain events[/Wave], we can't accept[BR]
	strangers there for now...[BR]
	[Wait][Next]
	Regardless, I can offer you some[BR]
	Boo Trials in Toad Town right now.[BR]
	[Wait][Next]
	Boo trials are a series of battles[BR]
	which you have to beat in a row,[BR]
	sharing a common theme.[BR]
	[Wait][Next]
	The first time you beat a trial,[BR]
	you get a special reward, as well[BR]
	as some Star Points, regardless[BR]
	of whether you depleted the[BR]
	[Wait][Next]
	Star Point Pool for those enemies[BR]
	earlier in your adventures.[BR]
	[Wait][Next]
	The further you progress, the[BR]
	more Trials I can offer you.[BR]
	[Wait][Next]
	Oh, but this is not for free.[BR]
	Each Trial has its own coin cost,[BR]
	though it's never too high.[BR]
	[Wait][Next]
	So, are you interested in a Trial?[BR]
	[Wait][End]
}

#message:08:(BooTrial_Intoduction_Again) {
	[Style right]
	Hello, Mario![BR]
	Interested in a trial?[BR]
	[Wait][End]
}

#message:08:(BooTrial_Intoduction_SwappingFormation) {
	[Style right]
	Well done! However, there's[BR]
	still more fights to go![BR]
	[Wait][End]
}

#message:08:(BooTrial_Intoduction_TrialSuccessFirstTime) {
	[Style right]
	Congratulations! That was some[BR]
	wonderful fighting.[BR]
	[Wait][Next]
	Since this is the first time you[BR]
	bested this Trial, here's a reward![BR]
	[Wait][End]
}

#message:08:(BooTrial_Intoduction_TrialSuccess) {
	[Style right]
	Congratulations! That was some[BR]
	wonderful fighting.[BR]
	[Wait][End]
}

#message:08:(BooTrial_Ch1_Name) {
	Chapter 1[End]
}

#message:08:(BooTrial_Ch1_Desc) {
	A standard showdown against[BR]
	enemies from Chapter 1.[End]
}


