#message:0B:(CH0_0000) {
	[Style right]
	[Voice star]
	[DitherFade 217]Oh, thank heavens![BR]
	[Pause 10]He's been gravely injured, but I[BR]
	think he'll recover.[Wait][End]
}

#message:0B:(CH0_0001) {
	[Style right]
	[Voice star]
	[DitherFade 217]But Bowser has the Star Rod![BR]
	Now he's mightier than Mario![BR]
	[Wait][Next]
	It's hopeless! All is lost![Wait][End]
}

#message:0B:(CH0_0002) {
	[Style right]
	[Voice star]
	[DitherFade 217]Everybody just calm down.[BR]
	[Pause 10]As long as we keep it together,[BR]
	there's always hope. Now...[BR]
	[Wait][Next]
	Our fates are in Mario's hands.[BR]
	We must try to revive him.[BR]
	[Wait][Next]
	Gather round, everyone.[BR]
	[Pause 15]Send Mario your power![Wait][End]
}

#message:0B:(CH0_0003) {
	[Style right]
	[Voice star]
	[DitherFade 217]Phew...that's it. That's all we[BR]
	can do right now.[BR]
	[Wait][Next]
	Mario...[BR]
	[Pause 10]Please get up... Please...[Wait][End]
}

#message:0B:(CH0_0004) {
	[Style right]
	It really sounded like something[BR]
	fell somewhere around here...[BR]
	[Wait][Next]
	Oh[Pause 3].[Pause 3].[Pause 3].[BR]
	[Pause 10]Who could that be?[Wait][End]
}

#message:0B:(CH0_0005) {
	[Style right]
	This red shirt, [Pause 5]this hat, [Pause 5]and[BR]
	this mustache...[BR]
	[Pause 10]You know, this really looks like[BR]
	the one and only Mario![BR]
	[Wait][Next]
	It couldn't be...could it?[BR]
	[Pause 10]The real Mario?[Wait][End]
}

#message:0B:(CH0_0006) {
	[Style right]
	[PrintRising]Hey! [Pause 4]Hey! Wake up![BR]
	[Pause 8]C'mon!! Up and at 'em!![BR]
	[/PrintRising][Wait][Next]
	Oh no! He won't wake up!!![Wait][End]
}

#message:0B:(CH0_0007) {
	[Style right]
	Oh, oh, what am I gonna do!?[Wait][End]
}

#message:0B:(CH0_0008) {
	[Style right]
	[PrintRising]Dad!![BR]
	[Pause 5]Goom-pa!![BR]
	[Pause 5]Goom-ba-rio!!![Wait][End]
}

#message:0B:(CH0_0009) {
	[Style right]
	[Voice star]
	[DitherFade 217][Pause 10]Mario...[BR]
	[Pause 10]Can you hear me, Mario...?[BR]
	[Wait][Next]
	I'm Eldstar, a Star Spirit...[BR]
	[Pause 15]I have something very important[BR]
	to tell you...[BR]
	[Wait][Next]
	It concerns the princess...and[BR]
	all of the Mushroom Kingdom...[BR]
	[Wait][Next]
	[Pause 10]But sadly,[BR]
	[Pause 5]I haven't the strength to talk[BR]
	to you here...[BR]
	[Wait][Next]
	Mario...[BR]
	[Pause 10]I need to have you come to[BR]
	[Color 0x20]Shooting Star Summit[Color 0xA].[BR]
	[Pause 10][Wait][Next]
	[Pause 5]Please... Mario...[BR]
	[Pause 10]We Star Spirits will be waiting[BR]
	for you at the summit...[Wait][End]
}

#message:0B:(CH0_000A) {
	[Style right]
	Oh...[Pause 5]Mario![BR]
	[Wait][Next]
	I'm so happy[BR]
	[Pause 10]to see you awake![Wait][End]
}

#message:0B:(CH0_000B) {
	[Style right]
	You haven't opened your eyes[BR]
	for days and days![BR]
	Everyone's been worried sick![Wait][End]
}

#message:0B:(CH0_000C) {
	[Style right]
	This place?[BR]
	[Wait][Next]
	This is [Color 0x20]Goomba Village[Color 0xA].[BR]
	[Pause 10]It's a tiny village that's just[BR]
	west of [Color 0x20]Toad Town[Color 0xA].[BR]
	[Wait][Next]
	The only residents are me and a[BR]
	single family of Goombas.[Wait][End]
}

#message:0B:(CH0_000D) {
	[Style right]
	The Goombas in the family are[BR]
	just the nicest folks you'll ever[BR]
	meet.[BR]
	[Wait][Next]
	They're the ones who found you[BR]
	unconscious in the forest and[BR]
	carried you here to get better. [Wait][End]
}

#message:0B:(CH0_000E) {
	[Style right]
	Huh...?[BR]
	[Pause 5]A Star with a mustache?[BR]
	[Pause 10]You're saying a star told you to[BR]
	go to Shooting Star Summit?[Wait][End]
}

#message:0B:(CH0_000F) {
	[Style right]
	No, [Pause 4]I saw nothing like that.[BR]
	[Pause 10]And I sure didn't see anyone[BR]
	come in or out of this house.[BR]
	[Wait][Next]
	I wonder, Mario...[BR]
	[Pause 10]Maybe you just had a dream?[Wait][End]
}

#message:0B:(CH0_0010) {
	[Style right]
	Although maybe not...[BR]
	[Pause 10]It could have been some sort of[BR]
	message from a Star Spirit.[BR]
	They live in Star Haven.[BR]
	[Wait][Next]
	Shooting Star Summit is the [BR]
	nearest place to Star Haven, so[BR]
	that would make sense...[Wait][End]
}

#message:0B:(CH0_0011) {
	[Style right]
	Who knows? In any case, I'm glad[BR]
	to see you've recovered.[BR]
	[Wait][Next]
	I know the Goombas would be[BR]
	happy if you paid them a visit.[Wait][End]
}

#message:0B:(CH0_0012) {
	[Style right]
	Please feel free to come here[BR]
	anytime you get tired.[BR]
	[Wait][Next]
	A good nap will work wonders[BR]
	when you're feeling weak.[Wait][End]
}

#message:0B:(CH0_0013) {
	[Style right]
	The Toad House's slogan is...[BR]
	[Pause 10]"Refresh your Body and Mind!"[BR]
	[Wait][Next]
	Anytime you feel tired, a good[BR]
	rest will fix you right up.[BR]
	[Wait][Next]
	Would you like to take a nap?[BR]
	[Yield][End]
}

#message:0B:(CH0_0014) {
	[Style right]
	Welcome to the Toad House! Our[BR]
	slogan is, "Refresh your Body[BR]
	and Mind!"[BR]
	[Wait][Next]
	Would you like to take a nap?[BR]
	[Yield][End]
}

#message:0B:(CH0_0015) {
	[Style right]
	...Really?[BR]
	[Pause 10]You look pretty healthy to me.[BR]
	[Pause 10]Are you sure you want to take a[BR]
	nap?[BR]
	[Yield][End]
}

#message:0B:(CH0_0016) {
	[Next]
	Please come again.[Wait][End]
}

#message:0B:(CH0_0017) {
	[Next]
	Make yourself comfortable and[BR]
	enjoy your stay.[Wait][End]
}

#message:0B:(CH0_0018) {
	[Style right]
	Did you sleep well?[BR]
	[Wait][Next]
	Take care now![Wait][End]
}

#message:0B:(CH0_0019) {
	[Style right]
	Ooh, you startled me![BR]
	[Pause 10]Hm, yes, Mario, isn't it?[BR]
	[Wait][Next]
	So you've awakened at last![BR]
	Good! Knew you'd pull through![BR]
	[Wait][Next]
	Call me Goompa.[BR]
	[Pause 15]I'm the Goomba grandfather,[BR]
	so...I'm Goompa.[BR]
	[Wait][Next]
	I'm sorry, but would you mind[BR]
	giving me the details later?[BR]
	[Wait][Next]
	I'm pretty busy fixing the[BR]
	veranda.[Wait][End]
}

#message:0B:(CH0_001A) {
	[Style right]
	Did you feel that earthquake the[BR]
	other day, young feller? It[BR]
	caused all kinds of damage.[BR]
	[Wait][Next]
	But little by little, Goompapa[BR]
	and I are fixing it all up.[BR]
	[Wait][Next]
	Folks are saying the center of[BR]
	the earthquake was right at[BR]
	Princess Peach's Castle.[BR]
	[Pause 10]Boy, I sure hope not.[Wait][End]
}

#message:0B:(CH0_001B) {
	[Style right]
	Did you feel that earthquake the[BR]
	other day, young feller? It[BR]
	caused all kinds of damage.[BR]
	[Wait][Next]
	But little by little, Goompapa[BR]
	and I are fixing it all up.[BR]
	[Wait][Next]
	Folks are saying the center of[BR]
	the earthquake was right at[BR]
	Princess Peach's Castle.[BR]
	[Pause 10]Boy, I sure hope not.[Wait][End]
}

#message:0B:(CH0_001C) {
	[Style right]
	Never worry, kids, here I am.[BR]
	[Pause 5]Thanks to young Mario here, I[BR]
	made it back all right.[Wait][End]
}

#message:0B:(CH0_001D) {
	[Style right]
	Oh, is that thing locked?[BR]
	[Pause 10]Let me open it up for you.[Wait][End]
}

#message:0B:(CH0_001E) {
	[Style right]
	Goompa![BR]
	[Pause 10]Where've you been?[BR]
	[Wait][Next]
	I looked outside and...wow![BR]
	[Pause 10]Both you and the veranda were[BR]
	just plain gone![Wait][End]
}

#message:0B:(CH0_001F) {
	[Style right]
	Goompa,[BR]
	[Pause 10]I was very, very worried about[BR]
	you! Really worried![Wait][End]
}

#message:0B:(CH0_0020) {
	[Style right]
	Sorry, kids, I apologize. [BR]
	[Pause 10]I didn't mean to make you fret.[BR]
	You just take it easy, now.[BR]
	[Wait][Next]
	I'm back safe and sound.[Wait][End]
}

#message:0B:(CH0_0021) {
	[Style right]
	Now![BR]
	[Wait][Next]
	Before I forget, I've decided to[BR]
	give you something, Mario.[BR]
	[Pause 10]Wait here a minute.[Wait][End]
}

#message:0B:(CH0_0022) {
	[Style right]
	Huh?[BR]
	[Pause 10]Hey... That dolly you've got...[BR]
	That's the one Goombaria lost![BR]
	[Wait][Next]
	She was looking all over for it.[BR]
	[Pause 10]Would you give it back to her?[BR]
	[Yield][End]
}

#message:0B:(CH0_0023) {
	[Next]
	Aw, that's just mean, Mario...[BR]
	[Wait][Next]
	I guess you can just give it[BR]
	back when you're done with it.[Wait][End]
}

#message:0B:(CH0_0024) {
	[Style right]
	[PrintRising]It's my dolly! Dolly, dolly![BR]
	[Pause 20]You're back!![BR]
	[/PrintRising]Thank you so much![HEART][BR]
	[Wait][Next]
	I'm so happy...[BR]
	[Pause 10]My sweet dolly! Don't you ever[BR]
	get lost again![Wait][End]
}

#message:0B:(CH0_0025) {
	[Style right]
	Here's a present from me![BR]
	[Pause 10]Look at the pretty glitter![Wait][End]
}

#message:0B:(CH0_0026) {
	[Style right]
	And [Pause 10]take this, [Pause 10]too![Wait][End]
}

#message:0B:(CH0_0027) {
	[Style right]
	You always seem to beat up your[BR]
	enemies... Do you work out?[BR]
	[Wait][Next]
	I study self-defense by reading[BR]
	books by the masters and[BR]
	listening to Dad and Goompa.[BR]
	[Wait][Next]
	And, I also exercise every day[BR]
	so I can be strong like you![BR]
	[Pause 10]It's starting to show, too! I'm[BR]
	getting big muscles![Wait][End]
}

#message:0B:(CH0_0028) {
	[Style right]
	Yeah, Goombario's head is hard[BR]
	as a rock now! Tee hee! [BR]
	[Wait][Next]
	When he does his Headbonk move,[BR]
	it really, really hurts![Wait][End]
}

#message:0B:(CH0_0029) {
	[Style right]
	Oh, be quiet, Goombaria! You're[BR]
	embarrassing me![BR]
	[Pause 10]Of course, it IS true...[Wait][End]
}

#message:0B:(CH0_002A) {
	[Style right]
	Sorry to have kept you waiting,[BR]
	Mario.[Wait][End]
}

#message:0B:(CH0_002B) {
	[Style right]
	It's OK, Goompa![BR]
	[Pause 10]We're just rapping with Mario...[Wait][End]
}

#message:0B:(CH0_002C) {
	[Style right]
	Oh. "Rapping," huh? Sorry.[BR]
	[Pause 10]I wanted to give this to Mario.[Wait][End]
}

#message:0B:(CH0_002D) {
	[Style right]
	This is called a [Color 0x20]Badge[Color 0xA].[BR]
	[Wait][Next]
	If you wear this, you'll be able[BR]
	to do a Power Jump, which means[BR]
	you'll be able to do a lot more[BR]
	damage with your Jump attack.[BR]
	[Wait][Next]
	But listen here, and listen well.[BR]
	You'll only be able to do it if[BR]
	you're wearing the Badge.[BR]
	[Wait][End]
}

#message:0B:(CH0_002E) {
	[Next]
	You'd better listen, Mario. This[BR]
	is really important![BR]
	[Pause 10]Could I please give you a brief[BR]
	lesson in Badges?[BR]
	[Yield][End]
}

#message:0B:(CH0_002F) {
	[Next]
	All right, I trust you.[Wait][End]
}

#message:0B:(CH0_0030) {
	[Next]
	OK, then press [START].[BR]
	[Pause 10]The menu will open.[BR]
	[Yield][End]
}

#message:0B:(CH0_0031) {
	[Style right]
	Now remember, you need[BR]
	[Color 0x20]FP (Flower Points) [Color 0xA]to use this[BR]
	Power Jump technique.[BR]
	[Wait][Next]
	[SavePos][Down 8][InlineImage index=0]
	[RestorePos][SetPosX 40][Down 6]Do you remember that we[BR]
	[SetPosX 40]saw a block like this on the[BR]
	[SetPosX 40]way back to the village?[BR]
	[Up 6][BR]
	[Wait][Next]
	Well, these blocks will restore[BR]
	not only HP but also FP.[BR]
	[Wait][Next]
	They're lifesavers, Mario! Use[BR]
	them whenever your HP and FP[BR]
	reserves are getting low.[Wait][End]
}

#message:0B:(CH0_0032) {
	[Style right]
	By the by, Mario,[BR]
	[Pause 15]I heard from Gooma...[BR]
	[Wait][Next]
	You're taking it upon yourself to[BR]
	try to rescue the princess[BR]
	from Bowser's clutches.[Wait][End]
}

#message:0B:(CH0_0033) {
	[Style right]
	Oh yeah! Mario can beat Bowser[BR]
	with one hand tied behind his[BR]
	back![Wait][End]
}

#message:0B:(CH0_0034) {
	[Style right]
	Hush, now, Goombario. Mario,[BR]
	please take this Hammer.[BR]
	[Wait][Next]
	It should serve you well. If I[BR]
	were just a bit younger, I'd[BR]
	accompany you on your trip. I'd[BR]
	have done some damage![BR]
	[Wait][Next]
	The years have started to weigh[BR]
	on me, though. I tell you, this[BR]
	lower back pain...[Wait][End]
}

#message:0B:(CH0_0035) {
	[Style right]
	Adventure...you're so lucky![BR]
	[Wait][Next]
	Princess-rescuing is so cool![BR]
	[Pause 10]I really want to be an[BR]
	adventurer, too, someday![Wait][End]
}

#message:0B:(CH0_0036) {
	[Style right]
	Me too!![Wait][End]
}

#message:0B:(CH0_0037) {
	[Style right]
	Oh! [Pause 5]Here's an idea![BR]
	[Pause 15]Goombario...[BR]
	[Wait][Next]
	Perhaps the timing is perfect.[BR]
	You are no longer a child, and[BR]
	evil times are upon us.[BR]
	[Wait][Next]
	I'm sure Mario will agree...[BR]
	[Pause 15]You should accompany Mario.[Wait][End]
}

#message:0B:(CH0_0038) {
	[Style right]
	What!? Really!? May I go,[BR]
	Goompa!? May I really go!? [BR]
	[Wait][Next]
	[PrintRising]Yes!!!!! Oh yeah!!![BR]
	[/PrintRising][Wait][Next]
	Mario! You won't regret this![Wait][End]
}

#message:0B:(CH0_0039) {
	[Style right]
	Way to go, Goombario![Wait][End]
}

#message:0B:(CH0_003A) {
	[Style right]
	Mario,[BR]
	[Pause 15]I know Goombario will prove to be[BR]
	a worthy companion.[BR]
	[Wait][Next]
	...Well, I think it's about time for[BR]
	my nap. I'll be in the house.[BR]
	[Wait][Next]
	Good-byes have a way of making[BR]
	this old Goomba get weepy.[Wait][End]
}

#message:0B:(CH0_003B) {
	[Style right]
	This is so cool! Mario![BR]
	[Pause 10][PrintRising][DelayOff]
	Let's go!![BR]
	[DelayOn]
	[Wait][End]
}

#message:0B:(CH0_003C) {
	[Style right]
	This is so cool! Mario![BR]
	[Pause 10][PrintRising][DelayOff]
	Let's go!![BR]
	[DelayOn]
	[/PrintRising][Wait][Next]
	But wait...[BR]
	[Pause 10]Your HP looks a little low.[BR]
	[Wait][Next]
	Maybe you ought to take a rest[BR]
	at the Toad House.[Wait][End]
}

#message:0B:(CH0_003D) {
	[Style right]
	Ah! Goombario,[BR]
	[Pause 10]I expect that you'll become a[BR]
	fine, upstanding young Goomba by[BR]
	the time you return.[Wait][End]
}

#message:0B:(CH0_003E) {
	[Style right]
	Mario, [Pause 10]you should know that[BR]
	danger lurks everywhere.[BR]
	It can even strike while you're[BR]
	fixing the veranda![BR]
	[Wait][Next]
	I know you get used to danger[BR]
	while you're adventuring, but[BR]
	don't ever scoff at it![BR]
	[Pause 20]You should always be careful![Wait][End]
}

#message:0B:(CH0_003F) {
	[Style right]
	So, Mario, how goes the[BR]
	adventure thus far?[BR]
	[Wait][Next]
	Are you keeping cool?[BR]
	[Pause 10]Keep your wits about you and[BR]
	you'll beat Bowser hands down.[Wait][End]
}

#message:0B:(CH0_0040) {
	[Style right]
	Mario, [Pause 10]how have you been?[BR]
	[Pause 15]You must have traveled all over[BR]
	the Mushroom Kingdom by now![BR]
	[Wait][Next]
	Is Goombario pulling his weight?[BR]
	[Wait][Next]
	The day you beat Bowser will be[BR]
	a fine time, yes indeedy![Wait][End]
}

#message:0B:(CH0_0041) {
	[Style right]
	Goombario, [Pause 10]how are you doing? I'm[BR]
	waiting for the day you come[BR]
	back a full-grown Goomba of the[BR]
	world![Wait][End]
}

#message:0B:(CH0_0042) {
	[Style right]
	Even out here we hear stories of[BR]
	your remarkable deeds![BR]
	[Wait][Next]
	Keep up the good work![Wait][End]
}

#message:0B:(CH0_0043) {
	[Style right]
	Goombario,[BR]
	[Pause 10]Your family misses you.[BR]
	[Pause 5]Come back to us soon![Wait][End]
}

#message:0B:(CH0_0044) {
	[Style right]
	Goompa,[BR]
	[Pause 10]I'll do my best![Wait][End]
}

#message:0B:(CH0_0045) {
	[Style right]
	You're Goompa, correct?[BR]
	[Wait][Next]
	The name's Parakarry. I deliver[BR]
	letters.[BR]
	[Wait][Next]
	I believe I have one for you.[BR]
	[Pause 10]Hang on a moment.[Wait][End]
}

#message:0B:(CH0_0046) {
	[Style right]
	Oh...no! Confound it![BR]
	[Pause 10]I seem to have lost it![BR]
	[Pause 10]...I'm terribly sorry.[Wait][End]
}

#message:0B:(CH0_0047) {
	[Style right]
	Another letter, duly delivered.[BR]
	A postman's job is never done.[Wait][End]
}

#message:0B:(CH0_0048) {
	[Style right]
	Now what could this be...?[BR]
	[Pause 10]Koopa Koot...?[BR]
	[Pause 5]Eh...I have a bad feeling about[BR]
	this, so I'll read it later.[BR]
	[Wait][Next]
	It's probably the old Koot's usual[BR]
	backstabbing gossip.  [BR]
	[Pause 10]He really needs to get out more.[BR]
	[Wait][Next]
	What's the point of sending all[BR]
	of these gossipy letters? Huh?[BR]
	[Wait][Next]
	I know you're pretty busy, so[BR]
	thanks for delivering this.[BR]
	[Pause 10]Why don't you take this as a[BR]
	token of my thanks?[Wait][End]
}

#message:0B:(CH0_0049) {
	[Style right]
	Hm, Mario.[BR]
	[Pause 10]It looks like something else is on[BR]
	your mind.[Wait][End]
}

#message:0B:(CH0_004A) {
	[Style right]
	What!?[BR]
	[Pause 10]Koopa Koot said he wants "The[BR]
	Tape" back?[BR]
	[Wait][Next]
	That old Koopa...[BR]
	[Pause 5]How does he remember things[BR]
	from so long ago?[BR]
	[Wait][Next]
	[Pause 10]OK...[BR]
	[Pause 5]Wait for just a minute. I'll bring[BR]
	it out for you.[Wait][End]
}

#message:0B:(CH0_004B) {
	[Style right]
	Here. [Pause 5]This is it.[BR]
	[Pause 10]When you see that old Koopa,[BR]
	give him my regards.[Wait][End]
}

#message:0B:(CH0_004C) {
	[Style right]
	What's that?[BR]
	[Pause 10]You want to know what's on The[BR]
	Tape, do you?[BR]
	[Wait][Next]
	Oh, no no... I'm sorry...[BR]
	[Pause 5]I'm afraid I can't tell you at[BR]
	the moment.[BR]
	[Wait][Next]
	It was great, though![Wait][End]
}

#message:0B:(CH0_004D) {
	[Style right]
	Hey Mario![BR]
	[Pause 10]I'm Goombario.[BR]
	[Pause 5]I'm your biggest fan![BR]
	[Wait][Next]
	You don't know what this means[BR]
	for me to meet you! Seriously![Wait][End]
}

#message:0B:(CH0_004E) {
	[Style right]
	Mario, I know all about your[BR]
	adventures around the world.[BR]
	You've been everywhere![BR]
	[Wait][Next]
	And you always get the best of[BR]
	the bad guys. Every time![BR]
	[Wait][Next]
	You're the coolest![BR]
	[Pause 5]I wanna be just like you![Wait][End]
}

#message:0B:(CH0_004F) {
	[Style right]
	Mario, I know all about your[BR]
	adventures around the world.[BR]
	You've been everywhere![BR]
	[Wait][Next]
	And you always get the best of[BR]
	the bad guys. Every time! [BR]
	[Wait][Next]
	You're the coolest![BR]
	[Pause 5]I wanna be just like you![Wait][End]
}

#message:0B:(CH0_0050) {
	[Style right]
	Oh! Mario...[BR]
	[Pause 10]My dad was looking for you.[BR]
	[Pause 10]He said to tell you that he[BR]
	finished fixing the gate.[BR]
	[Wait][Next]
	So I guess now you can travel[BR]
	east to Toad Town and Shooting [BR]
	Star Summit, huh?[BR]
	[Wait][End]
}

#message:0B:(CH0_0051) {
	[Style right]
	Hey...I know that ol' Koopa![BR]
	[Pause 10]That was Kammy Koopa![BR]
	[Wait][Next]
	She's way up in the ranks of the[BR]
	Koopa clan. Some people call her[BR]
	the brains behind Bowser.[BR]
	[Wait][Next]
	Boy, she sure looked like one[BR]
	mean Koopa, didn't she?[BR]
	[Wait][End]
}

#message:0B:(CH0_0052) {
	[Style right]
	Howdy, Mario![BR]
	[Pause 10]Feeling better?[BR]
	[Wait][Next]
	Feel free to rest in our house.[Wait][End]
}

#message:0B:(CH0_0053) {
	[Style right]
	You what?[BR]
	[Pause 10]You have to leave right now?[BR]
	[Wait][Next]
	[Pause 10]...Oh, Shooting Star Summit.[BR]
	Something important, no doubt.[BR]
	[Pause 10]Well, I believe that the summit[BR]
	is near Toad Town.[BR]
	[Wait][Next]
	You'll have to wait a bit.[BR]
	[Pause 10]I have to fix this gate before[BR]
	you can head out to the east.[BR]
	[Wait][Next]
	That earthquake the other day[BR]
	really did a job on it.[BR]
	[Pause 10]Did you feel that quake? Shoot![BR]
	I thought the sky was falling.[BR]
	[Wait][Next]
	Just relax and don't worry. I'll[BR]
	have this fixed in a jiffy.[Wait][End]
}

#message:0B:(CH0_0054) {
	[Style right]
	Just a little while longer...[BR]
	[Pause 10]This hinge on the bottom of the[BR]
	gate is kind of tricky.[Wait][End]
}

#message:0B:(CH0_0055) {
	[Style right]
	Hoo! What a job! Sorry to have[BR]
	kept you waiting.[BR]
	[Pause 10]The gate is finally fixed.[BR]
	[Wait][Next]
	If you take this road straight[BR]
	ahead, you'll eventually reach[BR]
	Toad Town, the home of Princess[BR]
	Peach's Castle.[BR]
	[Wait][Next]
	I believe that Shooting Star[BR]
	Summit is just beyond there.[BR]
	[Wait][Next]
	It's too bad you can't stay... I[BR]
	feel like I just met you! But[BR]
	duty calls, I know.[BR]
	[Pause 10]Come back and visit if you can.[BR]
	[Wait] [End]
}

#message:0B:(CH0_0056) {
	[Style right]
	Howdy, Mario![BR]
	[Pause 10]Feeling better?[BR]
	[Wait][Next]
	Feel free to rest in our house.[BR]
	[Wait][Next]
	It's not such a shabby place. It[BR]
	may look a little unkempt at the[BR]
	moment, but I'm fixing all the[BR]
	earthquake damage.[BR]
	[Wait][Next]
	In fact, I just spent ages[BR]
	fixing this gate.[Wait][End]
}

#message:0B:(CH0_0057) {
	[Style right]
	You what?[BR]
	[Pause 10]You have to leave right now?[BR]
	[Wait][Next]
	[Pause 10]...Oh, Shooting Star Summit.[BR]
	Something important, no doubt.[BR]
	[Pause 10]Well, I believe that the summit is[BR]
	near Toad Town.[BR]
	[Wait][Next]
	If you take this road straight[BR]
	ahead, you'll eventually reach[BR]
	Toad Town, the home of Princess[BR]
	Peach's Castle.[BR]
	[Wait][Next]
	I believe that Shooting Star[BR]
	Summit is just beyond there.[BR]
	[Wait][Next]
	It's too bad you can't stay... I[BR]
	feel like I just met you! But[BR]
	duty calls, I know.[BR]
	[Pause 10]Come back and visit if you can.[Wait][End]
}

#message:0B:(CH0_0058) {
	[Style right]
	Best of luck, Mario.[Wait][End]
}

#message:0B:(CH0_0059) {
	[Style right]
	[PrintRising]Heee!! [Pause 5]Yee hee heee!!![Wait][End]
}

#message:0B:(CH0_005A) {
	[Style right]
	Bleah heh heh heh...[BR]
	[Pause 10]Ah, my instincts were right...[BR]
	[Wait][Next]
	Mario... I can't believe you're on[BR]
	your feet after taking such a[BR]
	beating from King Bowser.[BR]
	[Wait][Next]
	You're a hardy one, all right.[BR]
	[Pause 10]I was smart to come here to[BR]
	check on you.[Wait][End]
}

#message:0B:(CH0_005B) {
	[Style right]
	Whuh...what? What's that,[BR]
	Daddy!?[BR]
	[Pause 10]What's that weird flying thing?[Wait][End]
}

#message:0B:(CH0_005C) {
	[Style right]
	Weird? You rude little...[BR]
	[Pause 10]I am a beautiful Koopa with a[BR]
	beautiful name: Kammy Koopa! [BR]
	[Wait][Next]
	Hmmmph!![BR]
	[Pause 10]I wish I had time to teach you a[BR]
	lesson, brat! But no.[BR]
	[Wait][Next]
	Mario! Hear this![BR]
	[Pause 10]It is useless for you to try to[BR]
	save Princess Peach. Ridiculous![BR]
	Laughable![BR]
	[Wait][Next]
	As you have seen, King Bowser is[BR]
	more powerful than even you can[BR]
	deal with this time.[BR]
	[Wait][Next]
	Here's a gift from him![Wait][End]
}

#message:0B:(CH0_005D) {
	[Style right]
	Nyeah heh heh heh![BR]
	[Wait][Next]
	Mario! [Pause 10]You will kneel and weep[BR]
	when you see the wonderful[BR]
	changes King Bowser's made! [BR]
	[Wait][Next]
	Your world is ours now![Wait][End]
}

#message:0B:(CH0_005E) {
	[Style right]
	[Wave]Bleah heh ho hyuck heh heh HA!! [BR]
	[Pause 20][End]
}

#message:0B:(CH0_005F) {
	[Style right]
	Ummmmmm...[BR]
	[Pause 10]I just fixed that gate[Pause 3].[Pause 5].[Pause 8]. [BR]
	[Wait][Next]
	Nobody say "gate" to me...[BR]
	[Wait][Next]
	Kammy Koopa, that fiend![BR]
	[Pause 10]Did you hear what she said about[BR]
	the princess?[BR]
	[Wait][Next]
	It didn't sound good. I hope[BR]
	nothing's happened to her...[Wait][End]
}

#message:0B:(CH0_0060) {
	[Style right]
	[PrintRising]Wha... [Pause 3]Wha... [Pause 3]What!?[BR]
	[/PrintRising][Pause 10]Bowser went and kidnapped [BR]
	Princess Peach?! Again?![BR]
	[Wait][Next]
	Oh, unbelievable! And now you[BR]
	have to go to Shooting Star[BR]
	Summit and help save her, right?[BR]
	[Wait][Next]
	Ummmm...[BR]
	[Pause 5]This could be a problem.[Wait][End]
}

#message:0B:(CH0_0061) {
	[Style right]
	Dad, we've just gotta do [BR]
	something, right?[BR]
	[Wait][Next]
	Mario's gotta save the princess![BR]
	Nobody else can do it![Wait][End]
}

#message:0B:(CH0_0062) {
	[Style right]
	Ummmmmmm...[BR]
	[Wait][Next]
	Oh, here's an idea![BR]
	[Wait][Next]
	Maybe we can break this block[BR]
	with Goompa's big Hammer![BR]
	[Wait][Next]
	I think he's using it now to fix[BR]
	the veranda.[BR]
	[Wait][Next]
	Go ask him for it, will you?[Wait][End]
}

#message:0B:(CH0_0063) {
	[Style right]
	I think Goompa is fixing the[BR]
	veranda on the house.[BR]
	[Wait][Next]
	I'm thinking his Hammer might be[BR]
	able to break this block.[Wait][End]
}

#message:0B:(CH0_0064) {
	[Style right]
	Dad![BR]
	[Pause 10]Did ya hear? I'm going out[BR]
	adventuring with Mario![BR]
	[Wait][Next]
	I'll make you proud, Dad, I swear[BR]
	it! Just wait![Wait][End]
}

#message:0B:(CH0_0065) {
	[Style right]
	Do your best, son.[BR]
	[Pause 10]You've grown into a strong boy. I[BR]
	know you'll be a great help.[BR]
	[Wait][Next]
	It's a good thing you've spent so[BR]
	much time training, huh?[BR]
	[Wait][Next]
	Now do your old Goompapa proud![Wait][End]
}

#message:0B:(CH0_0066) {
	[Style right]
	There we go! Problem solved.[BR]
	[Wait][Next]
	I have a feeling your road will be[BR]
	lined with difficulties, so try not[BR]
	to overdo it.[BR]
	[Wait][Next]
	Be watchful, yet stay cool.[BR]
	[Pause 10]A calm mind is the wisest.[Wait][End]
}

#message:0B:(CH0_0067) {
	[Style right]
	Oh, hang on now, Mario![BR]
	[Pause 10]I noticed you aren't wearing the[BR]
	Badge Goompa gave you.[BR]
	[Wait][Next]
	You know, that Badge won't do[BR]
	anything if you don't wear it.[BR]
	[Pause 20]I think you'd better put that[BR]
	thing on before you go.[Wait][End]
}

#message:0B:(CH0_0068) {
	[Style right]
	It's simple, Mario.[BR]
	[Pause 10]Just keep going straight on this[BR]
	road to find Toad Town.[Wait][End]
}

#message:0B:(CH0_0069) {
	[Style right]
	Howdy! Welcome back to Goomba[BR]
	Village, Mario![BR]
	[Pause 10]How's the adventure going?[Wait][End]
}

#message:0B:(CH0_006A) {
	[Style right]
	Howdy, Mario.[BR]
	[Pause 10]How're you doing?[Wait][End]
}

#message:0B:(CH0_006B) {
	[Style right]
	Howdy, Mario.[BR]
	[Pause 10]How's my son Goombario doing?[BR]
	[Wait][Next]
	Hey, by the way, I named the lad[BR]
	after you, Mario.[BR]
	[Wait][Next]
	I always wanted my son to grow[BR]
	up to be strong like you.[BR]
	[Wait][Next]
	He went a little overboard... Now[BR]
	he's way too energetic![BR]
	[Pause 10]Ha, ha, ha, ha![Wait][End]
}

#message:0B:(CH0_006C) {
	[Style right]
	Goombario, [Pause 10]how goes it, son?[BR]
	[Wait][Next]
	I can't wait to hear about all[BR]
	the remarkable things you're out[BR]
	doing.[Wait][End]
}

#message:0B:(CH0_006D) {
	[Style right]
	It must be pretty gloomy around[BR]
	the castle, huh?[BR]
	[Pause 20]I'm sure the people there are[BR]
	depending on you, Mario.[BR]
	[Wait][Next]
	The only way to help them is to[BR]
	beat Bowser and save Princess[BR]
	Peach. Please hurry![Wait][End]
}

#message:0B:(CH0_006E) {
	[Style right]
	Goombario,[BR]
	[Pause 10]do your best to help Mario, OK?[BR]
	[Wait][Next]
	I'll make a wish to the Stars for[BR]
	you to have good luck.[Wait][End]
}

#message:0B:(CH0_006F) {
	[Style right]
	You're Goompapa, correct?[BR]
	[Wait][Next]
	The name's Parakarry. I deliver[BR]
	letters.[BR]
	[Wait][Next]
	I believe I have one for you.[BR]
	[Pause 10]Hang on a moment.[Wait][End]
}

#message:0B:(CH0_0070) {
	[Style right]
	Oh...no! Confound it![BR]
	[Pause 10]I seem to have lost it![BR]
	[Pause 10]...I'm terribly sorry.[Wait][End]
}

#message:0B:(CH0_0071) {
	[Style right]
	Another letter, duly delivered.[BR]
	A postman's job is never done.[Wait][End]
}

#message:0B:(CH0_0072) {
	[Style right]
	Hey, thanks. Much obliged, Mr.[BR]
	Postal Worker![BR]
	[Pause 10]...Oh, great news! [BR]
	[Wait][Next]
	Fishing is one of my hobbies, and[BR]
	this is from a friend who's[BR]
	planning a fishing trip. [BR]
	[Pause 5]I can't wait... [BR]
	[Wait][Next]
	...Oh...[BR]
	[Pause 5]Sorry to pile work on you, but[BR]
	could I give you a letter?[BR]
	[Wait][Next]
	If it's at all possible for you,[BR]
	could you deliver this to a Toad[BR]
	named Muss T.? He hangs around[BR]
	the castle garden.[BR]
	[Wait][Next]
	I'd really appreciate it.[Wait][End]
}

#message:0B:(CH0_0073) {
	[Style right]
	Mr. Goompapa! Parakarry here.[BR]
	[Wait][Next]
	I have a letter for you.[BR]
	[Pause 10]Hang on a moment.[Wait][End]
}

#message:0B:(CH0_0074) {
	[Style right]
	Oh...no! Confound it![BR]
	[Pause 10]I seem to have lost it![BR]
	[Pause 10]...I'm terribly sorry.[Wait][End]
}

#message:0B:(CH0_0075) {
	[Style right]
	Another letter, duly delivered.[BR]
	A postman's job is never done.[Wait][End]
}

#message:0B:(CH0_0076) {
	[Style right]
	Thank you, sir. What would we do[BR]
	without postal service?[BR]
	[Wait][Next]
	Oh, how interesting... A letter[BR]
	for Goombaria.[BR]
	[Pause 15]I guess I could open it...[BR]
	[Pause 20][Wait][Next]
	I remember she wrote a letter[BR]
	just the other day and I was[BR]
	wondering what it was.[BR]
	[Pause 10]I see. I guess it was a question.[BR]
	[Wait][Next]
	And this seems like the answer.[BR]
	[Pause 5]It looks pretty complicated...[BR]
	but I think I understand.[BR]
	[Wait][Next]
	I'll tell her all about it.[BR]
	[Wait][Next]
	Thanks so much for the prompt[BR]
	delivery.[BR]
	[Pause 10]Here, take this![Wait][End]
}

#message:0B:(CH0_0077) {
	[Style right]
	Oh, land sakes! Mario![BR]
	[Pause 10]So nice to meet you! My![BR]
	[Wait][Next]
	I'm so glad you woke up! I can't[BR]
	tell you how worried I was when[BR]
	you were just lying there asleep[BR]
	for so long.[Wait][End]
}

#message:0B:(CH0_0078) {
	[Style right]
	You should know that my son,[BR]
	Goombario, is a big fan of yours.[BR]
	[Wait][Next]
	All he does the livelong day is[BR]
	train and tell people how he[BR]
	wants to be great like you.[BR]
	[Wait][Next]
	I tell him, "Goombario! It's all[BR]
	well and good to train, but don't[BR]
	you go getting into danger!"[Wait][End]
}

#message:0B:(CH0_0079) {
	[Style right]
	Goompa...?[BR]
	[Pause 5]I thought he was fixing the[BR]
	veranda.[BR]
	[Wait][Next]
	I think...[BR]
	[Pause 5]He most likely had the Hammer[BR]
	you're looking for, too.[Wait][End]
}

#message:0B:(CH0_007A) {
	[Style right]
	Mom![BR]
	[Pause 10]I get to go with Mario![BR]
	[Pause 10]I promise when I come back, I'll[BR]
	bring home souvenirs![Wait][End]
}

#message:0B:(CH0_007B) {
	[Style right]
	Oh, my little baby! I can't[BR]
	believe you're going out into the[BR]
	world with Mario![BR]
	[Wait][Next]
	Now you listen![BR]
	[Pause 10]You be a good boy, you hear![BR]
	Don't cause Mario any trouble![Wait][End]
}

#message:0B:(CH0_007C) {
	[Style right]
	I know, Mom, sheesh. I'll be good.[Wait][End]
}

#message:0B:(CH0_007D) {
	[Style right]
	Goombario, you mind your mom![BR]
	[Pause 10]Wear a sweater when it's cold![BR]
	[Pause 10]Don't be picky about your food![BR]
	Don't start fights! Be polite![BR]
	[Wait][Next]
	Don't boast about all the things[BR]
	Goompa taught you[BR]
	[Pause 10]as if you already knew them!![BR]
	[Wait][Next]
	And remember... And...[Wait][End]
}

#message:0B:(CH0_007E) {
	[Style right]
	Urgh...[BR]
	[Pause 5]Mom always nags me...[Wait][End]
}

#message:0B:(CH0_007F) {
	[Style right]
	Now hush! Mario,[BR]
	[Pause 10]please take good care of my[BR]
	sweet little Goombario.[Wait][End]
}

#message:0B:(CH0_0080) {
	[Style right]
	Mario, please take good care of[BR]
	my sweet little Goombario.[Wait][End]
}

#message:0B:(CH0_0081) {
	[Style right]
	Oh, land sakes! Mario![BR]
	[Pause 20]Is my Goombario bothering you?[BR]
	[Wait][Next]
	He can be a real handful,[BR]
	sometimes, so I worry...[Wait][End]
}

#message:0B:(CH0_0082) {
	[Style right]
	Ugh...[BR]
	[Pause 15]Mom! C'mon, cut it out![Wait][End]
}

#message:0B:(CH0_0083) {
	[Style right]
	I heard that Toad Town has[BR]
	finally calmed down a bit.[BR]
	[Pause 10]Finally! It's been ages since I[BR]
	went shopping in peace![BR]
	[Wait][Next]
	We owe it all to you, Mario.[BR]
	[Pause 20]...Or maybe, possibly, my dear[BR]
	son Goombario helped? A little,[BR]
	perhaps?[Wait][End]
}

#message:0B:(CH0_0084) {
	[Style right]
	Goombario, c'mere.[BR]
	[Pause 10]I'm sure you're working hard.[BR]
	[Wait][Next]
	Let me just get that gunk off[BR]
	your face. Hold still.[Wait][End]
}

#message:0B:(CH0_0085) {
	[Style right]
	C'mon, Mom, quit it![Wait][End]
}

#message:0B:(CH0_0086) {
	[Style right]
	I do love to shop, but the[BR]
	problem with Toad Town is that[BR]
	there are just too many things.[BR]
	[Wait][Next]
	Still, it's nice to be in a busy[BR]
	area now and then.[BR]
	[Wait][Next]
	I think the next time I shop, I'll[BR]
	bring Goombaria.[Wait][End]
}

#message:0B:(CH0_0087) {
	[Style right]
	Goombario, [Pause 10]good luck, sweetie![Wait][End]
}

#message:0B:(CH0_0088) {
	[Style right]
	Mario, you look better.[BR]
	[Pause 10]I'm so glad...[BR]
	[Wait][Next]
	I was really worried about you,[BR]
	[Pause 10]because you were lying there in[BR]
	the forest and you didn't open[BR]
	your eyes at all the whole time.[Wait][End]
}

#message:0B:(CH0_0089) {
	[Style right]
	I was the one who found you,[BR]
	you know, Mario. Me! Goombaria![BR]
	[Wait][Next]
	I was in the forest and I found[BR]
	you and then I called Daddy and[BR]
	Goompa and Goombario.[BR]
	[Wait][Next]
	And then they came and got you[BR]
	and I'm glad you're better![Wait][End]
}

#message:0B:(CH0_008A) {
	[Style right]
	I was the one who found you,[BR]
	you know, Mario. Me! Goombaria![BR]
	[Wait][Next]
	I was in the forest and I found[BR]
	you and then I called Daddy and[BR]
	Goompa and Goombario.[BR]
	[Wait][Next]
	And then they came and got you[BR]
	and I'm glad you're better![Wait][End]
}

#message:0B:(CH0_008B) {
	[Style right]
	I wanted to go with you, too, you[BR]
	know, but Daddy told me it was[BR]
	too dangerous, so I have to stay[BR]
	here instead. Hmmph.[Wait][End]
}

#message:0B:(CH0_008C) {
	[Style right]
	Goompa! Come out here! Mario's[BR]
	in trouble![Wait][End]
}

#message:0B:(CH0_008D) {
	[Style right]
	It's not fair! Goombario always[BR]
	gets to do all the fun stuff![BR]
	[Pause 10]Mario, when I grow up, can I go[BR]
	on an adventure, too?[Wait][End]
}

#message:0B:(CH0_008E) {
	[Style right]
	Mario! Have you been beating up[BR]
	lots and lots of bad guys?[Wait][End]
}

#message:0B:(CH0_008F) {
	[Style right]
	Mario! I wanna go with you like[BR]
	Goombario gets to![BR]
	[Wait][Next]
	You go to all kinds of pretty[BR]
	towns and places, don't you?[BR]
	[Pause 10]I wanna go, too! I wanna go![BR]
	Why can't I go, too?[Wait][End]
}

#message:0B:(CH0_0090) {
	[Style right]
	You're just a little too young[BR]
	right now, Goombaria.[BR]
	[Pause 10]You wouldn't believe how hard life[BR]
	is out on the road.[Wait][End]
}

#message:0B:(CH0_0091) {
	[Style right]
	Shut up, Goombario![BR]
	[Pause 10]Stop smiling! I wanna go, too![Wait][End]
}

#message:0B:(CH0_0092) {
	[Style right]
	Everyone in the world is counting[BR]
	on you, huh, Mario?[BR]
	[Pause 10]How do you deal with the[BR]
	pressure all the time?[BR]
	[Wait][Next]
	Well, if it helps at all, you can[BR]
	depend on me, Mario.[BR]
	[Pause 2]I'll grow up extra fast so I can[BR]
	help you out! [Wait][End]
}

#message:0B:(CH0_0093) {
	[Style right]
	Goombario,[BR]
	[Pause 10]do you actually do anything?[BR]
	[Pause 10]I never hear about anything you[BR]
	do. Only Mario.[Wait][End]
}

#message:0B:(CH0_0094) {
	[Style right]
	Of course you don't hear!![BR]
	[Pause 10]My role is to assist Mario, not to[BR]
	be the hero.[Wait][End]
}

#message:0B:(CH0_0095) {
	[Style right]
	Huh...?[BR]
	[Pause 15]Really...? You fibber...[Wait][End]
}

#message:0B:(CH0_0096) {
	[Style right]
	Please take care of Goombario,[BR]
	OK?[Wait][End]
}

#message:0B:(CH0_0097) {
	[Style right]
	Wait, Mario!![BR]
	[Wait][Next]
	That dolly you're holding is mine.[BR]
	I know it![BR]
	[Wait][Next]
	Give it back! Pretty please?[BR]
	[Yield][End]
}

#message:0B:(CH0_0098) {
	[Style right]
	That dolly you are holding is[BR]
	mine, I know it![BR]
	[Wait][Next]
	Give it back! Pretty please?[BR]
	[Yield][End]
}

#message:0B:(CH0_0099) {
	[Next]
	[PrintRising]You meanie, Mario![Wait][End]
}

#message:0B:(CH0_009A) {
	[Next]
	Oh, thanks, Mario![BR]
	[Pause 10]You're sweet![HEART][BR]
	[Wait][Next]
	Here, you can have this.[BR]
	[Pause 10]Isn't it pretty, the way it[BR]
	glitters in the sun?[Wait][End]
}

#message:0B:(CH0_009B) {
	[Style right]
	And [Pause 10]take this [Pause 10]too.[Wait][End]
}

#message:0B:(CH0_009C) {
	[Style right]
	Oh, Mario. Hello, dearie.[BR]
	[Pause 10]You may call me Gooma.[BR]
	[Wait][Next]
	I'm a Goomba grandmother, so[BR]
	that's where I got the name.[BR]
	[Pause 10]Ho [Pause 3]ho [Pause 3]ho [Pause 3]ho.[BR]
	[Wait][Next]
	Have you already met my lovely[BR]
	grandchildren? Aren't they[BR]
	sweet?[BR]
	[Wait][Next]
	Especially little Goombaria. Why,[BR]
	she looks just like I did when I[BR]
	was young...[BR]
	[Pause 10]Ho [Pause 3]ho [Pause 3]ho [Pause 3]ho.[Wait][End]
}

#message:0B:(CH0_009D) {
	[Style right]
	You're quite a looker, aren't[BR]
	you?[BR]
	[Pause 10]Why, if I were just 10 years[BR]
	younger, and single, of course...[Wait][End]
}

#message:0B:(CH0_009E) {
	[Style right]
	Are you looking for Goompa?[BR]
	[Pause 10]He was just on the veranda.[Wait][End]
}

#message:0B:(CH0_009F) {
	[Style right]
	Good health is all that matters![BR]
	[Pause 10]Stay healthy no matter what.[BR]
	[Pause 10]Don't overwork yourself, and[BR]
	take a rest when you're weary.[Wait][End]
}

#message:0B:(CH0_00A0) {
	[Style right]
	Take care, Goombario.[BR]
	[Pause 10]You're already one fine Goomba![Wait][End]
}

#message:0B:(CH0_00A1) {
	[Style right]
	I have a bad feeling in my bones[BR]
	these days.[BR]
	[Pause 5]Evil things are afoot, I think.[BR]
	[Wait][Next]
	I wish that everyone could just[BR]
	[Pause 5]live together in peace.[Wait][End]
}

#message:0B:(CH0_00A2) {
	[Style right]
	What lovely weather today![BR]
	[Pause 10]The laundry's already dry.[BR]
	[Wait][Next]
	How's my Goombario doing? [BR]
	[Pause 10]I get so much joy just seeing[BR]
	my grandchildren's cute faces...[BR]
	Ho ho ho![Wait][End]
}

#message:0B:(CH0_00A3) {
	[Style right]
	Is Goombario leaving again?[BR]
	[Wait][Next]
	I miss you when you're not[BR]
	around here, little Goomba![BR]
	[Pause 10]You hurry up and finish this trip[BR]
	and come home to Gooma![Wait][End]
}

#message:0B:(CH0_00A4) {
	[Style right]
	I'm sure our little Goombario is[BR]
	trying his best and is doing all[BR]
	sorts of great deeds.[BR]
	[Wait][Next]
	But I still miss him when he's[BR]
	gone, you know.[Wait][End]
}

#message:0B:(CH0_00A5) {
	[Style right]
	I'm sure our little Goombario is[BR]
	trying his best and is doing all[BR]
	sorts of great deeds.[BR]
	[Wait][Next]
	But I still miss him when he's[BR]
	gone, you know.[BR]
	[Wait][Next]
	Goombario...[BR]
	[Pause 5]When will you be able to stay[BR]
	at home for a while?[Wait][End]
}

#message:0B:(CH0_00A6) {
	[Style right]
	Oh, my back... [Pause 5]Hm? Who's that?[BR]
	That you, Mario?[BR]
	[Wait][Next]
	I remember a great crashing[BR]
	noise and then the veranda[BR]
	collapsed and I fell.[BR]
	[Wait][Next]
	Did you fall, too?[BR]
	[Pause 10]Just stepped out the door into[BR]
	thin air, did you?[BR]
	[Wait][Next]
	Well, we're both OK. Problem is,[BR]
	we can't get home because that[BR]
	block is in the way.[Wait][End]
}

#message:0B:(CH0_00A7) {
	[Style right]
	This block...[BR]
	[Pause 5]This block shouldn't be here.[BR]
	[Pause 10]Well, this is a problem for us.[Wait][End]
}

#message:0B:(CH0_00A8) {
	[Style right]
	......Huh?[BR]
	[Pause 5]A Hammer? Oh, of course![BR]
	[Pause 10]Um... [Pause 10]Where did it go?[BR]
	[Wait][Next]
	I was using it to fix the[BR]
	veranda, so it's likely around[BR]
	here somewhere...[BR]
	[Wait][Next]
	Hm! Nowhere to be seen.[BR]
	[Pause 20]I guess it must have fallen[BR]
	somewhere over there.[BR]
	[Wait][Next]
	Mario, [Pause 10]we'd better look for it.[Wait][End]
}

#message:0B:(CH0_00A9) {
	[Style right]
	The Hammer has got to be[BR]
	somewhere close by.[BR]
	[Wait][Next]
	[SavePos][SetPosX 18][Down 12][ItemIcon itemID=0x0004]
	[RestorePos][BR]
	[SetPosX 63][Down 6]It looks just like this.[BR]
	[BR]
	[Up 6][BR]
	[Wait][Next]
	Look for bushes that might cover[BR]
	it up.[BR]
	[Wait][Next]
	If "[Color 0x20]![Color 0xA]" appears over your head,[BR]
	you can press [A] to search. [Wait][End]
}

#message:0B:(CH0_00AA) {
	[Style right]
	Oh!! There we go![BR]
	[Pause 10]That's it! That's the Hammer![BR]
	[Wait][Next]
	I'll wager that if you use that[BR]
	Hammer, you can break the block[BR]
	that's in our way.[BR]
	[Wait][Next]
	You can also use the Hammer to[BR]
	hit trees and make them sway.[BR]
	Sometimes stuff will fall out![BR]
	[Wait][Next]
	You can use it by pressing [B].[Wait][End]
}

#message:0B:(CH0_00AB) {
	[Style right]
	Oh! Well now![BR]
	[Pause 5]I believe that's the dolly that[BR]
	Goombaria said she lost![BR]
	[Wait][Next]
	She'll no doubt be overjoyed if[BR]
	you give it back to her.[BR]
	[Wait][Next]
	So many people lose things all[BR]
	over the place, you know.[BR]
	[Pause 10]It almost makes one feel like[BR]
	looking around everywhere...[Wait][End]
}

#message:0B:(CH0_00AC) {
	[Style right]
	Hmmm... Well![BR]
	[Pause 10]We found the Hammer, so I guess[BR]
	we should head for home.[Wait][End]
}

#message:0B:(CH0_00AD) {
	[Style right]
	[PrintRising][Size 48,48]
	Youch!![Wait][End]
}

#message:0B:(CH0_00AE) {
	[Style right]
	[PrintRising]Who are you guys!?[BR]
	[Pause 5]This is my playground, idiots![BR]
	[Wait][Next]
	Nobody sets foot in here without[BR]
	my permission! Nobody![BR]
	[Wait][Next]
	Prepare to start crying at the[BR]
	feet of Master Jr. Troopa![Wait][End]
}

#message:0B:(CH0_00AF) {
	[Style right]
	Mario,[BR]
	[Pause 10]this is Jr. Troopa. He's the boss[BR]
	of the neighborhood gang. A bit[BR]
	of a bully, obviously.[BR]
	[Wait][Next]
	He's more bark than bite. You[BR]
	can beat him easily.[BR]
	[Wait][Next]
	Just boost yourself up and don't[BR]
	take any lip![BR]
	[Wait][Next][Color red][InputOff]
	Remember, Mario, you can[BR]
	make use of Action Commands![InputOn][Color 0xA][BR]
	[Wait][Next]
	I'll stay right here behind you[BR]
	and watch your progress.[Wait][End]
}

#message:0B:(CH0_00B0) {
	[Style right]
	Oh, excellent![BR]
	[Pause 10]Good move! Go on!![Wait][End]
}

#message:0B:(CH0_00B1) {
	[Style right]
	Grrrr!![BR]
	[Pause 10]I'm just getting warmed up![Wait][End]
}

#message:0B:(CH0_00B2) {
	[Style right]
	Mario,[BR]
	[Pause 5]you've almost got him![BR]
	[Pause 10]Keep it up! Go on![Wait][End]
}

#message:0B:(CH0_00B3) {
	[Style right]
	You... are still alive?![BR]
	[Pause 10]I bet you won't be after this![BR]
	[Wait][Next]
	[Down 10][PrintRising][Size 32,32]
	Full power!![Wait][End]
}

#message:0B:(JrTroopa1_UseThunderBolt) {
	[Style right]
	All right, you asked for it![BR]
	[Pause 10]Say hello to Jr. Troopa's special[BR]
	item![BR]
	[Wait][Next]
	[Down 10][PrintRising][Size 32,32]
	Thunder Bolt!![Wait][End]
}

#message:0B:(CH0_00B4) {
	[Style right]
	Mario,[BR]
	[Pause 10]that was wonderful fighting. You[BR]
	got [Color 0x20]Star Points[Color 0xA]![BR]
	[Wait][Next]
	You get Star Points every time[BR]
	you beat an enemy.[BR]
	[Wait][Next]
	Every time you save up 100 Star[BR]
	Points, you'll go up a level.[BR]
	[Wait][Next][Color red][InputOff]
	Each area has its own[BR]
	[Rainbow]"Star Point Pool"[/Rainbow].[BR]
	[InputOn][Wait][Next][InputOff]
	Star Points from regular enemies[BR]
	use up the current area's pool.[BR]
	[InputOn][Wait][Next][InputOff]
	Once the pool runs out, you[BR]
	won't receive SP in that area.[BR]
	[InputOn][Wait][Next][InputOff]
	Enemies drop the same amount of[BR]
	SP, regardless of your level.[BR]
	[InputOn][Color 0xA][Wait][Next]
	Always try hard to get points![Wait][End]
}

#message:0B:(CH0_00B5) {
	[Style right]
	[PrintRising]Shoooooot!![BR]
	[Pause 5]I was winning, too! [BR]
	[Pause 5]I'll be back, Mario![Wait][End]
}

#message:0B:(CH0_00B6) {
	[Style right]
	I mean it, I'll be back!![Wait][End]
}

#message:0B:(CH0_00B7) {
	[Style right]
	Heads up, Mario![BR]
	[Pause 10]I see bad Goombas ahead.[BR]
	They're loyal to Bowser.[BR]
	[Wait][Next]
	If they see you, they'll attack[BR]
	you without hesitation.[BR]
	[Wait][Next]
	If you can successfully attack[BR]
	an enemy in the field with a[BR]
	[Color 0x20]Jump [Color 0xA]or [Color 0x20]Hammer[Color 0xA],[BR]
	[Wait][Next]
	you'll get the [Color 0x20]First Strike [Color 0xA]when[BR]
	you enter the battle.[BR]
	[Wait][Next]
	Striking first really helps when[BR]
	it comes to battling.[Wait][End]
}

#message:0B:(CH0_00B8) {
	[Style right]
	Listen up, Mario.[BR]
	[Pause 10]The enemy's flying. [BR]
	[Pause 10]Your Hammer won't reach[BR]
	enemies in the air.[BR]
	[Wait][Next]
	To attack airborne enemies, use[BR]
	a Jump attack. [BR]
	[Wait][Next]
	You can jump over one enemy to[BR]
	attack one behind it, too.[BR]
	[Pause 10]This is good advice. Remember it![Wait][End]
}

#message:0B:(CH0_00B9) {
	[Style right]
	This is a Spiked Goomba.[BR]
	[Pause 10]See the spike on his head?[BR]
	[Wait][Next]
	Be careful not to jump on him.[BR]
	You'll definitely get hurt.[Wait][End]
}

#message:0B:(CH0_00BA) {
	[Style right]
	Hey Mario,[BR]
	[Wait][Next]
	during a battle, you can change[BR]
	the order we attack in with [Z].[BR]
	[Wait][Next]
	I can attack first if you want.[BR]
	I don't mind at all![BR]
	[Pause 10]Just keep it in mind, OK?[Wait][End]
}

#message:0B:(CH0_00BB) {
	[Style right]
	Hey hey! Hold it right there![BR]
	[Pause 20]You! Yeah you, suspicious guy![BR]
	[Pause 10]Don't move![Wait][End]
}

#message:0B:(CH0_00BC) {
	[Style right]
	Aha, you're Mario![BR]
	[Pause 20]I knew it. You can't go past[BR]
	here, Mr. Big Shot.[BR]
	[Wait][Next]
	It's a direct order from the[BR]
	Goomba King. That's right![BR]
	[Wait][Next]
	I'm sorry, but the only way by[BR]
	[Pause 5]is through the Goomba Bros.[BR]
	That's me, Red Goomba, and my[BR]
	brother, Blue Goomba.[Wait][End]
}

#message:0B:(CH0_00BD) {
	[Style right]
	Let's get him, Blue Goomba![Wait][End]
}

#message:0B:(CH0_00BE) {
	[Style right]
	Oh yeah! [Pause 5]Let's do it, my red[BR]
	brother![Wait][End]
}

#message:0B:(CH0_00BF) {
	[Style right]
	Mario![BR]
	[Pause 15]How'd you like some of this?[Wait][End]
}

#message:0B:(CH0_00C0) {
	[Style right]
	[Shake]Re... [Pause 5]Red Goomba, my brother...[BR]
	[/Shake][Pause 10]Noooooo! You meanie, Mario![Wait][End]
}

#message:0B:(CH0_00C1) {
	[Style right]
	[Shake]Blue, [Pause 5]Blue Goomba!!!!![BR]
	[/Shake][Pause 10]Gaaah! My little brother! You'll[BR]
	pay for that, Mario![Wait][End]
}

#message:0B:(CH0_00C2) {
	[Style right]
	[Shake]Geeaaaah!!![BR]
	[/Shake][Pause 10]I... I'll let you go for now![Wait][End]
}

#message:0B:(CH0_00C3) {
	[Style right]
	King Goomba! Help us![Wait][End]
}

#message:0B:(CH0_00C4) {
	[Style right]
	Mario beat us up![Wait][End]
}

#message:0B:(CH0_00C5) {
	[Style right]
	Hey, look, Mario![BR]
	[Pause 10]See that building over there?[BR]
	[Wait][Next]
	I'm pretty sure there used to[BR]
	be a bridge on the other side.[BR]
	[Pause 10]I wonder what happened to it.[Wait][End]
}

#message:0B:(CH0_00C6) {
	[Style right]
	[Shake][PrintRising]So, Mario, it's true! You've made[BR]
	it this far. [BR]
	[Pause 10]I respect you for that.[BR]
	[Wait][Next]
	Unfortunately, this is as far as[BR]
	you'll ever get.[BR]
	[Wait][Next]
	Because I, the great and[BR]
	powerful King Goomba, will see to[BR]
	it that you advance no farther![Wait][End]
}

#message:0B:(CH0_00C7) {
	[Style right]
	You hear that, Mario! No[BR]
	farther! Not one step![BR]
	[Pause 10]Are you scared, little man?[Wait][End]
}

#message:0B:(CH0_00C8) {
	[Style right]
	Bah ha ha!!![BR]
	[Pause 10]Yeah, you're scared, all right.[BR]
	You wanna say you're sorry?[Wait][End]
}

#message:0B:(CH0_00C9) {
	[Style right]
	Wow... That King Goomba is...[BR]
	really huge![BR]
	[Wait][Next]
	I'm sure he's no match for you,[BR]
	though, Mario![BR]
	[Pause 20]Let's get him![Wait][End]
}

#message:0B:(CH0_00CA) {
	[Style right]
	[Shake][PrintRising]Ready to meet my wrath, Mario?[BR]
	[Pause 10]You'd better be!![Wait][End]
}

#message:0B:(CH0_00CB) {
	[Style right]
	Beat him up, King Goomba!![Wait][End]
}

#message:0B:(CH0_00CC) {
	[Style right]
	We've got your back![Wait][End]
}

#message:0B:(CH0_00CD) {
	[Style right]
	Leave him to me![Wait][End]
}

#message:0B:(CH0_00CE) {
	[Style right]
	Hey Mario![BR]
	[Pause 10]I think maybe we ought to take[BR]
	out the Goomba Bros. first, don't[BR]
	you think?[BR]
	[Wait][Next]
	They must be pretty weak since[BR]
	we just finished beating them up[BR]
	back there.[Wait][End]
}

#message:0B:(CH0_GoombaKingRage_Start) {
	[Style right][Shake][PrintRising]
	Now you made me real mad, Mario![BR][Pause 10]
	Beating up my Bros. like that?![BR]
	[/Shake][/PrintRising][Wait][Next]
	I've been holding onto this [Color red]Soup[Color 0xA][BR]
	for this moment,[Shake][PrintRising] feel my wrath![BR]
	[Wait][End]
}

#message:0B:(CH0_GoombaKingRage_PostItem) {
	[Style right]
	[Shake]Ooh,[/Shake] you must be shaking now![BR][Pause 10]
	It's time for my unstoppable...[BR]
	[Wait][Next][PrintRising][Size 32,32]
	Triple Spin![BR]
	[SizeReset][/PrintRising][Wait][End]
}

#message:0B:(CH0_GoombaKingRage_PostItem_2) {
	[Style right]
	Actually, [Pause 5]I'd better rest a bit.[BR]
	Never fight on a full stomach![BR]
	[Wait][Next]
	Next turn though, it's over![BR]
	Three damage, three times, how[BR]
	would one survive that?[BR]
	[Wait][End]
}

#message:0B:(CH0_00CF) {
	[Style right]
	Oh no! It can't be! King[BR]
	Goomba!![Wait][End]
}

#message:0B:(CH0_00D0) {
	[Style right]
	I don't believe it! He beat our[BR]
	King Goomba![Wait][End]
}

#message:0B:(CH0_00D1) {
	[Style right]
	Wh...wh...what!?[BR]
	[Pause 10]How could I lose?[Wait][End]
}

#message:0B:(CH0_00D2) {
	[Style right]
	Yeah! I knew we could do it![BR]
	[Pause 10]Cooool!! Victory!![Wait][End]
}

#message:0B:(CH0_00D3) {
	[Style right]
	[DitherFade 217]Red Goomba,[BR]
	[Pause 10]you're positive that you hid the[BR]
	switch well, right?[Wait][End]
}

#message:0B:(CH0_00D4) {
	[Style right]
	[DitherFade 217]Of course, King Goomba![BR]
	[Pause 10]I hid it in the grass outside the[BR]
	fortress. [Wait][End]
}

#message:0B:(CH0_00D5) {
	[Style right]
	[DitherFade 217][PrintRising][Shake]Outside the... You idiot![BR]
	[/Shake][/PrintRising]You didn't hide it in here? Mario[BR]
	will find it for sure![Wait][End]
}

#message:0B:(CH0_00D6) {
	[Style right]
	[DitherFade 217][PrintRising]Oh! Do you think?[BR]
	[/PrintRising][Pause 10]You know...you might be right.[Wait][End]
}

#message:0B:(CH0_00D7) {
	[Style right]
	[DitherFade 217]King Goomba,[BR]
	[Pause 10]maybe we ought to try to trick[BR]
	Mario before he tries to...[Wait][End]
}

#message:0B:(CH0_00D8) {
	[Style right]
	Uh...Mario![BR]
	[Pause 10]Good fight and all that! I must[BR]
	warn you, however...[BR]
	[Wait][Next]
	If you happen to find a strange[BR]
	switch somewhere, you should[BR]
	definitely not press it.[BR]
	[Pause 10]It's dangerous. Understand?[BR]
	[Wait][Next]
	.[Pause 5].[Pause 5].[Pause 5]...you what?[BR]
	[Pause 15][PrintRising][Shake]You already pressed it?![Wait][End]
}

#message:0B:(CH0_00D9) {
	[Style right]
	[Shake][PrintRising][Size 48,48]
	Oh nooo!!![BR]
	[Pause 100][End]
}

#message:0B:(CH0_00DA) {
	[Style right]
	Look! The bridge!![BR]
	[Pause 10]Now we can cross it and continue[BR]
	our journey. All right![Wait][End]
}

#message:0B:(CH0_00DB) {
	[Style right]
	I wonder what my brother Mario[BR]
	is doing right now...[Wait][End]
}

#message:0B:(CH0_00DC) {
	[Style right]
	[Speed delay=1 chars=2]Whoa! Mario![BR]
	[Pause 15]It's you! Good to see you![Wait][End]
}

#message:0B:(CH0_00DD) {
	[Style right]
	And you're all right![BR]
	[Pause 10]After all that castle craziness,[BR]
	I was really worried about you.[BR]
	[Wait][Next]
	I ran outside just as the[BR]
	earthquake started, so I[BR]
	managed to escape in time.[Wait][End]
}

#message:0B:(CH0_00DE) {
	[Style right]
	Oh? [Pause 10]And who are you?[Wait][End]
}

#message:0B:(CH0_00DF) {
	[Style right]
	I'm Goombario.[BR]
	[Pause 10]Nice to meet you![Wait][End]
}

#message:0B:(CH0_00E0) {
	[Style right]
	You're Luigi, right?[BR]
	[Pause 10]My name's Kooper.[BR]
	[Pause 10]Pleasure meeting you![Wait][End]
}

#message:0B:(CH0_00E1) {
	[Style right]
	You're Luigi, huh?[BR]
	[Pause 10]I'm Bombette.[BR]
	[Pause 5]Nice to meet you![HEART][Wait][End]
}

#message:0B:(CH0_00E2) {
	[Style right]
	The name's Parakarry.[BR]
	[Pause 10]I'm helping Mario out on his[BR]
	adventures.[Wait][End]
}

#message:0B:(CH0_00E3) {
	[Style right]
	I see. Great, just great.[BR]
	[Pause 10]You're on an exciting adventure[BR]
	with Mario. Talk about unfair.[BR]
	[Wait][Next]
	See, someone has to look after[BR]
	this house, so I can't leave. Oh[BR]
	well. Take care of Mario, OK?[Wait][End]
}

#message:0B:(CH0_00E4) {
	[Style right]
	Somebody sure has to save the[BR]
	poor princess. Good luck![Wait][End]
}

#message:0B:(CH0_00E5) {
	[Style right]
	Good luck, Mario. You just have[BR]
	to save that princess![Wait][End]
}

#message:0B:(CH0_00E6) {
	[Style right]
	Mario, I'll go to any lengths to[BR]
	help you out.[BR]
	[Wait][Next]
	I have lots of talents, and I can[BR]
	jump really high and...[BR]
	[Wait][Next]
	What? Stay home and take care[BR]
	of the house?[BR]
	[Pause 15]Man, that's not exciting at all![Wait][End]
}

#message:0B:(CH0_00E7) {
	[Style right]
	Koopa Bros.?[BR]
	[Pause 10]You mean they're a bunch of[BR]
	brothers who're Koopa Troopas?[BR]
	[Pause 10]Tough name to remember, huh?[BR]
	[Wait][Next]
	I have an idea, Mario![BR]
	[Pause 10]Why don't we give them a taste[BR]
	of our Mario Bros. power![BR]
	[Wait][Next]
	I'll join you and together...[BR]
	[Wait][Next]
	What? I can't? Why not?[BR]
	[Pause 15]Come on, Mario![Wait][End]
}

#message:0B:(CH0_00E8) {
	[Style right]
	Hi, Mario.[BR]
	[Pause 10]I figure I'll have an adventure[BR]
	sooner or later, so I'm training.[BR]
	[Wait][Next]
	What's that? Dry Dry Desert?[BR]
	[Pause 10]Oh, sure. There's a train that[BR]
	goes there from Toad Town.[BR]
	[Wait][Next]
	Hey, maybe I'll tag along...[BR]
	[Wait][Next]
	No? You sure?[BR]
	[Pause 15]Just gimme a chance![Wait][End]
}

#message:0B:(CH0_00E9) {
	[Style right]
	I wonder how ol' Mario is doing in[BR]
	his quest.[Wait][End]
}

#message:0B:(CH0_00EA) {
	[Style right]
	[PrintRising]Ma... [Pause 5]Mario![BR]
	[/PrintRising][Wait][End]
}

#message:0B:(CH0_00EB) {
	[Style right]
	Uh-oh... [Pause 5]I mean, never mind.[BR]
	[Pause 15]How did you find this place?[Wait][End]
}

#message:0B:(CH0_00EC) {
	[Style inspect]
	There's nothing on the desk.[Wait][End]
}

#message:0B:(CH0_00ED) {
	[Style right]
	Anything wrong?[BR]
	[Pause 15]Nothing suspicious in the[BR]
	basement, was there?[Wait][End]
}

#message:0B:(CH0_00EE) {
	[Style right]
	Huff [Pause 5]huff...[BR]
	[Pause 5]You wouldn't believe it... Shy[BR]
	Guys were everywhere...[BR]
	[Wait][Next]
	They moved...like the wind! Huff[BR]
	huff... All I managed to do was[BR]
	get really upset and yell.[Wait][End]
}

#message:0B:(CH0_00EF) {
	[Style right]
	Huff [Pause 5]Huff...[BR]
	[Pause 5]I'm a great jumper, but my[BR]
	running really needs some work.[BR]
	[Wait][Next]
	A little more training and I'll be[BR]
	vital to your team...[BR]
	[Wait][Next]
	All right, take it easy. I know I[BR]
	can't go.[BR]
	[Pause 10]You go on your adventure. I[BR]
	don't even want to anymore.[BR]
	[Wait][Next]
	I know that it's up to you to[BR]
	save Princess Peach, so hurry[BR]
	up for my sake![Wait][End]
}

#message:0B:(CH0_00F0) {
	[Style right]
	...Hi, Mario. [Pause 15]Are you doing OK?[BR]
	[Pause 15][Wait][Next]
	Don't worry, Bro, I'll watch the[BR]
	house until you get back.[Wait][End]
}

#message:0B:(CH0_00F1) {
	[Style right]
	Boy, hanging out way up high[BR]
	sure was nice...  Such a great[BR]
	view and everything...[BR]
	[Wait][Next]
	Uh...never mind! Say, that's a[BR]
	cool Hammer you got there![BR]
	[Pause 15]I bet you can even beat up[BR]
	enemies with hard shells now![Wait][End]
}

#message:0B:(CH0_00F2) {
	[Style right]
	Boy, hanging out way up high[BR]
	sure was nice... Such a great[BR]
	view and everything...[BR]
	[Wait][Next]
	Uh...never mind. Say, are those[BR]
	new Boots? They look really[BR]
	flashy![BR]
	[Pause 15]Now you'll be a better jumper![Wait][End]
}

#message:0B:(CH0_00F3) {
	[Style right]
	Princess Peach is still caught[BR]
	way up there in the sky...[BR]
	[Wait][Next]
	C'mon, Mario![BR]
	[Pause 15]You're a hero, Bro! You have to[BR]
	save her![Wait][End]
}

#message:0B:(CH0_00F4) {
	Number of Battles:[End]
}

#message:0B:(CH0_00F5) {
	pcs.[End]
}

#message:0B:(CH0_00F6) {
	times[End]
}

#message:0B:(CH0_00F7) {
	Your First Strikes:[End]
}

#message:0B:(CH0_00F8) {
	Enemies' First Strikes:[End]
}

#message:0B:(CH0_00F9) {
	Total Power Bounces:[End]
}

#message:0B:(CH0_00FA) {
	?  ?  ?[End]
}

#message:0B:(CH0_00FB) {
	Star Pieces Collected:[End]
}

#message:0B:(CH0_00FC) {
	Coins Earned:[End]
}

#message:0B:(CH0_00FD) {
	Badges Collected:[End]
}

#message:0B:(CH0_00FE) {
	Tayce T.'s Recipes:[End]
}

#message:0B:(CH0_00FF) {
	Chuck Quizmo's Quizzes:[End]
}

#message:0B:(CH0_0100) {
	[Style inspect]
	There's Luigi's diary![Wait][End]
}

#message:0B:(CH0_0101) {
	[Style inspect]
	There's a letter for Mario![Wait][End]
}

#message:0B:(CH0_0102) {
	[Style inspect]
	Here's the box where letters[BR]
	addressed to Mario go.[BR]
	[Pause 10]It's empty right now.[Wait][End]
}

#message:0B:(CH0_0103) {
	[Style right]
	What's that, Mario?[BR]
	[Pause 10]You need something?[Wait][End]
}

#message:0B:(CH0_0104) {
	[Style right]
	He what? [BR]
	[Pause 10]Mr. Koopa Koot wants to get my[BR]
	autograph? Me? He wants me to[BR]
	sign something?[BR]
	[Wait][Next]
	Whoa! Cool! I'm flattered![BR]
	[Pause 10]I guess maybe I'm a little bit of[BR]
	a celebrity, huh?[BR]
	[Wait][Next]
	[Pause 10]Wait one second.[BR]
	[Pause 5]I'll write it right now.[Wait][End]
}

#message:0B:(CH0_0105) {
	[Style right]
	Here you are, Mario.[BR]
	[Pause 10]My autograph.[BR]
	[Wait][Next]
	Give my regards to Mr. Koopa[BR]
	Koot, OK?[Wait][End]
}

#message:0B:(CH0_0106) {
	[Style inspect]
	Do you want to go to bed?[BR]
	[Yield][End]
}

#message:0B:(CH0_0107) {
	[Style inspect]
	You're at peak strength. Do you[BR]
	still want to go to bed?[BR]
	[Yield][End]
}

#message:0B:(CH0_0108) {
	[Style inspect]
	Fully energized![Wait][End]
}


#message:0B:(CH0_ChallengeIntroduction) {
	[Style right]
	Hmmm, you do seem like[BR]
	a hero type...[BR]
	[Wait][Next]
	I've some unique artifacts[BR]
	with me. Legends say they[BR]
	harness unbelievable powers.[BR]
	[Wait][Next]
	Although, other legends warn[BR]
	about the cursed nature of[BR]
	these items.[BR]
	[Wait][Next]
	Common between all stories[BR]
	is the fact that they only[BR]
	impact true heroes.[BR]
	[Wait][Next]
	As such, they don't have any[BR]
	material value, and so they[BR]
	are useless to me.[BR]
	[Wait][Next]
	If you're willing to take the[BR]
	risk, then these can be yours[BR]
	at no cost![BR]
	[Wait][End]
}

#message:0B:(CH0_ChallengeRejected) {
	[Style right]
	Oh well, maybe another hero[BR]
	will be more... adventurous.[BR]
	[Wait][End]
}

#message:0B:(CH0_ChallengeAccepted) {
	[Style right]
	Well, I wish you the best of[BR]
	luck! No takebacks![BR]
	[Wait][End]
}

#message:0B:(CH0_ChallengeMoreThanOne) {
	[Style right]
	Oh, oh, oh! More than one?[BR]
	You must be very brave...[BR]
	[Wait][Next]
	Let's hope you know what[BR]
	you're doing...[BR]
	[Wait][End]
}

#message:0B:(CH0_ChallengeIntroductionAgainHasAny) {
	[Style right]
	Oh, you want more artifacts?[BR]
	Go on, then.[BR]
	[Wait][End]
}


#message:0B:(CH0_ChallengeIntroductionAgainWithoutAny) {
	[Style right]
	Oh, you changed your mind?[BR]
	Go on, then.[BR]
	[Wait][End]
}

#message:0B:(CH0_ChallengeIntroductionAgainHasAll) {
	[Style right]
	I'm afraid I don't have any[BR]
	more artifacts to give you.[BR]
	[Wait][End]
}
