#message:14:(Peach_CH1_KoopaBros_0000) {
	[Style right]
	Mighty King Bowser...[BR]
	[Pause 10]I've been looking for you.[BR]
	[Wait][Next]
	A report, Your Evilness:[BR]
	[Pause 10]Mario defeated the Goomba King.[BR]
	[Wait][Next]
	He's heading for Toad Town now.[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0001) {
	[Style right]
	[Voice bowser]
	What? Unbelievable![BR]
	[Pause 10]What was Goomba King thinking?[BR]
	[Wait][Next]
	I used the Star Rod to make him[BR]
	a king because he begged me...[BR]
	[Wait][Next]
	And Mario whips him so easily?[BR]
	[Pause 10]What a wimp!![BR]
	[Wait][Next]
	Uh...Kammy Koopa![BR]
	[Pause 10]You ARE sure that Mario can[BR]
	never defeat us, right?[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0002) {
	[Style right]
	Please, please, Your Vileness![BR]
	Try to be calm.[BR]
	[Pause 10]Goomba King is small-time.[BR]
	[Pause 10]I had a feeling he'd fail.[BR]
	[Wait][Next]
	It doesn't matter, because[BR]
	while you hold the Star Rod[BR]
	you are definitely invincible.[BR]
	[Wait][Next]
	You could beat Mario with one[BR]
	claw tied behind your back.[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0003) {
	[Style right]
	[Voice bowser]
	Yes, yes. Very good![BR]
	[Pause 10][PrintRising]Gwaaa ha ha ha ha!![BR]
	[/PrintRising][Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0004) {
	[Style right]
	[Voice bowser]
	By the way, Kammy Koopa,[BR]
	[Pause 10]those Star Spirits we captured[BR]
	don't have any way of giving[BR]
	Mario their power, do they?[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0005) {
	[Style right]
	Please, don't worry yourself.[BR]
	[Pause 10]Each is held separately.[BR]
	[Wait][Next]
	And each is carefully guarded by[BR]
	your handpicked subjects.[BR]
	[Wait][Next]
	Even Mario can't save all seven[BR]
	of the Star Spirits.[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0006) {
	[Style right]
	[Voice bowser]
	Hmmm...[BR]
	[Wait][Next]
	Who's the closest Star Spirit to[BR]
	Mario? It's that one at[BR]
	[Color 0x20]Koopa Bros. Fortress[Color 0xA], right?[BR]
	[Wait][Next]
	If Mario somehow reaches there,[BR]
	can the Koopa Bros. defeat him?[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0007) {
	[Style right]
	King Bowser, you mustn't worry...[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0008) {
	[Style right]
	[Down 6][Size 32,32]
	[PrintRising]Hi-yaa!![BR]
	[Pause 30][End]
}

#message:14:(Peach_CH1_KoopaBros_0009) {
	[Style right]
	[PrintRising]Here come the Koopa Bros.!![BR]
	[Wait][Next]
	[Pause 10]Uh-huh! Oh yeah! We're the[BR]
	coolest of cool![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_000A) {
	[Style right]
	[Voice bowser]
	.[Pause 5].[Pause 5].[Pause 10][Next]
	Pssst! Kammy Koopa.[BR]
	[Pause 5]Are you sure these guys can get[BR]
	the job done?[BR]
	[Wait][Next]
	That Goomba King was gigantic,[BR]
	and even he couldn't beat Mario.[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_000B) {
	[Style right]
	Pssshaw! Get real, [Pause 5]King Bowser![BR]
	[Wait][Next]
	Yeah, the Goomba King was huge,[BR]
	but he was a total wimpola![BR]
	We're nothing like him![BR]
	[Wait][Next]
	See, what we've got going on is[BR]
	the power of teamwork...[BR]
	[Wait][Next]
	Together, we can put the hurt[BR]
	on Mario in seconds flat![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_000C) {
	[Style right]
	Excellent![BR]
	[Pause 5]That's the spirit! Sell it,[BR]
	Koopa Bros.!![BR]
	[Wait][Next]
	Show our king that special[BR]
	attack you do so well![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_000D) {
	[Style right]
	Yes, ma'am![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_000E) {
	[Style right]
	Ready, everybody![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_000F) {
	[Style right]
	[Voice bowser]
	[Down 8][Size 32,32]
	[PrintRising][Shake]Ooh...OOOH![BR]
	[Pause 10][SizeReset]
	[BR]
	[Up 12][Wait][Scroll 3]That... This is... Ohhhhh!!!![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0010) {
	[Style right]
	How'd you like it?[BR]
	[Pause 10]King Bowser? How was it?[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0011) {
	[Style right]
	[Voice bowser]
	Oh, yeah! [Pause 10]Excellent!! Really!![BR]
	[Pause 10]I'm not easily impressed, either![BR]
	[Wait][Next]
	Mario won't have a chance if you[BR]
	finish him with that attack![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0012) {
	[Style right]
	We'll take him, King Bowser![Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0013) {
	[Style right]
	[Voice bowser]
	By the way, my Koopa Bros....[BR]
	[Pause 10][Wait][Next]
	About the captured Star Spirit[BR]
	I've locked up in your fortress...[BR]
	[Pause 10]Who's guarding him right now?[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0014) {
	[Style right]
	...Uh...nobody, sir...[BR]
	[Pause 10]You know, we're here and so...[Wait][End]
}

#message:14:(Peach_CH1_KoopaBros_0015) {
	[Style right]
	[Voice bowser]
	[PrintRising]You idiots!! Use your heads![BR]
	[Pause 10]Get back to the fortress and[BR]
	guard that Star Spirit![Wait][End]
}

#message:14:(Peach_0016) {
	[Style right]
	Sniffle...[Wait][End]
}

#message:14:(Peach_0017) {
	[Style right]
	Mario's probably hurt...[Wait][End]
}

#message:14:(Peach_0018) {
	[Style right]
	Everyone's in prison...[Wait][End]
}

#message:14:(Peach_0019) {
	[Style right]
	The Mushroom Kingdom will be[BR]
	destroyed if things continue the[BR]
	way they're going.[BR]
	[Wait][Next]
	[Pause 15]Something must be done[Pause 1].[Pause 2].[Pause 3].[BR]
	[Pause 10][Wait][Next]
	If only somebody could help me...[Wait][End]
}

#message:14:(Peach_001A) {
	[Style right]
	[Voice bowser]
	[PrintRising]Gwaa ha ha ha ha!![BR]
	[Yield][Pause 10][/PrintRising]My dear Princess Peach,[BR]
	[Pause 5]how are you doing this fine day?[Wait][End]
}

#message:14:(Peach_001B) {
	[Style right]
	It's no use waiting for Mario this[BR]
	time, my dear![BR]
	[Wait][Next]
	We're soooooo high above the sky[BR]
	right now.[BR]
	[Pause 10]Even Mario doesn't have a[BR]
	chance of reaching us up here![Wait][End]
}

#message:14:(Peach_001C) {
	[Style center]
	[Voice bowser]
	You know, Princess, as long as I[BR]
	have this Star Rod, no one in the[BR]
	Mushroom Kingdom can touch me.[BR]
	[Wait][Yield][Next]
	You know the power that grants[BR]
	everyone's wishes? It's mine![BR]
	[Pause 10]Isn't that just wonderful?[Wait][End]
}

#message:14:(Peach_001D) {
	[Style right]
	Nyeah hee hee hee![BR]
	[Wait][Next]
	Imagine what it's like down in[BR]
	your kingdom! Your subjects[BR]
	must be so upset because their[BR]
	wishes aren't being granted![BR]
	[Wait][Next]
	Oh, how delightful![BR]
	[Pause 10]They deserve it for the way[BR]
	they've treated us Koopas over[BR]
	the years![Wait][End]
}

#message:14:(Peach_001E) {
	[Style right]
	[Voice bowser]
	If you, you know, want anything,[BR]
	all you need to do is ask me,[BR]
	Princess. I can grant wishes.[BR]
	[Wait][Next]
	Of course, I'll only grant[BR]
	requests that I like...[BR]
	[Pause 10]Anyway, think about it.[BR]
	[Wait][Next]
	You take care, Princess Peach![BR]
	[Pause 10]Enjoy your stay here![Wait][End]
}

#message:14:(Peach_001F) {
	[Style right]
	You watch yourself, Princess.[BR]
	[Pause 10]You'd better not cause trouble.[BR]
	[Wait][Next]
	Bleah heh heh ho ha ha...[Wait][End]
}

#message:14:(Peach_0020) {
	[Style right]
	Oh... Please...[BR]
	[Pause 10]If only somebody could help me...[Wait][End]
}

#message:14:(Peach_0021) {
	[Style right]
	Huh?[Wait][End]
}

#message:14:(Peach_0022) {
	[Style right]
	[Voice star]
	Hello, Princess Peach![BR]
	[Pause 5]Pleased to meet you![BR]
	[Wait][Next]
	My name is Twink.[Wait][End]
}

#message:14:(Peach_0023) {
	[Style right]
	But you're...[BR]
	[Pause 5]You're a Star Kid, aren't you?[BR]
	[Pause 5]How'd you get here?[Wait][End]
}

#message:14:(Peach_0024) {
	[Style right]
	[Voice star]
	I came from Star Haven to[BR]
	grant your wish![BR]
	[Wait][Next]
	It's our job to grant wishes, you[BR]
	know.[Wait][End]
}

#message:14:(Peach_0025) {
	[Style right]
	Oh! You came because I wished[BR]
	that somebody could help me?[Wait][End]
}

#message:14:(Peach_0026) {
	[Style right]
	[Voice star]
	Yes, of course![Wait][End]
}

#message:14:(Peach_0027) {
	[Style right]
	Oh, that's just great![BR]
	[Pause 10]Thank you so much for coming![BR]
	[Wait][Next]
	Here's my wish: Go right now and[BR]
	take that Star Rod back from[BR]
	Bowser, OK?[BR]
	[Wait][Next]
	Think you can do it?[Wait][End]
}

#message:14:(Peach_0028) {
	[Style right]
	[Voice star]
	......[BR]
	[Pause 20][Wait][Next]
	Uh...sorry...[BR]
	[Pause 5]That's a little much for a novice[BR]
	Star like me...[BR]
	[Wait][Next]
	Maybe one of the honorable Star[BR]
	Spirits from Star Haven could[BR]
	grant a wish like that.[BR]
	[Wait][Next]
	I'm so sorry.[BR]
	[Pause 10]Please, ask for something easy,[BR]
	something a small Star can do.[Wait][End]
}

#message:14:(Peach_0029) {
	[Style right]
	Then... [Pause 3]Can you take me away[BR]
	from here?[BR]
	[Wait][Next]
	Everyone in my castle has been[BR]
	captured and I have to save[BR]
	them all as soon as possible.[Wait][End]
}

#message:14:(Peach_002A) {
	[Style right]
	[Voice star]
	...Oh...I'm sorry.[BR]
	[Pause 20]I can't grant that wish either,[BR]
	I'm afraid.[BR]
	[Wait][Next]
	Actually, I just got called up to[BR]
	the sky a day ago, so I can't do[BR]
	big wishes yet...[BR]
	[Wait][Next]
	If I were a more splendid Star,[BR]
	maybe I could actually help...[Wait][End]
}

#message:14:(Peach_002B) {
	[Style right]
	It's all right...[BR]
	[Pause 10]Don't be sad, Twink.[BR]
	[Wait][Next]
	Mario will definitely do something[BR]
	to save us all.[BR]
	[Pause 20]He's probably coming right now![Wait][End]
}

#message:14:(Peach_002C) {
	[Style right]
	Oh! Twink![BR]
	[Pause 20]Do you think you can find Mario?[BR]
	[Yield][Wait][Next]
	I want you to give this to him.[Wait][End]
}

#message:14:(Peach_002D) {
	[Style right]
	[Voice star]
	This is [Color 0x20]Speedy Spin[Color 0xA], isn't it?[BR]
	[Wait][Next]
	OK! I'll do it! Princess Peach,[BR]
	[Pause 10]I'll fly to the Mushroom Kingdom[BR]
	just as quick as I can![Wait][End]
}

#message:14:(Peach_002E) {
	[Style right]
	Oh! Wait, Twink![BR]
	[Pause 10]Wait one second! Can you also...[Wait][End]
}

#message:14:(Peach_002F) {
	[Style right]
	Please tell Mario that...[Wait][End]
}

#message:14:(Peach_0030) {
	[Style right]
	I'm fine and he shouldn't worry...[BR]
	[Pause 10]...OK? Can you tell him that?[Wait][End]
}

#message:14:(Peach_0031) {
	[Style right]
	[Voice star]
	Of course![BR]
	[Pause 15]I'll tell him your exact words,[BR]
	Princess Peach! Definitely![BR]
	[Wait][Next]
	Now, don't despair...[BR]
	[Pause 10]I'll be back soon, so stay safe[BR]
	until I return, OK?[Wait][End]
}

#message:14:(Peach_0032) {
	[Style right]
	Mario... Where are you...[Wait][End]
}

#message:14:(Peach_0033) {
	[Style right]
	I wonder what Mario is doing[BR]
	right now...[BR]
	[Wait][Next]
	I wonder if he's hurt...[BR]
	[Pause 20]I'm so worried about him![Wait][End]
}

#message:14:(Peach_0034) {
	[Style right]
	[Voice star]
	He'll be all right, Princess.[BR]
	[Wait][Next]
	Why, I bet he's saving some Star[BR]
	Spirits right now![Wait][End]
}

#message:14:(Peach_0035) {
	[Style right]
	Yes... You're right, Twink.[BR]
	[Wait][Next]
	I must be strong.[BR]
	[Wait][Next]
	I need to concentrate on finding[BR]
	a way out of here.[Wait][End]
}

#message:14:(Peach_0036) {
	[Style right]
	[Voice star]
	But there are tons of guards[BR]
	just beyond your door...[BR]
	[Wait][Next]
	And it's impossible for you to[BR]
	escape through the window...[Wait][End]
}

#message:14:(Peach_0037) {
	[Style right]
	Oh! Wait a minute![BR]
	[Wait][Next]
	I remember the Minister telling[BR]
	me that there was a secret[BR]
	passage out of this room![BR]
	[Wait][Next]
	Twink![BR]
	[Pause 10]Help me look for it![Wait][End]
}

#message:14:(Peach_0038) {
	[Style right]
	[Voice star]
	Cool! Great idea![Wait][End]
}

#message:14:(Peach_0039) {
	[Style right]
	The fireplace... Quite nice...[BR]
	[Pause 5]So big...and so warm...[Wait][End]
}

#message:14:(Peach_003A) {
	[Style right]
	Hmmm... A warm fireplace?[BR]
	[Pause 15]Don't you find that suspicious?[Wait][End]
}

#message:14:(Peach_003B) {
	[Style right]
	Do you really think so, Twink?[Wait][End]
}

#message:14:(Peach_003C) {
	[Style right]
	So many dresses...and yet they[BR]
	all look exactly the same![Wait][End]
}

#message:14:(Peach_003D) {
	[Style right]
	They're not the same![BR]
	[Pause 5]The designs are all slightly[BR]
	different and very fashionable![Wait][End]
}

#message:14:(Peach_003E) {
	[Style right]
	Oh! [Pause 5]A photo of Mario![Wait][End]
}

#message:14:(Peach_003F) {
	[Style right]
	Don't look at that![Wait][End]
}

#message:14:(Peach_0040) {
	[Style right]
	This is no time to sleep.[Wait][End]
}

#message:14:(Peach_0041) {
	[Style right]
	Yes, let's keep looking![Wait][End]
}

#message:14:(Peach_0042) {
	[Style right]
	Beautiful flowers, aren't they?[BR]
	[Pause 10]They smell so good...[HEART][Wait][End]
}

#message:14:(Peach_0043) {
	[Style right]
	Sure. I guess.[Wait][End]
}

#message:14:(Peach_0044) {
	[Style right]
	Oh... Eeew![BR]
	[Pause 10]I look frightful![Wait][End]
}

#message:14:(Peach_0045) {
	[Style right]
	It's not real, Princess...[BR]
	[Pause 15][Wait][Next]
	but... I must say...[BR]
	[Pause 10]That's not a good look for you.[Wait][End]
}

#message:14:(Peach_0046) {
	[Style right]
	[Voice star]
	Oh! Look![BR]
	[Pause 10]There's something behind this[BR]
	drawing![Wait][End]
}

#message:14:(Peach_0047) {
	[Style right]
	[Voice star]
	Yes!! Cool!![BR]
	[Pause 10]Now we can get out of this room![Wait][End]
}

#message:14:(Peach_0048) {
	[InputOff]
	[Style right]
	[PrintRising][BR]
	[Down 8][Right 80]Ohhhh!!![BR]
	[/PrintRising][Pause 30][End]
}

#message:14:(Peach_0049) {
	[Style right]
	[Voice star]
	Where are we... ?[Wait][End]
}

#message:14:(Peach_004A) {
	[Style right]
	[Voice star]
	Looks like it's locked.[BR]
	[Wait][Next]
	Oh no[Pause 3].[Pause 3].[Pause 3].[BR]
	[Pause 3]We can't get out![Wait][End]
}

#message:14:(Peach_004B) {
	[Style right]
	[Voice star]
	Hey! Look at this![BR]
	[Wait][Next]
	It looks like somebody left a[BR]
	private diary just lying around.[BR]
	[Pause 15]Should we read it?[BR]
	[Yield][End]
}

#message:14:(Peach_004C) {
	[Next]
	[Voice star]
	Ohhh... You like doing this sort of[BR]
	thing, do you? Tsk tsk![BR]
	[Wait][Next]
	OK, then...very quietly...[Wait][End]
}

#message:14:(Peach_004D) {
	[Style right]
	[Voice star]
	Let's see...[BR]
	[Wait][Next]
	[Color 0x0]Day: [CIRCLE]/[CIRCLE]  Month: [STAR] [BR]
	Sunny[BR]
	[Wait][Next]
	Today I went to Star Haven and[BR]
	stole the Star Rod.[BR]
	[Pause 10]Now I'm invincible! Cool![BR]
	[Wait][Next]
	I also captured those seven[BR]
	Star Spirits, so they won't[BR]
	annoy me anymore.[BR]
	[Wait][Next]
	It was a hard day's work and[BR]
	I'm feeling pretty bushed.[BR]
	[Pause 10]Dinner was nice but a bit bland.[BR]
	[Pause 10][Wait][Next]
	[Color 0xA]........[BR]
	[Wait][Next]
	I feel like I might know the[BR]
	person who wrote this...[BR]
	[Pause 10]Should we read more?[BR]
	[Yield][End]
}

#message:14:(Peach_004E) {
	[Next]
	[Voice star]
	OK, let's continue.[BR]
	[Wait][Next]
	[Color 0x0]Day: [CIRCLE]/[CROSS]  Month: [STAR][BR]
	Cloudy then sunny[BR]
	[Wait][Next]
	Today was great, diary! I used[BR]
	my castle to lift Princess[BR]
	Peach's Castle way up into the[BR]
	sky! [BR]
	[Wait][Next]
	Then I barged into Peach's[BR]
	Castle and beat up Mario! Yeah![BR]
	[Pause 10]Unbelievable, I know! So fun![BR]
	[Wait][Next]
	And there's more! After that, I[BR]
	kidnapped Princess Peach![BR]
	[Pause 10]I couldn't be happier, diary![BR]
	[Pause 5]I hope she likes me...[BR]
	[Pause 10][Wait][Next]
	[PrintRising][Color 0xA]...!!![Wait][End]
}

#message:14:(Peach_004F) {
	[Style right]
	[Voice star]
	Princess Peach! This is Bowser's[BR]
	diary! Ugh![BR]
	[Wait][Next]
	What'll we do?[BR]
	[Pause 10]Should we read more?[BR]
	[Yield][End]
}

#message:14:(Peach_0050) {
	[Next]
	[Voice star]
	What? Really?[BR]
	[Pause 10]You're stopping now?[BR]
	[Wait][Next]
	There might be a hint that can[BR]
	help Mario in here![BR]
	[Yield][End]
}

#message:14:(Peach_0051) {
	[Next]
	[Voice star]
	[Color 0x0]Day: [CROSS]/[CROSS]  Month: [STAR][BR]
	Sunny[BR]
	[Wait][Next]
	Well, the Koopa Bros. got beaten[BR]
	by Mario, diary.[BR]
	[Pause 10]He even set free that stupid[BR]
	Star Spirit I kept there.[BR]
	[Wait][Next]
	I'm so mad I can barely write![BR]
	[Pause 10]"Ohh, I'm Mario, I'm so big and[BR]
	strong and good and helpful..."[BR]
	[Wait][Next]
	I hate him! But I'm not worried.[BR]
	[Wait][Next]
	There's no way Mario can save[BR]
	the Star Spirit being held[BR]
	in [Color 0x7]Dry Dry Ruins[Color 0x0].[BR]
	[Wait][Next]
	To do that, he'd have to solve[BR]
	the mystery of the sands and[BR]
	then find Dry Dry Ruins in [BR]
	[Color 0x7]Dry Dry Desert[Color 0x0].[BR]
	[Wait][Next]
	How would he even know to go to[BR]
	the desert, anyway?[BR]
	[Wait][Next]
	So I'm not worried at all.[BR]
	[Pause 10]In fact, I'm so calm I'm gonna go[BR]
	to bed now.[BR]
	[Pause 10][Wait][End]
}

#message:14:(Peach_0052) {
	[Style right]
	[Voice star]
	[PrintRising]!!!!![BR]
	[/PrintRising][Pause 10][Wait][Next]
	Dry Dry Ruins in the middle of[BR]
	Dry Dry Desert![BR]
	[Pause 10]One of the revered Star Spirits[BR]
	is being held there![Wait][End]
}

#message:14:(Peach_0053) {
	[Style right]
	Twink, do you think you can[BR]
	find Mario and tell him that?[Wait][End]
}

#message:14:(Peach_0054) {
	[Style right]
	[Voice star]
	Yes, of course, Princess Peach![BR]
	[Pause 10]I'll find Mario right away...[BR]
	[Wait][Next]
	???[Wait][End]
}

#message:14:(Peach_0055) {
	[Style right]
	[Voice bowser]
	Oh no! I can't believe I left my[BR]
	secret diary lying out![BR]
	[Wait][Next]
	It would be so embarrassing if[BR]
	somebody read that thing...[Wait][End]
}

#message:14:(Peach_0056) {
	[Style right]
	[Voice bowser]
	[PrintRising]Whuh... Wha... Whaaaat?[BR]
	[Pause 5]What's the princess doing here?[Wait][End]
}

#message:14:(Peach_0057) {
	[Style right]
	[Voice bowser]
	[PrintRising]AAhhhh!! You little sneak![BR]
	[Pause 10][/PrintRising]You read my diary![Wait][End]
}

#message:14:(Peach_0058) {
	[Style right]
	King Bowser![BR]
	[Pause 5]Is there a problem?[Wait][End]
}

#message:14:(Peach_0059) {
	[Style right]
	[Voice bowser]
	You're the worst guards ever![BR]
	[Pause 10]Take Princess Peach back to her[BR]
	room! Immediately!![Wait][End]
}

#message:14:(Peach_005A) {
	[Style right]
	Yes, sir! Straight away! Forgive[BR]
	us, sir![Wait][End]
}

#message:14:(Peach_005B) {
	[Style right]
	[Wave]Noooooo! Put me dooown![Wait][End]
}

#message:14:(Peach_005C) {
	[Style right]
	[Voice bowser]
	Gwaa ha ha ha...hello.[BR]
	[Yield][Pause 10]How're you feeling, Princess?[BR]
	[Wait][Next]
	Nothing makes me happier than a[BR]
	smile from you, Peach.[Wait][End]
}

#message:14:(Peach_005D) {
	[Style right]
	Well, tough luck! I'm in a very[BR]
	bad mood, you monster![BR]
	[Wait][Next]
	You've imprisoned all of the[BR]
	guests from the castle![BR]
	[Wait][Next]
	You are the single greatest[BR]
	disaster to ever befall the[BR]
	Mushroom Kingdom![BR]
	[Wait][Next]
	I'll tell you what: I'll smile[BR]
	when you make everything as it[BR]
	was before you showed up![Wait][End]
}

#message:14:(Peach_005E) {
	[Style right]
	[Voice bowser]
	Gwaa ha ha! Oh, that's rich![BR]
	[Pause 10]You know I can't do that![BR]
	[Yield][Wait][Next]
	That jerk Mario just beat the[BR]
	Koopa Bros. and Tutankoopa![BR]
	[Wait][Next]
	Sure, they were complete wimps,[BR]
	but they were still loyal to me. I[BR]
	can't forgive Mario for[BR]
	disrespecting me![BR]
	[Wait][Next]
	I'm nipping this in the bud right[BR]
	now. I'm going to use Invincible[BR]
	Tubba Blubba on him.[BR]
	[Wait][Next]
	He's the strongest creature I[BR]
	know...after me.[BR]
	[Pause 10]You'd best forget about Mario...[Wait][End]
}

#message:14:(Peach_005F) {
	[Style right]
	Your Nastiness![Wait][End]
}

#message:14:(Peach_0060) {
	[Style right]
	We have a problem![Wait][End]
}

#message:14:(Peach_0061) {
	[Style right]
	[Voice bowser]
	Why, Kammy Koopa![BR]
	[Pause 10]What's got you so riled up? You[BR]
	look upset.[Wait][End]
}

#message:14:(Peach_0062) {
	[Style right]
	[Wave]Psst...Psst...Psst...[BR]
	[Pause 20][/Wave][Wait][End]
}

#message:14:(Peach_0063) {
	[Style right]
	[Voice bowser]
	[PrintRising]Whaaaat!!?[BR]
	[Pause 5]The Star Spirit flew away from[BR]
	Tubba Blubba's Castle...!?[Wait][End]
}

#message:14:(Peach_0064) {
	[Style right]
	Ki... King Bowser![BR]
	[Pause 10]Keep your voice down![BR]
	[Pause 10]Princess Peach will hear you![Wait][End]
}

#message:14:(Peach_0065) {
	[Style right]
	[Voice bowser]
	Mmmm... Yes, right... [BR]
	[Wait][Next]
	Tell me the details over there.[Wait][End]
}

#message:14:(Peach_0066) {
	[Style right]
	Twink, did you hear that?[Wait][End]
}

#message:14:(Peach_0067) {
	[Style right]
	[Voice star]
	Yes! I sure did![BR]
	[Pause 5]The Star Spirit must have[BR]
	escaped...[BR]
	[Wait][Next]
	Did you hear him call that Tubba[BR]
	Blubba thing "invincible"?[BR]
	[Wait][Next]
	That doesn't sound good![BR]
	[Pause 10]Do you think Mario can win?[Wait][End]
}

#message:14:(Peach_0068) {
	[Style right]
	We'd better try to find out[BR]
	about Tubba Blubba.[BR]
	[Wait][Next]
	If we could find something,[BR]
	ANYTHING, about a weak point...[BR]
	it might just save Mario![Wait][End]
}

#message:14:(Peach_0069) {
	[Style right]
	[Voice star]
	Good idea![Wait][End]
}

#message:14:(Peach_006A) {
	[Style right]
	Then... There's no time to lose.[BR]
	[Pause 5]We won't get anything done if we[BR]
	stay in this room.[Wait][End]
}

#message:14:(Peach_006B) {
	[Style right]
	[Voice star]
	There are still guards outside.[BR]
	[Pause 10]Be careful not to get caught.[Wait][End]
}

#message:14:(Peach_006C) {
	[Style right]
	[Voice star]
	There are guards here, too. [BR]
	[Pause 10]Probably lots of them. We'd[BR]
	better be extra careful.[Wait][End]
}

#message:14:(Peach_006D) {
	[Style right]
	[PrintRising]![Wait][End]
}

#message:14:(Peach_006E) {
	[Style center]
	[Volume 50]...Hey...  [Pause 5]Have you heard[BR]
	[Pause 5]about Master Tubba Blubba?[BR]
	[Wait][Next]
	I heard a rumor that he loves[BR]
	eating ghosts![Wait][End]
}

#message:14:(Peach_006F) {
	[Style left]
	[Volume 50]Ugh... Ghosts, huh?[BR]
	[Wait][Next]
	Master Tubba Blubba... [BR]
	[Pause 10]He lives deep inside of[BR]
	[Color 0x20]Forever Forest[Color 0xA], doesn't he?[BR]
	[Wait][Next]
	I think he's guarding one of the[BR]
	Star Spirits right now.[Wait][End]
}

#message:14:(Peach_0070) {
	[Style center]
	[Volume 50]Yeah, Master Tubba Blubba lives[BR]
	in the castle at the top[BR]
	of [Color 0x20]Gusty Gulch[Color 0xA].[BR]
	[Wait][Next]
	I heard that somewhere near his[BR]
	castle is a mansion and a village[BR]
	full of ghosts.[BR]
	[Wait][Next]
	I guess Master Tubba Blubba [BR]
	sometimes goes there to catch[BR]
	Boos.[BR]
	[Wait][Next]
	And then, when he catches one,[BR]
	he gobbles it down starting with[BR]
	its head! Chomp![Wait][End]
}

#message:14:(Peach_0071) {
	[Style left]
	[Volume 50][Shake]Brrrrr...[BR]
	[Pause 10]Oh, man, that's so scary...[BR]
	[Wait][Next]
	Now I won't be able to walk to[BR]
	the bathroom alone at night...[BR]
	[Pause 10]And I'm gonna have nightmares, I[BR]
	know it! Why'd you tell me?[Wait][End]
}

#message:14:(Peach_0072) {
	[Style center]
	[Volume 50]I also heard that Master Tubba[BR]
	Blubba is invincible.[BR]
	[Pause 10]They say he can't be hurt.[BR]
	Nobody can even scratch him![BR]
	[Wait][Next]
	He might even be stronger than[BR]
	King Bowser...[Wait][End]
}

#message:14:(Peach_0073) {
	[Style left]
	[Volume 50]Stronger than King Bowser?[BR]
	[Pause 10]Come on! That's impossible![BR]
	[Wait][Next]
	Even Master Tubba Blubba has to[BR]
	have some weak points. It's just[BR]
	common sense![Wait][End]
}

#message:14:(Peach_0074) {
	[Style center]
	[Volume 50]Yeah... You may be right...[BR]
	[Pause 10][Wait][Next]
	There's another rumor that[BR]
	Tubba Blubba's got a secret[BR]
	that would ruin him if it ever[BR]
	got out.[BR]
	[Wait][Next]
	I bet it's about his past. I[BR]
	heard he didn't used to be[BR]
	strong at all...[Wait][End]
}

#message:14:(Peach_0075) {
	[Style left]
	[BR]
	[Down 5][Shake]Shhhhhhhh!!!!![BR]
	[/Shake] [BR]
	[Up 5][Wait][Next]
	[Volume 50]What if Tubba Blubba hears you?[BR]
	He might gobble us up![BR]
	[Wait][Next]
	...Still...[BR]
	[Pause 10]What do you think his secret[BR]
	could be, anyway?[Wait][End]
}

#message:14:(Peach_0076) {
	[Style center]
	[Volume 50]I don't know.[BR]
	[Pause 10]No one knows. That's why it's a[BR]
	secret, you half-wit![Wait][End]
}

#message:14:(Peach_0077) {
	[Style right]
	[Volume 50]Twink... [BR]
	[Pause 10]It sounds like Tubba Blubba has[BR]
	a weak point, after all.[Wait][End]
}

#message:14:(Peach_0078) {
	[Style right]
	[Volume 50][Voice star]
	If only we could find out...[Wait][End]
}

#message:14:(Peach_0079) {
	[Style center]
	[Volume 50]...Huh?[BR]
	[Pause 5]Hey... Did you hear someone[BR]
	talking just now?[Wait][End]
}

#message:14:(Peach_007A) {
	[Style left]
	[Size 48,48]
	[PrintRising]Gasp![BR]
	[/PrintRising][SizeReset]
	[Wait][Scroll 4][Down 4][Volume 50]Do you think someone knows we're[BR]
	goofing off in here?[Wait][End]
}

#message:14:(Peach_007B) {
	[Style right]
	Oh! Whoa![BR]
	[Pause 5]Princess Peach!![BR]
	[Pause 5]How'd you get here?[Wait][End]
}

#message:14:(Peach_007C) {
	[Style right]
	I'm sorry to do this, but...[BR]
	[Pause 5]You have to go back to your[BR]
	room. Right now.[Wait][End]
}

#message:14:(Peach_007D) {
	[Style right]
	[Wave]Oh! Nooo![Wait][End]
}

#message:14:(Peach_007E) {
	[Style right]
	[Voice star]
	I wonder how Mario is doing...[BR]
	[Pause 5]Do you think he found a way to[BR]
	beat that Tubba Blubba?[Wait][End]
}

#message:14:(Peach_007F) {
	[Style right]
	I wonder, too.[BR]
	[Pause 10]I'm so worried...  What if Mario[BR]
	got hurt...?[Wait][End]
}

#message:14:(Peach_0080) {
	[Style right]
	[Voice star]
	Well... [Pause 5]Um... [Pause 5]No use wondering![BR]
	[Pause 10]Why don't we go out and try to[BR]
	eavesdrop again?[BR]
	[Wait][Next]
	If Mario managed to beat Tubba[BR]
	Blubba by now,[BR]
	[Wait][Next]
	Bowser and his followers will be[BR]
	really, really mad![BR]
	[Pause 20]...Don't you think?[Wait][End]
}

#message:14:(Peach_0081) {
	[Style right]
	You may be right, Twink![BR]
	[Pause 10]There's no use just sitting[BR]
	around worrying like this.[BR]
	[Pause 10]Let's see what we can find out.[Wait][End]
}

#message:14:(Peach_0082) {
	[Style right]
	[Voice bowser]
	[PrintRising]It can't be!! No! No! No![BR]
	[/PrintRising][Pause 5]Explain that again! Slowly![Wait][End]
}

#message:14:(Peach_0083) {
	[Style right]
	Your Wretchedness,[BR]
	[Pause 10]I keep trying to tell you.[BR]
	[Wait][Next]
	Tubba Blubba was...gulp...[BR]
	defeated by Mario.[Wait][End]
}

#message:14:(Peach_0084) {
	[Style right]
	[Voice bowser]
	Well, that's strange because...[BR]
	[Pause 10]YOU TOLD ME HE WAS INVINCIBLE![BR]
	[Pause 10]How can you beat someone who's[BR]
	invincible?[Wait][End]
}

#message:14:(Peach_0085) {
	[Style right]
	[Voice bowser]
	Grrrr...  [Pause 5]Stupid Mario...[BR]
	[Pause 10]I guess maybe he found out the[BR]
	secret that made Tubba Blubba[BR]
	not quite so invincible...[BR]
	[Wait][Next]
	And then he beat him...[BR]
	[Pause 10]Gah!!! I despise Mario! Really![Wait][End]
}

#message:14:(Peach_0086) {
	[Style right]
	Your Filthiness...[BR]
	[Pause 5]We have to come up with another[BR]
	tactic, and quickly.[BR]
	[Wait][Next]
	Mario will most likely go[BR]
	to [Color 0x20]Shy Guy's Toy Box [Color 0xA]next.[Wait][End]
}

#message:14:(Peach_0087) {
	[Style right]
	[Voice bowser]
	Yes... So we should prepare[BR]
	something there for his arrival.[BR]
	[Wait][Next]
	I won't be satisfied just having[BR]
	him beaten up anymore![BR]
	[Wait][Next]
	What we need to do is find his[BR]
	weak point and completely[BR]
	humiliate him! Yeah![BR]
	[Wait][Next]
	Kammy Koopa, you've gotta find[BR]
	out what Mario hates, and...[BR]
	[Pause 20][Wait][End]
}

#message:14:(Peach_0088) {
	[Style right]
	[Voice bowser]
	Unh...?[BR]
	[Pause 15][Wait][End]
}

#message:14:(Peach_0089) {
	[Style right]
	[Next]
	[Voice bowser]
	[Size 48,48]
	[PrintRising]Gaaaah![BR]
	[Pause 15][Yield][End]
}

#message:14:(Peach_008A) {
	[Scroll 4][Down 5][Voice bowser]
	[SizeReset]
	[/PrintRising]For the love of... Why...[BR]
	[Pause 10]Why is Princess Peach here?![BR]
	[Pause 10]What's wrong with those guards?[Wait][End]
}

#message:14:(Peach_008B) {
	[Style right]
	[Voice bowser]
	No... Wait, hang on.[BR]
	[Pause 10]This is actually good timing,[BR]
	my mischievous princess.[BR]
	[Wait][Next]
	We're just discussing the weak[BR]
	points of our mutual friend,[BR]
	Mario.[BR]
	[Wait][Next]
	So... Princess Peach...[BR]
	[Pause 10]What do you know about his[BR]
	weaknesses, huh?[BR]
	[Wait][Next]
	And listen. [Pause 5]You must be honest![BR]
	[Pause 10]Which one of these things does[BR]
	Mario hate most?[BR]
	[Yield][End]
}

#message:14:(Peach_008C) {
	[Next]
	[Voice bowser]
	Mmm...[BR]
	[Pause 10]I see! Excellent![BR]
	[Wait][Next]
	Is there another thing that fills[BR]
	him with dread?[BR]
	[Yield][End]
}

#message:14:(Peach_008D) {
	[Next]
	[Voice bowser]
	Good, good...[BR]
	[Pause 10]And how about these things?[BR]
	Which of these does he hate?[BR]
	[Yield][End]
}

#message:14:(Peach_008E) {
	[Next]
	[Voice bowser]
	Oh, excellent![BR]
	[Pause 5]Perfect! Thanks, Princess![BR]
	[Wait][Next]
	Gwaa ha ha ha ha!!![BR]
	[Pause 10]Be sure Mario can't avoid these[BR]
	things that he hates! We'll[BR]
	beat him for sure![Wait][End]
}

#message:14:(Peach_008F) {
	[Style right]
	[Voice bowser]
	Did you get all that, Kammy[BR]
	Koopa?[BR]
	[Pause 10]Get going immediately![Wait][End]
}

#message:14:(Peach_0090) {
	[Style right]
	[Wave]Bleah heh nyeah heh ho![BR]
	[/Wave][Pause 10]Of course, Your Gnarliness![BR]
	[Wait][Next]
	Mario's really in for it now...[BR]
	[Pause 20]...or is he...?[BR]
	[Pause 10]Hmmm... I started to wonder for[BR]
	a second there...[BR]
	[Wait][Next]
	But, then again, King Bowser's[BR]
	ordered this so I have no choice[BR]
	but to obey him...[BR]
	[Pause 10]I guess we'll see![Wait][End]
}

#message:14:(Peach_0091) {
	[Style right]
	I'm not sure we can entirely[BR]
	trust what the princess tells us[BR]
	about Mario's weak points, but[BR]
	I'll do as you say.[Wait][End]
}

#message:14:(Peach_0092) {
	[Style right]
	[Voice bowser]
	Of course you will.[BR]
	[Pause 10]My tactics are brilliant. They're[BR]
	pure art![BR]
	[Wait][Yield][End]
}

#message:14:(Peach_0093) {
	[Next]
	[Voice bowser]
	So... Kammy Koopa,[BR]
	[Pause 10]have Princess Peach taken back[BR]
	to her room immediately.[BR]
	[Wait][Next]
	Finally, we will witness the end[BR]
	of Mario! At last![BR]
	[Pause 10][PrintRising]Gwaa ha ha ha ha ha!![Wait][End]
}

#message:14:(Peach_0094) {
	[Style right]
	Guards! Attention![BR]
	[Pause 10]Take Princess Peach back to her[BR]
	room at once![Wait][End]
}

#message:14:(Peach_0095) {
	[Style right]
	Yes, ma'am!![Wait][End]
}

#message:14:(Peach_0096) {
	[Style right]
	[Wave]Noooo! [Pause 5]Not again...[Wait][End]
}

#message:14:(Peach_0097) {
	[Style right]
	Hey... Twink.[BR]
	[Pause 10]Those guards have stopped[BR]
	paying attention to us again.[BR]
	[Wait][Next]
	Let's sneak out of here.[BR]
	[Pause 10]We might be able to find some[BR]
	news to help Mario.[Wait][End]
}

#message:14:(Peach_0098) {
	[Style right]
	[Voice star]
	Do you think it's still safe to[BR]
	use that secret path?[BR]
	[Wait][Next]
	Don't you think Bowser's figured[BR]
	it out by now?[Wait][End]
}

#message:14:(Peach_0099) {
	[Style right]
	It's still all right, Twink.[BR]
	[Pause 5]Bowser hasn't noticed anything.[BR]
	[Wait][Next]
	He looks scary, but he's[BR]
	basically a major bonehead.[BR]
	[Pause 10]Let's get out of here. C'mon![Wait][End]
}

#message:14:(Peach_009A) {
	[Style right]
	Urp... Huh...?[BR]
	[Pause 10]Who are you?[Wait][End]
}

#message:14:(Peach_009B) {
	[Style right]
	Why, I'm Princess Peach.[BR]
	[Pause 10]And who might you be?[Wait][End]
}

#message:14:(Peach_009C) {
	[Style right]
	Oh! You're Princess Peach.[BR]
	[Pause 10]Everyone calls me the Gourmet[BR]
	Guy for some reason.[BR]
	[Wait][Next]
	I guess I'd better report you to[BR]
	King Bowser. You aren't[BR]
	supposed to leave your room.[BR]
	[Wait][Next]
	But I AM really hungry... Tell[BR]
	you what... I'll keep this a[BR]
	secret if you make me something[BR]
	really yummy.[BR]
	[Wait][Next]
	So, Princess Peach,[BR]
	[Pause 10]what do you say? Will you cook[BR]
	me something or what?[Wait][End]
}

#message:14:(Peach_009D) {
	[Style right]
	I'd love to cook for you, Mr.[BR]
	Gourmet Guy, but...[BR]
	[Pause 10]I have no ingredients and no[BR]
	utensils.[Wait][End]
}

#message:14:(Peach_009E) {
	[Style right]
	Aw, that's no problem.[BR]
	[Pause 10]There's a kitchen one floor below[BR]
	us. It's five-star![BR]
	[Wait][Next]
	You can go cook there![Wait][End]
}

#message:14:(Peach_009F) {
	[Style right]
	Here, you'll need this.[BR]
	[Pause 10]This key will open the door that[BR]
	leads downstairs.[BR]
	[Pause 10]Now you can get to the kitchen.[Wait][End]
}

#message:14:(Peach_00A0) {
	[Style right]
	So! I'll just sit here and wait[BR]
	for my yummy meal, OK?[BR]
	[Wait][Next]
	[Pause 10]Oh yeah, I forgot...[BR]
	[Pause 15]There are plenty of guards[BR]
	downstairs, so be careful.[Wait][End]
}

#message:14:(Peach_00A1) {
	[Style right]
	Oh... I can't wait...[HEART][BR]
	[Wait][End]
}

#message:14:(Peach_00A2) {
	[Style right]
	Here you go![Wait][End]
}

#message:14:(Peach_00A3) {
	[Style right]
	Oh! I've been waiting so long![BR]
	[Pause 10]I've wasted away to nothing![Wait][End]
}

#message:14:(Peach_00A4) {
	[Style right]
	Thank you![HEART][Wait][End]
}

#message:14:(Peach_00A5) {
	[Style right]
	Nooooooo! Haaaaackpth![BR]
	[Pause 10]Aw, disgusting! This is awful![BR]
	[Wait][Next]
	Where'd you learn to cook, Truck[BR]
	Driving School?[BR]
	[Pause 10]Go back to the kitchen and follow[BR]
	a recipe or something![Wait][End]
}

#message:14:(Peach_00A6) {
	[Style right]
	I'll never eat such a nasty[BR]
	creation again, I tell you![BR]
	[Pause 10]I swear...trying to poison me...[BR]
	[Wait][Next]
	Go back down there and make[BR]
	something good, will you?[Wait][End]
}

#message:14:(Peach_00A7) {
	[Style right]
	What ingredients did you use in[BR]
	that monstrosity?[BR]
	[Wait][Next]
	Whatever they were, I think they[BR]
	were seriously wrong![Wait][End]
}

#message:14:(Peach_00A8) {
	[Style right]
	Ack! Bleeaaagh...![BR]
	[Pause 10]Awful! Just awful![BR]
	[Wait][Next]
	You didn't mix the ingredients[BR]
	very well![BR]
	[Wait][Next]
	You have to mix them right![Wait][End]
}

#message:14:(Peach_00A9) {
	[Style right]
	Cough...gag... Pbbbbth![BR]
	[Pause 10]This wasn't baked for the right[BR]
	length of time![BR]
	[Wait][Next]
	Listen, baking is the most[BR]
	important part of cake making![BR]
	[Pause 10]You have to time it properly![Wait][End]
}

#message:14:(Peach_00AA) {
	[Style right]
	Mmmmm... No no no. All wrong.[BR]
	[Pause 10]Look at this decoration. Awful.[BR]
	[Wait][Next]
	You shouldn't have too much or[BR]
	too little decoration on a cake,[BR]
	don't you know that?[BR]
	[Wait][Next]
	Try to use a little more care[BR]
	next time, OK?[BR]
	[Pause 10]I feel sorry for the cake.[Wait][End]
}

#message:14:(Peach_00AB) {
	[InputOff]
	[Style right]
	[PrintRising]Oh...       [Pause 35]Ohhh,[BR]
	[Pause 35]Ohhhhhhh!!!!![BR]
	[/PrintRising][Pause 30][Next]
	[Shake]Deliciooooooous!!![BR]
	[Pause 45][/Shake][Next]
	[Wave]This [Pause 3]is [Pause 4]way [Pause 5]too [Pause 6]DELICIOUS![Pause 2]![Pause 2]![Pause 2]![BR]
	[Pause 50][End]
}

#message:14:(Peach_00AC) {
	[Style right]
	Phew... [BR]
	[Pause 10]That was really good.[BR]
	[Wait][Next]
	I haven't felt this way since...[BR]
	well, ever![BR]
	[Pause 10]To show you my gratitude, I'll[BR]
	tell you a secret.[Wait][End]
}

#message:14:(Peach_00AD) {
	[Style right]
	One of the Star Spirits is inside[BR]
	[Color 0x20]Mt. Lavalava [Color 0xA]on [Color 0x20]Lavalava[BR]
	Island[Color 0xA].[BR]
	This island is to the south.[BR]
	[Wait][Next]
	You should tell this to Mario.[BR]
	[Wait][Next]
	But you'd better tell him that[BR]
	there's also a nasty Lava[BR]
	Piranha guarding the Star[BR]
	Spirit.[BR]
	[Wait][Next]
	He'd better be careful.[BR]
	[Pause 10]I really don't dislike Mario.[BR]
	[Pause 10]That's why I'm telling you this.[Wait][End]
}

#message:14:(Peach_00AE) {
	[Style right]
	Twink, did you hear that!?[BR]
	[Pause 10]Mt. Lavalava! Lavalava Island.[BR]
	[Pause 10]The Star Spirit is being held[BR]
	inside that volcano![Wait][End]
}

#message:14:(Peach_00AF) {
	[Style right]
	[Voice star]
	Mario could really use this[BR]
	information, huh?[Wait][End]
}

#message:14:(Peach_00B0) {
	[Style right]
	Yes, he could...[BR]
	[Wait][Next]
	Twink, I'm sorry that I keep[BR]
	asking you to do this stuff,[BR]
	but...can you go tell Mario?[Wait][End]
}

#message:14:(Peach_00B1) {
	[Style right]
	[Voice star]
	Of course I will.[BR]
	[Pause 5]I'll do it right now![Wait][End]
}

#message:14:(Peach_00B2) {
	[Style right]
	[Voice star]
	I'll be back soon, Princess[BR]
	Peach![Wait][End]
}

#message:14:(Peach_00B3) {
	[Style right]
	[Shake]What's with all the shouting?[BR]
	[Pause 10]Keep it quiet in here!![Wait][End]
}

#message:14:(Peach_00B4) {
	[Style right]
	So! [Pause 5]It was you, Princess Peach![BR]
	[Pause 5]You've got to keep it down![BR]
	[Wait][Next]
	You're a prisoner, and as a[BR]
	prisoner you need to keep...[BR]
	[Wait][Next]
	[Pause 4].[Pause 4].[Pause 4].[Pause 5][PrintRising]Whuh!?[BR]
	[/PrintRising][Yield][Pause 10]What are you doing out of your[BR]
	room, anyway![Wait][End]
}

#message:14:(Peach_00B5) {
	[Style right]
	Guards!![BR]
	[Pause 10]Get the princess![Wait][End]
}

#message:14:(Peach_00B6) {
	[Style right]
	[Wave]Nooooo!![Wait][End]
}

#message:14:(Peach_00B7) {
	[Style right]
	Things are getting pretty weird[BR]
	in the castle, huh?[Wait][End]
}

#message:14:(Peach_00B8) {
	[Style right]
	[Voice star]
	You said it...[BR]
	[Pause 10]But at least we can go[BR]
	downstairs with this key.[BR]
	[Wait][Next]
	Maybe we'll find something out[BR]
	while we're down there![Wait][End]
}

#message:14:(Peach_00B9) {
	[Style right]
	Well, here's the kitchen.[BR]
	[Wait][Next]
	So...[BR]
	[Pause 10]What shall we do first?[Wait][End]
}

#message:14:(Peach_00BA) {
	[Style right]
	[Voice star]
	Princess Peach![BR]
	[Pause 10]This looks like a good cookbook.[BR]
	[Pause 10]Let's use it, OK?[Wait][End]
}

#message:14:(Peach_00BB) {
	[Style right]
	How's it look? [Pause 5]Twink?[BR]
	[Pause 10]Anything look really yummy?[Wait][End]
}

#message:14:(Peach_00BC) {
	[Style right]
	[Voice star]
	Hang on a second...[BR]
	[Pause 10][Wait][Next]
	[Pause 10]Oh! How about this?[BR]
	[Pause 10]"Special Strawberry Cake."[Wait][End]
}

#message:14:(Peach_00BD) {
	[Style right]
	...Sounds good![HEART][BR]
	[Pause 10]Let's whip one up![BR]
	[Wait][Next]
	OK, Twink,[BR]
	[Pause 5]read me the recipe.[Wait][End]
}

#message:14:(Peach_00BE) {
	[Style right]
	[Voice star]
	We're in the middle of the[BR]
	recipe! Where are you going?[Wait][End]
}

#message:14:(Peach_00BF) {
	[Next]
	[Voice star]
	Ummmm...[BR]
	[Pause 10]You haven't made anything yet.[Wait][End]
}

#message:14:(Peach_00C0) {
	[Next]
	[Voice star]
	Ummm... It needs something...[BR]
	[Pause 10]You haven't decorated it yet.[Wait][End]
}

#message:14:(Peach_00C1) {
	[Style right]
	[Voice star]
	Princess Peach, you're leaving[BR]
	without the cake![Wait][End]
}

#message:14:(Peach_00C2) {
	[Style right]
	[Voice star]
	OK, Princess Peach.[BR]
	[Pause 10]This time, we're gonna make a[BR]
	delicious cake, right?[Wait][End]
}

#message:14:(Peach_00C3) {
	[Style right]
	We sure are! I know we can![BR]
	[Pause 10]This is going to be the best cake[BR]
	Gourmet Guy's ever eaten![BR]
	[Wait][Yield][End]
}

#message:14:(Peach_00C4) {
	[Next]
	OK, Twink,[BR]
	[Pause 5]if you please, read me that[BR]
	recipe again.[Wait][End]
}

#message:14:(Peach_00C5) {
	[Style right]
	[Voice star]
	Let's start from where we left[BR]
	off, OK?[BR]
	[Wait][Next]
	We got as far as putting in the[BR]
	Sugar and Eggs...[BR]
	[Wait][Next]
	but we need to mix it better.[Wait][End]
}

#message:14:(Peach_00C6) {
	[Style right]
	[Voice star]
	Your bowl's over there. It has[BR]
	Sugar and Eggs already in it.[BR]
	[Pause 5]Why don't you go over there?[Wait][End]
}

#message:14:(Peach_00C7) {
	[Style right]
	[Voice star]
	Let's start from where we left[BR]
	off, OK?[BR]
	[Wait][Next]
	We got as far as mixing the[BR]
	materials in the bowl...[BR]
	[Wait][Next]
	but the Flour and Butter need[BR]
	to be added properly.[Wait][End]
}

#message:14:(Peach_00C8) {
	[Style right]
	[Voice star]
	You already have a bowl with[BR]
	some batter in it over there.[BR]
	[Wait][Next]
	Now you need to add Flour and[BR]
	Butter to the bowl.[Wait][End]
}

#message:14:(Peach_00C9) {
	[Style right]
	[Voice star]
	Let's start from where we left[BR]
	off, OK?[BR]
	[Wait][Next]
	We got as far as adding Flour[BR]
	and Butter...[BR]
	[Wait][Next]
	but the actual baking part[BR]
	needs some work.[Wait][End]
}

#message:14:(Peach_00CA) {
	[Style right]
	[Voice star]
	Your bowl full of batter is right[BR]
	over there.[BR]
	[Wait][Next]
	Mix it lightly and pour it into the[BR]
	pan, OK, Princess?[BR]
	[Wait][Next]
	After you've poured it into the[BR]
	pan, bake it in the oven for 30[BR]
	seconds.[Wait][End]
}

#message:14:(Peach_00CB) {
	[Style right]
	[Voice star]
	Let's start from where we left[BR]
	off, OK.[BR]
	[Wait][Next]
	We got as far as baking the[BR]
	cake in the oven...[BR]
	[Wait][Next]
	We should've decorated it with[BR]
	the Cream first and then the[BR]
	Strawberries, I guess. Oh well.[BR]
	Let's do it right this time.[Wait][End]
}

#message:14:(Peach_00CC) {
	[Style right]
	[Voice star]
	Hey, that's one good looking[BR]
	cake, huh?[BR]
	[Wait][Next]
	All we have to do now is decorate[BR]
	it and we're done.[BR]
	[Wait][Next]
	What you want to do is put some[BR]
	Cream on it first and then add[BR]
	some Strawberries.[Wait][End]
}

#message:14:(Peach_00CD) {
	[Next]
	[Voice star]
	You want to start over from the[BR]
	beginning, Princess?[BR]
	[Pause 10]Let's clean up first.[Wait][End]
}

#message:14:(Peach_00CE) {
	[Style right]
	[Voice star]
	OK, Princess Peach,[BR]
	[Pause 10]this time we can do it![Wait][End]
}

#message:14:(Peach_00CF) {
	[Style right]
	We sure can! I know we can![BR]
	[Pause 10]This is going to be the best cake[BR]
	Gourmet Guy's ever eaten![BR]
	[Wait][Yield][End]
}

#message:14:(Peach_00D0) {
	[Next]
	OK, Twink,[BR]
	[Pause 5]if you please, read me that[BR]
	recipe again.[Wait][End]
}

#message:14:(Peach_00D1) {
	[Style right]
	[Voice star]
	Well[Pause 4].[Pause 4].[Pause 4].[BR]
	[Pause 5][Wait][Next]
	OK. Please listen carefully.[BR]
	[Pause 10]First... [BR]
	[Pause 5][Wait][Next]
	[Color 0x0]put Sugar and Eggs in a bowl[Color 0xA].[BR]
	[Wait][Next]
	Go ahead, Princess Peach.[BR]
	[Wait][Next]
	When you've finished, let me know[BR]
	and we'll move on to the next[BR]
	step.[Wait][End]
}

#message:14:(Peach_00D2) {
	[Style right]
	[Voice star]
	Done?[BR]
	[Yield][End]
}

#message:14:(Peach_00D3) {
	[Next]
	[Voice star]
	Please tell me when you're done.[Wait][End]
}

#message:14:(Peach_00D4) {
	[Next]
	[Voice star]
	OK. Let's move on to the next[BR]
	step then.[BR]
	[Wait][Next]
	Now[Pause 4].[Pause 4].[Pause 4].[BR]
	[Pause 5][Wait][Next]
	[Color 0x0]Mix and whip the ingredients in[BR]
	the bowl[Color 0xA].[Wait][End]
}

#message:14:(Peach_00D5) {
	[Style right]
	[Voice star]
	All set?[BR]
	[Wait][Next]
	When I say "start," press [A] as[BR]
	fast as you can for 10 seconds[BR]
	to mix the batter.[BR]
	[Wait][Next]
	Are you ready?[BR]
	[Wait][Next]
	Start![BR]
	[Pause 60][End]
}

#message:14:(Peach_00D6) {
	[Style right]
	[Voice star]
	That's it! Great job![BR]
	[Pause 10]Did it go well, Princess Peach?[BR]
	[Yield][End]
}

#message:14:(Peach_00D7) {
	[Next]
	[Voice star]
	Oh, no! In that case, what do[BR]
	you want to do now?[BR]
	[Yield][End]
}

#message:14:(Peach_00D8) {
	[Style right]
	[Voice star]
	OK. Let's go on to the next step[BR]
	then.[BR]
	[Wait][Next]
	Now[Pause 4].[Pause 4].[Pause 4].[BR]
	[Pause 5][Wait][Next]
	[Color 0x0]Put Flour and Butter in the bowl[Color 0xA].[BR]
	[Wait][Next]
	Go ahead, Princess Peach.[BR]
	[Wait][Next]
	Just let me know when you're[BR]
	done and we'll move on to the[BR]
	next part of the recipe.[Wait][End]
}

#message:14:(Peach_00D9) {
	[Style right]
	[Voice star]
	Done?[BR]
	[Yield][End]
}

#message:14:(Peach_00DA) {
	[Next]
	[Voice star]
	Just let me know as soon as[BR]
	you're done.[Wait][End]
}

#message:14:(Peach_00DB) {
	[Style right]
	[Voice star]
	OK. After you've mixed the[BR]
	ingredients in the bowl, pour it[BR]
	into the pan.[Wait][End]
}

#message:14:(Peach_00DC) {
	[Style right]
	[Voice star]
	On to the next step![BR]
	[Wait][Next]
	Now[Pause 4].[Pause 4].[Pause 4].[BR]
	[Pause 5][Wait][Next]
	[Color 0x0]Bake the batter in the oven for[BR]
	30 seconds[Color 0xA].[BR]
	[Wait][Next]
	OK. Head over to the oven.[Wait][End]
}

#message:14:(Peach_00DD) {
	[Style right]
	[Voice star]
	You can put the cake in the[BR]
	oven with [A].[BR]
	[Wait][Next]
	Press [A] again when you think[BR]
	30 seconds has passed, then[BR]
	take the cake out of the oven.[BR]
	[Wait][Next]
	You can't redo this part, so be[BR]
	extra careful.[BR]
	[Wait][Next]
	OK. Please put it in the oven.[Wait][End]
}

#message:14:(Peach_00DE) {
	[Style right]
	[Voice star]
	Done?[BR]
	[Yield][End]
}

#message:14:(Peach_00DF) {
	[Next]
	[Voice star]
	Oh, no! In that case, what do[BR]
	you want to do now?[BR]
	[Yield][End]
}

#message:14:(Peach_00E0) {
	[Next]
	[Voice star]
	OK, put the cake on the table to[BR]
	cool.[Wait][End]
}

#message:14:(Peach_00E1) {
	[Style right]
	[Voice star]
	OK. This is the last thing to do.[BR]
	[Pause 10][Color 0x0]We're going to decorate it with[BR]
	cream and strawberries.[BR]
	[Color 0xA][Wait][Next]
	Let me know when you're all[BR]
	finished decorating.[Wait][End]
}

#message:14:(Peach_00E2) {
	[Style right]
	[Voice star]
	Done?[BR]
	[Yield][End]
}

#message:14:(Peach_00E3) {
	[Next]
	[Voice star]
	Just let me know as soon as[BR]
	you're done.[Wait][End]
}

#message:14:(Peach_00E4) {
	[Next]
	[Voice star]
	Yes!![BR]
	[Pause 10]We made it! It looks great![BR]
	[Wait][Next]
	OK! Let's take this to Gourmet[BR]
	Guy![Wait][End]
}

#message:14:(Peach_00E5) {
	[Style inspect]
	[Color 0x0]Pick up this [Color 0x7][Var 0][Color 0x0]?[BR]
	[Yield][End]
}

#message:14:(Peach_00E6) {
	[Style inspect]
	[Color 0x0]Put down this [Color 0x7][Var 0][Color 0x0]?[BR]
	[Yield][End]
}

#message:14:(Peach_00E7) {
	[Style inspect]
	[Color 0x0]You picked up the [Color 0x7][Var 0][Color 0x0].[Wait][End]
}

#message:14:(Peach_00E8) {
	[Next]
	[Color 0x0]You put down the [Color 0x7][Var 0][Color 0x0].[Wait][End]
}

#message:14:(Peach_00E9) {
	[Style inspect]
	[Color 0x0]Put down this [Color 0x7][Var 0][Color 0x0] and[BR]
	pick up this [Color 0x7][Var 1][Color 0x0]?[BR]
	[Yield][End]
}

#message:14:(Peach_00EA) {
	[Next]
	[Color 0x0]You put down the [Color 0x7][Var 0][Color 0x0] and[BR]
	picked up the [Color 0x7][Var 1][Color 0x0].[Wait][End]
}

#message:14:(Peach_00EB) {
	[Style right]
	...[BR]
	[Pause 20][Wait][Next]
	...Hey, Twink...[BR]
	[Pause 10]How would you feel about[BR]
	sneaking out of here again?[BR]
	[Pause 10]Shall we try?[Wait][End]
}

#message:14:(Peach_00EC) {
	[Style right]
	[Voice star]
	Princess Peach![BR]
	[Pause 10]You've gotten so bold![BR]
	[Wait][Next]
	And here I thought you were[BR]
	gentle and delicate...[Wait][End]
}

#message:14:(Peach_00ED) {
	[Style right]
	[PrintRising]Oh.......[BR]
	[/PrintRising][Pause 10]I... [Pause 10]I am delicate![BR]
	[Wait][Next]
	I'm behaving like a delicate[BR]
	princess, just like the Ministers[BR]
	taught me to! [BR]
	[Wait][Next]
	I [Pause 5]love [Pause 5]to [Pause 5]be [Pause 5]del[Pause 5]icate![Pause 5][HEART][Wait][End]
}

#message:14:(Peach_00EE) {
	[Style right]
	[Voice star]
	OK, OK...[BR]
	[Pause 15]...I believe you, Peach. You're[BR]
	the princess...[BR]
	[Wait][Next]
	Anyway, let's go for it.[Wait][End]
}

#message:14:(Peach_00EF) {
	[Style right]
	[PrintRising]Oh! [Pause 10]It's Princess Peach![BR]
	[/PrintRising]How'd she get out?![BR]
	[Wait][Next]
	King Bowser's really gonna flip[BR]
	his wig if we don't take her back[BR]
	to her room![Wait][End]
}

#message:14:(Peach_00F0) {
	[Style right]
	Now, hang on just a second. Get[BR]
	a grip on yourself, OK? No need[BR]
	to panic. She can't get out of[BR]
	the castle, anyway.[BR]
	[Wait][Next]
	And besides... What do you think[BR]
	about asking Princess Peach to[BR]
	participate in our little game?[BR]
	[Wait][Next]
	She'd be ideal, and we need a[BR]
	third person...[Wait][End]
}

#message:14:(Peach_00F1) {
	[Style right]
	Hmmm... [Pause 5]Yeeeeah. Yeah![BR]
	[Pause 10]You might be on to something![Wait][End]
}

#message:14:(Peach_00F2) {
	[Style right]
	OK! Let's do it![BR]
	[Wait][Next]
	Princess Peach, have you been[BR]
	listening? Come this way.[BR]
	[Wait][Next]
	We won't tell King Bowser about[BR]
	your escape if you help us with[BR]
	this little game we're playing.[Wait][End]
}

#message:14:(Peach_00F3) {
	[Style right]
	We're set up right over here.[Wait][End]
}

#message:14:(Peach_00F4) {
	[Style right]
	[Voice star]
	Oh no... [Pause 5]Princess Peach![Wait][End]
}

#message:14:(Peach_00F5) {
	[Style left]
	Koopa Corps. Presents...[BR]
	[Pause 25][Scroll 1][CenterX 156][Down 8]        The 64th[BR]
	[Down 5][PrintRising][Wave]  Trivia Quiz-Off!![Wait][End]
}

#message:14:(Peach_00F6) {
	[Style left]
	I'm your host,[BR]
	[PrintRising][Wave]Mr. Hammer!![Wait][End]
}

#message:14:(Peach_00F7) {
	[Style right]
	? [Pause 10]? ? [Pause 10]? ? ? ? ? ? ? ?[Wait][End]
}

#message:14:(Peach_00F8) {
	[Style right]
	Let's get right to it, hey![BR]
	[Pause 10]I'm gonna ask you 10 questions,[BR]
	and the contestant who gets the[BR]
	most right is our winner![BR]
	[Wait][Next]
	Press [A] when you think you know[BR]
	the answer, OK, folks?[BR]
	[Wait][Next]
	The winner will get a gorgeous,[BR]
	fabulous prize![BR]
	[Pause 10]Good luck to all of you![BR]
	[Wait][Next]
	Oh, and I gotta tell you...[BR]
	[Wait][Next]
	We're also giving prizes just[BR]
	for participating, so everybody[BR]
	will be a winner! That's just the[BR]
	kind of show we are![Wait][End]
}

#message:14:(Peach_00F9) {
	[Style right]
	[PrintRising]All right! Princess Peach![BR]
	[Pause 40][End]
}

#message:14:(Peach_00FA) {
	[Style right]
	[PrintRising]All right! Spiky Tom![BR]
	[Pause 40][End]
}

#message:14:(Peach_00FB) {
	[Style right]
	[PrintRising]All right! Spiky John![BR]
	[Pause 40][End]
}

#message:14:(Peach_00FC) {
	[Style right]
	Ready?[BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 1![BR]
	[Down 5][Wait][Scroll 3]What's the name of the boss[BR]
	inside the volcano on Lavalava[BR]
	Island?[BR]
	[Yield][End]
}

#message:14:(Peach_00FD) {
	[Style right]
	Uhhh...Lava Piranha?[BR]
	[Pause 40][End]
}

#message:14:(Peach_00FE) {
	[Style right]
	Let's go on to the next question,[BR]
	OK, folks?[BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 2![BR]
	[Down 5][Wait][Scroll 3]Where did Master Huff N. Puff [BR]
	imprison the Star Spirit?[BR]
	[Yield][End]
}

#message:14:(Peach_00FF) {
	[Style right]
	In Flower Fields![BR]
	[Pause 40][End]
}

#message:14:(Peach_0100) {
	[Style right]
	OK!  Next![BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 3![BR]
	[Down 5][Wait][Scroll 3]What is the name of the scary[BR]
	round monster living in Dry Dry[BR]
	Ruins?[BR]
	[Yield][End]
}

#message:14:(Peach_0101) {
	[Style right]
	A...Chomp![BR]
	[Pause 40][End]
}

#message:14:(Peach_0102) {
	[Style right]
	You've still got a chance to make[BR]
	a comeback![BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 4![BR]
	[Down 5][Wait][Scroll 3]How would you get to Flower[BR]
	Fields?[BR]
	[Yield][End]
}

#message:14:(Peach_0103) {
	[Style right]
	Ummm...by passing through the[BR]
	Flower Gate![BR]
	[Pause 40][End]
}

#message:14:(Peach_0104) {
	[Style right]
	It's still anyone's game![BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 5![BR]
	[Down 5][Wait][Scroll 3]What's the name of the person[BR]
	who King Bowser really loves?[BR]
	[Yield][End]
}

#message:14:(Peach_0105) {
	[Style right]
	That's easy! Princess Peach![BR]
	[Pause 40][End]
}

#message:14:(Peach_0106) {
	[Style right]
	Careful now![BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 6![BR]
	[Down 5][Wait][Scroll 3]What thing is most deeply [BR]
	related to Flower Fields?[BR]
	[Yield][End]
}

#message:14:(Peach_0107) {
	[Style right]
	I know! Flowers![BR]
	[Pause 40][End]
}

#message:14:(Peach_0108) {
	[Style right]
	This next question is an easy[BR]
	one, folks.[BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 7![BR]
	[Down 5][Wait][Scroll 3]What's the name of the most[BR]
	admirable, invincible, just[BR]
	downright cool guy around?[BR]
	[Yield][End]
}

#message:14:(Peach_0109) {
	[Style right]
	King Bowser, of course.[BR]
	[Pause 40][End]
}

#message:14:(Peach_010A) {
	[Style right]
	Think carefully, now.[BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 8![BR]
	[Down 5][Wait][Scroll 3]What's the name for the ghosts[BR]
	who live in and around Forever[BR]
	Forest?[BR]
	[Yield][End]
}

#message:14:(Peach_010B) {
	[Style right]
	Boos... Boos![BR]
	[Pause 40][End]
}

#message:14:(Peach_010C) {
	[Style right]
	Use your memory on this one![BR]
	[Wait][Next]
	[BR]
	[Down 5]            Question 9![BR]
	[Down 5][Wait][Scroll 3]What's the name of the area[BR]
	just to the south of the post[BR]
	office in Toad Town?[BR]
	[Yield][End]
}

#message:14:(Peach_010D) {
	[Style right]
	Ooh! The flower garden![BR]
	[Pause 40][End]
}

#message:14:(Peach_010E) {
	[Style right]
	Now for the final question![BR]
	[Pause 10]Stay calm, everyone...[BR]
	[Wait][Next]
	[BR]
	[Down 5]           Question 10![BR]
	[Down 5][Wait][Scroll 3]Where is Peach's Castle now?[BR]
	[Yield][End]
}

#message:14:(Peach_010F) {
	[Style right]
	Way up in the sky, on top of[BR]
	Bowser's Castle.[BR]
	[Pause 40][End]
}

#message:14:(Peach_0110) {
	[Style right]
	[PrintRising]That's correct![BR]
	[Pause 40][End]
}

#message:14:(Peach_0111) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "Lava Piranha."[Wait][End]
}

#message:14:(Peach_0112) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "Flower Fields."[Wait][End]
}

#message:14:(Peach_0113) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "Chomp."[Wait][End]
}

#message:14:(Peach_0114) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "By passing[BR]
	through the Flower Gate."[Wait][End]
}

#message:14:(Peach_0115) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "Princess[BR]
	Peach."[Wait][End]
}

#message:14:(Peach_0116) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "flowers."[Wait][End]
}

#message:14:(Peach_0117) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "King Bowser."[Wait][End]
}

#message:14:(Peach_0118) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "Boos."[Wait][End]
}

#message:14:(Peach_0119) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "The flower [BR]
	garden."[Wait][End]
}

#message:14:(Peach_011A) {
	[Style right]
	I'm sorry...that's wrong![BR]
	[Pause 40][Next]
	The answer was "Above Bowser's[BR]
	Castle in the sky."[Wait][End]
}

#message:14:(Peach_011B) {
	[Style right]
	So the 64th Trivia Quiz-Off has[BR]
	ended...[BR]
	[Pause 10]in great success![BR]
	[Wait][Next]
	The winner is... [Pause 10]Spi[Pause 5]ky [Pause 5]TOM![BR]
	[Wait][Yield][End]
}

#message:14:(Peach_011C) {
	[Next]
	Congratulations![BR]
	[Pause 10]Here's your prize.[Wait][End]
}

#message:14:(Peach_011D) {
	[Style inspect]
	Spiky Tom got Jammin' Jelly.[Wait][End]
}

#message:14:(Peach_011E) {
	[Style right]
	So the 64th Trivia Quiz-Off has[BR]
	ended...[BR]
	[Pause 10]in great success![BR]
	[Wait][Next]
	The winner is...[BR]
	[Pause 10]Spiky [Pause 5]JOHN!!!!!!![BR]
	[Wait][Yield][End]
}

#message:14:(Peach_011F) {
	[Next]
	Congratulations![BR]
	[Pause 10]Here's your prize.[Wait][End]
}

#message:14:(Peach_0120) {
	[Style inspect]
	Spiky John got Jammin' Jelly.[Wait][End]
}

#message:14:(Peach_0121) {
	[Style right]
	So the 64th Trivia Quiz-Off has[BR]
	ended...[BR]
	[Pause 10]in great success![BR]
	[Wait][Next]
	The winner is... [Pause 10]Wow![BR]
	[Pause 5]Our unexpected guest, Princess[BR]
	Peach!![BR]
	[Wait][Yield][End]
}

#message:14:(Peach_0122) {
	[Next]
	Congratulations, Peach![BR]
	[Pause 10]Here's your prize.[Wait][End]
}

#message:14:(Peach_0123) {
	[Style right]
	So the 64th Trivia Quiz-Off has[BR]
	ended...[BR]
	[Pause 10]in great success![BR]
	[Pause 15][Wait][Next]
	The winner is... Oops![BR]
	[Pause 10]Princess Peach and Spiky Tom[BR]
	have the same score![BR]
	[Pause 5]It's a draw![BR]
	[Wait][Next]
	So I'll take the prize. Ha![Wait][End]
}

#message:14:(Peach_0124) {
	[Style right]
	So the 64th Trivia Quiz-Off has[BR]
	ended...[BR]
	[Pause 10]in great success![BR]
	[Pause 15][Wait][Next]
	The winner is... Hey![BR]
	[Pause 10]No one has any points! Weak![BR]
	[Pause 5]It's a tie![BR]
	[Wait][Next]
	So I'll take the prize. Ha![Wait][End]
}

#message:14:(Peach_0125) {
	[Style right]
	Thank you for coming, everyone![BR]
	It's been grand![BR]
	[Wait][Next]
	We'll see you at the next Trivia[BR]
	Quiz-Off!![Wait][End]
}

#message:14:(Peach_0126) {
	[Style right]
	Oh... [Pause 5]Princess Peach.[BR]
	[Pause 10]I almost forgot! Here's your[BR]
	prize for participating.[Wait][End]
}

#message:14:(Peach_0127) {
	[Style right]
	This is a Sneaky Parasol.[BR]
	[Pause 10]If you face someone and press[BR]
	[B] you can transform into that[BR]
	person.[BR]
	[Wait][Next]
	You just have to promise not to[BR]
	use it to sneak around.[BR]
	[Pause 10]I mean, nobody would know you[BR]
	were Princess Peach! Imagine![BR]
	[Wait][Next]
	Sorry for giving you such a little[BR]
	prize, Princess.[BR]
	[Wait][Next]
	Heh heh heh... Hey, it's only a[BR]
	prize for participating...so what[BR]
	do you expect!?[Wait][End]
}

#message:14:(Peach_0128) {
	[Style right]
	[Voice bowser]
	Huh?[BR]
	[Pause 10]What are you all doing?[BR]
	[Yield][End]
}

#message:14:(Peach_0129) {
	[Wait][Next]
	[Voice bowser]
	Hey! It looks fun![BR]
	[Pause 10]I'm gonna join in![Wait][End]
}

#message:14:(Peach_012A) {
	[Style right]
	[Voice bowser]
	What?[BR]
	[Pause 10]You've already finished?[BR]
	[Pause 15]Aw, of all the rotten luck...[Wait][End]
}

#message:14:(Peach_012B) {
	[Style right]
	[Voice bowser]
	[PrintRising]Gaaaah!![BR]
	[/PrintRising][Yield][Pause 10]Princess Peach? What's she doing[BR]
	here?[BR]
	[Wait][Next]
	She sneaked out again! Grr![BR]
	[Wait][Next]
	You!! [BR]
	[Pause 10]Take Princess Peach back to her[BR]
	room! Now!![Wait][End]
}

#message:14:(Peach_012C) {
	[Style right]
	Yes, sir!![Wait][End]
}

#message:14:(Peach_012D) {
	[Style right]
	Sorry, Princess Peach![Wait][End]
}

#message:14:(Peach_012E) {
	[Style right]
	[PrintRising]Nooooo!![Wait][End]
}

#message:14:(Peach_012F) {
	[Style right]
	Hey... Twink.[BR]
	[Pause 10]You know the Sneaky Parasol I[BR]
	got on that quiz show?[BR]
	[Wait][Next]
	I can change into someone else[BR]
	when I use it, right?[BR]
	[Wait][Next]
	So don't you think I can use it[BR]
	to get out of here?[Wait][End]
}

#message:14:(Peach_0130) {
	[Style right]
	[Voice star]
	Yeah... I bet you can...[BR]
	[Pause 10]Why don't you try it out?[BR]
	[Wait][Next]
	Press [B] while facing whoever it[BR]
	is you want to transform into. [Wait][End]
}

#message:14:(Peach_0131) {
	[Style right]
	Hey. [Pause 5]How goes it?[BR]
	[Wait][Next]
	Phew... They've been working me[BR]
	like a dog lately... [Wait][End]
}

#message:14:(Peach_0132) {
	[Style right]
	You too?[BR]
	[Pause 10]Seems like everybody's busy...[BR]
	[Wait][Next]
	King Bowser's all ticked off[BR]
	about something and Kammy[BR]
	Koopa takes it out on us.[BR]
	[Wait][Next]
	You think, maybe...? Maybe it[BR]
	means that Mario's coming to[BR]
	defeat King Bowser![Wait][End]
}

#message:14:(Peach_0133) {
	[Style right]
	Sayyyy...[BR]
	[Pause 10]I heard that Kammy Koopa is[BR]
	building some big thing above[BR]
	Princess Peach's Castle.[BR]
	[Wait][Next]
	I bet you it's a secret weapon[BR]
	designed to defeat Mario.[Wait][End]
}

#message:14:(Peach_0134) {
	[Style right]
	That thing that Kammy Koopa's[BR]
	making up above the castle... I[BR]
	wonder what she could possibly[BR]
	do with it?[BR]
	[Wait][Next]
	It's not even possible for Mario[BR]
	to get up here, so why would she[BR]
	need a secret weapon?[Wait][End]
}

#message:14:(Peach_0135) {
	[Style right]
	On patrol? Very good, then.[BR]
	[Pause 5]You can pass through.[Wait][End]
}

#message:14:(Peach_0136) {
	[Style right]
	What are you doing here?[BR]
	[Pause 5]Get back to your station![BR]
	[Wait][Next]
	Kammy Koopa will chew us both[BR]
	out if she finds you here instead[BR]
	of at your post![Wait][End]
}

#message:14:(Peach_0137) {
	[Style right]
	Huh? [Pause 5]Are you insane? Get back [BR]
	to your post! Do you have any[BR]
	idea what Kammy Koopa will do to[BR]
	you if she finds you here?[Wait][End]
}

#message:14:(Peach_0138) {
	[Style right]
	Why do we bother patrolling?[BR]
	[Pause 10]I mean, don't you agree? Sure, I[BR]
	know, Princess Peach got out a[BR]
	couple of times... [BR]
	[Wait][Next]
	But this castle is hovering in the[BR]
	middle of the sky! Where's she[BR]
	gonna go? Huh?[BR]
	[Wait][Next]
	I think King Bowser's nervous. He[BR]
	hides it well, though.[Wait][End]
}

#message:14:(Peach_0139) {
	[Style right]
	Listen, don't hang around me.[BR]
	Kammy Koopa'll get really mad[BR]
	if she finds you here.[BR]
	[Wait][Next]
	I guess I understand why you're[BR]
	so curious, though.[BR]
	[Pause 10]It's not often you get to see so[BR]
	many books in one place.[BR]
	[Wait][Next]
	I've gotta admit, sometimes I[BR]
	sneak a few peeks myself... [BR]
	[Pause 5]Heh heh heh...[Wait][End]
}

#message:14:(Peach_013A) {
	[Style right]
	Wha... [Pause 5]What're you looking at?[BR]
	[Pause 10]I... I'm not looking for the book[BR]
	you think I'm looking for![BR]
	[Wait][Next]
	I swear! No fooling![BR]
	[Wait][Next]
	I'm trying to study...something![BR]
	[Pause 10]Here, take this and go away! [Wait][End]
}

#message:14:(Peach_013B) {
	[Style right]
	Seriously, leave me alone.[BR]
	[Pause 10]I'm really trying to study.[BR]
	[Wait][Next]
	I always get this killer headache[BR]
	when I open a book...[Wait][End]
}

#message:14:(Peach_013C) {
	[Style right]
	Hey! You![BR]
	[Pause 10]Stop loitering around here![Wait][End]
}

#message:14:(Peach_013D) {
	[Style right]
	Are you still here!?[BR]
	[Pause 5]Get back to your post before I'm[BR]
	forced to report you to Kammy[BR]
	Koopa![Wait][End]
}

#message:14:(Peach_013E) {
	[Style right]
	Why'd you leave your station?[BR]
	[Pause 5]Oh... You're looking for your[BR]
	relief, huh? Well, get a move on,[BR]
	then![Wait][End]
}

#message:14:(Peach_013F) {
	[Style right]
	Sighhh... [Pause 10]So booooored...[BR]
	[Wait][Next]
	I wish I were Princess Peach's[BR]
	personal guard. Then I could[BR]
	admire at her beauty all day[BR]
	long.[BR]
	[Wait][Next]
	I hope she breaks out of her[BR]
	room and comes here today...[BR]
	[Pause 10]I can't believe I said that! You[BR]
	didn't hear that, did you?[Wait][End]
}

#message:14:(Peach_0140) {
	[Style right]
	Hey! Hold up![BR]
	[Pause 10]Your shift? Oh, hurry up, then![Wait][End]
}

#message:14:(Peach_0141) {
	[Style right]
	All quiet here![BR]
	[Pause 10]... Me? Nervous? No, not me! You[BR]
	surprised me, that's all.[Wait][End]
}

#message:14:(Peach_0142) {
	[Style right]
	I'm not goofing off! I swear it![BR]
	[Pause 5]Please, let me guard in peace![Wait][End]
}

#message:14:(Peach_0143) {
	[Style right]
	Where have you been?[BR]
	[Pause 10]You took your sweet time![Wait][End]
}

#message:14:(Peach_0144) {
	[Style right]
	Where's my relief, already?[BR]
	[Pause 10]My shift has been over for ages[BR]
	now! [BR]
	[Wait][Next]
	Listen... Could you go find that[BR]
	slacker and get him up here?[BR]
	[Pause 8]Please! I'm exhausted![BR]
	[Wait][Next]
	[SavePos][SetPosX 5][Down 1][AnimDelay index=0 delay=5][AnimSprite spriteID=0x0039 raster=31]
	[AnimDelay index=1 delay=6][AnimSprite spriteID=0x0039 raster=32]
	[AnimDelay index=2 delay=5][AnimSprite spriteID=0x0039 raster=31]
	[AnimDelay index=3 delay=6][AnimSprite spriteID=0x0039 raster=32]
	[AnimLoop 0 0][AnimDone 0][RestorePos][BR]
	[SetPosX 70][Down 5][LEFT] He looks like this.[BR]
	[BR]
	[Up 5][Wait][Scroll 4][Down 11]He's probably goofing off[BR]
	outside the castle somewhere.[BR]
	[Pause 10]Here. [Pause 5]Take this to find him.[Wait][End]
}

#message:14:(Peach_0145) {
	[Style right]
	It's the key to the entrance of[BR]
	the castle.[BR]
	[Wait][Next]
	You won't be able to get[BR]
	downstairs without it.[Wait][End]
}

#message:14:(Peach_0146) {
	[Style right]
	He still hasn't shown up...[BR]
	[Wait][Next]
	[SavePos][SetPosX 5][Down 1][AnimDelay index=0 delay=5][AnimSprite spriteID=0x0039 raster=31]
	[AnimDelay index=1 delay=6][AnimSprite spriteID=0x0039 raster=32]
	[AnimDelay index=2 delay=5][AnimSprite spriteID=0x0039 raster=31]
	[AnimDelay index=3 delay=6][AnimSprite spriteID=0x0039 raster=32]
	[AnimLoop 0 0][AnimDone 0][RestorePos][BR]
	[SetPosX 70][Down 5][LEFT] Find this guy, OK?[BR]
	[BR]
	[Up 5][Wait][End]
}

#message:14:(Peach_0147) {
	[Style right]
	Ah! Finally! About time![BR]
	[Pause 10]You're so late! Again![BR]
	[Pause 10]Don't you know how to read the[BR]
	shift schedule?[BR]
	[Wait][Next]
	[Pause 10]Well, I guess I'll let it go this[BR]
	time, but watch it, OK?[BR]
	[Pause 10]OK. Have a good shift.[BR]
	[Pause 10]I'm shovin' off.[Wait][End]
}

#message:14:(Peach_0148) {
	[Style right]
	Don't goof off, either![BR]
	[Pause 10]You're on thin ice, buddy![Wait][End]
}

#message:14:(Peach_0149) {
	[Style right]
	[Wave]Zzzzz...[Wait][End]
}

#message:14:(Peach_014A) {
	[Style right]
	[Wave]Uh...nnnn...[BR]
	[Pause 10]...Princess Peach...somewhere[BR]
	around here...close by...[BR]
	[Wait][Next]
	Zzz... mumble... mumble...[Wait][End]
}

#message:14:(Peach_014B) {
	[Style right]
	Hey, it's you![BR]
	[Pause 20]Oh no, it's just me. Hello me![BR]
	[Pause 10][Wave]Zzz... mumble... mumble...[Wait][End]
}

#message:14:(Peach_014C) {
	[Style right]
	So sleepy... So very sleepy...[BR]
	[Pause 10]Just lemme catch a quick nap...[BR]
	but don't tell anyone...[BR]
	[Pause 10][Wave]Zzz... mumble... mumble...[Wait][End]
}

#message:14:(Peach_014D) {
	[Style right]
	Hey, you! Yeah, you![BR]
	[Pause 10]Entry is prohibited for[BR]
	unauthorized people.[BR]
	[Wait][Next]
	But...you're already up here, so[BR]
	I guess it's too late.[BR]
	[Wait][Next]
	It's a stupid restriction,[BR]
	anyway.[Wait][End]
}

#message:14:(Peach_014E) {
	[Style right]
	It's about time Kammy Koopa[BR]
	came back down.[BR]
	[Wait][Next]
	I wonder what she could be doing[BR]
	up there? All those construction[BR]
	sounds...[Wait][End]
}

#message:14:(Peach_014F) {
	[Style right]
	OK, OK. Everything's finally[BR]
	ready.[BR]
	[Wait][Next]
	Even if Mario shows up with all of[BR]
	the Star Spirits, we'll still be[BR]
	all right![BR]
	[Wait][Next]
	It pays to expect the worst.[Wait][End]
}

#message:14:(Peach_0150) {
	[Style right]
	Absolutely! Affirmative! You're[BR]
	right, Kammy Koopa![Wait][End]
}

#message:14:(Peach_0151) {
	[Style right]
	Mmm!![BR]
	[Pause 10]You there![Wait][End]
}

#message:14:(Peach_0152) {
	[Style right]
	You're doing a fine job.[Wait][End]
}

#message:14:(Peach_0153) {
	[Style right]
	Keep up the good... Wait...[BR]
	[Pause 5]Something's weird about you...[BR]
	[Pause 10]You smell...too nice...[Wait][End]
}

#message:14:(Peach_0154) {
	[Style right]
	Yahhhh![Wait][End]
}

#message:14:(Peach_0155) {
	[Style right]
	[PrintRising]Uh-oh![Wait][End]
}

#message:14:(Peach_0156) {
	[Style right]
	You... [Pause 5]Why you little...[BR]
	[Pause 5]Princess Peach![BR]
	[Pause 10]Unbelievable! Out again!![Wait][End]
}

#message:14:(Peach_0157) {
	[Style right]
	Guards! All of you![BR]
	[Pause 5]Catch this little runaway and[BR]
	take her back to her room![Wait][End]
}

#message:14:(Peach_0158) {
	[Style right]
	[Wave]Noooo![Wait][End]
}

#message:14:(Peach_0159) {
	[Style right]
	[Voice star]
	Are you all right, Princess?[BR]
	You're not hurt, are you?[Wait][End]
}

#message:14:(Peach_015A) {
	[Style right]
	Yes, I'm fine. Thank you, Twink.[BR]
	[Pause 10]That was such a dumb mistake![BR]
	I've got to be more careful.[BR]
	[Wait][End]
}

#message:14:(Peach_015B) {
	[Style right]
	[Voice star]
	It'll be OK next time, Princess[BR]
	Peach.[BR]
	[Wait][Next]
	If you put that Sneaky Parasol[BR]
	to good use, you can get out of[BR]
	here without being spotted.[BR]
	[Wait][Next]
	Press [B] while facing the person[BR]
	you want to change into.[Wait][End]
}

#message:14:(Peach_015C) {
	[Style right]
	[Voice star]
	Princess Peach, you need to be[BR]
	more careful, OK?[BR]
	[Wait][Next]
	That Sneaky Parasol is the key[BR]
	to getting out of here without[BR]
	being discovered. Just use it[BR]
	properly.[BR]
	[Wait][Next]
	Press [B] while facing the person[BR]
	you want to change into.[Wait][End]
}

#message:14:(Peach_015D) {
	[Style right]
	[Voice star]
	It looks like you can't get out[BR]
	this door, Princess.[BR]
	[Pause 10]There has to be another way...[BR]
	[Wait][Next]
	Hey! Princess Peach![BR]
	[Pause 10]Do you remember that Sneaky[BR]
	Parasol that you won?[BR]
	[Wait][Next]
	If you put that Sneaky Parasol[BR]
	to good use, you can get out of[BR]
	here without being spotted. I'm[BR]
	sure of it![BR]
	[Wait][Next]
	Press [B] while facing the person[BR]
	you want to change into.[Wait][End]
}

#message:14:(Peach_015E) {
	[Style right]
	Oh, Mario... I wonder what he's[BR]
	doing now?[BR]
	[Wait][Next]
	I wish I knew if I was helping him[BR]
	at all...[Wait][End]
}

#message:14:(Peach_015F) {
	[Style right]
	[Voice star]
	Of course you are![BR]
	[Wait][Next]
	Mario will be fine! You should be[BR]
	proud of your efforts![BR]
	[Wait][Next]
	Mario knows all you've done.[BR]
	[Wait][Next]
	And don't you worry, Princess![BR]
	You'll be able to talk to him in[BR]
	person before long![Wait][End]
}

#message:14:(Peach_0160) {
	[Style right]
	...Tee hee hee... I hope you're[BR]
	right, Twink.[BR]
	[Pause 10]Thanks for cheering me up.[BR]
	[Wait][Next]
	Let's go back to the room, shall[BR]
	we?[Wait][End]
}

#message:14:(Peach_0161) {
	[Style right]
	[Voice bowser]
	Oh, Princess Peach! Your cuddly[BR]
	old Bowser's here![Wait][End]
}

#message:14:(Peach_0162) {
	[Style right]
	[Voice bowser]
	Can't we have a friendly[BR]
	conversation for a change?[BR]
	[Wait][Next]
	C'mon! Lemme see a smile![Wait][End]
}

#message:14:(Peach_0163) {
	[Style right]
	I have nothing to say to you.[Wait][End]
}

#message:14:(Peach_0164) {
	[Style right]
	[Voice bowser]
	Oh, don't be such a pill.[BR]
	[Wait][Next]
	You're stuck with me for a long,[BR]
	long time, beautiful.[BR]
	[Wait][Next]
	You'd better get used to it.[Wait][End]
}

#message:14:(Peach_0165) {
	[Style right]
	Mario is coming, Bowser. And you[BR]
	can't stop him.[Wait][End]
}

#message:14:(Peach_0166) {
	[Style right]
	[Down 8][Size 32,32]
	[Voice bowser]
	Gwaa ha ha ha!![BR]
	[SizeReset]
	[BR]
	[Up 12][Yield][Wait][Scroll 3]Oh, you poor, silly girl![BR]
	[Wait][Next]
	I'm invincible with this Star Rod,[BR]
	didn't you know?[BR]
	[Pause 10]Mario's no match for me![BR]
	[Wait][Next]
	He's history. Get over it.[Wait][End]
}

#message:14:(Peach_0167) {
	[Style right]
	................[BR]
	[Pause 10][Wait][End]
}

#message:14:(Peach_0168) {
	[Style right]
	Your Raunchiness! We have an[BR]
	emergency![Wait][End]
}

#message:14:(Peach_0169) {
	[Style right]
	[Voice bowser]
	Grr! It'd better be important![BR]
	[Pause 10]I'm right in the middle of a[BR]
	friendly chat with the princess.[Wait][End]
}

#message:14:(Peach_016A) {
	[Style right]
	Uh... Mario has now saved all of[BR]
	the Star Spirits![BR]
	[Wait][Next]
	There...IS a chance he could[BR]
	come here using their power...[BR]
	[Wait][Next]
	We must make ourselves ready in[BR]
	case he shows up.[Wait][End]
}

#message:14:(Peach_016B) {
	[Style right]
	[Voice bowser]
	What! Gah![BR]
	[Pause 10]Mar-i-ooooo![BR]
	[Wait][Next]
	OK. Listen, Kammy Koopa.[BR]
	[Pause 10]Send everyone to their posts! [BR]
	[Wait][Next]
	We'll ambush him the second he[BR]
	enters my castle!![Wait][End]
}

#message:14:(Peach_016C) {
	[Style right]
	[Voice bowser]
	Princess Peach, why don't you[BR]
	come with me to watch...[BR]
	[Pause 10]You can have a front-row seat[BR]
	to see Mario get crushed.[BR]
	[Wait][Next]
	You! Yeah, you![BR]
	[Pause 10]Tie her up immediately! If she[BR]
	gets out this time, heads will[BR]
	roll![Wait][End]
}

#message:14:(Peach_016D) {
	[Style right]
	No! Please![BR]
	[Pause 30][End]
}

#message:14:(Peach_016E) {
	[Style right]
	[Voice star]
	You big...Koopa! Show some[BR]
	respect to the princess![Wait][End]
}

#message:14:(Peach_016F) {
	[Style right]
	[Voice bowser]
	What is this whining little[BR]
	glittering thing? Confetti?[Wait][End]
}

#message:14:(Peach_0170) {
	[Style right]
	[Voice bowser]
	Gah! Buzz off![Wait][End]
}

#message:14:(Peach_0171) {
	[Style right]
	[PrintRising]Twiiiiink![Wait][End]
}

#message:14:(Peach_0172) {
	[Style right]
	[Voice bowser]
	Take the princess! Now! Let's[BR]
	move![Wait][End]
}

#message:14:(Peach_0173) {
	[Style right]
	[Wave]Noooo![Wait][End]
}

#message:14:(Peach_0174) {
	[Style right]
	What?! Princess Peach![BR]
	[Pause 10][Wait][End]
}

#message:14:(Peach_0175) {
	[Style right]
	You know you're not allowed to[BR]
	leave the room![BR]
	[Wait][Next]
	I'm sorry, but I have to take[BR]
	you back.[Wait][End]
}

#message:14:(Peach_0176) {
	[Style right]
	[Voice star]
	Are you all right, Princess? Did[BR]
	they hurt you?[Wait][End]
}

#message:14:(Peach_0177) {
	[Style right]
	Yes, I'm fine. Thank you, Twink.[BR]
	[Pause 10]That was just plain stupid! I've[BR]
	got to be more careful![Wait][End]
}

#message:14:(Peach_0178) {
	[Style right]
	[Voice star]
	It'll be OK next time, Princess[BR]
	Peach.[Wait][End]
}

#message:14:(Peach_0179) {
	[Style right]
	[Voice star]
	You just need to watch your[BR]
	step a little, Princess.[Wait][End]
}

#message:14:(Peach_017A) {
	[Style right]
	[Voice star]
	It doesn't look like you can get[BR]
	out through this door.[Wait][End]
}

#message:14:(Peach_017B) {
	[Style inspect]
	A rather large fireplace.[BR]
	[Pause 10]The fire feels quite warm.[Wait][End]
}

#message:14:(Peach_017C) {
	[Style inspect]
	Princess Peach's dresses.[BR]
	[Pause 10]Her favorite outfits![HEART][Wait][End]
}

#message:14:(Peach_017D) {
	[Style inspect]
	A photo of Mario.[HEART][Wait][End]
}

#message:14:(Peach_017E) {
	[Style inspect]
	A soft and comfortable bed.[HEART][Wait][End]
}

#message:14:(Peach_017F) {
	[Style inspect]
	A bouquet of Princess Peach's[BR]
	favorite flowers.[HEART][BR]
	[Pause 10]It smells incredible.[HEART][Wait][End]
}

#message:14:(Peach_0180) {
	[Style right]
	[Voice star]
	It seems to be locked.[BR]
	[Pause 5]You can't open it.[Wait][End]
}

#message:14:(Peach_0181) {
	[Style right]
	[Voice star]
	Hello? Is anyone in here?[Wait][End]
}

#message:14:(Peach_0182) {
	[Style right]
	Oh noo! I'm caught for sure![BR]
	[Wait][Next]
	... [Pause 10]Huh!?[BR]
	[Pause 10]Princess Peach! You're OK![BR]
	Thank the Stars![Wait][End]
}

#message:14:(Peach_0183) {
	[Style right]
	You're a Toad from the castle?[BR]
	[Pause 10]How long have you been hiding in[BR]
	here?[Wait][End]
}

#message:14:(Peach_0184) {
	[Style right]
	Well, since Bowser took over.[BR]
	[Pause 10]I was so scared of being caught[BR]
	that I jumped into this closet.[BR]
	[Wait][Next]
	I'm hiding here until Mario comes[BR]
	and saves us all.[BR]
	[Wait][Next]
	Princess Peach, you ought to[BR]
	hide too! It's risky out there![BR]
	[Pause 10]Please don't take any chances![Wait][End]
}

#message:14:(Peach_0185) {
	[Style right]
	Nobody's in here! Go away![Wait][End]
}

#message:14:(Peach_0186) {
	[Style right]
	Nothing in here but clothes![BR]
	Please don't open... Oh![Wait][End]
}

#message:14:(Peach_0187) {
	[Style right]
	Huh!? Mario!?[BR]
	[Wait][Next]
	... Oh, sweet!![BR]
	[Pause 10]You came to save me, right?[BR]
	[Wait][Next]
	Phew... I was so scared...[BR]
	[Wait][Next]
	Thanks for coming![BR]
	[Pause 20][Wait][Next]
	While you're here, would you like[BR]
	to take a quick nap?[BR]
	[Wait][Next]
	I'll wake you if anyone bad comes[BR]
	in, I swear it.[BR]
	[Wait][Next]
	Would you like to take a nap?[BR]
	[Yield][End]
}

#message:14:(Peach_0188) {
	[Style right]
	Huh!? Mario!?[BR]
	[Wait][Next]
	... Oh, sweet!![BR]
	[Pause 10]You came to save me, right?[BR]
	[Wait][Next]
	Phew... I was so scared...[BR]
	[Wait][Next]
	Thanks for coming![BR]
	[Pause 20][Wait][Next]
	While you're here, would you like[BR]
	to take a quick nap?[BR]
	[Wait][Next]
	Oh... Actually... You look fine.[BR]
	[Wait][Next]
	You could take a nap anyway.[BR]
	What do you say?[BR]
	[Yield][End]
}

#message:14:(Peach_0189) {
	[Style right]
	The Toad House slogan is...[BR]
	"Refresh your Body and Soul!"[BR]
	[Wait][Next]
	Tee hee hee... I always wanted[BR]
	to say that.[BR]
	[Wait][Next]
	Would you like to take a nap?[BR]
	[Yield][End]
}

#message:14:(Peach_018A) {
	[Style right]
	... ?[BR]
	[Pause 10]You look healthy to me.[BR]
	[Pause 10]Still, you're the boss. Are you[BR]
	sure you want a nap?[BR]
	[Yield][End]
}

#message:14:(Peach_018B) {
	[Next]
	Good luck![BR]
	[Pause 10]I'll be rooting for you, Mario... [BR]
	from in here.[Wait][End]
}

#message:14:(Peach_018C) {
	[Next]
	Please enjoy your rest.[Wait][End]
}

#message:14:(Peach_018D) {
	[Style right]
	Did you sleep well?[BR]
	[Wait][Next]
	Good luck, Mario![Wait][End]
}

#message:14:(Peach_018E) {
	[Style right]
	[Voice star]
	Oh! Look there![BR]
	[Pause 5]What a beautifully crafted[BR]
	treasure chest![Wait][End]
}

#message:14:(Peach_018F) {
	[Style right]
	Yes, do you like it?[BR]
	[Wait][Next]
	This is a mysterious treasure[BR]
	chest that's been passed down[BR]
	through generations of my family[BR]
	here at the castle.[Wait][End]
}

#message:14:(Peach_0190) {
	[Style right]
	[Voice star]
	Really? How mysterious.[BR]
	[Pause 5]A mysterious treasure chest...[Wait][End]
}

#message:14:(Peach_0191) {
	[Style right]
	That's right. This chest is[BR]
	connected to another mysterious[BR]
	treasure chest somewhere in the[BR]
	Mushroom Kingdom.[BR]
	[Wait][Next]
	They say you can put things in[BR]
	this chest and take them out of[BR]
	the other chest. Isn't that, well,[BR]
	mysterious?[Wait][End]
}

#message:14:(Peach_0192) {
	[Style right]
	[Voice star]
	Yeah! Wow, that's really cool.[BR]
	[Pause 10]So, where is the other treasure[BR]
	chest, anyway?[Wait][End]
}

#message:14:(Peach_0193) {
	[Style right]
	Err... Where IS it...?[BR]
	[Pause 10]You know, I can't remember![Wait][End]
}

#message:14:(Peach_0194) {
	[Style right]
	[Voice star]
	This is that mysterious treasure[BR]
	chest, isn't it?[Wait][End]
}

#message:14:(Peach_0195) {
	[Style right]
	Yes, Twink. It is.[Wait][End]
}

#message:14:(Peach_0196) {
	[Style right]
	[Voice star]
	So if I have this right, you can[BR]
	put something in here and[BR]
	someone can take it out of the[BR]
	other one, right?[BR]
	[Wait][Next]
	You know, maybe Mario could get[BR]
	whatever you put in here.[Wait][End]
}

#message:14:(Peach_0197) {
	[Style right]
	Yeah, maybe he could! What can I[BR]
	put in?[Wait][End]
}

#message:14:(Peach_0198) {
	[Style inspect]
	You put in [Var 0][Wait][End]
}
