#message:1B:(EntityTattle_HammerBlock1_CanBreak) {
	[Style tattle]
	[EnableCDownNext]Your Hammer can shatter this[BR]
	block.[BR]
	[Wait][Next]
	Break it down, Mario![Wait][End]
}

#message:1B:(EntityTattle_HammerBlock2_CantBreak) {
	[Style tattle]
	[EnableCDownNext]Your Hammer isn't strong enough[BR]
	to break this block.[BR]
	[Wait][Next]
	You might be able to break it[BR]
	with a more powerful Hammer.[Wait][End]
}

#message:1B:(EntityTattle_HammerBlock2_CanBreak) {
	[Style tattle]
	[EnableCDownNext]Your Hammer can shatter this[BR]
	block.[BR]
	[Wait][Next]
	Break it down, Mario![Wait][End]
}

#message:1B:(EntityTattle_HammerBlock3_CantBreak) {
	[Style tattle]
	[EnableCDownNext]Your Hammer isn't strong enough[BR]
	to break this block.[BR]
	[Wait][Next]
	You might be able to break it [BR]
	with a more powerful Hammer.[Wait][End]
}

#message:1B:(EntityTattle_HammerBlock3_CanBreak) {
	[Style tattle]
	[EnableCDownNext]Your Hammer can shatter this[BR]
	block.[BR]
	[Wait][Next]
	Break it down, Mario![Wait][End]
}

#message:1B:(EntityTattle_BrickBlock) {
	[Style tattle]
	[EnableCDownNext]This is a brick block.[BR]
	[Pause 5]You can break it by jumping or[BR]
	by Hammering it.[BR]
	[Wait][Next]
	You might find something inside[BR]
	when you break it.[Wait][End]
}

#message:1B:(EntityTattle_ItemBlock) {
	[Style tattle]
	[EnableCDownNext]It's a ? block.[BR]
	[Pause 5]If you smash it, you'll get[BR]
	something from inside it.[BR]
	[Wait][Next]
	A prize in every block! How[BR]
	exciting![Wait][End]
}

#message:1B:(EntityTattle_InertBlock) {
	[Style tattle]
	[EnableCDownNext]You already smashed this![BR]
	Nothing more will come out. [Wait][End]
}

#message:1B:(EntityTattle_PushBlock) {
	[Style tattle]
	[EnableCDownNext]It's a movable block.[BR]
	[Pause 10]You can push it around and even[BR]
	stand on it if you want to.[BR]
	[Wait][Next]
	My Goompa used to tell me[BR]
	stories about these blocks.[Wait][End]
}

#message:1B:(EntityTattle_BadgeBlock) {
	[Style tattle]
	[EnableCDownNext]It's a red ? block.[BR]
	[Pause 5]If you smash it, you'll get[BR]
	something from inside it.[BR]
	[Wait][Next]
	A prize in every block! How[BR]
	exciting![Wait][End]
}

#message:1B:(EntityTattle_Spring) {
	[Style tattle]
	[EnableCDownNext]It's a jump pad.[BR]
	[Pause 5]You can catch crazy air if you[BR]
	jump on it.[BR]
	[Wait][Next]
	If you use it right, you can[BR]
	reach new heights.[Wait][End]
}

#message:1B:(EntityTattle_Switch) {
	[Style tattle]
	[EnableCDownNext]It's a switch.[BR]
	[Pause 5]Something's bound to happen if[BR]
	you jump on it or smash it.[Wait][End]
}

#message:1B:(EntityTattle_BigSwitch_SpinJump) {
	[Style tattle]
	[EnableCDownNext]It's a big switch.[BR]
	[Pause 5]You may have to Spin Jump on[BR]
	this one to activate it.[Wait][End]
}

#message:1B:(EntityTattle_BigSwitch_TornadoJump) {
	[Style tattle]
	[EnableCDownNext]It's a big switch.[BR]
	[Pause 5]You may have to Tornado Jump on[BR]
	this one to activate it.[Wait][End]
}

#message:1B:(EntityTattle_FloorSwitch_SpinJump) {
	[Style tattle]
	[EnableCDownNext]It's a floor switch.[BR]
	[Pause 5]Something's bound to happen if [BR]
	you Spin Jump on it.[Wait][End]
}

#message:1B:(EntityTattle_FloorSwitch_TornadoJump) {
	[Style tattle]
	[EnableCDownNext]It's a floor switch.[BR]
	[Pause 5]Something's bound to happen if [BR]
	you Tornado Jump on it. [Wait][End]
}

#message:1B:(EntityTattle_Pipe) {
	[Style tattle]
	[EnableCDownNext]It's a pipe.[BR]
	[Pause 5]It'll take us somewhere.[BR]
	[Wait][Next]
	I've heard that they even lead[BR]
	to faraway towns sometimes.[Wait][End]
}

#message:1B:(EntityTattle_PadLock) {
	[Style tattle]
	[EnableCDownNext]It's a padlock.[BR]
	[Pause 5]It looks like we need to find a[BR]
	key to unlock it.[BR]
	[Wait][Next]
	I wonder what's on the other[BR]
	side of the door... Let's find[BR]
	the key and find out![Wait][End]
}

#message:1B:(EntityTattle_SignPost) {
	[Style tattle]
	[EnableCDownNext]If you see a ! over your head,[BR]
	check the area with [A].[Wait][End]
}

#message:1B:(EntityTattle_ArrowSign) {
	[Style tattle]
	[EnableCDownNext]It's a sign that points the way[BR]
	to Dry Dry Desert.[Wait][End]
}

#message:1B:(EntityTattle_BombableRock) {
	[Style tattle]
	[EnableCDownNext]This is certainly a large rock.[BR]
	[Pause 5]It looks cracked... I wonder if[BR]
	we could blow it up...[Wait][End]
}

#message:1B:(EntityTattle_Chest) {
	[Style tattle]
	[EnableCDownNext]It's a treasure chest.[BR]
	[Pause 5]Let's open it! I've gotta know[BR]
	what's inside there![Wait][End]
}

#message:1B:(EntityTattle_EmptyChest) {
	[Style tattle]
	[EnableCDownNext]It's a treasure chest.[BR]
	[Pause 5]It looks like it's empty.[Wait][End]
}

#message:1B:(EntityTattle_WoodenCrate_CantBreak) {
	[Style tattle]
	[EnableCDownNext]This box looks sort of fragile,[BR]
	but you can't break it with the[BR]
	power level you have now.[Wait][End]
}

#message:1B:(EntityTattle_WoodenCrate_SpinJump) {
	[Style tattle]
	[EnableCDownNext]It's a wooden box.[BR]
	[Pause 5]You can break it if you Spin[BR]
	Jump on top of it.[BR]
	[Wait][Next]
	There might be something inside.[BR]
	Let's break it open to find out![Wait][End]
}

#message:1B:(EntityTattle_WoodenCrate_TornadoJump) {
	[Style tattle]
	[EnableCDownNext]It's a wooden box.[BR]
	[Pause 5]You can break it if you Tornado[BR]
	Jump on top of it.[BR]
	[Wait][Next]
	There might be something inside.[BR]
	Let's break it open to find out![Wait][End]
}

#message:1B:(EntityTattle_BoardedFloor_CantBreak) {
	[Style tattle]
	[EnableCDownNext]This floor looks breakable, but[BR]
	you can't smash it with the[BR]
	power level you have now.[Wait][End]
}

#message:1B:(EntityTattle_BoardedFloor_SpinJump) {
	[Style tattle]
	[EnableCDownNext]You can break this floor if you[BR]
	Spin Jump on top of it.[Wait][End]
}

#message:1B:(EntityTattle_BoardedFloor_TornadoJump) {
	[Style tattle]
	[EnableCDownNext]You can break this floor if you[BR]
	Tornado Jump on top of it.[Wait][End]
}

#message:1B:(EntityTattle_JackInTheBox_SpinJump) {
	[Style tattle]
	[EnableCDownNext]It's a jack-in-the-box.[BR]
	[Pause 5]If you Spin Jump on it, you'll get[BR]
	launched into the air.[BR]
	[Wait][Next]
	You can also set it off by[BR]
	smashing it with your Hammer.[Wait][End]
}

#message:1B:(EntityTattle_JackInTheBox_TornadoJump) {
	[Style tattle]
	[EnableCDownNext]It's a jack-in-the-box.[BR]
	[Pause 5]If you Tornado Jump on it, you'll[BR]
	get launched into the air.[BR]
	[Wait][Next]
	You can also set it off by [BR]
	smashing it with your Hammer.[Wait][End]
}

#message:1B:(EntityTattle_BellbellPlant) {
	[Style tattle]
	[EnableCDownNext]It's a Bellbell Plant.[BR]
	[Pause 10]It grows only on Lavalava Island[BR]
	and swings like chimes when you[BR]
	touch it.[BR]
	[Wait][Next]
	It makes a cool, jingling sound.[BR]
	[Pause 10]Well... [Pause 5]that's all it does...[Wait][End]
}

#message:1B:(EntityTattle_TrumpetPlant) {
	[Style tattle]
	[EnableCDownNext]It's a Trumpet Plant.[BR]
	[Pause 10]It grows only on Lavalava Island[BR]
	and blows star dust from inside[BR]
	its flowers. [BR]
	[Wait][Next]
	Sometimes it'll blow out other[BR]
	things, too, so be ready.[Wait][End]
}

#message:1B:(EntityTattle_CymbalBush) {
	[Style tattle]
	[EnableCDownNext]It's a Cymbal Bush.[BR]
	[Pause 10]It grows only on Lavalava Island[BR]
	and has two stiff petals growing[BR]
	side by side.[BR]
	[Wait][Next]
	If you disturb it, the petals[BR]
	slam![BR]
	[Pause 10]Wanna try? I dare you![Wait][End]
}

#message:1B:(EntityTattle_Munchlesia) {
	[Style tattle]
	[EnableCDownNext]It's a Munchlesia.[BR]
	[Wait][Next]
	It grows only on Lavalava[BR]
	Island. If you jump on it, it'll[BR]
	wrap you up tight and take some[BR]
	of your health.[Wait][End]
}

#message:1B:(EntityTattle_SpinningFlower) {
	[Style tattle]
	[EnableCDownNext]It's a Spinning Flower.[BR]
	[Pause 10]It grows only on Lavalava Island[BR]
	and spins constantly.[BR]
	[Wait][Next]
	If you press the [Z] button while[BR]
	on the flower, you'll spin up into[BR]
	the air for a while.[Wait][End]
}

#message:1B:(EntityTattle_BulbBush) {
	[Style tattle]
	[EnableCDownNext]It's a Bulb Bush.[BR]
	[Pause 10]It grows only on Lavalava [BR]
	Island. If you touch it, it'll[BR]
	give out light for a little bit.[BR]
	[Wait][Next]
	It also wiggles a little and will[BR]
	sometimes surprise you.[BR]
	[Pause 10]I doubt it would surprise me.[Wait][End]
}

#message:1B:(EntityTattle_Interact) {
	[Style tattle]
	[EnableCDownNext]If you see a ! over your head,[BR]
	check the object or the area[BR]
	with [A].[Wait][End]
}
