#message:1F:(MenuTip_None) {
	None[End]
}

#message:1F:(MenuTip_StatsTab) {
	Check here to see what Mario's[BR]
	current status is.[End]
}

#message:1F:(MenuTip_BadgesTab) {
	Check Badges available and[BR]
	put on or remove Badges.[BR]
	[End]
}

#message:1F:(MenuTip_ItemsTab) {
	Look to see which items[BR]
	Mario is now carrying.[End]
}

#message:1F:(MenuTip_PartyTab) {
	Check your party and see[BR]
	each member's abilities.[End]
}

#message:1F:(MenuTip_SpiritsTab) {
	See which Star Spirits you've[BR]
	saved and check their powers.[End]
}

#message:1F:(MenuTip_MapTab) {
	Look at the map to see the[BR]
	places you've been to so far.[End]
}

#message:1F:(MenuTip_ControllingMario) {
	  [STAR] How to Control Mario [STAR][BR]
	Control Stick: Walk or Run[BR]
	[A]: Jump, Talk, or Check "!"[BR]
	[B]: Use Hammer[BR]
	[C-UP]: Display the Status Bar[BR]
	[C-LEFT]: Use Items[BR]
	[C-DOWN]: Use Party Members' Abilities[BR]
	[C-RIGHT]: Switch Party Members[BR]
	[Z]: Spin or Dash[BR]
	[START]: Display Pause Menu Screen[End]
}

#message:1F:(MenuTip_HeartPoints) {
	Shows status of Mario's health.[BR]
	When Mario's hurt, HP goes down.[End]
}

#message:1F:(MenuTip_FlowerPoints) {
	Shows points available for Mario's[BR]
	or party members' abilities.[End]
}

#message:1F:(MenuTip_BadgePoints) {
	Shows points available for[BR]
	wearing Badges.[End]
}

#message:1F:(MenuTip_Boots1) {
	Shows Boots that Mario is now[BR]
	wearing. Press [A] to jump.[End]
}

#message:1F:(MenuTip_Boots2) {
	Shows Boots that Mario is now[BR]
	wearing. Press [A] to jump.[BR]
	Press [A] again while in the air[BR]
	to do a Spin Jump.[End]
}

#message:1F:(MenuTip_Boots3) {
	Shows Boots that Mario is now[BR]
	wearing. Press [A] to jump.[BR]
	Press [A] again while in the air[BR]
	to do a Tornado Jump.[End]
}

#message:1F:(MenuTip_Hammer0) {
	You don't have a Hammer yet.[End]
}

#message:1F:(MenuTip_Hammer1) {
	Shows Hammer that Mario is now[BR]
	carrying. Press [B] to use it.  [BR]
	You can destroy Yellow Blocks[BR]
	with this Hammer.[End]
}

#message:1F:(MenuTip_Hammer2) {
	Shows Hammer that Mario is now[BR]
	carrying. Press [B] to use it.  [BR]
	You can destroy Stone Blocks[BR]
	with this Hammer.[End]
}

#message:1F:(MenuTip_Hammer3) {
	Shows Hammer that Mario is now[BR]
	carrying. Press [B] to use it.  [BR]
	You can destroy Metal Blocks[BR]
	with this Hammer.[End]
}

#message:1F:(MenuTip_StarPower) {
	Shows energy needed to use [BR]
	Star Spirits' powers.[End]
}

#message:1F:(MenuTip_StarPoints) {
	Earn points for enemies beaten.[BR]
	Go up 1 level every 100 points.[End]
}

#message:1F:(MenuTip_Coins) {
	Shows coins Mario has now.[BR]
	Buy items or Badges with them.[End]
}

#message:1F:(MenuTip_Secrets) {
	Wondering what this is for?[BR]
	Secret![BR]
	[End]
}

#message:1F:(MenuTip_StarPieces) {
	Shows the number of Star Pieces[BR]
	that Mario has collected.[End]
}

#message:1F:(MenuTip_Time) {
	Shows time used so far for your[BR]
	adventure in the Mushroom World.[End]
}

#message:1F:(MenuTip_ItemTab_KeyItems) {
	Lists important items Mario's[BR]
	found. Some can be given away.[BR]
	[End]
}

#message:1F:(MenuTip_ItemTab_Consumables) {
	Lists items Mario now has. Use[BR]
	them on the field or in battle.[End]
}

#message:1F:(MenuTip_BadgeTab_All) {
	Shows all Badges that Mario has[BR]
	collected.[BR]
	Select one with the Control Stick.[BR]
	Press [A] to wear or remove it.[BR]
	[End]
}

#message:1F:(MenuTip_BadgeTab_Equipped) {
	Shows Badges that Mario is[BR]
	currently wearing.[BR]
	Select one with the Control Stick.[BR]
	Press [A] to wear or remove it.[BR]
	[End]
}

#message:1F:(MenuTip_BadgeTutorial_01) {
	Putting On and Taking Off Badges[End]
}

#message:1F:(MenuTip_BadgeTutorial_02) {
	Here's how you put on [BR]
	or take off Badges.[End]
}

#message:1F:(MenuTip_BadgeTutorial_03) {
	Use the Control Stick to[BR]
	point at the Badge Tab.[BR]
	[End]
}

#message:1F:(MenuTip_BadgeTutorial_04) {
	Press the A Button to enter[BR]
	the Badge Screen.[End]
}

#message:1F:(MenuTip_BadgeTutorial_05) {
	Press the A Button again to[BR]
	go to the list of All Badges. [End]
}

#message:1F:(MenuTip_BadgeTutorial_06) {
	Wearing Badges often takes Badge[BR]
	Points. This one takes 1 BP.[End]
}

#message:1F:(MenuTip_BadgeTutorial_07) {
	The Badge is on now. Press the[BR]
	A Button again to take it off.[End]
}

#message:1F:(MenuTip_BadgeTutorial_08) {
	The Badge is now off, and[BR]
	1 BP is returned to your total.[End]
}

#message:1F:(MenuTip_BadgeTutorial_09) {
	Next[End]
}

#message:1F:(MenuTip_BadgeTutorial_10) {
	Select a Badge[End]
}

#message:1F:(MenuTip_BadgeTutorial_11) {
	Next[End]
}

#message:1F:(MenuTip_BadgeTutorial_12) {
	Next[End]
}

#message:1F:(MenuTip_BadgeTutorial_13) {
	Put on a Badge[End]
}

#message:1F:(MenuTip_BadgeTutorial_14) {
	Take off a Badge[End]
}

#message:1F:(MenuTip_BadgeTutorial_15) {
	Exit Menu[End]
}

#message:1F:(MenuTip_002B) {
	not used[End]
}

#message:1F:(MenuTip_002C) {
	not used[End]
}

#message:1F:(MenuTip_002D) {
	not used[End]
}

#message:1F:(MenuTip_002E) {
	not used[End]
}

#message:1F:(MenuTip_002F) {
	not used[End]
}

#message:1F:(MenuTip_0030) {
	not used[End]
}

#message:1F:(MenuTip_0031) {
	not used[End]
}

#message:1F:(MenuTip_0032) {
	Badge[End]
}

#message:1F:(MenuTip_0033) {
	Letters[End]
}

#message:1F:(MenuTip_0034) {
	/[End]
}

#message:1F:(MenuTip_BooTrial) {
	Trial[End]
}
