#message:23:(ItemShortDesc_FireFlower) {
	A flower that burns all enemies [BR]
	with fireballs. Attack Power: 3[End]
}

#message:23:(ItemShortDesc_SnowmanDoll) {
	A snowman that crushes all[BR]
	enemies. Attack Power: 4[End]
}

#message:23:(ItemShortDesc_ThunderRage) {
	Lightning that strikes all[BR]
	enemies.  Attack Power: 5[End]
}

#message:23:(ItemShortDesc_ThunderBolt) {
	Lightning that strikes 1 enemy.[BR]
	Attack Power: 5[End]
}

#message:23:(ItemShortDesc_ShootingStar) {
	Shooting stars that hit all[BR]
	enemies. Attack Power: 6[End]
}

#message:23:(ItemShortDesc_DustyHammer) {
	A dusty old Hammer. Throw it to[BR]
	damage 1 enemy.[End]
}

#message:23:(ItemShortDesc_Pebble) {
	A common pebble. Throw it to[BR]
	damage 1 enemy.[End]
}

#message:23:(ItemShortDesc_StoneCap) {
	Turns Mario to stone and makes[BR]
	him unable to move for a while. [End]
}

#message:23:(ItemShortDesc_VoltShroom) {
	Electrifies Mario briefly and[BR]
	damages enemies who touch him.  [End]
}

#message:23:(ItemShortDesc_Mushroom) {
	A regular Mushroom. Restores[BR]
	5 HP.[End]
}

#message:23:(ItemShortDesc_SuperShroom) {
	A truly super Mushroom.[BR]
	Restores 10 HP.[End]
}

#message:23:(ItemShortDesc_UltraShroom) {
	An ultra-fine Mushroom. Restores[BR]
	50 HP.[End]
}

#message:23:(ItemShortDesc_LifeShroom) {
	A life-giving Mushroom. Restores[BR]
	10 HP when Mario's HP hits 0.[End]
}

#message:23:(ItemShortDesc_DriedShroom) {
	A very dry Mushroom. Restores[BR]
	1 HP.[End]
}

#message:23:(ItemShortDesc_TastyTonic) {
	A very tasty tonic. Cures[BR]
	poisoning and shrinking.[End]
}

#message:23:(ItemShortDesc_SuperSoda) {
	A bubbly soda. Cures shrinking or[BR]
	poisoning and restores 5 FP.[End]
}

#message:23:(ItemShortDesc_BlueBerry) {
	A berry found in Flower Fields.[BR]
	Restores 5 FP.[End]
}

#message:23:(ItemShortDesc_RedBerry) {
	A berry found in Flower Fields.[BR]
	Restores 5 HP.[End]
}

#message:23:(ItemShortDesc_YellowBerry) {
	A berry found in Flower Fields.[BR]
	Restores 3 HP and 3 FP.[End]
}

#message:23:(ItemShortDesc_BubbleBerry) {
	A berry found in Flower Fields.[BR]
	Restores 5 HP.[End]
}

#message:23:(ItemShortDesc_Lime) {
	A fruit found in a desert oasis.[BR]
	Restores 3 FP.[End]
}

#message:23:(ItemShortDesc_Lemon) {
	A fruit found in a desert oasis.[BR]
	Restores 1 HP and 2 FP.[End]
}

#message:23:(ItemShortDesc_HoneySyrup) {
	Sweet honey syrup. Restores[BR]
	5 FP.[End]
}

#message:23:(ItemShortDesc_MapleSyrup) {
	Delicious maple syrup. Restores[BR]
	10 FP.[End]
}

#message:23:(ItemShortDesc_JamminJelly) {
	A highly nutritious snack.[BR]
	Restores 50 FP.[End]
}

#message:23:(ItemShortDesc_WhackasBump) {
	A Whacka Bump from Mt. Rugged.[BR]
	Restores 25 HP and 25 FP.[End]
}

#message:23:(ItemShortDesc_Apple) {
	A sweet, tangy apple. Restores[BR]
	5 HP.[End]
}

#message:23:(ItemShortDesc_Goomnut) {
	A special nut found only in [BR]
	Goomba Village. Restores 3 FP.[BR]
	[End]
}

#message:23:(ItemShortDesc_KoopaLeaf) {
	A leaf found in Koopa Village.[BR]
	Restores 3 FP.[End]
}

#message:23:(ItemShortDesc_DriedPasta) {
	Pasta from Dry Dry Outpost.[BR]
	Restores 3 HP and 2 FP.[End]
}

#message:23:(ItemShortDesc_DriedFruit) {
	A fruit found deep within Dry[BR]
	Dry Desert. Restores 15 HP.[End]
}

#message:23:(ItemShortDesc_StrangeLeaf) {
	A very rare leaf. Restores 5 FP.[BR]
	[End]
}

#message:23:(ItemShortDesc_CakeMix) {
	A mix used to bake tasty cakes.[BR]
	Restores 1 FP.[End]
}

#message:23:(ItemShortDesc_Egg) {
	An egg of unknown origin.[BR]
	Restores 5 HP.[End]
}

#message:23:(ItemShortDesc_Coconut) {
	A coconut from Lavalava Island.[BR]
	Throw it to damage 1 enemy.[End]
}

#message:23:(ItemShortDesc_Melon) {
	A succulent, ripe melon. Restores[BR]
	15 HP.[End]
}

#message:23:(ItemShortDesc_StinkyHerb) {
	This herb smells kind of bad...[BR]
	Restores 5 FP.[End]
}

#message:23:(ItemShortDesc_IcedPotato) {
	A tough potato found in the[BR]
	Shiver Region. Restores 5 HP.[End]
}

#message:23:(ItemShortDesc_SleepySheep) {
	If it works, makes all enemies[BR]
	sleep for a little while.[End]
}

#message:23:(ItemShortDesc_POWBlock) {
	Flips shell enemies and inflicts[BR]
	2 damage points on all enemies.[End]
}

#message:23:(ItemShortDesc_StopWatch) {
	If it works, paralyzes all[BR]
	enemies for a short time.[End]
}

#message:23:(ItemShortDesc_DizzyDial) {
	If it works, dazes and paralyzes[BR]
	all enemies briefly.[BR]
	[End]
}

#message:23:(ItemShortDesc_FrightJar) {
	Makes a scary spirit appear and[BR]
	chase some enemies away.[End]
}

#message:23:(ItemShortDesc_Mystery) {
	Who knows what it does... Take a[BR]
	chance to find out![End]
}

#message:23:(ItemShortDesc_RepelGel) {
	Makes Mario transparent and[BR]
	invulnerable for a short time. [End]
}

#message:23:(ItemShortDesc_SpicySoup) {
	A hot soup cooked by Tayce T.[BR]
	Restores 4 HP and 4 FP.[End]
}

#message:23:(ItemShortDesc_ApplePie) {
	An apple pie baked by Tayce T.[BR]
	Restores 5 HP and 15 FP.[End]
}

#message:23:(ItemShortDesc_HoneyShroom) {
	A dessert made by Tayce T.[BR]
	Restores 5 HP and 5 FP.[End]
}

#message:23:(ItemShortDesc_MapleShroom) {
	A dessert made by Tayce T.[BR]
	Restores 5 HP and 10 FP.[End]
}

#message:23:(ItemShortDesc_JellyShroom) {
	A dessert made by Tayce T.[BR]
	Restores 5 HP and 50 FP.[End]
}

#message:23:(ItemShortDesc_HoneySuper) {
	A dessert made by Tayce T.[BR]
	Restores 10 HP and 5 FP.[End]
}

#message:23:(ItemShortDesc_MapleSuper) {
	A dessert made by Tayce T.[BR]
	Restores 10 HP and 10 FP.[End]
}

#message:23:(ItemShortDesc_JellySuper) {
	A dessert made by Tayce T.[BR]
	Restores 10 HP and 50 FP.[BR]
	[End]
}

#message:23:(ItemShortDesc_HoneyUltra) {
	A dessert made by Tayce T.[BR]
	Restores 50 HP and 5 FP.[End]
}

#message:23:(ItemShortDesc_MapleUltra) {
	A dessert made by Tayce T.[BR]
	Restores 50 HP and 10 FP.[BR]
	[End]
}

#message:23:(ItemShortDesc_JellyUltra) {
	A dessert made by Tayce T.[BR]
	Restores 50 HP and 50 FP.[End]
}

#message:23:(ItemShortDesc_Koopasta) {
	Special pasta made by Tayce T.[BR]
	Restores 7 HP and 7 FP.[BR]
	[End]
}

#message:23:(ItemShortDesc_FriedShroom) {
	A snack made by Tayce T.[BR]
	Restores 6 HP and 2 FP.[End]
}

#message:23:(ItemShortDesc_HotShroom) {
	A snack made by Tayce T.[BR]
	Restores 15 HP and 5 FP.[End]
}

#message:23:(ItemShortDesc_ShroomSteak) {
	A dish cooked by Tayce T.[BR]
	Restores 30 HP and 10 FP.[BR]
	[End]
}

#message:23:(ItemShortDesc_ShroomCake) {
	A cake baked by Tayce T.[BR]
	Restores 10 HP and 10 FP.[End]
}

#message:23:(ItemShortDesc_SweetShroom) {
	A yummy cake baked by Tayce T.[BR]
	Restores 30 HP and 20 FP.[End]
}

#message:23:(ItemShortDesc_BlandMeal) {
	Boring food cooked by Tayce T.[BR]
	Restores 10 HP and 10 FP.[End]
}

#message:23:(ItemShortDesc_YummyMeal) {
	Tasty food cooked by Tayce T.[BR]
	Restores 20 HP and 20 FP.[End]
}

#message:23:(ItemShortDesc_DeluxeFeast) {
	Amazing food cooked by Tayce T.[BR]
	Restores 40 HP and 40 FP.[End]
}

#message:23:(ItemShortDesc_SpecialShake) {
	A smoothie made by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:23:(ItemShortDesc_HealthyJuice) {
	A juice blend made by Tayce T.[BR]
	Restores 40 FP.[End]
}

#message:23:(ItemShortDesc_BigCookie) {
	A huge cookie baked by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:23:(ItemShortDesc_Cake) {
	A tasty cake baked by Tayce T.[BR]
	Restores 15 FP.[End]
}

#message:23:(ItemShortDesc_Mistake) {
	This doesn't look very good![BR]
	Restores 1 HP and 1 FP.[End]
}

#message:23:(ItemShortDesc_KoopaTea) {
	Tea brewed by Tayce T.[BR]
	Restores 7 FP.[End]
}

#message:23:(ItemShortDesc_Spaghetti) {
	Spaghetti cooked by Tayce T.[BR]
	Restores 6 HP and 4 FP.[End]
}

#message:23:(ItemShortDesc_EggMissile) {
	An egg Bomb made by Tayce T.[BR]
	Throw it to damage 1 enemy.[End]
}

#message:23:(ItemShortDesc_FriedEgg) {
	Food cooked by Tayce T.[BR]
	Restores 10 HP.[End]
}

#message:23:(ItemShortDesc_HoneyCandy) {
	A sweet candy made by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:23:(ItemShortDesc_ElectroPop) {
	A tart lollipop made by Tayce T.[BR]
	Restores 15 FP.[End]
}

#message:23:(ItemShortDesc_FirePop) {
	A hot lollipop made by Tayce T.[BR]
	Restores 20 FP but uses 1 HP.[BR]
	[End]
}

#message:23:(ItemShortDesc_LimeCandy) {
	A tangy candy made by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:23:(ItemShortDesc_CocoPop) {
	A sweet candy made by Tayce T.[BR]
	Restores 3 HP and 15 FP.[End]
}

#message:23:(ItemShortDesc_LemonCandy) {
	A tangy candy made by Tayce T.[BR]
	Restores 5 HP and 15 FP.[End]
}

#message:23:(ItemShortDesc_JellyPop) {
	A big lollipop made by Tayce T.[BR]
	Restores 64 FP.[End]
}

#message:23:(ItemShortDesc_StrangeCake) {
	This electrifies Mario, turns him [BR]
	transparent, or makes him sleep.[End]
}

#message:23:(ItemShortDesc_KookyCookie) {
	Makes Mario electric, sleepy,[BR]
	or transparent. Restores 15 FP.[End]
}

#message:23:(ItemShortDesc_FrozenFries) {
	A side dish made by Tayce T.[BR]
	Restores 15 HP.[End]
}

#message:23:(ItemShortDesc_PotatoSalad) {
	A side dish made by Tayce T.[BR]
	Restores 10 HP.[End]
}

#message:23:(ItemShortDesc_NuttyCake) {
	A nut cake baked by Tayce T.[BR]
	Restores 10 FP.[End]
}

#message:23:(ItemShortDesc_BoiledEgg) {
	Food cooked by Tayce T.[BR]
	Restores 8 HP and 8 FP.[End]
}

#message:23:(ItemShortDesc_YoshiCookie) {
	A cookie baked by Tayce T.[BR]
	Restores 15 HP and 15 FP.[End]
}

#message:23:(ItemShortDesc_PowerJump) {
	Mario stomps on a single enemy[BR]
	using a lot of attack power.[End]
}

#message:23:(ItemShortDesc_MegaJump) {
	Mario stomps on a single enemy[BR]
	using tons of attack power.[End]
}

#message:23:(ItemShortDesc_JumpCharge) {
	When charged, Mario's Jump[BR]
	power goes up by 2.[End]
}

#message:23:(ItemShortDesc_SJumpChg) {
	When supercharged, Mario's Jump[BR]
	power goes up by 3.[End]
}

#message:23:(ItemShortDesc_SleepStomp) {
	If it works, the enemy Mario[BR]
	jumps on falls asleep for a bit.[End]
}

#message:23:(ItemShortDesc_DizzyStomp) {
	If it works, the enemy Mario[BR]
	jumps on becomes dizzy.[End]
}

#message:23:(ItemShortDesc_Multibounce) {
	Jumps on all enemies in a row if[BR]
	action command is timed right.[End]
}

#message:23:(ItemShortDesc_ShrinkStomp) {
	If it works, the enemy shrinks.[BR]
	Its attack power decreases.[End]
}

#message:23:(ItemShortDesc_DDownJump) {
	Disables an enemy's defense[BR]
	power and causes some damage.[End]
}

#message:23:(ItemShortDesc_PowerBounce) {
	Jumps on one enemy continuously [BR]
	until you miss an action command.[End]
}

#message:23:(ItemShortDesc_PowerSmash) {
	Hammers an enemy using lots of[BR]
	attack power.[End]
}

#message:23:(ItemShortDesc_MegaSmash) {
	Hammers an enemy with a huge[BR]
	amount of attack power.[End]
}

#message:23:(ItemShortDesc_SmashCharge) {
	When charged, Mario's Hammer[BR]
	power goes up by 2.[End]
}

#message:23:(ItemShortDesc_SSmashChg) {
	When supercharged, Mario's[BR]
	Hammer power goes up by 3.[End]
}

#message:23:(ItemShortDesc_HammerThrow) {
	Hits one enemy with the Hammer,[BR]
	no matter where the enemy is. [End]
}

#message:23:(ItemShortDesc_ShrinkSmash) {
	If it works, the enemy shrinks.[BR]
	Its attack power decreases.[End]
}

#message:23:(ItemShortDesc_SpinSmash) {
	If Mario hits an enemy, it[BR]
	smashes into the ones behind it.[End]
}

#message:23:(ItemShortDesc_DDownPound) {
	Disables an enemy's defense[BR]
	power and injures it.[End]
}

#message:23:(ItemShortDesc_QuakeHammer) {
	Slightly damages all enemies on[BR]
	the ground or ceiling.[End]
}

#message:23:(ItemShortDesc_PowerQuake) {
	Greatly damages all enemies on[BR]
	the ground or ceiling.[End]
}

#message:23:(ItemShortDesc_MegaQuake) {
	Severely damages all enemies on[BR]
	the ground or ceiling.[End]
}

#message:23:(ItemShortDesc_DoubleDip) {
	During battle, lets you use two[BR]
	items during one turn.[End]
}

#message:23:(ItemShortDesc_TripleDip) {
	During battle, lets you use three[BR]
	items during one turn.[End]
}

#message:23:(ItemShortDesc_GroupFocus) {
	Lets Mario's party members use[BR]
	the Focus command, as well.[End]
}

#message:23:(ItemShortDesc_QuickChange) {
	Changes your party member and[BR]
	attacks with it on that turn.[End]
}

#message:23:(ItemShortDesc_HPPlus) {
	Increases maximum HP by 5.[End]
}

#message:23:(ItemShortDesc_FPPlus) {
	Increases maximum FP by 5.[End]
}

#message:23:(ItemShortDesc_PowerPlus) {
	Increases Mario's Jump and[BR]
	Hammer attack powers by 1.[End]
}

#message:23:(ItemShortDesc_DefendPlus) {
	Decreases the damage that[BR]
	Mario takes by 1.[End]
}

#message:23:(ItemShortDesc_DamageDodge) {
	If you do the action command,[BR]
	decreases Mario's damage by 1.[End]
}

#message:23:(ItemShortDesc_PUpDDown) {
	Increases attack power by 1.[BR]
	Decreases defense power by 1.[End]
}

#message:23:(ItemShortDesc_PDownDUp) {
	Decreases attack power by 1.[BR]
	Increases defense power by 1.[End]
}

#message:23:(ItemShortDesc_HPDrain) {
	Decreases Mario's attack power [BR]
	by 1. Restores 1 HP per turn.[End]
}

#message:23:(ItemShortDesc_HappyHeart) {
	Restores HP automatically during[BR]
	battle at a slow rate.[End]
}

#message:23:(ItemShortDesc_HappyFlower) {
	Restores FP automatically during[BR]
	battle at a slow rate.[End]
}

#message:23:(ItemShortDesc_FlowerSaver) {
	During battle, saves 1 FP every[BR]
	time you attack. [End]
}

#message:23:(ItemShortDesc_HeartFinder) {
	After beating an enemy, makes[BR]
	more hearts appear than usual.[End]
}

#message:23:(ItemShortDesc_FlowerFinder) {
	After beating an enemy, makes [BR]
	more flowers appear than usual.[End]
}

#message:23:(ItemShortDesc_DeepFocus) {
	When using Focus, charges Star[BR]
	Energy more than usual.[End]
}

#message:23:(ItemShortDesc_SpikeShield) {
	Lets Mario jump on a spiked[BR]
	enemy without taking damage.[End]
}

#message:23:(ItemShortDesc_DodgeMaster) {
	Makes the action command work[BR]
	more frequently.[End]
}

#message:23:(ItemShortDesc_PrettyLucky) {
	Makes enemies fail to attack[BR]
	Mario every once in a while.[End]
}

#message:23:(ItemShortDesc_LuckyDay) {
	Sometimes makes enemies fail to[BR]
	attack Mario.[End]
}

#message:23:(ItemShortDesc_CloseCall) {
	When Mario's in Danger, enemies[BR]
	sometimes fail to attack.[End]
}

#message:23:(ItemShortDesc_PowerRush) {
	When Mario's in Danger, his[BR]
	attack power increases by 2.[End]
}

#message:23:(ItemShortDesc_LastStand) {
	When Mario's in Danger, he[BR]
	receives only half the damage.[End]
}

#message:23:(ItemShortDesc_MegaRush) {
	When Mario's in Peril, his attack[BR]
	power goes up by 4.  [End]
}

#message:23:(ItemShortDesc_FirstAttack) {
	Lets Mario destroy a weaker[BR]
	enemy with a First Strike.  [End]
}

#message:23:(ItemShortDesc_BumpAttack) {
	Lets Mario destroy a weaker [BR]
	enemy in the field by hitting it.[End]
}

#message:23:(ItemShortDesc_SpinAttack) {
	Lets Mario destroy a weaker[BR]
	enemy with a spinning move.[End]
}

#message:23:(ItemShortDesc_DizzyAttack) {
	Delivers a blow that makes an[BR]
	enemy dizzy and unable to move. [End]
}

#message:23:(ItemShortDesc_SpeedySpin) {
	Increases the distance Mario[BR]
	can Spin Dash.[End]
}

#message:23:(ItemShortDesc_FeelingFine) {
	Protects Mario from poisoning[BR]
	and dizziness during attack.[End]
}

#message:23:(ItemShortDesc_AttackFXA) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:23:(ItemShortDesc_AttackFXD) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:23:(ItemShortDesc_AttackFXB) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:23:(ItemShortDesc_AttackFXE) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:23:(ItemShortDesc_AttackFXC) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:23:(ItemShortDesc_AttackFXF) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:23:(ItemShortDesc_AllorNothing) {
	If the action command works,[BR]
	attack power +1. If not, it's 0.[End]
}

#message:23:(ItemShortDesc_SlowGo) {
	Makes Mario unable to run. His[BR]
	pace becomes very slow.[End]
}

#message:23:(ItemShortDesc_IcePower) {
	Increases attack power against[BR]
	fire enemies by 2.  [End]
}

#message:23:(ItemShortDesc_PayOff) {
	The more damage Mario takes,[BR]
	the more coins he receives.[End]
}

#message:23:(ItemShortDesc_FireShield) {
	Makes the damage Mario takes[BR]
	from fire attacks go down by 1.[End]
}

#message:23:(ItemShortDesc_ChillOut) {
	Keeps you from being hit by a[BR]
	First Strike.[End]
}

#message:23:(ItemShortDesc_ZapTap) {
	In battle, makes most enemies[BR]
	who touch Mario take damage.  [End]
}

#message:23:(ItemShortDesc_MoneyMoney) {
	After a battle, lets Mario get[BR]
	twice as many coins as usual.[End]
}

#message:23:(ItemShortDesc_RightOn) {
	Makes the action command work[BR]
	every time Mario attacks.[End]
}

#message:23:(ItemShortDesc_RunawayPay) {
	Lets Mario earn Star Points[BR]
	even if he escapes from battle. [End]
}

#message:23:(ItemShortDesc_Refund) {
	Refunds some coins if you use an[BR]
	item in battle.[End]
}

#message:23:(ItemShortDesc_ISpy) {
	A sound and icon alert you to a[BR]
	nearby hidden panel.[End]
}

#message:23:(ItemShortDesc_Peekaboo) {
	Makes it possible to see your[BR]
	enemy's HP.[End]
}

#message:23:(ItemShortDesc_Boots) {
	Jump and stomp on an enemy.[End]
}

#message:23:(ItemShortDesc_SuperBoots) {
	Jump and stomp on an enemy.[End]
}

#message:23:(ItemShortDesc_UltraBoots) {
	Jump and stomp on an enemy.[End]
}

#message:23:(ItemShortDesc_Hammer) {
	Smack enemies with the Hammer.[End]
}

#message:23:(ItemShortDesc_SuperHammer) {
	Smack enemies with the Hammer.[End]
}

#message:23:(ItemShortDesc_UltraHammer) {
	Smack enemies with the Hammer.[End]
}

#message:23:(ItemShortDesc_LuckyStar) {
	A star-shaped pendant. Lets[BR]
	you use the action command.[End]
}

#message:23:(ItemShortDesc_KoopaFortressKey) {
	Opens a locked door in the[BR]
	Koopa Bros. Fortress.[End]
}

#message:23:(ItemShortDesc_RuinsKey) {
	Opens a locked door in Dry Dry[BR]
	Ruins.[End]
}

#message:23:(ItemShortDesc_TubbaCastleKey) {
	Opens a locked door in Tubba[BR]
	Blubba's Castle.[End]
}

#message:23:(ItemShortDesc_CrystalPalaceKey) {
	Opens a locked door in the[BR]
	Crystal Palace.[End]
}

#message:23:(ItemShortDesc_BowserCastleKey) {
	Opens a locked door in Bowser's[BR]
	Castle.[End]
}

#message:23:(ItemShortDesc_PeachKey) {
	Opens a locked door in Princess[BR]
	Peach's Castle.[End]
}

#message:23:(ItemShortDesc_OddKey) {
	Opens a locked door in the Odd[BR]
	House.[End]
}

#message:23:(ItemShortDesc_Dolly) {
	An adorable doll that looks [BR]
	exactly like Princess Peach.[End]
}

#message:23:(ItemShortDesc_KooperShell) {
	Kooper's blue shell.[End]
}

#message:23:(ItemShortDesc_PulseStone) {
	The closer you get to Dry Dry [BR]
	Ruins, the faster it flashes.[End]
}

#message:23:(ItemShortDesc_Artifact) {
	A strange artifact found in Dry[BR]
	Dry Ruins.[End]
}

#message:23:(ItemShortDesc_GoldenJar) {
	A sparkling gold pot. Moustafa[BR]
	was looking for this.[End]
}

#message:23:(ItemShortDesc_LunarStone) {
	A crescent-shaped stone found[BR]
	in Dry Dry Ruins.[End]
}

#message:23:(ItemShortDesc_PyramidStone) {
	A triangle-shaped stone found[BR]
	in Dry Dry Ruins.[End]
}

#message:23:(ItemShortDesc_DiamondStone) {
	A star-shaped stone found in[BR]
	Dry Dry Ruins.[End]
}

#message:23:(ItemShortDesc_BooRecord) {
	A record of upbeat music. How[BR]
	can you play this?[End]
}

#message:23:(ItemShortDesc_BooWeight) {
	A very heavy weight. How can[BR]
	you use this?[End]
}

#message:23:(ItemShortDesc_BooPortrait) {
	A portrait of an old male Boo.[End]
}

#message:23:(ItemShortDesc_MysticalKey) {
	A key found in Tubba Blubba's[BR]
	room.[End]
}

#message:23:(ItemShortDesc_StoreroomKey) {
	A key to the storeroom in a[BR]
	Toad Town shop.[End]
}

#message:23:(ItemShortDesc_ToyTrain) {
	A very well designed toy train.[BR]
	Could this be more than a toy?[End]
}

#message:23:(ItemShortDesc_FryingPan) {
	Tayce T.'s frying pan. Return it[BR]
	to her.[End]
}

#message:23:(ItemShortDesc_Dictionary) {
	The scholar Russ T.'s dictionary.[BR]
	Return it to him.[End]
}

#message:23:(ItemShortDesc_MysteryNote) {
	You can't read this. Show it to [BR]
	someone who is very smart.[End]
}

#message:23:(ItemShortDesc_Mailbag) {
	A bag full of letters. Return it[BR]
	to the post office.[End]
}

#message:23:(ItemShortDesc_MagicalSeed1) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:23:(ItemShortDesc_MagicalSeed2) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:23:(ItemShortDesc_MagicalSeed3) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:23:(ItemShortDesc_MagicalSeed4) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:23:(ItemShortDesc_CrystalBerry) {
	A glittering berry made of[BR]
	crystal.[End]
}

#message:23:(ItemShortDesc_WaterStone) {
	A magical stone. Water springs[BR]
	from it.[End]
}

#message:23:(ItemShortDesc_MagicalBean) {
	A bean. It's twitching as if to[BR]
	say, "Plant me this instant!"[End]
}

#message:23:(ItemShortDesc_FertileSoil) {
	Absolutely pollutant free. This[BR]
	smells like very good soil.[End]
}

#message:23:(ItemShortDesc_MiracleWater) {
	Very cold water. It glitters in[BR]
	the sun.[End]
}

#message:23:(ItemShortDesc_CrystalBall) {
	A gorgeous crystal ball. Give it[BR]
	to Merluvlee.[End]
}

#message:23:(ItemShortDesc_Calculator) {
	The calculator from Rowf's[BR]
	Badge Shop. Return it to him.[End]
}

#message:23:(ItemShortDesc_Cookbook) {
	A book Gourmet Guy dropped.[BR]
	Show it to a good cook.[End]
}

#message:23:(ItemShortDesc_JadeRaven) {
	The jade statue of a Raven that[BR]
	Yoshi's Village Leader gave you.[End]
}

#message:23:(ItemShortDesc_VolcanoVase) {
	A treasure found inside Mt.[BR]
	Lavalava.[End]
}

#message:23:(ItemShortDesc_WarehouseKey) {
	A key to the warehouse in Shiver[BR]
	City.[End]
}

#message:23:(ItemShortDesc_SnowmanBucket) {
	An ordinary bucket that the[BR]
	Shiver City Mayor gave you.[End]
}

#message:23:(ItemShortDesc_SnowmanScarf) {
	An ordinary scarf from Merle in[BR]
	Starborn Valley.[End]
}

#message:23:(ItemShortDesc_StarStone) {
	A stone. It opens the path to[BR]
	the Crystal Palace.[End]
}

#message:23:(ItemShortDesc_RedKey) {
	A big red key.[End]
}

#message:23:(ItemShortDesc_BlueKey) {
	A big blue key.[End]
}

#message:23:(ItemShortDesc_SneakyParasol) {
	A fabulous parasol given to quiz[BR]
	show participants.[End]
}

#message:23:(ItemShortDesc_PrisonKey) {
	A key to the prison in Bowser's[BR]
	Castle.[End]
}

#message:23:(ItemShortDesc_Lyrics) {
	Show it to a composer somewhere[BR]
	in the world.[End]
}

#message:23:(ItemShortDesc_Melody) {
	Give it to the Master Poet in[BR]
	Toad Town.[End]
}

#message:23:(ItemShortDesc_BakingSugar) {
	Snow white sugar.[End]
}

#message:23:(ItemShortDesc_BakingSalt) {
	As salty as salt gets.[End]
}

#message:23:(ItemShortDesc_BakingEgg) {
	Newly laid eggs.[End]
}

#message:23:(ItemShortDesc_BakingCream) {
	Very rich and fresh cream.[End]
}

#message:23:(ItemShortDesc_BakingStrawberry) {
	Bright red strawberries. They[BR]
	look fresh and juicy.[End]
}

#message:23:(ItemShortDesc_BakingButter) {
	The best butter available. It[BR]
	looks freshly churned.[End]
}

#message:23:(ItemShortDesc_BakingCleanser) {
	Detergent to wash utensils.[End]
}

#message:23:(ItemShortDesc_BakingWater) {
	Ordinary water.[End]
}

#message:23:(ItemShortDesc_BakingFlour) {
	The best flour available to bake[BR]
	the finest royal cakes.[End]
}

#message:23:(ItemShortDesc_BakingMilk) {
	Milk, fresh from the cow![End]
}

#message:23:(ItemShortDesc_FirstDegreeCard) {
	Proof of Mario's strength, won[BR]
	by defeating Chan at the Dojo.[End]
}

#message:23:(ItemShortDesc_SecondDegreeCard) {
	Proof of Mario's strength, won[BR]
	by defeating Lee at the Dojo.[End]
}

#message:23:(ItemShortDesc_ThirdDegreeCard) {
	Proof of Mario's strength, for[BR]
	besting The Master at the Dojo.[End]
}

#message:23:(ItemShortDesc_FourthDegreeCard) {
	Proof of Mario's strength, for[BR]
	besting The Master at the Dojo.[End]
}

#message:23:(ItemShortDesc_Diploma) {
	Proof of Mario's strength. Now[BR]
	Mario is the strongest.[End]
}

#message:23:(ItemShortDesc_UltraStone) {
	A stone. Use it to ultra-rank[BR]
	one of your party members.[End]
}

#message:23:(ItemShortDesc_SilverCredit) {
	A card Koopa Koot gave you. Use[BR]
	it to play in the Playroom.[End]
}

#message:23:(ItemShortDesc_GoldCredit) {
	A card Koopa Koot gave you. Use[BR]
	it to play in the Playroom.[End]
}

#message:23:(ItemShortDesc_Letter25) {
	A letter to Kolorado.[End]
}

#message:23:(ItemShortDesc_Letter01) {
	A letter to Merlon in Toad Town.[BR]
	[End]
}

#message:23:(ItemShortDesc_Letter02) {
	A letter to Goompa in Goomba[BR]
	Village.[End]
}

#message:23:(ItemShortDesc_Letter03) {
	A letter to Mort T. in Koopa[BR]
	Village.[End]
}

#message:23:(ItemShortDesc_Letter04) {
	A letter to Russ T. in Toad[BR]
	Town.[End]
}

#message:23:(ItemShortDesc_Letter05) {
	A letter to Mayor Penguin in[BR]
	Shiver City.[End]
}

#message:23:(ItemShortDesc_Letter06) {
	A letter to Merlow at Shooting[BR]
	Star Summit.[End]
}

#message:23:(ItemShortDesc_Letter07) {
	A letter to Fice T. near the[BR]
	entrance to Forever Forest.[End]
}

#message:23:(ItemShortDesc_Letter08) {
	A letter to the traveling[BR]
	Nomadimouse on the road.[End]
}

#message:23:(ItemShortDesc_Letter09) {
	A letter to Minh T. in Toad[BR]
	Town.[End]
}

#message:23:(ItemShortDesc_Letter10) {
	A letter to Goompapa in Goomba[BR]
	Village.[End]
}

#message:23:(ItemShortDesc_Letter11) {
	A letter to Igor in Boo's Shop.[End]
}

#message:23:(ItemShortDesc_Letter12) {
	A letter to Franky in Boo's[BR]
	Mansion.[End]
}

#message:23:(ItemShortDesc_Letter13) {
	A letter to Muss T. near[BR]
	Princess Peach's Castle.[End]
}

#message:23:(ItemShortDesc_Letter14) {
	A letter to Koover in Koopa[BR]
	Village.[End]
}

#message:23:(ItemShortDesc_Letter15) {
	A letter to Fishmael at the Toad[BR]
	Town Port.[End]
}

#message:23:(ItemShortDesc_Letter16) {
	A letter to Koover in Koopa[BR]
	Village.[End]
}

#message:23:(ItemShortDesc_Letter17) {
	A letter to Mr. E. in Dry Dry[BR]
	Outpost.[End]
}

#message:23:(ItemShortDesc_Letter18) {
	A letter to Miss T. near the[BR]
	Toad Town Dojo.[End]
}

#message:23:(ItemShortDesc_Letter19) {
	A letter to Little Mouser in the[BR]
	Dry Dry Outpost shop.[End]
}

#message:23:(ItemShortDesc_Letter20) {
	A letter to Dane T. near Toad[BR]
	Town Station.[End]
}

#message:23:(ItemShortDesc_Letter21) {
	A letter to the Red Yoshi Kid in[BR]
	Yoshi's Village.[End]
}

#message:23:(ItemShortDesc_Letter22) {
	A letter to Dane T. near Toad[BR]
	Town Station.[End]
}

#message:23:(ItemShortDesc_Letter23) {
	A letter to Frost T. in Starborn[BR]
	Valley.[End]
}

#message:23:(ItemShortDesc_Letter24) {
	A letter to Goompapa in Goomba[BR]
	Village.[End]
}

#message:23:(ItemShortDesc_KootKoopaLegends) {
	Kolorado's strange book. Deliver[BR]
	this to Koopa Koot.[End]
}

#message:23:(ItemShortDesc_KootTheTape) {
	A tape returned by Goompa.[BR]
	Deliver it to Koopa Koot.[End]
}

#message:23:(ItemShortDesc_KootLuigiAutograph) {
	Luigi's autograph. Koopa Koot[BR]
	wants this.[End]
}

#message:23:(ItemShortDesc_KootEmptyWallet) {
	A wallet Koopa Koot dropped.[BR]
	Return it to him.[End]
}

#message:23:(ItemShortDesc_KootMerluvleeAutograph) {
	An autograph from Merluvlee.[BR]
	Koopa Koot wants this.[End]
}

#message:23:(ItemShortDesc_KootOldPhoto) {
	Is this a picture of a young[BR]
	Koopa Koot? He wants this.[End]
}

#message:23:(ItemShortDesc_KootGlasses) {
	Glasses Koopa Koot dropped.[BR]
	Deliver them to him.[End]
}

#message:23:(ItemShortDesc_KootPackage) {
	A package received from a Boo.[BR]
	Deliver it to Koopa Koot.[End]
}

#message:23:(ItemShortDesc_KootRedJar) {
	A jar at Little Mouser's Shop.[BR]
	A collector's item, perhaps?[End]
}
