#message:24:(ItemShopDesc_FireFlower) {
	A flower that burns all enemies [BR]
	with fireballs. Attack Power: 3[End]
}

#message:24:(ItemShopDesc_SnowmanDoll) {
	A snowman that crushes all[BR]
	enemies. Attack Power: 4[End]
}

#message:24:(ItemShopDesc_ThunderRage) {
	Lightning that strikes all[BR]
	enemies. Attack Power: 5[End]
}

#message:24:(ItemShopDesc_ThunderBolt) {
	Lightning that strikes an enemy.[BR]
	Attack Power: 5[End]
}

#message:24:(ItemShopDesc_ShootingStar) {
	Shooting stars that hit all[BR]
	enemies. Attack Power: 6[End]
}

#message:24:(ItemShopDesc_DustyHammer) {
	A dusty old Hammer. Throw it to[BR]
	damage an enemy.[End]
}

#message:24:(ItemShopDesc_Pebble) {
	A common pebble. Throw it to[BR]
	damage an enemy.[End]
}

#message:24:(ItemShopDesc_StoneCap) {
	Turns Mario to stone and makes[BR]
	him unable to move for a while. [End]
}

#message:24:(ItemShopDesc_VoltShroom) {
	Electrifies Mario briefly and[BR]
	damages enemies who touch him.[End]
}

#message:24:(ItemShopDesc_Mushroom) {
	A regular Mushroom. Restores[BR]
	5 HP.[End]
}

#message:24:(ItemShopDesc_SuperShroom) {
	A truly super Mushroom.[BR]
	Restores 10 HP.[End]
}

#message:24:(ItemShopDesc_UltraShroom) {
	An ultra-fine Mushroom. Restores[BR]
	50 HP.[End]
}

#message:24:(ItemShopDesc_LifeShroom) {
	A life-giving Mushroom. Restores[BR]
	10 HP when Mario's HP hits 0.[End]
}

#message:24:(ItemShopDesc_DriedShroom) {
	A very dry Mushroom. Restores[BR]
	1 HP.[End]
}

#message:24:(ItemShopDesc_TastyTonic) {
	A very tasty tonic. Cures[BR]
	poisoning and shrinking.[End]
}

#message:24:(ItemShopDesc_SuperSoda) {
	A bubbly soda. Cures shrinking or[BR]
	poisoning and restores 5 FP.[End]
}

#message:24:(ItemShopDesc_BlueBerry) {
	no data[End]
}

#message:24:(ItemShopDesc_RedBerry) {
	no data[End]
}

#message:24:(ItemShopDesc_YellowBerry) {
	no data[End]
}

#message:24:(ItemShopDesc_BubbleBerry) {
	no data[End]
}

#message:24:(ItemShopDesc_Lime) {
	no data[End]
}

#message:24:(ItemShopDesc_Lemon) {
	no data[End]
}

#message:24:(ItemShopDesc_HoneySyrup) {
	Sweet honey syrup. Restores[BR]
	5 FP.[End]
}

#message:24:(ItemShopDesc_MapleSyrup) {
	Delicious maple syrup. Restores[BR]
	10 FP.[End]
}

#message:24:(ItemShopDesc_JamminJelly) {
	A highly nutritious snack.[BR]
	Restores 50 FP.[End]
}

#message:24:(ItemShopDesc_WhackasBump) {
	no data[End]
}

#message:24:(ItemShopDesc_Apple) {
	no data[End]
}

#message:24:(ItemShopDesc_Goomnut) {
	no data[BR]
	[End]
}

#message:24:(ItemShopDesc_KoopaLeaf) {
	no data[End]
}

#message:24:(ItemShopDesc_DriedPasta) {
	Pasta from Dry Dry Outpost.[BR]
	Restores 3 HP and 2 FP.[End]
}

#message:24:(ItemShopDesc_DriedFruit) {
	no data[End]
}

#message:24:(ItemShopDesc_StrangeLeaf) {
	no data[End]
}

#message:24:(ItemShopDesc_CakeMix) {
	no data[BR]
	[End]
}

#message:24:(ItemShopDesc_Egg) {
	no data[End]
}

#message:24:(ItemShopDesc_Coconut) {
	no data[End]
}

#message:24:(ItemShopDesc_Melon) {
	no data[End]
}

#message:24:(ItemShopDesc_StinkyHerb) {
	no data[End]
}

#message:24:(ItemShopDesc_IcedPotato) {
	no data[End]
}

#message:24:(ItemShopDesc_SleepySheep) {
	If it works, makes all enemies [BR]
	sleep for a little while.[End]
}

#message:24:(ItemShopDesc_POWBlock) {
	Flips shell enemies and inflicts[BR]
	2 damage points on all enemies.[End]
}

#message:24:(ItemShopDesc_StopWatch) {
	If it works, paralyzes all[BR]
	enemies for a short time.[End]
}

#message:24:(ItemShopDesc_DizzyDial) {
	If it works, dazes and paralyzes[BR]
	all enemies briefly.[BR]
	[End]
}

#message:24:(ItemShopDesc_FrightJar) {
	Makes a scary spirit appear and[BR]
	chase some enemies away.[End]
}

#message:24:(ItemShopDesc_Mystery) {
	Who knows what it does... Take a[BR]
	chance to find out![End]
}

#message:24:(ItemShopDesc_RepelGel) {
	Makes Mario transparent and[BR]
	invulnerable for a short time. [End]
}

#message:24:(ItemShopDesc_SpicySoup) {
	nothing[End]
}

#message:24:(ItemShopDesc_ApplePie) {
	nothing[End]
}

#message:24:(ItemShopDesc_HoneyShroom) {
	nothing[End]
}

#message:24:(ItemShopDesc_MapleShroom) {
	nothing[End]
}

#message:24:(ItemShopDesc_JellyShroom) {
	nothing[End]
}

#message:24:(ItemShopDesc_HoneySuper) {
	nothing[End]
}

#message:24:(ItemShopDesc_MapleSuper) {
	nothing[End]
}

#message:24:(ItemShopDesc_JellySuper) {
	nothing[End]
}

#message:24:(ItemShopDesc_HoneyUltra) {
	nothing[End]
}

#message:24:(ItemShopDesc_MapleUltra) {
	nothing[End]
}

#message:24:(ItemShopDesc_JellyUltra) {
	nothing[End]
}

#message:24:(ItemShopDesc_Koopasta) {
	nothing[End]
}

#message:24:(ItemShopDesc_FriedShroom) {
	nothing[End]
}

#message:24:(ItemShopDesc_HotShroom) {
	nothing[End]
}

#message:24:(ItemShopDesc_ShroomSteak) {
	nothing[End]
}

#message:24:(ItemShopDesc_ShroomCake) {
	nothing[End]
}

#message:24:(ItemShopDesc_SweetShroom) {
	nothing[End]
}

#message:24:(ItemShopDesc_BlandMeal) {
	nothing[End]
}

#message:24:(ItemShopDesc_YummyMeal) {
	nothing[End]
}

#message:24:(ItemShopDesc_DeluxeFeast) {
	nothing[End]
}

#message:24:(ItemShopDesc_SpecialShake) {
	nothing[End]
}

#message:24:(ItemShopDesc_HealthyJuice) {
	nothing[End]
}

#message:24:(ItemShopDesc_BigCookie) {
	nothing[End]
}

#message:24:(ItemShopDesc_Cake) {
	nothing[End]
}

#message:24:(ItemShopDesc_Mistake) {
	nothing[End]
}

#message:24:(ItemShopDesc_KoopaTea) {
	nothing[End]
}

#message:24:(ItemShopDesc_Spaghetti) {
	nothing[End]
}

#message:24:(ItemShopDesc_EggMissile) {
	nothing[End]
}

#message:24:(ItemShopDesc_FriedEgg) {
	nothing[End]
}

#message:24:(ItemShopDesc_HoneyCandy) {
	nothing[End]
}

#message:24:(ItemShopDesc_ElectroPop) {
	nothing[End]
}

#message:24:(ItemShopDesc_FirePop) {
	nothing[End]
}

#message:24:(ItemShopDesc_LimeCandy) {
	nothing[End]
}

#message:24:(ItemShopDesc_CocoPop) {
	nothing[End]
}

#message:24:(ItemShopDesc_LemonCandy) {
	nothing[End]
}

#message:24:(ItemShopDesc_JellyPop) {
	nothing[End]
}

#message:24:(ItemShopDesc_StrangeCake) {
	nothing[End]
}

#message:24:(ItemShopDesc_KookyCookie) {
	nothing[End]
}

#message:24:(ItemShopDesc_FrozenFries) {
	nothing[End]
}

#message:24:(ItemShopDesc_PotatoSalad) {
	nothing[End]
}

#message:24:(ItemShopDesc_NuttyCake) {
	nothing[End]
}

#message:24:(ItemShopDesc_BoiledEgg) {
	nothing[End]
}

#message:24:(ItemShopDesc_YoshiCookie) {
	nothing[End]
}

#message:24:(ItemShopDesc_PowerJump) {
	Mario stomps on a single enemy[BR]
	using a lot of attack power.[End]
}

#message:24:(ItemShopDesc_MegaJump) {
	Mario stomps on a single enemy[BR]
	using tons of attack power.[End]
}

#message:24:(ItemShopDesc_JumpCharge) {
	When charged, Mario's Jump[BR]
	power goes up by 2.[End]
}

#message:24:(ItemShopDesc_SJumpChg) {
	When supercharged, Mario's Jump[BR]
	power goes up by 3.[End]
}

#message:24:(ItemShopDesc_SleepStomp) {
	If it works, the enemy Mario[BR]
	jumps on falls asleep for a bit.[End]
}

#message:24:(ItemShopDesc_DizzyStomp) {
	If it works, the enemy Mario [BR]
	jumps on becomes dizzy.[End]
}

#message:24:(ItemShopDesc_Multibounce) {
	Jumps on all enemies in a row if[BR]
	action command is timed right.[End]
}

#message:24:(ItemShopDesc_ShrinkStomp) {
	If it works, the enemy shrinks.[BR]
	Its attack power decreases.[End]
}

#message:24:(ItemShopDesc_DDownJump) {
	Disables an enemy's defense[BR]
	power and causes some damage.[End]
}

#message:24:(ItemShopDesc_PowerBounce) {
	Jumps on one enemy continuously [BR]
	until you miss an action command.[End]
}

#message:24:(ItemShopDesc_PowerSmash) {
	Hammers an enemy using lots of[BR]
	attack power.[End]
}

#message:24:(ItemShopDesc_MegaSmash) {
	Hammers an enemy with a huge[BR]
	amount of attack power.[End]
}

#message:24:(ItemShopDesc_SmashCharge) {
	When charged, Mario's Hammer[BR]
	power goes up by 2.[End]
}

#message:24:(ItemShopDesc_SSmashChg) {
	When supercharged, Mario's [BR]
	Hammer power goes up by 3.[End]
}

#message:24:(ItemShopDesc_HammerThrow) {
	Hits one enemy with the Hammer,[BR]
	no matter where the enemy is. [End]
}

#message:24:(ItemShopDesc_ShrinkSmash) {
	If it works, the enemy shrinks.[BR]
	Its attack power decreases.[End]
}

#message:24:(ItemShopDesc_SpinSmash) {
	If Mario hits an enemy, it[BR]
	smashes into the ones behind it.[End]
}

#message:24:(ItemShopDesc_DDownPound) {
	Disables an enemy's defense[BR]
	power and injures it.[End]
}

#message:24:(ItemShopDesc_QuakeHammer) {
	Slightly damages all enemies [BR]
	on the ground or ceiling.[End]
}

#message:24:(ItemShopDesc_PowerQuake) {
	Greatly damages all enemies [BR]
	on the ground or ceiling.[End]
}

#message:24:(ItemShopDesc_MegaQuake) {
	Severely damages all enemies[BR]
	on the ground or ceiling.[End]
}

#message:24:(ItemShopDesc_DoubleDip) {
	During battle, lets you use two[BR]
	items during one turn.[End]
}

#message:24:(ItemShopDesc_TripleDip) {
	During battle, lets you use three[BR]
	items during one turn.[End]
}

#message:24:(ItemShopDesc_GroupFocus) {
	Lets Mario's party members use[BR]
	the Focus command as well.[End]
}

#message:24:(ItemShopDesc_QuickChange) {
	Changes your party member and[BR]
	attacks with it on that turn.[End]
}

#message:24:(ItemShopDesc_HPPlus) {
	Increases maximum HP by 5.[End]
}

#message:24:(ItemShopDesc_FPPlus) {
	Increases maximum FP by 5.[End]
}

#message:24:(ItemShopDesc_PowerPlus) {
	Increases Mario's Jump and[BR]
	Hammer attack powers by 1.[End]
}

#message:24:(ItemShopDesc_DefendPlus) {
	Decreases the damage that[BR]
	Mario takes by 1.[End]
}

#message:24:(ItemShopDesc_DamageDodge) {
	If you do the action command,[BR]
	decreases Mario's damage by 1.[End]
}

#message:24:(ItemShopDesc_PUpDDown) {
	Increases attack power by 1.[BR]
	Decreases defense power by 1.[End]
}

#message:24:(ItemShopDesc_PDownDUp) {
	Decreases attack power by 1.[BR]
	Increases defense power by 1.[End]
}

#message:24:(ItemShopDesc_HPDrain) {
	Decreases Mario's attack power [BR]
	by 1. Restores 1 HP per turn.[End]
}

#message:24:(ItemShopDesc_HappyHeart) {
	Restores HP automatically during[BR]
	battle at a slow rate.[End]
}

#message:24:(ItemShopDesc_HappyFlower) {
	Restores FP automatically during[BR]
	battle at a slow rate.[End]
}

#message:24:(ItemShopDesc_FlowerSaver) {
	During battle, saves 1 FP every[BR]
	time you attack. [End]
}

#message:24:(ItemShopDesc_HeartFinder) {
	After beating an enemy, makes[BR]
	more hearts appear than usual.[End]
}

#message:24:(ItemShopDesc_FlowerFinder) {
	After beating an enemy, makes [BR]
	more flowers appear than usual.[End]
}

#message:24:(ItemShopDesc_DeepFocus) {
	When using Focus, charges Star[BR]
	Energy more than usual.[End]
}

#message:24:(ItemShopDesc_SpikeShield) {
	Lets Mario jump on a spiked[BR]
	enemy without taking damage.[End]
}

#message:24:(ItemShopDesc_DodgeMaster) {
	Makes the action command work[BR]
	more frequently.[End]
}

#message:24:(ItemShopDesc_PrettyLucky) {
	Makes enemies fail to attack[BR]
	Mario every once in a while.[End]
}

#message:24:(ItemShopDesc_LuckyDay) {
	Sometimes makes enemies fail to[BR]
	attack Mario.[End]
}

#message:24:(ItemShopDesc_CloseCall) {
	When Mario's in Danger, enemies[BR]
	sometimes fail to attack.[End]
}

#message:24:(ItemShopDesc_PowerRush) {
	When Mario's in Danger, his[BR]
	attack power increases by 2.[End]
}

#message:24:(ItemShopDesc_LastStand) {
	When Mario's in Danger, he[BR]
	receives only half the damage.[End]
}

#message:24:(ItemShopDesc_MegaRush) {
	When Mario's in Peril, his[BR]
	attack power goes up by 4.   [End]
}

#message:24:(ItemShopDesc_FirstAttack) {
	Lets Mario destroy a weaker [BR]
	enemy with a First Strike.  [End]
}

#message:24:(ItemShopDesc_BumpAttack) {
	Lets Mario destroy a weaker[BR]
	enemy in the field by hitting it.[End]
}

#message:24:(ItemShopDesc_SpinAttack) {
	Lets Mario destroy a weaker[BR]
	enemy with a spinning move.[End]
}

#message:24:(ItemShopDesc_DizzyAttack) {
	Delivers a blow that makes an[BR]
	enemy dizzy and unable to move.[End]
}

#message:24:(ItemShopDesc_SpeedySpin) {
	Increases the distance Mario[BR]
	can Spin Dash.[End]
}

#message:24:(ItemShopDesc_FeelingFine) {
	Protects Mario from poisoning[BR]
	and dizziness during attack.[End]
}

#message:24:(ItemShopDesc_AttackFXA) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:24:(ItemShopDesc_AttackFXD) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:24:(ItemShopDesc_AttackFXB) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:24:(ItemShopDesc_AttackFXE) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:24:(ItemShopDesc_AttackFXC) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:24:(ItemShopDesc_AttackFXF) {
	Changes the sound effects[BR]
	when Mario's attacking.[End]
}

#message:24:(ItemShopDesc_AllorNothing) {
	If the action command works,[BR]
	attack power +1. If not, it's 0.[End]
}

#message:24:(ItemShopDesc_SlowGo) {
	Makes Mario unable to run. His[BR]
	pace becomes very slow.[End]
}

#message:24:(ItemShopDesc_IcePower) {
	Increases attack power against[BR]
	fire enemies by 2.  [End]
}

#message:24:(ItemShopDesc_PayOff) {
	The more damage Mario takes,[BR]
	the more coins he receives.[End]
}

#message:24:(ItemShopDesc_FireShield) {
	Makes the damage Mario takes[BR]
	from fire attacks go down by 1.[End]
}

#message:24:(ItemShopDesc_ChillOut) {
	Keeps you from being hit by a[BR]
	First Strike.[End]
}

#message:24:(ItemShopDesc_ZapTap) {
	In battle, makes most enemies[BR]
	who touch Mario take damage.  [End]
}

#message:24:(ItemShopDesc_MoneyMoney) {
	After a battle, lets Mario get[BR]
	twice as many coins as usual.[End]
}

#message:24:(ItemShopDesc_RightOn) {
	Makes the action command work[BR]
	every time Mario attacks.[End]
}

#message:24:(ItemShopDesc_RunawayPay) {
	Lets Mario earn Star Points[BR]
	even if he escapes from battle. [End]
}

#message:24:(ItemShopDesc_Refund) {
	Refunds some coins if you use an[BR]
	item in battle.[End]
}

#message:24:(ItemShopDesc_ISpy) {
	A sound and icon alert you to a[BR]
	nearby hidden panel.[End]
}

#message:24:(ItemShopDesc_Peekaboo) {
	Makes it possible to see your[BR]
	enemy's HP.[End]
}

#message:24:(ItemShopDesc_Boots) {
	no data[End]
}

#message:24:(ItemShopDesc_SuperBoots) {
	no data[End]
}

#message:24:(ItemShopDesc_UltraBoots) {
	no data[End]
}

#message:24:(ItemShopDesc_Hammer) {
	no data[End]
}

#message:24:(ItemShopDesc_SuperHammer) {
	no data[End]
}

#message:24:(ItemShopDesc_UltraHammer) {
	no data[End]
}

#message:24:(ItemShopDesc_LuckyStar) {
	no data[End]
}

#message:24:(ItemShopDesc_KoopaFortressKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_RuinsKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_TubbaCastleKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_CrystalPalaceKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_BowserCastleKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_PeachKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_OddKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_Dolly) {
	nothing[End]
}

#message:24:(ItemShopDesc_KooperShell) {
	nothing[End]
}

#message:24:(ItemShopDesc_PulseStone) {
	nothing[End]
}

#message:24:(ItemShopDesc_Artifact) {
	nothing[End]
}

#message:24:(ItemShopDesc_GoldenJar) {
	nothing[End]
}

#message:24:(ItemShopDesc_LunarStone) {
	nothing[End]
}

#message:24:(ItemShopDesc_PyramidStone) {
	nothing[End]
}

#message:24:(ItemShopDesc_DiamondStone) {
	nothing[End]
}

#message:24:(ItemShopDesc_BooRecord) {
	nothing[End]
}

#message:24:(ItemShopDesc_BooWeight) {
	nothing[End]
}

#message:24:(ItemShopDesc_BooPortrait) {
	nothing[End]
}

#message:24:(ItemShopDesc_MysticalKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_StoreroomKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_ToyTrain) {
	nothing[End]
}

#message:24:(ItemShopDesc_FryingPan) {
	nothing[End]
}

#message:24:(ItemShopDesc_Dictionary) {
	nothing[End]
}

#message:24:(ItemShopDesc_MysteryNote) {
	nothing[End]
}

#message:24:(ItemShopDesc_Mailbag) {
	nothing[End]
}

#message:24:(ItemShopDesc_MagicalSeed1) {
	nothing[End]
}

#message:24:(ItemShopDesc_MagicalSeed2) {
	nothing[End]
}

#message:24:(ItemShopDesc_MagicalSeed3) {
	nothing[End]
}

#message:24:(ItemShopDesc_MagicalSeed4) {
	nothing[End]
}

#message:24:(ItemShopDesc_CrystalBerry) {
	nothing[End]
}

#message:24:(ItemShopDesc_WaterStone) {
	nothing[End]
}

#message:24:(ItemShopDesc_MagicalBean) {
	nothing[End]
}

#message:24:(ItemShopDesc_FertileSoil) {
	nothing[End]
}

#message:24:(ItemShopDesc_MiracleWater) {
	nothing[End]
}

#message:24:(ItemShopDesc_CrystalBall) {
	nothing[End]
}

#message:24:(ItemShopDesc_Calculator) {
	nothing[End]
}

#message:24:(ItemShopDesc_Cookbook) {
	nothing[End]
}

#message:24:(ItemShopDesc_JadeRaven) {
	nothing[End]
}

#message:24:(ItemShopDesc_VolcanoVase) {
	nothing[End]
}

#message:24:(ItemShopDesc_WarehouseKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_SnowmanBucket) {
	nothing[End]
}

#message:24:(ItemShopDesc_SnowmanScarf) {
	nothing[End]
}

#message:24:(ItemShopDesc_StarStone) {
	nothing[End]
}

#message:24:(ItemShopDesc_RedKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_BlueKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_SneakyParasol) {
	nothing[End]
}

#message:24:(ItemShopDesc_PrisonKey) {
	nothing[End]
}

#message:24:(ItemShopDesc_Lyrics) {
	nothing[End]
}

#message:24:(ItemShopDesc_Melody) {
	nothing[End]
}

#message:24:(ItemShopDesc_BakingSugar) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingSalt) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingEgg) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingCream) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingStrawberry) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingButter) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingCleanser) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingWater) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingFlour) {
	no data[End]
}

#message:24:(ItemShopDesc_BakingMilk) {
	no data[End]
}

#message:24:(ItemShopDesc_FirstDegreeCard) {
	no data[End]
}

#message:24:(ItemShopDesc_SecondDegreeCard) {
	no data[End]
}

#message:24:(ItemShopDesc_ThirdDegreeCard) {
	no data[End]
}

#message:24:(ItemShopDesc_FourthDegreeCard) {
	no data[End]
}

#message:24:(ItemShopDesc_Diploma) {
	no data[End]
}

#message:24:(ItemShopDesc_UltraStone) {
	no data[End]
}

#message:24:(ItemShopDesc_SilverCredit) {
	no data[End]
}

#message:24:(ItemShopDesc_GoldCredit) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter25) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter01) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter02) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter03) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter04) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter05) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter06) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter07) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter08) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter09) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter10) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter11) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter12) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter13) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter14) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter15) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter16) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter17) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter18) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter19) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter20) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter21) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter22) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter23) {
	no data[End]
}

#message:24:(ItemShopDesc_Letter24) {
	no data[End]
}

#message:24:(ItemShopDesc_KootKoopaLegends) {
	none[End]
}

#message:24:(ItemShopDesc_KootTheTape) {
	none[End]
}

#message:24:(ItemShopDesc_KootLuigiAutograph) {
	none[End]
}

#message:24:(ItemShopDesc_KootEmptyWallet) {
	none[End]
}

#message:24:(ItemShopDesc_KootMerluvleeAutograph) {
	none[End]
}

#message:24:(ItemShopDesc_KootOldPhoto) {
	none[End]
}

#message:24:(ItemShopDesc_KootGlasses) {
	none[End]
}

#message:24:(ItemShopDesc_KootPackage) {
	none[End]
}

#message:24:(ItemShopDesc_KootRedJar) {
	none[End]
}
