#message:25:(ItemFullDesc_FireFlower) {
	A flower that burns all enemies[BR]
	for 4 turns, and deals 1 damage.[End]
}

#message:25:(ItemFullDesc_SnowmanDoll) {
	A snowman that crushes all[BR]
	enemies. Attack Power: 4[End]
}

#message:25:(ItemFullDesc_ThunderRage) {
	Lightning that strikes all[BR]
	enemies. Attack Power: 5[End]
}

#message:25:(ItemFullDesc_ThunderBolt) {
	Lightning that strikes an enemy.[BR]
	Attack Power: 5[End]
}

#message:25:(ItemFullDesc_ShootingStar) {
	Shooting stars that hit all[BR]
	enemies. Attack Power: 6[End]
}

#message:25:(ItemFullDesc_DustyHammer) {
	A dusty old Hammer. Throw it to[BR]
	damage an enemy.[End]
}

#message:25:(ItemFullDesc_Pebble) {
	A common pebble. Throw it to[BR]
	damage an enemy.[End]
}

#message:25:(ItemFullDesc_StoneCap) {
	Turns Mario to stone and makes[BR]
	him unable to move for a while. [BR]
	While in this state, Mario can't[BR]
	be damaged.[End]
}

#message:25:(ItemFullDesc_VoltShroom) {
	Electrifies Mario for a short[BR]
	time.[BR]
	Any enemies who touch him will[BR]
	take damage.  [End]
}

#message:25:(ItemFullDesc_Mushroom) {
	A regular Mushroom. Restores[BR]
	5 HP.[End]
}

#message:25:(ItemFullDesc_SuperShroom) {
	A truly super Mushroom.[BR]
	Restores 10 HP.[End]
}

#message:25:(ItemFullDesc_UltraShroom) {
	An ultra-fine Mushroom. Restores[BR]
	50 HP.[End]
}

#message:25:(ItemFullDesc_LifeShroom) {
	A life-giving Mushroom. Restores[BR]
	10 HP when Mario's HP hits 0.[End]
}

#message:25:(ItemFullDesc_DriedShroom) {
	A very dry Mushroom. Restores[BR]
	1 HP.[End]
}

#message:25:(ItemFullDesc_TastyTonic) {
	A very tasty tonic. Cures[BR]
	debuffs, and recovers 5 FP[BR]
	per cleared debuff.[End]
}

#message:25:(ItemFullDesc_SuperSoda) {
	A bubbly soda. Cures debuffs[BR]
	and restores 5 FP.[End]
}

#message:25:(ItemFullDesc_BlueBerry) {
	A berry found in Flower Fields.[BR]
	Restores 5 FP.[End]
}

#message:25:(ItemFullDesc_RedBerry) {
	A berry found in Flower Fields.[BR]
	Restores 5 HP.[End]
}

#message:25:(ItemFullDesc_YellowBerry) {
	A berry found in Flower Fields.[BR]
	Restores 3 HP and 3 FP.[End]
}

#message:25:(ItemFullDesc_BubbleBerry) {
	A berry found in Flower Fields.[BR]
	Restores 5 HP.[End]
}

#message:25:(ItemFullDesc_Lime) {
	A fruit found in a desert oasis.[BR]
	Restores 3 FP.[End]
}

#message:25:(ItemFullDesc_Lemon) {
	A fruit found in a desert oasis.[BR]
	Restores 1 HP and 2 FP.[End]
}

#message:25:(ItemFullDesc_HoneySyrup) {
	Sweet honey syrup. Restores[BR]
	5 FP.[End]
}

#message:25:(ItemFullDesc_MapleSyrup) {
	Delicious maple syrup. Restores[BR]
	10 FP.[End]
}

#message:25:(ItemFullDesc_JamminJelly) {
	A highly nutritious snack.[BR]
	Restores 50 FP.[End]
}

#message:25:(ItemFullDesc_WhackasBump) {
	A Whacka Bump from Mt. Rugged.[BR]
	Restores 25 HP and 25 FP.[End]
}

#message:25:(ItemFullDesc_Apple) {
	A sweet, tangy apple. Restores[BR]
	5 HP.[End]
}

#message:25:(ItemFullDesc_Goomnut) {
	Restores 3 FP.[BR]
	+2 DEF for 1 turn.[BR]
	A special nut found only in[BR]
	Goomba Village.[End]
}

#message:25:(ItemFullDesc_KoopaLeaf) {
	Restores 1 FP, reduces FP costs[BR]
	by 2 for 2 turns.[BR]
	A leaf found in Koopa Village.[End]
}

#message:25:(ItemFullDesc_DriedPasta) {
	Pasta from Dry Dry Outpost.[BR]
	Restores 3 HP and 2 FP.[End]
}

#message:25:(ItemFullDesc_DriedFruit) {
	A fruit found deep within Dry[BR]
	Dry Desert. Restores 15 HP.[End]
}

#message:25:(ItemFullDesc_StrangeLeaf) {
	A very rare leaf. Restores 5 FP.[End]
}

#message:25:(ItemFullDesc_CakeMix) {
	A mix used to bake tasty cakes.[BR]
	[End]
}

#message:25:(ItemFullDesc_Egg) {
	An egg of unknown origin.[BR]
	Restores 7 HP.[End]
}

#message:25:(ItemFullDesc_Coconut) {
	A coconut from Lavalava Island.[BR]
	Throw it to damage 1 enemy.[End]
}

#message:25:(ItemFullDesc_Melon) {
	A succulent, ripe melon. Restores[BR]
	15 HP.[End]
}

#message:25:(ItemFullDesc_StinkyHerb) {
	This herb smells kind of bad...[BR]
	Restores 5 FP.[End]
}

#message:25:(ItemFullDesc_IcedPotato) {
	A tough potato found in the[BR]
	Shiver Region. Restores 5 HP.[End]
}

#message:25:(ItemFullDesc_SleepySheep) {
	If it works, makes all enemies [BR]
	sleep for a little while.[End]
}

#message:25:(ItemFullDesc_POWBlock) {
	Flips shell enemies and inflicts[BR]
	2 damage points on all enemies.[End]
}

#message:25:(ItemFullDesc_StopWatch) {
	If it works, paralyzes all[BR]
	enemies for a short time.[End]
}

#message:25:(ItemFullDesc_DizzyDial) {
	If it works, dazes all enemies,[BR]
	making them miss attacks.[BR]
	It's especially effective against[BR]
	flying enemies.[End]
}

#message:25:(ItemFullDesc_FrightJar) {
	Scares all enemies, reducing[BR]
	their DEF by 2 for 2 turns.[End]
}

#message:25:(ItemFullDesc_Mystery) {
	Who knows what it does... Take a[BR]
	chance to find out![End]
}

#message:25:(ItemFullDesc_RepelGel) {
	Makes Mario transparent and[BR]
	invulnerable for a short time. [End]
}

#message:25:(ItemFullDesc_SpicySoup) {
	A hot soup cooked by Tayce T.[BR]
	+1 HP, +2 ATK for 1 turn.[End]
}

#message:25:(ItemFullDesc_ApplePie) {
	An apple pie baked by Tayce T.[BR]
	Restores 5 HP and 15 FP.[End]
}

#message:25:(ItemFullDesc_HoneyShroom) {
	A dessert made by Tayce T.[BR]
	Restores 5 HP and 5 FP.[End]
}

#message:25:(ItemFullDesc_MapleShroom) {
	A dessert made by Tayce T.[BR]
	Restores 5 HP and 10 FP.[End]
}

#message:25:(ItemFullDesc_JellyShroom) {
	A dessert made by Tayce T.[BR]
	Restores 5 HP and 50 FP.[End]
}

#message:25:(ItemFullDesc_HoneySuper) {
	A dessert made by Tayce T.[BR]
	Restores 10 HP and 5 FP.[End]
}

#message:25:(ItemFullDesc_MapleSuper) {
	A dessert made by Tayce T.[BR]
	Restores 10 HP and 10 FP.[End]
}

#message:25:(ItemFullDesc_JellySuper) {
	A dessert made by Tayce T.[BR]
	Restores 10 HP and 50 FP.[End]
}

#message:25:(ItemFullDesc_HoneyUltra) {
	A dessert made by Tayce T.[BR]
	Restores 50 HP and 5 FP.[End]
}

#message:25:(ItemFullDesc_MapleUltra) {
	A dessert made by Tayce T.[BR]
	Restores 50 HP and 10 FP.[End]
}

#message:25:(ItemFullDesc_JellyUltra) {
	A dessert made by Tayce T.[BR]
	Restores 50 HP and 50 FP.[End]
}

#message:25:(ItemFullDesc_Koopasta) {
	Special pasta made by Tayce T.[BR]
	Restores 7 HP and 7 FP.[End]
}

#message:25:(ItemFullDesc_FriedShroom) {
	A snack made by Tayce T.[BR]
	Restores 6 HP and 2 FP.[End]
}

#message:25:(ItemFullDesc_HotShroom) {
	A snack made by Tayce T.[BR]
	Restores 5 HP, electrifies[BR]
	Mario for 2 turns and[BR]
	charges next move by 1 ATK.[End]
}

#message:25:(ItemFullDesc_ShroomSteak) {
	A dish cooked by Tayce T.[BR]
	Restores 30 HP and 10 FP.[End]
}

#message:25:(ItemFullDesc_ShroomCake) {
	A cake baked by Tayce T.[BR]
	Restores 10 HP and 10 FP.[End]
}

#message:25:(ItemFullDesc_SweetShroom) {
	A yummy cake baked by Tayce T.[BR]
	Restores 30 HP and 20 FP.[End]
}

#message:25:(ItemFullDesc_BlandMeal) {
	Boring food cooked by Tayce T.[BR]
	Restores 10 HP and 10 FP.[End]
}

#message:25:(ItemFullDesc_YummyMeal) {
	Tasty food cooked by Tayce T.[BR]
	Restores 20 HP and 20 FP.[End]
}

#message:25:(ItemFullDesc_DeluxeFeast) {
	Amazing food cooked by Tayce T.[BR]
	Restores 40 HP and 40 FP.[End]
}

#message:25:(ItemFullDesc_SpecialShake) {
	A smoothie made by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:25:(ItemFullDesc_HealthyJuice) {
	A juice blend made by Tayce T.[BR]
	Restores 40 FP.[End]
}

#message:25:(ItemFullDesc_BigCookie) {
	A huge cookie baked by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:25:(ItemFullDesc_Cake) {
	A tasty cake baked by Tayce T.[BR]
	Restores 15 FP.[End]
}

#message:25:(ItemFullDesc_Mistake) {
	This doesn't look very good![BR]
	Restores 1 HP and 1 FP.[BR]
	Poisons you for 3 turns.[End]
}

#message:25:(ItemFullDesc_KoopaTea) {
	Tea brewed by Tayce T.[BR]
	Restores 5 FP, reduces FP[BR]
	costs by 1 for 4 turns.[End]
}

#message:25:(ItemFullDesc_Spaghetti) {
	Spaghetti cooked by Tayce T.[BR]
	Restores 6 HP and 4 FP.[End]
}

#message:25:(ItemFullDesc_EggMissile) {
	An egg Bomb made by Tayce T.[BR]
	Throw it to damage 1 enemy.[End]
}

#message:25:(ItemFullDesc_FriedEgg) {
	Food cooked by Tayce T.[BR]
	Restores 13 HP.[End]
}

#message:25:(ItemFullDesc_HoneyCandy) {
	A sweet candy made by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:25:(ItemFullDesc_ElectroPop) {
	A tart lollipop made by Tayce T.[BR]
	Restores 15 FP.[End]
}

#message:25:(ItemFullDesc_FirePop) {
	A hot lollipop made by Tayce T.[BR]
	Restores 20 FP but uses 1 HP.[End]
}

#message:25:(ItemFullDesc_LimeCandy) {
	A tangy candy made by Tayce T.[BR]
	Restores 20 FP.[End]
}

#message:25:(ItemFullDesc_CocoPop) {
	A sweet candy made by Tayce T.[BR]
	Restores 3 HP and 15 FP.[End]
}

#message:25:(ItemFullDesc_LemonCandy) {
	A tangy candy made by Tayce T.[BR]
	Restores 5 HP and 15 FP.[End]
}

#message:25:(ItemFullDesc_JellyPop) {
	A big lollipop made by Tayce T.[BR]
	Restores 64 FP.[End]
}

#message:25:(ItemFullDesc_StrangeCake) {
	A bizarre and mysterious cake[BR]
	made by Tayce T.[BR]
	It electrifies Mario, turns him[BR]
	transparent, or makes him sleep.[End]
}

#message:25:(ItemFullDesc_KookyCookie) {
	A delicious but kooky cookie[BR]
	made by Tayce T.[BR]
	Makes Mario electric, sleepy,[BR]
	or transparent. Restores 15 FP.[BR]
	[End]
}

#message:25:(ItemFullDesc_FrozenFries) {
	A side dish made by Tayce T.[BR]
	Restores 15 HP.[End]
}

#message:25:(ItemFullDesc_PotatoSalad) {
	A side dish made by Tayce T.[BR]
	Restores 10 HP.[End]
}

#message:25:(ItemFullDesc_NuttyCake) {
	A nut cake baked by Tayce T.[BR]
	Restores 5 FP and increases[BR]
	DEF by 1 for 2 turns.[End]
}

#message:25:(ItemFullDesc_BoiledEgg) {
	Food cooked by Tayce T.[BR]
	Restores 8 HP and 8 FP.[End]
}

#message:25:(ItemFullDesc_YoshiCookie) {
	A cookie baked by Tayce T.[BR]
	Restores 15 HP and 15 FP.[End]
}

#message:25:(ItemFullDesc_PowerJump) {
	Lets you do a Power Jump.[BR]
	Uses 2 FP for +2 ATK.[BR]
	Mario stomps on a single enemy[BR]
	using a lot of attack power.[End]
}

#message:25:(ItemFullDesc_MegaJump) {
	Lets you do a Mega Jump.[BR]
	Uses 6 FP.[BR]
	Mario stomps on a single enemy[BR]
	using tons of attack power.[End]
}

#message:25:(ItemFullDesc_JumpCharge) {
	Lets you charge up Jump power.[BR]
	Uses 1 FP.[BR]
	When charged, Mario's Jump[BR]
	power goes up by 2. Lets you[BR]
	charge unlimited times, but[BR]
	power fades after attack.[End]
}

#message:25:(ItemFullDesc_SJumpChg) {
	Greatly charges up Jump power.[BR]
	Uses 4 FP.[BR]
	When supercharged, Mario's Jump[BR]
	power goes up by 3.[BR]
	Lets you charge unlimited times,[BR]
	but power fades after attack.[End]
}

#message:25:(ItemFullDesc_SleepStomp) {
	Lets you do a Sleep Stomp.[BR]
	Uses 2 FP.[BR]
	If it works, the enemy Mario[BR]
	jumps on falls asleep for a bit.[End]
}

#message:25:(ItemFullDesc_DizzyStomp) {
	Lets you do a Dizzy Stomp.[BR]
	Uses 2 FP.[BR]
	If it works, the enemy Mario [BR]
	jumps on becomes dizzy.[BR]
	It also paralyzes the enemy for[BR]
	a short time.[BR]
	[End]
}

#message:25:(ItemFullDesc_Multibounce) {
	Lets you do a Multibounce.[BR]
	Uses 2 FP.[BR]
	Jumps on all enemies in a row if[BR]
	action command is timed right.[End]
}

#message:25:(ItemFullDesc_ShrinkStomp) {
	Lets you do a Shrink Stomp.[BR]
	Uses 2 FP.[BR]
	If it works, the enemy Mario [BR]
	stomps on shrinks.[BR]
	It also decreases the enemy's[BR]
	attack power by half for a bit.[End]
}

#message:25:(ItemFullDesc_DDownJump) {
	Lets you do a D-Down Jump.[BR]
	Uses 2 FP.[BR]
	Disables an enemy's defense[BR]
	power and causes some damage.[End]
}

#message:25:(ItemFullDesc_PowerBounce) {
	Lets you do a Power Bounce.[BR]
	Uses 3 FP.[BR]
	Jumps on one enemy continuously [BR]
	until you miss an action command.[End]
}

#message:25:(ItemFullDesc_PowerSmash) {
	Lets you do a Power Smash.[BR]
	Uses 2 FP.[BR]
	Hammers an enemy using lots of[BR]
	attack power.[End]
}

#message:25:(ItemFullDesc_MegaSmash) {
	Lets you do a Mega Smash.[BR]
	Uses 6 FP.[BR]
	Hammers an enemy with a huge[BR]
	amount of attack power.[End]
}

#message:25:(ItemFullDesc_SmashCharge) {
	Lets you charge up your Hammer.[BR]
	Uses 1 FP.[BR]
	When charged, Mario's Hammer[BR]
	power goes up by 2.[BR]
	Lets you charge unlimited times,[BR]
	but power fades after attack.[End]
}

#message:25:(ItemFullDesc_SSmashChg) {
	Greatly charges up your Hammer.[BR]
	Uses 4 FP.[BR]
	When supercharged, Mario's [BR]
	Hammer power goes up by 3.[BR]
	Lets you charge unlimited times,[BR]
	but power fades after attack.[End]
}

#message:25:(ItemFullDesc_HammerThrow) {
	Hits one enemy with the Hammer,[BR]
	no matter where the enemy is.[BR]
	+1 ATK to grounded enemies,[BR]
	and +2 to airborne targets.[End]
}

#message:25:(ItemFullDesc_ShrinkSmash) {
	Lets you do a Shrink Smash.[BR]
	Uses 1 FP.[BR]
	If it works, the enemy Mario hits[BR]
	shrinks.[BR]
	It also decreases the enemy's[BR]
	attack power by half for a bit.[End]
}

#message:25:(ItemFullDesc_SpinSmash) {
	Lets you do a Spin Smash.[BR]
	Uses 2 FP.[BR]
	If Mario hits an enemy, it[BR]
	smashes into the ones behind it.[End]
}

#message:25:(ItemFullDesc_DDownPound) {
	Lets you do a D-Down Pound.[BR]
	Uses 2 FP.[BR]
	Disables an enemy's defense[BR]
	power and injures it.[End]
}

#message:25:(ItemFullDesc_QuakeHammer) {
	Lets you do a Quake Hammer.[BR]
	Uses 2 FP.[BR]
	Slightly damages all enemies on[BR]
	the ground or ceiling.[End]
}

#message:25:(ItemFullDesc_PowerQuake) {
	Lets you do a Power Quake.[BR]
	Uses 4 FP.[BR]
	Greatly damages all enemies on[BR]
	the ground or ceiling.[End]
}

#message:25:(ItemFullDesc_MegaQuake) {
	Lets you do a Mega Quake.[BR]
	Uses 7 FP.[BR]
	Severely damages all enemies on[BR]
	the ground or ceiling.[End]
}

#message:25:(ItemFullDesc_DoubleDip) {
	During battle, lets you use two[BR]
	items during one turn.[BR]
	Uses 3 FP.[BR]
	[End]
}

#message:25:(ItemFullDesc_TripleDip) {
	During battle, lets you use three[BR]
	items during one turn.[BR]
	Uses 6 FP.[BR]
	[End]
}

#message:25:(ItemFullDesc_GroupFocus) {
	Lets Mario's party members use[BR]
	the Focus command, as well.[End]
}

#message:25:(ItemFullDesc_QuickChange) {
	During battle, lets you change[BR]
	your party member...[BR]
	...and still use the new member[BR]
	without losing a turn.[End]
}

#message:25:(ItemFullDesc_HPPlus) {
	Increases maximum HP by 5.[End]
}

#message:25:(ItemFullDesc_FPPlus) {
	Increases maximum FP by 5.[End]
}

#message:25:(ItemFullDesc_PowerPlus) {
	Increases Mario's Jump and[BR]
	Hammer attack powers by 1.[End]
}

#message:25:(ItemFullDesc_DefendPlus) {
	Decreases the damage that[BR]
	Mario takes by 1.[End]
}

#message:25:(ItemFullDesc_DamageDodge) {
	If you do the action command,[BR]
	decreases Mario's damage by 1.[End]
}

#message:25:(ItemFullDesc_PUpDDown) {
	Increases attack power by 1.[BR]
	Decreases defense power by 1.[End]
}

#message:25:(ItemFullDesc_PDownDUp) {
	Decreases attack power by 1.[BR]
	Increases defense power by 1.[End]
}

#message:25:(ItemFullDesc_HPDrain) {
	Decreases Mario's attack power[BR]
	by 1.[BR]
	But for every attack turn,[BR]
	Mario's HP recovers by 1.[BR]
	Mario's HP can recover by a[BR]
	maximum of 5.[End]
}

#message:25:(ItemFullDesc_HappyHeart) {
	Restores HP automatically during[BR]
	battle at a slow rate.[End]
}

#message:25:(ItemFullDesc_HappyFlower) {
	Restores FP automatically during[BR]
	battle at a slow rate.[End]
}

#message:25:(ItemFullDesc_FlowerSaver) {
	During battle, saves 1 FP every[BR]
	time you attack. [End]
}

#message:25:(ItemFullDesc_HeartFinder) {
	After beating an enemy, makes[BR]
	more hearts appear than usual.[End]
}

#message:25:(ItemFullDesc_FlowerFinder) {
	After beating an enemy, makes [BR]
	more flowers appear than usual.[End]
}

#message:25:(ItemFullDesc_DeepFocus) {
	When using Focus, charges Star[BR]
	Energy more than usual.[End]
}

#message:25:(ItemFullDesc_SpikeShield) {
	Lets Mario jump on a spiked[BR]
	enemy without taking damage.[End]
}

#message:25:(ItemFullDesc_DodgeMaster) {
	Makes the action command work[BR]
	more frequently.[End]
}

#message:25:(ItemFullDesc_PrettyLucky) {
	Makes enemies fail to attack[BR]
	Mario every once in a while.[End]
}

#message:25:(ItemFullDesc_LuckyDay) {
	Sometimes makes enemies fail to[BR]
	attack Mario.[End]
}

#message:25:(ItemFullDesc_CloseCall) {
	When an attack puts Mario into[BR]
	Danger, he gains +1 DEF until[BR]
	his next turn. Does not impact[BR]
	the attack putting him in Danger.[End]
}

#message:25:(ItemFullDesc_PowerRush) {
	When Mario's in Danger, his[BR]
	attack power increases by 2.[End]
}

#message:25:(ItemFullDesc_LastStand) {
	When Mario's in Danger, he[BR]
	receives only half the damage.[End]
}

#message:25:(ItemFullDesc_MegaRush) {
	When Mario's in Peril, his attack[BR]
	power goes up by 4.  [End]
}

#message:25:(ItemFullDesc_FirstAttack) {
	Lets Mario destroy a weaker[BR]
	enemy with a First Strike.  [End]
}

#message:25:(ItemFullDesc_BumpAttack) {
	Lets Mario destroy a weaker [BR]
	enemy in the field by hitting it.[End]
}

#message:25:(ItemFullDesc_SpinAttack) {
	Lets Mario destroy a weaker[BR]
	enemy with a spinning move.[End]
}

#message:25:(ItemFullDesc_DizzyAttack) {
	Delivers a blow that makes an[BR]
	enemy dizzy and miss attacks.[End]
}

#message:25:(ItemFullDesc_SpeedySpin) {
	Increases the distance Mario[BR]
	can Spin Dash.[End]
}

#message:25:(ItemFullDesc_FeelingFine) {
	Protects Mario from poisoning[BR]
	and dizziness during attack.[End]
}

#message:25:(ItemFullDesc_AttackFXA) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:25:(ItemFullDesc_AttackFXD) {
	Changes the sound effects when[BR]
	Mario's attacking.[BR]
	[End]
}

#message:25:(ItemFullDesc_AttackFXB) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:25:(ItemFullDesc_AttackFXE) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:25:(ItemFullDesc_AttackFXC) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:25:(ItemFullDesc_AttackFXF) {
	Changes the sound effects when[BR]
	Mario's attacking.[End]
}

#message:25:(ItemFullDesc_AllorNothing) {
	If you use the action command, [BR]
	Mario's attack power goes up 1.[BR]
	If you fail, it goes to 0.[End]
}

#message:25:(ItemFullDesc_SlowGo) {
	Makes Mario unable to run. His[BR]
	pace becomes very slow.[End]
}

#message:25:(ItemFullDesc_IcePower) {
	Increases attack power against[BR]
	fire enemies by 2.[BR]
	Mario won't take damage when he[BR]
	jumps on a fire enemy.[End]
}

#message:25:(ItemFullDesc_PayOff) {
	The more damage Mario takes,[BR]
	the more coins he receives.[End]
}

#message:25:(ItemFullDesc_FireShield) {
	Makes the damage Mario takes[BR]
	from fire attacks go down by 1.[BR]
	Mario won't take damage when he[BR]
	jumps on a fire enemy. [End]
}

#message:25:(ItemFullDesc_ChillOut) {
	Keeps you from being hit by a[BR]
	First Strike.[End]
}

#message:25:(ItemFullDesc_ZapTap) {
	In battle, makes most enemies[BR]
	who touch Mario take damage.  [End]
}

#message:25:(ItemFullDesc_MoneyMoney) {
	After a battle, lets Mario get[BR]
	twice as many coins as usual.[End]
}

#message:25:(ItemFullDesc_RightOn) {
	Makes the action command work[BR]
	every time Mario attacks.[End]
}

#message:25:(ItemFullDesc_RunawayPay) {
	Lets Mario earn Star Points[BR]
	even if he escapes from battle. [End]
}

#message:25:(ItemFullDesc_Refund) {
	Refunds some coins if you use an[BR]
	item in battle.[End]
}

#message:25:(ItemFullDesc_ISpy) {
	A sound and icon alert you to a[BR]
	nearby hidden panel.[End]
}

#message:25:(ItemFullDesc_Peekaboo) {
	Makes it possible to see your[BR]
	enemy's HP.[End]
}

#message:25:(ItemFullDesc_Boots) {
	Jump and stomp on an enemy.[End]
}

#message:25:(ItemFullDesc_SuperBoots) {
	Jump and stomp on an enemy.[End]
}

#message:25:(ItemFullDesc_UltraBoots) {
	Jump and stomp on an enemy.[End]
}

#message:25:(ItemFullDesc_Hammer) {
	Smack enemies with the Hammer.[End]
}

#message:25:(ItemFullDesc_SuperHammer) {
	Smack enemies with the Hammer.[End]
}

#message:25:(ItemFullDesc_UltraHammer) {
	Smack enemies with the Hammer.[End]
}

#message:25:(ItemFullDesc_LuckyStar) {
	A star-shaped pendant. Lets[BR]
	you use the action command.[End]
}

#message:25:(ItemFullDesc_KoopaFortressKey) {
	Opens a locked door in the[BR]
	Koopa Bros. Fortress.[End]
}

#message:25:(ItemFullDesc_RuinsKey) {
	Opens a locked door in Dry Dry[BR]
	Ruins.[End]
}

#message:25:(ItemFullDesc_TubbaCastleKey) {
	Opens a locked door in Tubba[BR]
	Blubba's Castle.[End]
}

#message:25:(ItemFullDesc_CrystalPalaceKey) {
	Opens a locked door in the[BR]
	Crystal Palace.[End]
}

#message:25:(ItemFullDesc_BowserCastleKey) {
	Opens a locked door in Bowser's[BR]
	Castle.[End]
}

#message:25:(ItemFullDesc_PeachKey) {
	Opens a locked door in Princess[BR]
	Peach's Castle.[End]
}

#message:25:(ItemFullDesc_OddKey) {
	Opens a locked door in the Odd[BR]
	House.[End]
}

#message:25:(ItemFullDesc_Dolly) {
	An adorable doll that looks[BR]
	exactly like Princess Peach.[End]
}

#message:25:(ItemFullDesc_KooperShell) {
	Kooper's blue shell.[End]
}

#message:25:(ItemFullDesc_PulseStone) {
	The closer you get to Dry Dry[BR]
	Ruins, the faster it flashes.[BR]
	If you place it somewhere, the[BR]
	ruins will appear.[End]
}

#message:25:(ItemFullDesc_Artifact) {
	A strange artifact found in Dry[BR]
	Dry Ruins.[End]
}

#message:25:(ItemFullDesc_GoldenJar) {
	A sparkling gold pot. Moustafa[BR]
	was looking for this.[End]
}

#message:25:(ItemFullDesc_LunarStone) {
	A crescent-shaped stone found[BR]
	in Dry Dry Ruins.[BR]
	[End]
}

#message:25:(ItemFullDesc_PyramidStone) {
	A triangle-shaped stone found[BR]
	in Dry Dry Ruins.[End]
}

#message:25:(ItemFullDesc_DiamondStone) {
	A star-shaped stone found in[BR]
	Dry Dry Ruins.[End]
}

#message:25:(ItemFullDesc_BooRecord) {
	A record of upbeat music. How[BR]
	can you play this?[End]
}

#message:25:(ItemFullDesc_BooWeight) {
	A very heavy weight. How can you[BR]
	use this?[End]
}

#message:25:(ItemFullDesc_BooPortrait) {
	A portrait of an old male Boo.[End]
}

#message:25:(ItemFullDesc_MysticalKey) {
	A key found in Tubba Blubba's[BR]
	room.[End]
}

#message:25:(ItemFullDesc_StoreroomKey) {
	A key to the storeroom in a Toad[BR]
	Town shop.[BR]
	Return it to its original owner.[End]
}

#message:25:(ItemFullDesc_ToyTrain) {
	A very well designed toy train.[BR]
	Could this be more than a toy?[End]
}

#message:25:(ItemFullDesc_FryingPan) {
	Tayce T.'s frying pan. Return it[BR]
	to her.[End]
}

#message:25:(ItemFullDesc_Dictionary) {
	The scholar Russ T.'s dictionary.[BR]
	Return it to him.[End]
}

#message:25:(ItemFullDesc_MysteryNote) {
	A note written in a language[BR]
	that you can't read.[BR]
	Show it to someone who is very[BR]
	smart.[End]
}

#message:25:(ItemFullDesc_Mailbag) {
	A bag full of letters. Return it[BR]
	to the post office.[End]
}

#message:25:(ItemFullDesc_MagicalSeed1) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:25:(ItemFullDesc_MagicalSeed2) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:25:(ItemFullDesc_MagicalSeed3) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:25:(ItemFullDesc_MagicalSeed4) {
	A seed. Have it planted in the[BR]
	Flower Garden in Toad Town.[End]
}

#message:25:(ItemFullDesc_CrystalBerry) {
	A glittering berry made of[BR]
	crystal.[End]
}

#message:25:(ItemFullDesc_WaterStone) {
	A magical stone. Water springs[BR]
	from it.[BR]
	It will bring dried-up things[BR]
	back to life.[End]
}

#message:25:(ItemFullDesc_MagicalBean) {
	A bean. It's twitching as if to[BR]
	say, "Plant me this instant!"[End]
}

#message:25:(ItemFullDesc_FertileSoil) {
	Absolutely pollutant free. This[BR]
	smells like very good soil.[End]
}

#message:25:(ItemFullDesc_MiracleWater) {
	Very cold water. It glitters in[BR]
	the sun.[End]
}

#message:25:(ItemFullDesc_CrystalBall) {
	A gorgeous crystal ball. Give it[BR]
	to Merluvlee.[End]
}

#message:25:(ItemFullDesc_Calculator) {
	The calculator from Rowf's[BR]
	Badge Shop. Return it to him.[End]
}

#message:25:(ItemFullDesc_Cookbook) {
	A book Gourmet Guy dropped.[BR]
	Show it to a good cook.[End]
}

#message:25:(ItemFullDesc_JadeRaven) {
	The jade statue of a Raven that[BR]
	Yoshi's Village Leader gave you.[End]
}

#message:25:(ItemFullDesc_VolcanoVase) {
	A treasure found inside Mt.[BR]
	Lavalava.[End]
}

#message:25:(ItemFullDesc_WarehouseKey) {
	A key to the warehouse in Shiver[BR]
	City.[End]
}

#message:25:(ItemFullDesc_SnowmanBucket) {
	An ordinary bucket that the[BR]
	Shiver City Mayor gave you.[End]
}

#message:25:(ItemFullDesc_SnowmanScarf) {
	An ordinary scarf from Merle in[BR]
	Starborn Valley.[End]
}

#message:25:(ItemFullDesc_StarStone) {
	A stone. It opens the path to[BR]
	the Crystal Palace.[End]
}

#message:25:(ItemFullDesc_RedKey) {
	A big red key.[End]
}

#message:25:(ItemFullDesc_BlueKey) {
	A big blue key.[End]
}

#message:25:(ItemFullDesc_SneakyParasol) {
	A fabulous parasol given to quiz[BR]
	show participants.[End]
}

#message:25:(ItemFullDesc_PrisonKey) {
	A key to the prison in Bowser's[BR]
	Castle.[End]
}

#message:25:(ItemFullDesc_Lyrics) {
	Show it to a composer somewhere[BR]
	in the world.[End]
}

#message:25:(ItemFullDesc_Melody) {
	Give it to the Master Poet in[BR]
	Toad Town.[End]
}

#message:25:(ItemFullDesc_BakingSugar) {
	Snow white sugar.[End]
}

#message:25:(ItemFullDesc_BakingSalt) {
	As salty as salt gets.[End]
}

#message:25:(ItemFullDesc_BakingEgg) {
	Newly laid eggs.[End]
}

#message:25:(ItemFullDesc_BakingCream) {
	Very rich and fresh cream.[End]
}

#message:25:(ItemFullDesc_BakingStrawberry) {
	Bright red strawberries. They[BR]
	look fresh and juicy.[End]
}

#message:25:(ItemFullDesc_BakingButter) {
	The best butter available. It[BR]
	looks freshly churned.[End]
}

#message:25:(ItemFullDesc_BakingCleanser) {
	Detergent to wash utensils.[End]
}

#message:25:(ItemFullDesc_BakingWater) {
	Ordinary water.[End]
}

#message:25:(ItemFullDesc_BakingFlour) {
	The best flour available to bake[BR]
	the finest royal cakes.[End]
}

#message:25:(ItemFullDesc_BakingMilk) {
	Milk, fresh from the cow![End]
}

#message:25:(ItemFullDesc_FirstDegreeCard) {
	Proof of Mario's strength, won[BR]
	by defeating Chan at the Dojo.[End]
}

#message:25:(ItemFullDesc_SecondDegreeCard) {
	Proof of Mario's strength, won[BR]
	by defeating Lee at the Dojo.[End]
}

#message:25:(ItemFullDesc_ThirdDegreeCard) {
	Proof of Mario's strength, for[BR]
	besting The Master at the Dojo.[End]
}

#message:25:(ItemFullDesc_FourthDegreeCard) {
	Proof of Mario's strength, for[BR]
	besting The Master at the Dojo.[End]
}

#message:25:(ItemFullDesc_Diploma) {
	Proof of Mario's strength.[BR]
	[BR]
	Now Mario is regarded as[BR]
	stronger than The Master.[End]
}

#message:25:(ItemFullDesc_UltraStone) {
	A stone. Use it to ultra-rank[BR]
	one of your party members.[End]
}

#message:25:(ItemFullDesc_SilverCredit) {
	A card Koopa Koot gave you. Use[BR]
	it to play in the Playroom.[End]
}

#message:25:(ItemFullDesc_GoldCredit) {
	A card Koopa Koot gave you. Use[BR]
	it to play in the Playroom.[End]
}

#message:25:(ItemFullDesc_Letter25) {
	A letter to Kolorado.[BR]
	[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter01) {
	A letter to Merlon in Toad Town.[BR]
	[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter02) {
	A letter to Goompa in Goomba[BR]
	Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter03) {
	A letter to Mort T. in Koopa[BR]
	Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter04) {
	A letter to Russ T. in Toad Town.[BR]
	[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter05) {
	A letter to Mayor Penguin in[BR]
	Shiver City.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter06) {
	A letter to Merlow at Shooting[BR]
	Star Summit.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter07) {
	A letter to Fice T. near the[BR]
	entrance to Forever Forest.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter08) {
	A letter to the traveling[BR]
	Nomadimouse on the road.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter09) {
	A letter to Minh T. in Toad Town.[BR]
	[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter10) {
	A letter to Goompapa in Goomba[BR]
	Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter11) {
	A letter to Igor in Boo's Shop.[BR]
	[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter12) {
	A letter to Franky in Boo's[BR]
	Mansion.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter13) {
	A letter to Muss T. near[BR]
	Princess Peach's Castle.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter14) {
	A letter to Koover in Koopa[BR]
	Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter15) {
	A letter to Fishmael at the Toad[BR]
	Town Port.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter16) {
	A letter to Koover in Koopa[BR]
	Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter17) {
	A letter to Mr. E. in Dry Dry[BR]
	Outpost.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter18) {
	A letter to Miss T. near the[BR]
	Toad Town Dojo.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter19) {
	A letter to Little Mouser in the[BR]
	Dry Dry Outpost shop.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter20) {
	A letter to Dane T. near Toad[BR]
	Town Station.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter21) {
	A letter to the Red Yoshi Kid in[BR]
	Yoshi's Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter22) {
	A letter to Dane T. near Toad[BR]
	Town Station.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter23) {
	A letter to Frost T. in Starborn[BR]
	Valley.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_Letter24) {
	A letter to Goompapa in Goomba[BR]
	Village.[BR]
	You can deliver it with your[BR]
	Paratroopa partner, Parakarry.[End]
}

#message:25:(ItemFullDesc_KootKoopaLegends) {
	Kolorado's strange book. Deliver[BR]
	this to Koopa Koot.[End]
}

#message:25:(ItemFullDesc_KootTheTape) {
	A tape returned by Goompa.[BR]
	Deliver it to Koopa Koot.[End]
}

#message:25:(ItemFullDesc_KootLuigiAutograph) {
	Luigi's autograph. Koopa Koot[BR]
	wants this.[End]
}

#message:25:(ItemFullDesc_KootEmptyWallet) {
	A wallet Koopa Koot dropped.[BR]
	Return it to him.[End]
}

#message:25:(ItemFullDesc_KootMerluvleeAutograph) {
	An autograph from Merluvlee.[BR]
	Koopa Koot wants this.[End]
}

#message:25:(ItemFullDesc_KootOldPhoto) {
	Is this a picture of a young[BR]
	Koopa Koot? He wants this.[End]
}

#message:25:(ItemFullDesc_KootGlasses) {
	Glasses Koopa Koot dropped.[BR]
	Deliver them to him.[End]
}

#message:25:(ItemFullDesc_KootPackage) {
	A package received from a Boo.[BR]
	Deliver it to Koopa Koot.[End]
}

#message:25:(ItemFullDesc_KootRedJar) {
	A jar at Little Mouser's Shop.[BR]
	A collector's item, perhaps?[End]
}

#message:25:(ItemFullDesc_ChillJump) {
	Lets you do a Chill Stomp. Drops[BR]
	enemy ATK by 1 for 3 turns. 3 FP.[End]
}
