#message:27:(Shop_00_MAC00) {
	[Style right]
	You need [Var 1] coin[Var 2] for[BR]
	"[Var 0]". [BR]
	Want to buy it?[BR]
	[Yield][End]
}

#message:27:(Shop_01_MAC00) {
	[Next]
	You don't have enough coins![Wait][End]
}

#message:27:(Shop_02_MAC00) {
	[Next]
	You can't carry any more items[BR]
	right now.[BR]
	[Wait][Next]
	Please come back after selling,[BR]
	checking, or using some items.[Wait][End]
}

#message:27:(Shop_03_MAC00) {
	[Next]
	Thank you very much.[Wait][End]
}

#message:27:(Shop_04_MAC00) {
	[Style right]
	Welcome to Shroom Grocery![BR]
	[Wait][Next]
	How can I help you today?[BR]
	[Yield][End]
}

#message:27:(Shop_05_MAC00) {
	[Next]
	If there's anything you want to[BR]
	buy, stand in front of it and[BR]
	press [A].[Wait][End]
}

#message:27:(Shop_06_MAC00) {
	[Next]
	You don't appear to have any[BR]
	items.[Wait][End]
}

#message:27:(Shop_07_MAC00) {
	[Next]
	Which item would you like to sell?[Wait][End]
}

#message:27:(Shop_08_MAC00) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2]. [BR]
	Do we have a deal?[BR]
	[Yield][End]
}

#message:27:(Shop_09_MAC00) {
	[Style right]
	Oh, OK.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_MAC00) {
	[Style right]
	Thank you very much.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_MAC00) {
	[Style right]
	Thank you very much.[Wait][End]
}

#message:27:(Shop_0C_MAC00) {
	[Next]
	You don't seem to have any[BR]
	items.[Wait][End]
}

#message:27:(Shop_0D_MAC00) {
	[Next]
	I'm sorry, but we can't check[BR]
	any more items.[Wait][End]
}

#message:27:(Shop_0E_MAC00) {
	[Next]
	We can check [Var 0] more item[Var 1].[BR]
	What would you like to check?[BR]
	[Wait][End]
}

#message:27:(Shop_0F_MAC00) {
	[Style right]
	OK, we'll take good care of it.[Wait][End]
}

#message:27:(Shop_10_MAC00) {
	[Style right]
	OK, we'll take good care of it.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	us to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_MAC00) {
	[Next]
	Oh?[BR]
	[Pause 5]I'm sorry--we aren't holding[BR]
	anything for you.[Wait][End]
}

#message:27:(Shop_12_MAC00) {
	[Next]
	You can't carry any more items[BR]
	right now.[BR]
	[Wait][Next]
	Please come back after selling [BR]
	or using some items.[Wait][End]
}

#message:27:(Shop_13_MAC00) {
	[Next]
	Which item would you like to claim?[Wait][End]
}

#message:27:(Shop_14_MAC00) {
	[Style right]
	This is the item.[Wait][End]
}

#message:27:(Shop_15_MAC00) {
	[Style right]
	OK, this is the item.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	to claim?[BR]
	[Yield][End]
}

#message:27:(Shop_16_MAC00) {
	[Style right]
	[Next]
	Please come again.[Wait][End]
}

#message:27:(Shop_00_MAC01) {
	[Style right]
	Uh-huh![BR]
	[Pause 10]I knew it, Mario.[BR]
	[Wait][Next]
	I knew you had an keen eye for[BR]
	Badges.[BR]
	That's a good one.[BR]
	[Wait][Next]
	You need [Var 1] coins for [BR]
	"[Var 0]".[BR]
	[Wait][Next]
	The BP you need in order to use[BR]
	this Badge is "[Var 2]".[BR]
	[Wait][Next]
	Would you like to buy it?[BR]
	[Yield][End]
}

#message:27:(Shop_01_MAC01) {
	[Next]
	Sorry, Mario, but[BR]
	[Pause 10]you don't have quite enough coins[BR]
	to buy that Badge.[Wait][End]
}

#message:27:(Shop_03_MAC01) {
	[Next]
	Thanks![BR]
	[Wait][Next]
	I change my stock of Badges[BR]
	now and then, so please check [BR]
	back occasionally.[Wait][End]
}

#message:27:(Shop_16_MAC01) {
	[Style right]
	[Next]
	I change my stock of Badges[BR]
	now and then, so please check [BR]
	back occasionally.[BR]
	[Wait][Next]
	You never know when you'll find[BR]
	a real winner![Wait][End]
}

#message:27:(Shop_00_MAC04) {
	[Style right]
	You need [Var 1] coin[Var 2] for[BR]
	"[Var 0]". [BR]
	Want to buy it?[BR]
	[Yield][End]
}

#message:27:(Shop_01_MAC04) {
	[Next]
	You don't have enough coins![Wait][End]
}

#message:27:(Shop_02_MAC04) {
	[Next]
	You seem to have too many items.[BR]
	[Wait][Next]
	Please drop by again after [BR]
	selling, checking, or using some[BR]
	items.[Wait][End]
}

#message:27:(Shop_03_MAC04) {
	[Next]
	Thank you so much.[Wait][End]
}

#message:27:(Shop_04_MAC04) {
	[Style right]
	Welcome to Harry's Shop.[BR]
	[Wait][Next]
	How can I help you today?[BR]
	[Yield][End]
}

#message:27:(Shop_05_MAC04) {
	[Next]
	If there's anything you want to[BR]
	buy, stand in front of it and[BR]
	press [A].[Wait][End]
}

#message:27:(Shop_06_MAC04) {
	[Next]
	You don't seem to have any[BR]
	items.[Wait][End]
}

#message:27:(Shop_07_MAC04) {
	[Next]
	Which item would you like to sell[BR]
	today?[Wait][End]
}

#message:27:(Shop_08_MAC04) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2].[BR]
	Is that OK with you?[BR]
	[Yield][End]
}

#message:27:(Shop_09_MAC04) {
	[Style right]
	Oh, all right.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_MAC04) {
	[Style right]
	Thank you very much.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_MAC04) {
	[Style right]
	Thank you very much.[Wait][End]
}

#message:27:(Shop_0C_MAC04) {
	[Next]
	You don't seem to have any [BR]
	items.[Wait][End]
}

#message:27:(Shop_0D_MAC04) {
	[Next]
	I am sorry, but we can't check[BR]
	any more items.[Wait][End]
}

#message:27:(Shop_0E_MAC04) {
	[Next]
	We can check [Var 0] more item[Var 1]. [BR]
	What would you like to check?[Wait][End]
}

#message:27:(Shop_0F_MAC04) {
	[Style right]
	We'll store it with extra care.[Wait][End]
}

#message:27:(Shop_10_MAC04) {
	[Style right]
	We'll store it with extra care.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	us to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_MAC04) {
	[Next]
	You do?[BR]
	[Pause 5]But we're not keeping anything [BR]
	for you.[Wait][End]
}

#message:27:(Shop_12_MAC04) {
	[Next]
	You can't carry any more items[BR]
	right now.[BR]
	[Wait][Next]
	Please drop by again after[BR]
	selling or using some items.[Wait][End]
}

#message:27:(Shop_13_MAC04) {
	[Next]
	Which one would you like to claim?[Wait][End]
}

#message:27:(Shop_14_MAC04) {
	[Style right]
	Here's the item.[Wait][End]
}

#message:27:(Shop_15_MAC04) {
	[Style right]
	Here's the item.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	to claim?[BR]
	[Yield][End]
}

#message:27:(Shop_16_MAC04) {
	[Style right]
	[Next]
	Please drop by again.[Wait][End]
}

#message:27:(Shop_00_NOK01) {
	[Style right]
	"[Var 0]" costs [Var 1] coin[Var 2].  [BR]
	Are you buying?[BR]
	[Yield][End]
}

#message:27:(Shop_01_NOK01) {
	[Next]
	Hmmm. Sorry.[BR]
	[Pause 5]You don't have enough coins.[BR]
	[Pause 10]Come again after saving up a[BR]
	few more coins.[Wait][End]
}

#message:27:(Shop_02_NOK01) {
	[Next]
	I think you have too many items[BR]
	with you.[BR]
	[Wait][Next]
	You need to sell, check, or use[BR]
	some items.[Wait][End]
}

#message:27:(Shop_03_NOK01) {
	[Next]
	Thank you!![Wait][End]
}

#message:27:(Shop_04_NOK01) {
	[Style right]
	Welcome![BR]
	[Pause 10]This is the reliable and credible[BR]
	Koopa's Shop![BR]
	[Wait][Next]
	Well, what do you want?[BR]
	[Yield][End]
}

#message:27:(Shop_05_NOK01) {
	[Next]
	If you came here to shop, stand[BR]
	in front of the item you want to[BR]
	buy and press [A].[Wait][End]
}

#message:27:(Shop_06_NOK01) {
	[Next]
	Hey, you don't have any items[BR]
	at all![Wait][End]
}

#message:27:(Shop_07_NOK01) {
	[Next]
	So, which item do you want to[BR]
	sell me?[Wait][End]
}

#message:27:(Shop_08_NOK01) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2].  [BR]
	Do you want to sell it?[BR]
	[Yield][End]
}

#message:27:(Shop_09_NOK01) {
	[Style right]
	So...[BR]
	[Pause 5]are there any other items you [BR]
	want to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_NOK01) {
	[Style right]
	Thank you!![BR]
	[Pause 5]Are there any more items you [BR]
	want to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_NOK01) {
	[Style right]
	Thank you!![Wait][End]
}

#message:27:(Shop_0C_NOK01) {
	[Next]
	Hey, you don't have any items [BR]
	at all![Wait][End]
}

#message:27:(Shop_0D_NOK01) {
	[Next]
	Sorry, but I can't possibly store[BR]
	any more items.[Wait][End]
}

#message:27:(Shop_0E_NOK01) {
	[Next]
	I can check [Var 0] more item[Var 1].[BR]
	What do you want to check?[Wait][End]
}

#message:27:(Shop_0F_NOK01) {
	[Style right]
	OK, I'll hang on to it for you.[Wait][End]
}

#message:27:(Shop_10_NOK01) {
	[Style right]
	OK, I'll hang on to it for you.[BR]
	[Wait][Next]
	Do you want me to store[BR]
	anything else?[BR]
	[Yield][End]
}

#message:27:(Shop_11_NOK01) {
	[Next]
	Yes?[BR]
	[Pause 5]You didn't store anything.[Wait][End]
}

#message:27:(Shop_12_NOK01) {
	[Next]
	Hey, you couldn't possibly carry[BR]
	anything else.[BR]
	[Wait][Next]
	Come back after selling or using[BR]
	some items.[Wait][End]
}

#message:27:(Shop_13_NOK01) {
	[Next]
	What do you want to pick up?[Wait][End]
}

#message:27:(Shop_14_NOK01) {
	[Style right]
	Then here it is.[Wait][End]
}

#message:27:(Shop_15_NOK01) {
	[Style right]
	Then here it is.[BR]
	[Wait][Next]
	Do you want to pick up anything[BR]
	else?[BR]
	[Yield][End]
}

#message:27:(Shop_16_NOK01) {
	[Style right]
	[Next]
	I hope to see you again.[Wait][End]
}

#message:27:(Shop_00_DR001) {
	[Style right]
	"[Var 0]" will be [Var 1] coin[Var 2], [BR]
	but are you sure you want it? [BR]
	[Yield][End]
}

#message:27:(Shop_01_DR001) {
	[Next]
	Hey, hey, hold up.[BR]
	[Pause 5]You need a few more coins to buy[BR]
	that one.[Wait][End]
}

#message:27:(Shop_02_DR001) {
	[Next]
	You're already carrying a full[BR]
	load.[BR]
	[Wait][Next]
	Come back after using, selling,[BR]
	or checking some items.[Wait][End]
}

#message:27:(Shop_03_DR001) {
	[Next]
	All right![BR]
	[Pause 5]Thanks!![Wait][End]
}

#message:27:(Shop_04_DR001) {
	[Style right]
	Welcome, traveler![BR]
	[Wait][Next]
	This is the renowned Little[BR]
	Mouser's Shop of Dry Dry[BR]
	Outpost.[BR]
	[Wait][Next]
	What can we interest you in?[BR]
	[Yield][End]
}

#message:27:(Shop_05_DR001) {
	[Next]
	All right![BR]
	[Pause 10]So you want to spend some loot.[BR]
	Stand in front of the item you[BR]
	want to buy, then press [A].[BR]
	[Wait][Next]
	I'm proud to offer quality items[BR]
	at low, low prices![BR]
	[Pause 10]No other shop can compare with[BR]
	my prices![Wait][End]
}

#message:27:(Shop_06_DR001) {
	[Next]
	What?[BR]
	[Pause 10]You can't sell me items that you[BR]
	don't have![Wait][End]
}

#message:27:(Shop_07_DR001) {
	[Next]
	Which one do you want to sell?[Wait][End]
}

#message:27:(Shop_08_DR001) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2]. [BR]
	Are you sure you want to sell it?[BR]
	[Yield][End]
}

#message:27:(Shop_09_DR001) {
	[Style right]
	Okay.[BR]
	[Pause 5]Is there any other item you want[BR]
	to sell me?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_DR001) {
	[Style right]
	Thanks![BR]
	[Pause 5]Is there any other item you want[BR]
	to sell me?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_DR001) {
	[Style right]
	Thanks![Wait][End]
}

#message:27:(Shop_0C_DR001) {
	[Next]
	What?[BR]
	[Pause 10]Hey, I can't check items that[BR]
	don't exist.[Wait][End]
}

#message:27:(Shop_0D_DR001) {
	[Next]
	I can't check any more.[BR]
	[Pause 10]Sorry. The storeroom's packed.[Wait][End]
}

#message:27:(Shop_0E_DR001) {
	[Next]
	I can check [Var 0] more item[Var 1].[BR]
	What do you want to check?[Wait][End]
}

#message:27:(Shop_0F_DR001) {
	[Style right]
	All right.[BR]
	[Pause 10]I'll stash it for you.[Wait][End]
}

#message:27:(Shop_10_DR001) {
	[Style right]
	All right.[BR]
	[Pause 10]I'll stash it for you.[BR]
	[Wait][Next]
	Do you want to leave anything [BR]
	else?[BR]
	[Yield][End]
}

#message:27:(Shop_11_DR001) {
	[Next]
	Hang on there![BR]
	[Pause 5]I'm not holding anything.[BR]
	[Wait][Next]
	Don't try to claim things you[BR]
	haven't checked.[Wait][End]
}

#message:27:(Shop_12_DR001) {
	[Next]
	You're already carrying a full[BR]
	load.[BR]
	[Wait][Next]
	Come to me after selling or using[BR]
	some items.[Wait][End]
}

#message:27:(Shop_13_DR001) {
	[Next]
	So, which one do you want back?[Wait][End]
}

#message:27:(Shop_14_DR001) {
	[Style right]
	Here you are.[Wait][End]
}

#message:27:(Shop_15_DR001) {
	[Style right]
	Here you are.[BR]
	[Wait][Next]
	Do you want anything else back?[BR]
	[Yield][End]
}

#message:27:(Shop_16_DR001) {
	[Style right]
	[Next]
	I look forward to seeing you[BR]
	again.[Wait][End]
}

#message:27:(Shop_00_OBK03) {
	[Style right]
	You need [Var 1] coin[Var 2] for[BR]
	"[Var 0]", [BR]
	but are you sure?[BR]
	[Yield][End]
}

#message:27:(Shop_01_OBK03) {
	[Next]
	You don't have enough coins![Wait][End]
}

#message:27:(Shop_02_OBK03) {
	[Next]
	You're carrying too much as it is.[BR]
	[Wait][Next]
	Why don't you come back after [BR]
	selling, checking, or using some[BR]
	items?[Wait][End]
}

#message:27:(Shop_03_OBK03) {
	[Next]
	Boo you very much.[Wait][End]
}

#message:27:(Shop_04_OBK03) {
	[Style right]
	Welcome to Boo's Shop.[BR]
	[Wait][Next]
	How can I scare you today?[BR]
	[Yield][End]
}

#message:27:(Shop_05_OBK03) {
	[Next]
	If there's anything you want to[BR]
	buy, stand in front of it and[BR]
	press [A].[Wait][End]
}

#message:27:(Shop_06_OBK03) {
	[Next]
	You don't seem to have anything,[BR]
	so...BOO![Wait][End]
}

#message:27:(Shop_07_OBK03) {
	[Next]
	Which one would you like to sell?[Wait][End]
}

#message:27:(Shop_08_OBK03) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2]. [BR]
	How does that sound?[BR]
	[Yield][End]
}

#message:27:(Shop_09_OBK03) {
	[Style right]
	All right, all right.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_OBK03) {
	[Style right]
	Boo you very much.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_OBK03) {
	[Style right]
	Boo you very much.[Wait][End]
}

#message:27:(Shop_0C_OBK03) {
	[Next]
	You don't seem to have any items[BR]
	so...BOO![Wait][End]
}

#message:27:(Shop_0D_OBK03) {
	[Next]
	I'm sorry, but we can't possibly[BR]
	keep any more items.[Wait][End]
}

#message:27:(Shop_0E_OBK03) {
	[Next]
	We can check [Var 0] more item[Var 1].[BR]
	What would you like to check?[Wait][End]
}

#message:27:(Shop_0F_OBK03) {
	[Style right]
	OK, we will keep it safe.[Wait][End]
}

#message:27:(Shop_10_OBK03) {
	[Style right]
	OK, we will keep it safe.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	us to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_OBK03) {
	[Next]
	Say what?[BR]
	[Pause 5]We aren't keeping anything for[BR]
	you, so...BOO![Wait][End]
}

#message:27:(Shop_12_OBK03) {
	[Next]
	You're carrying too much as it is.[BR]
	[Wait][Next]
	Come on back after selling or[BR]
	using some items.[Wait][End]
}

#message:27:(Shop_13_OBK03) {
	[Next]
	Which one would you like to claim?[Wait][End]
}

#message:27:(Shop_14_OBK03) {
	[Style right]
	Here you go.[Wait][End]
}

#message:27:(Shop_15_OBK03) {
	[Style right]
	Here you go.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	to claim?[BR]
	[Yield][End]
}

#message:27:(Shop_16_OBK03) {
	[Style right]
	[Next]
	Come back anytime.[Wait][End]
}

#message:27:(Shop_00_JAN03) {
	[Style right]
	You need [Var 1] coin[Var 2] for[BR]
	"[Var 0]". [BR]
	Sound OK to you?[BR]
	[Yield][End]
}

#message:27:(Shop_01_JAN03) {
	[Next]
	Aw, you need more coins![Wait][End]
}

#message:27:(Shop_02_JAN03) {
	[Next]
	You can't carry any more stuff.[BR]
	[Wait][Next]
	Please come again after selling,[BR]
	checking, or using some items.[Wait][End]
}

#message:27:(Shop_03_JAN03) {
	[Next]
	Thank you very much.[Wait][End]
}

#message:27:(Shop_04_JAN03) {
	[Style right]
	Welcome to Yoshi's Cabana.[BR]
	[Wait][Next]
	What's your pleasure?[BR]
	[Yield][End]
}

#message:27:(Shop_05_JAN03) {
	[Next]
	If there's anything you want to[BR]
	buy, stand in front of it and[BR]
	press [A].[Wait][End]
}

#message:27:(Shop_06_JAN03) {
	[Next]
	Uh...it doesn't look like you have[BR]
	any items.[Wait][End]
}

#message:27:(Shop_07_JAN03) {
	[Next]
	Which one would you like to sell?[Wait][End]
}

#message:27:(Shop_08_JAN03) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2]. [BR]
	Sound OK to you?[BR]
	[Yield][End]
}

#message:27:(Shop_09_JAN03) {
	[Style right]
	OK, fair enough.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_JAN03) {
	[Style right]
	Thank you very much.[BR]
	[Pause 5]Is there anything else you'd like[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_JAN03) {
	[Style right]
	Thank you very much.[Wait][End]
}

#message:27:(Shop_0C_JAN03) {
	[Next]
	Uh...it doesn't look like you have[BR]
	any items.[Wait][End]
}

#message:27:(Shop_0D_JAN03) {
	[Next]
	I am deeply sorry, but we can't[BR]
	keep any more items.[Wait][End]
}

#message:27:(Shop_0E_JAN03) {
	[Next]
	We can check [Var 0] more item[Var 1].[BR]
	What would you like to check?[Wait][End]
}

#message:27:(Shop_0F_JAN03) {
	[Style right]
	OK, we'll store it carefully.[Wait][End]
}

#message:27:(Shop_10_JAN03) {
	[Style right]
	OK, we'll store it carefully.[BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	us to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_JAN03) {
	[Next]
	Oh? You must be mistaken.[BR]
	[Pause 5]We don't have anything of yours.[Wait][End]
}

#message:27:(Shop_12_JAN03) {
	[Next]
	You can't carry any more stuff.[BR]
	[Wait][Next]
	Please come again after selling [BR]
	or using some items.[Wait][End]
}

#message:27:(Shop_13_JAN03) {
	[Next]
	Which one would you like to claim?[Wait][End]
}

#message:27:(Shop_14_JAN03) {
	[Style right]
	There you go![Wait][End]
}

#message:27:(Shop_15_JAN03) {
	[Style right]
	There you go![BR]
	[Wait][Next]
	Is there anything else you'd like[BR]
	to claim?[BR]
	[Yield][End]
}

#message:27:(Shop_16_JAN03) {
	[Style right]
	[Next]
	Please come back often.[Wait][End]
}

#message:27:(Shop_00_SAM02) {
	[Style right]
	You need [Var 1] coin[Var 2] for[BR]
	"[Var 0]".[BR]
	Is that cool with you?[BR]
	[Yield][End]
}

#message:27:(Shop_01_SAM02) {
	[Next]
	Hey! You can't afford that![Wait][End]
}

#message:27:(Shop_02_SAM02) {
	[Next]
	You're packed a little heavy.[BR]
	[Wait][Next]
	Please come again after selling,[BR]
	checking, or using some items.[Wait][End]
}

#message:27:(Shop_03_SAM02) {
	[Next]
	Many thanks.[Wait][End]
}

#message:27:(Shop_04_SAM02) {
	[Style right]
	Welcome to Shiver Shop.[BR]
	[Wait][Next]
	How can I help you today?[BR]
	[Yield][End]
}

#message:27:(Shop_05_SAM02) {
	[Next]
	If there's anything you want to[BR]
	buy, stand in front of it and[BR]
	press [A].[Wait][End]
}

#message:27:(Shop_06_SAM02) {
	[Next]
	You need to own items in order[BR]
	to sell them.[Wait][End]
}

#message:27:(Shop_07_SAM02) {
	[Next]
	Which one would you like to sell?[Wait][End]
}

#message:27:(Shop_08_SAM02) {
	[Style right]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2].[BR]
	Is that cool with you?[BR]
	[Yield][End]
}

#message:27:(Shop_09_SAM02) {
	[Style right]
	All right, chill out.[BR]
	[Pause 5]Is there anything else you want[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_SAM02) {
	[Style right]
	Thank you very much.[BR]
	[Pause 5]Is there anything else you want[BR]
	to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_SAM02) {
	[Style right]
	Thank you very much.[Wait][End]
}

#message:27:(Shop_0C_SAM02) {
	[Next]
	You have to own some items in[BR]
	order to check them.[Wait][End]
}

#message:27:(Shop_0D_SAM02) {
	[Next]
	I am sorry, but we have no more[BR]
	room for items.[Wait][End]
}

#message:27:(Shop_0E_SAM02) {
	[Next]
	We can check [Var 0] more item[Var 1].[BR]
	What would you like to check?[Wait][End]
}

#message:27:(Shop_0F_SAM02) {
	[Style right]
	OK, we'll put it in deep freeze.[Wait][End]
}

#message:27:(Shop_10_SAM02) {
	[Style right]
	OK, we'll put it in deep freeze.[BR]
	[Wait][Next]
	Is there anything else you would[BR]
	like us to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_SAM02) {
	[Next]
	Excuse me?[BR]
	[Pause 5]But we aren't keeping anything [BR]
	for you![Wait][End]
}

#message:27:(Shop_12_SAM02) {
	[Next]
	You're packed a little heavy.[BR]
	[Wait][Next]
	Please come again after selling [BR]
	or using some items.[Wait][End]
}

#message:27:(Shop_13_SAM02) {
	[Next]
	Which one would you like to claim?[Wait][End]
}

#message:27:(Shop_14_SAM02) {
	[Style right]
	Here it is![Wait][End]
}

#message:27:(Shop_15_SAM02) {
	[Style right]
	Here it is![BR]
	[Wait][Next]
	Is there anything else you want[BR]
	to claim?[BR]
	[Yield][End]
}

#message:27:(Shop_16_SAM02) {
	[Style right]
	[Next]
	Come chill out anytime![Wait][End]
}

#message:27:(Shop_00_HOS03) {
	[Style right]
	[Voice star]
	You need [Var 1] coin[Var 2] for[BR]
	"[Var 0]". [BR]
	Is that agreeable?[BR]
	[Yield][End]
}

#message:27:(Shop_01_HOS03) {
	[Voice star]
	[Next]
	You lack the funds. I'm sorry.[Wait][End]
}

#message:27:(Shop_02_HOS03) {
	[Voice star]
	[Next]
	You seem to have too many items.[BR]
	[Wait][Next]
	Please return after selling,[BR]
	checking, or using some items.[Wait][End]
}

#message:27:(Shop_03_HOS03) {
	[Voice star]
	[Next]
	Thank you kindly.[Wait][End]
}

#message:27:(Shop_04_HOS03) {
	[Style right]
	[Voice star]
	Welcome to Star Haven Shop.[BR]
	[Wait][Next]
	What is your wish?[BR]
	[Yield][End]
}

#message:27:(Shop_05_HOS03) {
	[Voice star]
	[Next]
	If there's anything you want to[BR]
	buy, stand in front of it and[BR]
	press [A].[Wait][End]
}

#message:27:(Shop_06_HOS03) {
	[Voice star]
	[Next]
	It would appear that you have[BR]
	no items.[Wait][End]
}

#message:27:(Shop_07_HOS03) {
	[Voice star]
	[Next]
	Which one would you like to sell?[Wait][End]
}

#message:27:(Shop_08_HOS03) {
	[Style right]
	[Voice star]
	[Next]
	I'll buy "[Var 0]" for[BR]
	[Var 1] coin[Var 2].[BR]
	Is that agreeable?[BR]
	[Yield][End]
}

#message:27:(Shop_09_HOS03) {
	[Style right]
	[Voice star]
	Oh. I understand.[BR]
	[Pause 5]Is there anything else you would[BR]
	like to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_HOS03) {
	[Style right]
	[Voice star]
	Thank you kindly.[BR]
	[Pause 5]Is there anything else you would[BR]
	like to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_HOS03) {
	[Style right]
	[Voice star]
	Thank you kindly.[Wait][End]
}

#message:27:(Shop_0C_HOS03) {
	[Voice star]
	[Next]
	It appears that you have no[BR]
	items.[Wait][End]
}

#message:27:(Shop_0D_HOS03) {
	[Voice star]
	[Next]
	I am sorry, but we have reached[BR]
	our storage capacity.[Wait][End]
}

#message:27:(Shop_0E_HOS03) {
	[Voice star]
	[Next]
	We can check [Var 0] more item[Var 1], [BR]
	but would you like us to do so?[Wait][End]
}

#message:27:(Shop_0F_HOS03) {
	[Style right]
	[Voice star]
	OK, we will take special care.[Wait][End]
}

#message:27:(Shop_10_HOS03) {
	[Style right]
	[Voice star]
	OK, we will take special care.[BR]
	[Wait][Next]
	Is there anything else you would[BR]
	like us to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_HOS03) {
	[Voice star]
	[Next]
	No, there must be a mistake.[BR]
	[Pause 5]We aren't holding anything for[BR]
	you.[Wait][End]
}

#message:27:(Shop_12_HOS03) {
	[Voice star]
	[Next]
	You seem to have too many items.[BR]
	[Wait][Next]
	Please return after selling or[BR]
	using some items.[Wait][End]
}

#message:27:(Shop_13_HOS03) {
	[Voice star]
	[Next]
	Which one would you like to claim?[Wait][End]
}

#message:27:(Shop_14_HOS03) {
	[Style right]
	[Voice star]
	Here you are. Enjoy![Wait][End]
}

#message:27:(Shop_15_HOS03) {
	[Style right]
	[Voice star]
	Here you are. Enjoy![BR]
	[Wait][Next]
	Is there anything else you would[BR]
	like to claim?[BR]
	[Yield][End]
}

#message:27:(Shop_16_HOS03) {
	[Style right]
	[Voice star]
	[Next]
	Please stop in again sometime.[Wait][End]
}

#message:27:(Shop_00_KPA96) {
	[Style right]
	"[Var 0]"?[BR]
	I'll give it to you if you give me[BR]
	[Var 1] coin[Var 2].[BR]
	[Yield][End]
}

#message:27:(Shop_01_KPA96) {
	[Next]
	Hey, man, you don't have the[BR]
	cash![Wait][End]
}

#message:27:(Shop_02_KPA96) {
	[Next]
	You're carrying too much, man.[BR]
	[Wait][Next]
	Come on back after selling, [BR]
	checking, or using some items.[Wait][End]
}

#message:27:(Shop_03_KPA96) {
	[Next]
	Heh-heh.[BR]
	[Pause 10]Thanks, man.[Wait][End]
}

#message:27:(Shop_04_KPA96) {
	[Style right]
	Yep.[BR]
	[Pause 10]This is the Storehouse of [BR]
	Bowser's Castle.[BR]
	[Wait][Next]
	Why in the world are you here?[BR]
	[Yield][End]
}

#message:27:(Shop_05_KPA96) {
	[Next]
	Go on and press [A] in front of[BR]
	the item you want.[Wait][End]
}

#message:27:(Shop_06_KPA96) {
	[Next]
	You can't sell nothing, pal![Wait][End]
}

#message:27:(Shop_07_KPA96) {
	[Next]
	So, what do you want to sell,[BR]
	huh?[Wait][End]
}

#message:27:(Shop_08_KPA96) {
	[Style right]
	[Next]
	I'll trade "[Var 0]" for [BR]
	[Var 1] coin[Var 2].[BR]
	[Yield][End]
}

#message:27:(Shop_09_KPA96) {
	[Style right]
	Fine. I don't care.[BR]
	[Pause 5]Anything else you want to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0A_KPA96) {
	[Style right]
	Heh-heh.[BR]
	[Pause 10]Good deal, man.[BR]
	[Wait][Next]
	[Pause 5]Anything else you want to sell?[BR]
	[Yield][End]
}

#message:27:(Shop_0B_KPA96) {
	[Style right]
	Heh-heh.[BR]
	[Pause 10]Good deal, man.[Wait][End]
}

#message:27:(Shop_0C_KPA96) {
	[Next]
	Hey! You don't have anything![Wait][End]
}

#message:27:(Shop_0D_KPA96) {
	[Next]
	I ran out of storage space.[Wait][End]
}

#message:27:(Shop_0E_KPA96) {
	[Next]
	I can hold on to [Var 0] more item[Var 1].[BR]
	What do you want me to hold?[Wait][End]
}

#message:27:(Shop_0F_KPA96) {
	[Style right]
	All right, then. I'll keep it.[Wait][End]
}

#message:27:(Shop_10_KPA96) {
	[Style right]
	All right, then. I'll keep it.[BR]
	[Wait][Next]
	Anything else to check?[BR]
	[Yield][End]
}

#message:27:(Shop_11_KPA96) {
	[Next]
	Don't try to fool me, pal![BR]
	[Pause 5]You know you don't have any[BR]
	items in storage![Wait][End]
}

#message:27:(Shop_12_KPA96) {
	[Next]
	You're carrying too much, man.[BR]
	[Wait][Next]
	Come back after selling or using[BR]
	some items.[Wait][End]
}

#message:27:(Shop_13_KPA96) {
	[Next]
	Which one do you want?[Wait][End]
}

#message:27:(Shop_14_KPA96) {
	[Style right]
	Here you go, man.[Wait][End]
}

#message:27:(Shop_15_KPA96) {
	[Style right]
	Here you go, man.[BR]
	[Wait][Next]
	You want anything else?[BR]
	[Yield][End]
}

#message:27:(Shop_16_KPA96) {
	[Style right]
	[Next]
	Hey! Don't tell King Bowser[BR]
	about any of this![Wait][End]
}

#message:27:(Shop_PortableStorage_Greeting_FirstTime) {
	[Style right]
	Hi, Mario![BR]
	I'm one of the many Boos[BR]
	responsible for running the[BR]
	Portable Item Network![BR]
	[Wait][Next]
	If you've ever wondered how[BR]
	you can store items in one[BR]
	shop, and retrieve them in[BR]
	another, well, we're how![BR]
	[Wait][Next]
	If you wish to store, sell[BR]
	or claim some items, I can[BR]
	help with that.[BR]
	[Yield][End]
}

#message:27:(Shop_PortableStorage_Greeting_Normal) {
	[Style right]
	Boo from the Portable Item[BR]
	Network here, what would you[BR]
	like to do?[BR]
	[Yield][End]
}

#message:27:(Shop_PortableStorage_NotEnoughRoom) {
	[Next]
	You're carrying too much![BR]
	[Wait][Next]
	Come on back after selling,[BR]
	checking, or using some items.[Wait][End]
}

#message:27:(Shop_PortableStorage_NothingToSell) {
	[Next]
	You have nothing to sell,[BR]
	I'm afraid.[Wait][End]
}

#message:27:(Shop_PortableStorage_WhatToSell) {
	[Next]
	So, what would you like to sell?[Wait][End]
}

#message:27:(Shop_PortableStorage_NothingToCheck) {
	[Next]
	You have nothing to store,[BR]
	I'm afraid.[Wait][End]
}

#message:27:(Shop_PortableStorage_NoCheckRoom) {
	[Next]
	Whoa, hold on![BR]
	You have too many items in[BR]
	the Network already![Wait][End]
}

#message:27:(Shop_PortableStorage_StoreWhich) {
	[Next]
	We can hold on to [Var 0] more item[Var 1].[BR]
	What do you want us to hold?[Wait][End]
}

#message:27:(Shop_PortableStorage_NothingToClaim) {
	[Next]
	You have nothing in the Network.[BR]
	Try storing some items first![Wait][End]
}

#message:27:(Shop_PortableStorage_NoClaimSpace) {
	[Next]
	You're carrying too much.[BR]
	Come back after selling or using[BR]
	some items.[Wait][End]
}

#message:27:(Shop_PortableStorage_ClaimWhich) {
	[Next]
	Which item would you like?[Wait][End]
}

#message:27:(Shop_PortableStorage_Farewell) {
	[Style right]
	[Next]
	'Till we meet again![BR]
	[Wait][End]
}
