#message:2A:(PlayerMoveName_PowerJump) {
	Power Jump[End]
}

#message:2A:(PlayerMoveName_MegaJump) {
	Mega Jump[End]
}

#message:2A:(PlayerMoveName_JumpCharge) {
	Charge[End]
}

#message:2A:(PlayerMoveName_SuperJumpCharge) {
	Super Charge[End]
}

#message:2A:(PlayerMoveName_SleepStomp) {
	Sleep Stomp[End]
}

#message:2A:(PlayerMoveName_DizzyStomp) {
	Dizzy Stomp[End]
}

#message:2A:(PlayerMoveName_Multibounce) {
	Multibounce[End]
}

#message:2A:(PlayerMoveName_ShrinkStomp) {
	Shrink Stomp[End]
}

#message:2A:(PlayerMoveName_DDownJump) {
	D-Down Jump[End]
}

#message:2A:(PlayerMoveName_PowerBounce) {
	Power Bounce[End]
}

#message:2A:(PlayerMoveName_PowerSmash) {
	Power Smash[End]
}

#message:2A:(PlayerMoveName_MegaSmash) {
	Mega Smash[End]
}

#message:2A:(PlayerMoveName_SmashCharge) {
	Charge[End]
}

#message:2A:(PlayerMoveName_SuperSmashCharge) {
	Super Charge[End]
}

#message:2A:(PlayerMoveName_HammerThrow) {
	Hammer Throw[End]
}

#message:2A:(PlayerMoveName_ShrinkSmash) {
	Shrink Smash[End]
}

#message:2A:(PlayerMoveName_SpinSmash) {
	Spin Smash[End]
}

#message:2A:(PlayerMoveName_DDownPound) {
	D-Down Pound[End]
}

#message:2A:(PlayerMoveName_QuakeHammer) {
	Quake Hammer[End]
}

#message:2A:(PlayerMoveName_PowerQuake) {
	Power Quake[End]
}

#message:2A:(PlayerMoveName_MegaQuake) {
	Mega Quake[End]
}

#message:2A:(PlayerMoveName_DoubleDip) {
	Double Dip[End]
}

#message:2A:(PlayerMoveName_TripleDip) {
	Triple Dip[End]
}

#message:2A:(PlayerMoveName_GroupFocus) {
	Group Focus[End]
}

#message:2A:(PlayerMoveName_QuickChange) {
	Quick Change[End]
}

#message:2A:(PlayerMoveName_PUpDDown) {
	P-Up & D-Down[End]
}

#message:2A:(PlayerMoveName_PDownDUp) {
	P-Down & D-Up[End]
}

#message:2A:(PlayerMoveName_PoisonThrow) {
	Poison Throw[End]
}
