#message:2B:(PartnerMoveName_Headbonk) {
	Headbonk[End]
}

#message:2B:(PartnerMoveName_Tattle) {
	Tattle[End]
}

#message:2B:(PartnerMoveName_Charge) {
	Charge[End]
}

#message:2B:(PartnerMoveName_Multibonk) {
	Multibonk[End]
}

#message:2B:(PartnerMoveName_ShellToss) {
	Shell Toss[End]
}

#message:2B:(PartnerMoveName_PowerShell) {
	Power Shell[End]
}

#message:2B:(PartnerMoveName_DizzyShell) {
	Dizzy Shell[End]
}

#message:2B:(PartnerMoveName_FireShell) {
	Fire Shell[End]
}

#message:2B:(PartnerMoveName_BodySlam) {
	Body Slam[End]
}

#message:2B:(PartnerMoveName_Bomb) {
	Bomb[End]
}

#message:2B:(PartnerMoveName_PowerBomb) {
	Power Bomb[End]
}

#message:2B:(PartnerMoveName_MegaBomb) {
	Mega Bomb[End]
}

#message:2B:(PartnerMoveName_SkyDive) {
	Sky Dive[End]
}

#message:2B:(PartnerMoveName_ShellShot) {
	Shell Shot[End]
}

#message:2B:(PartnerMoveName_AirLift) {
	Air Lift[End]
}

#message:2B:(PartnerMoveName_AirRaid) {
	Air Raid[End]
}

#message:2B:(PartnerMoveName_Smack) {
	Smack[End]
}

#message:2B:(PartnerMoveName_OuttaSight) {
	Outta Sight[End]
}

#message:2B:(PartnerMoveName_Spook) {
	Spook[End]
}

#message:2B:(PartnerMoveName_FanSmack) {
	Fan Smack[End]
}

#message:2B:(PartnerMoveName_ElectroDash) {
	Electro Dash[End]
}

#message:2B:(PartnerMoveName_PowerShock) {
	Power Shock[End]
}

#message:2B:(PartnerMoveName_TurboCharge) {
	Turbo Charge[End]
}

#message:2B:(PartnerMoveName_MegaShock) {
	Mega Shock[End]
}

#message:2B:(PartnerMoveName_BellyFlop) {
	Belly Flop[End]
}

#message:2B:(PartnerMoveName_Squirt) {
	Squirt[End]
}

#message:2B:(PartnerMoveName_WaterBlock) {
	Water Block[End]
}

#message:2B:(PartnerMoveName_TidalWave) {
	Tidal Wave[End]
}

#message:2B:(PartnerMoveName_SpinyFlip) {
	Spiny Flip[End]
}

#message:2B:(PartnerMoveName_SpinySurge) {
	Spiny Surge[End]
}

#message:2B:(PartnerMoveName_CloudNine) {
	Cloud Nine[End]
}

#message:2B:(PartnerMoveName_Hurricane) {
	Hurricane[End]
}
