#message:2C:(QuizQuestion_01) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Which item did Jr. Troopa hold[BR]
	when you first met him?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_02) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the first strike damage[BR]
	of your starting hammer?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_03) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Do you have to open the pause[BR]
	menu in order to see full[BR]
	item descriptions?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_04) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What's the maximum DEF[BR]
	obtainable during Prologue?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_05) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How much HP did the Goomba King[BR]
	have?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_06) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many windows does the[BR]
	Goomba House in Goomba Village[BR]
	have?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_07) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What's the name of the leader of[BR]
	the Red and Blue Goomba Bros.?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_08) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What color are Luigi's pants?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_09) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many members are there in[BR]
	Goombario's family?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_10) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What will you receive when you [BR]
	get the right answer in a quiz?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_11) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the smart[BR]
	Toad living in Toad Town?[BR]
	[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_12) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many buildings are there in[BR]
	Koopa Village?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_13) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Of the following, who is NOT a[BR]
	member of the Koopa Bros.?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_14) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many coins are needed to[BR]
	buy a Mushroom at the shop in[BR]
	Koopa Village?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_15) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Where does Merluvlee, who tells[BR]
	fortunes about special things,[BR]
	live?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_16) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the[BR]
	character who joined you at the[BR]
	Koopa Bros. Fortress?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_17) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What color is Bowser's hair?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_18) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many Star Spirits do you[BR]
	have to save?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_19) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What's the name of the elderly[BR]
	Koopa Troopa who always asks[BR]
	for errands to be run?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_20) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many Bob-ombs besides[BR]
	Bombette were imprisoned in the[BR]
	jail at the Koopa Bros.[BR]
	Fortress?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_21) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Where is the house of the[BR]
	explorer, Kolorado?[BR]
	[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_22) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the destination of the[BR]
	train which departs from Toad[BR]
	Town station?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_23) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the fellow[BR]
	who sells Badges in Toad Town?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_24) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What treasure did Bowser steal[BR]
	from Star Haven?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_25) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the color of the roof of[BR]
	the house in Koopa Village where[BR]
	you can listen to a radio?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_26) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who does Kooper idolize?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_27) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What does Merlee of Dry Dry [BR]
	Outpost specialize in? [BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_28) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who hides inside a coffin in Dry[BR]
	Dry Ruins?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_29) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What can you get when you take[BR]
	Star Pieces to Merlow at[BR]
	Shooting Star Summit?[BR]
	[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_30) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who knew the location of Dry Dry[BR]
	Ruins in Dry Dry Desert?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_31) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	When you want Tayce T., who[BR]
	loves cooking, to make Lemon [BR]
	Candy, what do you have to give[BR]
	her besides a Lemon?[BR]
	[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_32) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who among the following lives in[BR]
	Forever Forest?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_33) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What are Boos, exactly?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_34) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What appears when you hit the[BR]
	Whacka living on Mt. Rugged?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_35) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Other than Lemons, what fruit[BR]
	drops when you hit a tree in the[BR]
	desert oasis?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_36) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the strange[BR]
	person in Toad Town who can[BR]
	increase Mario's status?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_37) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What ability does Bombette[BR]
	frequently use?[BR]
	[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_38) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What does Gourmet Guy like?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_39) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who was the second companion to[BR]
	join your team?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_40) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who tried to steal coins from you[BR]
	in the desert? [BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_41) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the Star[BR]
	Spirit who can use Star Storm?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_42) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What are addressed to your [BR]
	companions and sent to the post[BR]
	office?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_43) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Among the following, which [BR]
	building is NOT in Toad Town?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_44) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What kind of book did Gourmet[BR]
	Guy drop?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_45) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who am I?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_46) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Where do I show up?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_47) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the plant[BR]
	that grows in Jade Jungle and[BR]
	blows out stars?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_48) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What color was the leader of [BR]
	Yoshi's Village?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_49) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the elderly[BR]
	man who tells fortunes in Toad[BR]
	Town?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_50) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many colors of Yoshis did[BR]
	you see in Yoshi's Village?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_51) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How would the Yoshi Kids in [BR]
	Yoshi's Village describe Sushie?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_52) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What building is across from the[BR]
	Toad Town post office?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_53) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What kind of card do you get[BR]
	when you defeat Lee at the Dojo[BR]
	in Toad Town?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_54) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What color is the brooch that[BR]
	Princess Peach wears?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_55) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Who gave you Miracle Water in[BR]
	Flower Fields?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_56) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of Lakilester's[BR]
	girlfriend?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_57) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How do you make the Pipe leading[BR]
	to the Toad Town Playroom come[BR]
	out?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_58) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Among the following, who is inside[BR]
	Club 64?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_59) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Which of the following do Shy[BR]
	Guys never do?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_60) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What best describes the[BR]
	relationship between Mario and[BR]
	Luigi?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_61) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	Among the following, who is found[BR]
	in Starborn Valley?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_62) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many companions do you[BR]
	travel with?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_63) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	What is the name of the Star Kid[BR]
	who's always with Princess[BR]
	Peach?[BR]
	[Yield][End]
}

#message:2C:(QuizQuestion_64) {
	[Style right]
	Question.[BR]
	[Wait][Next]
	How many Star Spirits have you[BR]
	saved in total?[BR]
	[Yield][End]
}
