#message:2D:(QuizChoice_01) {
	[Style choice pos=100,70 size=140,62]
	[DelayOff]
	[Cursor 0][Option 0]Mushroom[BR]
	[Cursor 1][Option 1]Thunder Rage[BR]
	[Cursor 2][Option 2]Thunder Bolt[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_02) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]1[BR]
	[Cursor 1][Option 1]2[BR]
	[Cursor 2][Option 2]3[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_03) {
	[Style choice pos=114,70 size=92,62]
	[DelayOff]
	[Cursor 0][Option 0]Yes[BR]
	[Cursor 1][Option 1]No[BR]
	[Cursor 2][Option 2]Idk[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_04) {
	[Style choice pos=86,70 size=148,62]
	[DelayOff]
	[Cursor 0][Option 0]One[BR]
	[Cursor 1][Option 1]Three[BR]
	[Cursor 2][Option 2]Four[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_05) {
	[Style choice pos=98,70 size=124,62]
	[DelayOff]
	[Cursor 0][Option 0]12[BR]
	[Cursor 1][Option 1]18[BR]
	[Cursor 2][Option 2]15[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_06) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]One[BR]
	[Cursor 1][Option 1]Two[BR]
	[Cursor 2][Option 2]Three[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_07) {
	[Style choice pos=95,70 size=130,62]
	[DelayOff]
	[Cursor 0][Option 0]Dr. Goomba[BR]
	[Cursor 1][Option 1]Big Goom[BR]
	[Cursor 2][Option 2]Goomba King[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_08) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]Blue[BR]
	[Cursor 1][Option 1]Green[BR]
	[Cursor 2][Option 2]Yellow[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_09) {
	[Style choice pos=121,70 size=78,62]
	[DelayOff]
	[Cursor 0][Option 0]Four[BR]
	[Cursor 1][Option 1]Five[BR]
	[Cursor 2][Option 2]Six[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_10) {
	[Style choice pos=99,70 size=122,62]
	[DelayOff]
	[Cursor 0][Option 0]It's me[HEART][BR]
	[Cursor 1][Option 1]Star Piece[BR]
	[Cursor 2][Option 2]Mushroom[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_11) {
	[Style choice pos=106,70 size=108,62]
	[DelayOff]
	[Cursor 0][Option 0]Russ T.[BR]
	[Cursor 1][Option 1]Smarr T.[BR]
	[Cursor 2][Option 2]Toace T.[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_12) {
	[Style choice pos=121,70 size=78,62]
	[DelayOff]
	[Cursor 0][Option 0]Four[BR]
	[Cursor 1][Option 1]Five[BR]
	[Cursor 2][Option 2]Six[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_13) {
	[Style choice pos=77,70 size=166,62]
	[DelayOff]
	[Cursor 0][Option 0]Red Ninjakoopa[BR]
	[Cursor 1][Option 1]Blue Ninjakoopa[BR]
	[Cursor 2][Option 2]Black Ninjakoopa[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_14) {
	[Style choice pos=112,70 size=96,62]
	[DelayOff]
	[Cursor 0][Option 0]2 coins[BR]
	[Cursor 1][Option 1]4 coins[BR]
	[Cursor 2][Option 2]8 coins[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_15) {
	[Style choice pos=62,70 size=196,62]
	[DelayOff]
	[Cursor 0][Option 0]Shooting Star Summit[BR]
	[Cursor 1][Option 1]Toad Town[BR]
	[Cursor 2][Option 2]Bowser's Castle[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_16) {
	[Style choice pos=103,70 size=114,62]
	[DelayOff]
	[Cursor 0][Option 0]Goombario[BR]
	[Cursor 1][Option 1]Kooper[BR]
	[Cursor 2][Option 2]Bombette[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_17) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]Red[BR]
	[Cursor 1][Option 1]Green[BR]
	[Cursor 2][Option 2]Yellow[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_18) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]One[BR]
	[Cursor 1][Option 1]Five[BR]
	[Cursor 2][Option 2]Seven[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_19) {
	[Style choice pos=97,70 size=126,62]
	[DelayOff]
	[Cursor 0][Option 0]Koopa Krab[BR]
	[Cursor 1][Option 1]Koopa Koot[BR]
	[Cursor 2][Option 2]Old Koop[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_20) {
	[Style choice pos=114,70 size=92,62]
	[DelayOff]
	[Cursor 0][Option 0]Four[BR]
	[Cursor 1][Option 1]Eight[BR]
	[Cursor 2][Option 2]Twelve[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_21) {
	[Style choice pos=87,70 size=146,62]
	[DelayOff]
	[Cursor 0][Option 0]Koopa Village[BR]
	[Cursor 1][Option 1]Toad Town[BR]
	[Cursor 2][Option 2]Goomba Village[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_22) {
	[Style choice pos=87,70 size=146,62]
	[DelayOff]
	[Cursor 0][Option 0]Goomba Village[BR]
	[Cursor 1][Option 1]Koopa Village[BR]
	[Cursor 2][Option 2]Mt. Rugged[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_23) {
	[Style choice pos=107,70 size=106,62]
	[DelayOff]
	[Cursor 0][Option 0]Merlow[BR]
	[Cursor 1][Option 1]Rowf[BR]
	[Cursor 2][Option 2]Kolorado[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_24) {
	[Style choice pos=83,70 size=154,62]
	[DelayOff]
	[Cursor 0][Option 0]Star Rod[BR]
	[Cursor 1][Option 1]Twink[BR]
	[Cursor 2][Option 2]Princess Peach[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_25) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]Red[BR]
	[Cursor 1][Option 1]Yellow[BR]
	[Cursor 2][Option 2]Blue[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_26) {
	[Style choice pos=98,70 size=124,62]
	[DelayOff]
	[Cursor 0][Option 0]Mario[BR]
	[Cursor 1][Option 1]Kolorado[BR]
	[Cursor 2][Option 2]Koopa Koot[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_27) {
	[Style choice pos=83,70 size=154,62]
	[DelayOff]
	[Cursor 0][Option 0]Fortune-telling[BR]
	[Cursor 1][Option 1]Casting spells[BR]
	[Cursor 2][Option 2]Cooking[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_28) {
	[Style choice pos=93,70 size=134,62]
	[DelayOff]
	[Cursor 0][Option 0]Mummy Man[BR]
	[Cursor 1][Option 1]Moustafa[BR]
	[Cursor 2][Option 2]Pokey Mummy[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_29) {
	[Style choice pos=112,70 size=96,62]
	[DelayOff]
	[Cursor 0][Option 0]Cards[BR]
	[Cursor 1][Option 1]Coins[BR]
	[Cursor 2][Option 2]Badges[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_30) {
	[Style choice pos=103,70 size=114,62]
	[DelayOff]
	[Cursor 0][Option 0]Kolorado[BR]
	[Cursor 1][Option 1]Moustafa[BR]
	[Cursor 2][Option 2]Goombario[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_31) {
	[Style choice pos=99,70 size=122,62]
	[DelayOff]
	[Cursor 0][Option 0]Star Piece[BR]
	[Cursor 1][Option 1]Cake Mix[BR]
	[Cursor 2][Option 2]Mushroom[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_32) {
	[Style choice pos=99,70 size=122,62]
	[DelayOff]
	[Cursor 0][Option 0]Jr. Troopa[BR]
	[Cursor 1][Option 1]Oaklie[BR]
	[Cursor 2][Option 2]Cleft[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_33) {
	[Style choice pos=111,70 size=98,62]
	[DelayOff]
	[Cursor 0][Option 0]Ghosts[BR]
	[Cursor 1][Option 1]Thieves[BR]
	[Cursor 2][Option 2]Sheets[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_34) {
	[Style choice pos=106,70 size=108,62]
	[DelayOff]
	[Cursor 0][Option 0]Heart[BR]
	[Cursor 1][Option 1]Mushroom[BR]
	[Cursor 2][Option 2]Bump[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_35) {
	[Style choice pos=110,70 size=100,62]
	[DelayOff]
	[Cursor 0][Option 0]Coconut[BR]
	[Cursor 1][Option 1]Apple[BR]
	[Cursor 2][Option 2]Lime[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_36) {
	[Style choice pos=96,70 size=128,62]
	[DelayOff]
	[Cursor 0][Option 0]Rat Cheepa[BR]
	[Cursor 1][Option 1]Diz Onnest[BR]
	[Cursor 2][Option 2]Chet Rippo[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_37) {
	[Style choice pos=116,70 size=88,62]
	[DelayOff]
	[Cursor 0][Option 0]Sing[BR]
	[Cursor 1][Option 1]Dance[BR]
	[Cursor 2][Option 2]Bomb[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_38) {
	[Style choice pos=102,70 size=116,62]
	[DelayOff]
	[Cursor 0][Option 0]Cake[BR]
	[Cursor 1][Option 1]Mushrooms[BR]
	[Cursor 2][Option 2]Kooper[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_39) {
	[Style choice pos=99,70 size=122,62]
	[DelayOff]
	[Cursor 0][Option 0]Bombette[BR]
	[Cursor 1][Option 1]Kooper[BR]
	[Cursor 2][Option 2]Parakarry[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_40) {
	[Style choice pos=94,70 size=132,62]
	[DelayOff]
	[Cursor 0][Option 0]Pokey[BR]
	[Cursor 1][Option 1]Bandit[BR]
	[Cursor 2][Option 2]Nomadimouse[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_41) {
	[Style choice pos=106,70 size=108,62]
	[DelayOff]
	[Cursor 0][Option 0]Eldstar[BR]
	[Cursor 1][Option 1]Muskular[BR]
	[Cursor 2][Option 2]Skolar[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_42) {
	[Style choice pos=106,70 size=108,62]
	[DelayOff]
	[Cursor 0][Option 0]Parcels[BR]
	[Cursor 1][Option 1]Letters[BR]
	[Cursor 2][Option 2]Handbills[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_43) {
	[Style choice pos=87,70 size=146,62]
	[DelayOff]
	[Cursor 0][Option 0]Shop[BR]
	[Cursor 1][Option 1]Station[BR]
	[Cursor 2][Option 2]Mayor's House[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_44) {
	[Style choice pos=102,70 size=116,62]
	[DelayOff]
	[Cursor 0][Option 0]Gardening[BR]
	[Cursor 1][Option 1]Cooking[BR]
	[Cursor 2][Option 2]Fishing[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_45) {
	[Style choice pos=92,70 size=136,62]
	[DelayOff]
	[Cursor 0][Option 0]Sir Quizzby[BR]
	[Cursor 1][Option 1]I. Q. Testa[BR]
	[Cursor 2][Option 2]Chuck Quizmo[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_46) {
	[Style choice pos=61,70 size=198,62]
	[DelayOff]
	[Cursor 0][Option 0]In towns and villages[BR]
	[Cursor 1][Option 1]On the street[BR]
	[Cursor 2][Option 2]In the jail[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_47) {
	[Style choice pos=86,70 size=148,62]
	[DelayOff]
	[Cursor 0][Option 0]Trumpet Plant[BR]
	[Cursor 1][Option 1]Hurt Plant[BR]
	[Cursor 2][Option 2]Bellbell Plant[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_48) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]Blue[BR]
	[Cursor 1][Option 1]Green[BR]
	[Cursor 2][Option 2]Pink[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_49) {
	[Style choice pos=105,70 size=110,62]
	[DelayOff]
	[Cursor 0][Option 0]Merlow[BR]
	[Cursor 1][Option 1]Merlon[BR]
	[Cursor 2][Option 2]Merluvlee[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_50) {
	[Style choice pos=119,70 size=82,62]
	[DelayOff]
	[Cursor 0][Option 0]Six[BR]
	[Cursor 1][Option 1]Eight[BR]
	[Cursor 2][Option 2]Ten[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_51) {
	[Style choice pos=103,70 size=114,62]
	[DelayOff]
	[Cursor 0][Option 0]Easygoing[BR]
	[Cursor 1][Option 1]Bossy[BR]
	[Cursor 2][Option 2]Sleepy[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_52) {
	[Style choice pos=87,70 size=146,62]
	[DelayOff]
	[Cursor 0][Option 0]Shop[BR]
	[Cursor 1][Option 1]Station[BR]
	[Cursor 2][Option 2]Merlon's house[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_53) {
	[Style choice pos=84,70 size=152,62]
	[DelayOff]
	[Cursor 0][Option 0]First-Degree[BR]
	[Cursor 1][Option 1]Second-Degree[BR]
	[Cursor 2][Option 2]Third-Degree[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_54) {
	[Style choice pos=123,70 size=74,62]
	[DelayOff]
	[Cursor 0][Option 0]Blue[BR]
	[Cursor 1][Option 1]Red[BR]
	[Cursor 2][Option 2]Pink[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_55) {
	[Style choice pos=119,70 size=82,62]
	[DelayOff]
	[Cursor 0][Option 0]Posie[BR]
	[Cursor 1][Option 1]Rosie[BR]
	[Cursor 2][Option 2]Lily[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_56) {
	[Style choice pos=104,70 size=112,62]
	[DelayOff]
	[Cursor 0][Option 0]Landolaki[BR]
	[Cursor 1][Option 1]Lakitofu[BR]
	[Cursor 2][Option 2]Lakilulu[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_57) {
	[Style choice pos=94,70 size=132,62]
	[DelayOff]
	[Cursor 0][Option 0]Jump[BR]
	[Cursor 1][Option 1]Hit a tree[BR]
	[Cursor 2][Option 2]Hit a switch[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_58) {
	[Style choice pos=105,70 size=110,62]
	[DelayOff]
	[Cursor 0][Option 0]Dancer[BR]
	[Cursor 1][Option 1]Composer[BR]
	[Cursor 2][Option 2]Pop Diva[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_59) {
	[Style choice pos=116,70 size=88,62]
	[DelayOff]
	[Cursor 0][Option 0]Sing[BR]
	[Cursor 1][Option 1]Dance[BR]
	[Cursor 2][Option 2]Run[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_60) {
	[Style choice pos=104,70 size=112,62]
	[DelayOff]
	[Cursor 0][Option 0]Neighbors[BR]
	[Cursor 1][Option 1]Friends[BR]
	[Cursor 2][Option 2]Brothers[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_61) {
	[Style choice pos=111,70 size=98,62]
	[DelayOff]
	[Cursor 0][Option 0]Penguin[BR]
	[Cursor 1][Option 1]Lakitu[BR]
	[Cursor 2][Option 2]Ninji[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_62) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]Seven[BR]
	[Cursor 1][Option 1]Eight[BR]
	[Cursor 2][Option 2]Nine[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_63) {
	[Style choice pos=118,70 size=84,62]
	[DelayOff]
	[Cursor 0][Option 0]Gleem[BR]
	[Cursor 1][Option 1]Twink[BR]
	[Cursor 2][Option 2]Glo[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}

#message:2D:(QuizChoice_64) {
	[Style choice pos=117,70 size=86,62]
	[DelayOff]
	[Cursor 0][Option 0]Five[BR]
	[Cursor 1][Option 1]Seven[BR]
	[Cursor 2][Option 2]Ten[BR]
	[Option 255][DelayOn]
	[EndChoice 3][Yield][End]
}
